### ISSUE TITLE
encoder error

### ISSUE THREAD

**Issue by hrt644** [WWBN/AVideo#1634]
My encoder doesn't send the encoded video to main website. I checked the log configuration:

[07-Apr-2019 12:20:27 America/New_York] downloadFile: downloadedFile = /var/www/html/tube-encoder/videos/original_05WSAIdentities_YPTuniqid_5caa23480acca9.64916047 | url = http://10.26.20.180/tube-encoder/videos/original_05WSAIdentities_YPTuniqid_5caa23480acca9.64916047
[07-Apr-2019 12:20:27 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/html/tube-encoder/objects/Encoder.php:385
Stack trace:
#0 /var/www/html/tube-encoder/objects/Encoder.php(253): Encoder::getVideoFile('http://10.26.20...', '9', '/var/www/html/t...', '/var/www/html/t...')
#1 /var/www/html/tube-encoder/objects/Encoder.php(515): Encoder::downloadFile('9')
#2 /var/www/html/tube-encoder/view/run.php(6): Encoder::run()
#3 {main}
  thrown in /var/www/html/tube-encoder/objects/Encoder.php on line 385
[07-Apr-2019 12:20:32 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/tube-encoder/objects/functions.php:60
Stack trace:
#0 /var/www/html/tube-encoder/objects/Encoder.php(865): url_get_contents('/var/www/html/t...')
#1 /var/www/html/tube-encoder/view/status.php(34): Encoder::getVideoConversionStatus('9')
#2 {main}
  thrown in /var/www/html/tube-encoder/objects/functions.php on line 60

The status of encoder is **downloading....**  . Any idea how can I resolve the issue?

![error](https://user-images.githubusercontent.com/29139178/55686552-10b7ce00-5939-11e9-8ff7-6f7395e3c2c6.jpg)

**Comment by tbennett6421** [comment]
This can be fixed in by running the following.
`sudo apt-get install php-xml`

@DanielnetoDotCom This should be added to the install documents
