### ISSUE TITLE
Cant play video after enable "GoogleAds_IMA"

### ISSUE THREAD

**Issue by ykhuat** [WWBN/AVideo#1805]
HI Daniel,

I try to enable "GoogleAds_IMA" today and find out all my video unable to play, after enable the plugin.

Here the error from the youphptube i get:-

[22-Jun-2019 16:32:32 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined method YouPHPTubePlugin::showAds() in /var/www/html/YouPHPTube/plugin/GoogleAds_IMA/GoogleAds_IMA.php(14) : eval()'d code(1) : eval()'d code:54
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/YouPHPTubePlugin.php(34): GoogleAds_IMA->getHeadCode()
#1 /var/www/html/YouPHPTube/view/include/head.php(3): YouPHPTubePlugin::getHeadCode()
#2 /var/www/html/YouPHPTube/view/modeYoutube.php(192): include('/var/www/html/Y...')
#3 /var/www/html/YouPHPTube/view/index.php(25): require('/var/www/html/Y...')
#4 {main}
  thrown in /var/www/html/YouPHPTube/plugin/GoogleAds_IMA/GoogleAds_IMA.php(14) : eval()'d code(1) : eval()'d code on line 54

tq for help..

**Comment by DanielnetoDotCom** [comment]
Hi

Please make sure you have your streamer up to date with the git version.
https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by ykhuat** [comment]
Hi Daniel,

it that any way to fix it without upgrade to new version?

I already try the new version, it have a lot error, and it was very slow..

**Comment by ykhuat** [comment]
i just try to upgrade to version 7.2. after that i get a lot of this error:-

[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443
[23-Jun-2019 05:15:15 Asia/Shanghai] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/category.php on line 443

**Comment by DanielnetoDotCom** [comment]
really strange error.

make sure your async job is unchecked

![image](https://user-images.githubusercontent.com/18009293/60102854-e229e200-9734-11e9-8c8c-aa52e30c5222.png)

also if you can disable the cache plugin

**Comment by ykhuat** [comment]
Hi Daniel,

I already updated to latest version (7.2). please forget about the previous error, it was related to permission setting on ubuntu.

I already tested the "GoogleAds_IMA" plugin in version 7.2 it was working with some issue. It will randomly play "Google ads" (i only select "start").

it also will play "google ads" when i fast forward the video to the median of the video.
fast froward or backward also will load google ads 1 time.

so sorry for my bad English.  Hope you can understand my issue.
