### ISSUE TITLE
LiveStream and LiveLinks

### ISSUE THREAD

**Issue by clienttask** [WWBN/AVideo#1950]
The LiveLinks is not showing the link I added. Please, any tip to solve below error:

#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 123
[12-Aug-2019 08:36:14 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:123
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(26): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 123
[12-Aug-2019 08:36:14 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:123
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(26): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 123
[12-Aug-2019 08:36:25 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:123
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(26): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 123
[12-Aug-2019 08:36:25 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:123
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(26): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 123
[12-Aug-2019 08:36:27 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:123
Stack trace:

**Comment by akhilleusuggo** [comment]
I have never seen this error but , are you using a valid url ? ( remember that url youtube/twitch are not working for sure , i have tested them myself )
Make sure the time of Starting at ( from now ) , ending in , are correct and not on the past . Like tha start should be as example 12/08/2019 and ending on 12/09/2019 . You can try this as example , you will see the notification

**Comment by clienttask** [comment]
Hello,

Yes, I did the same but still it is not showing.  I'm using m3u8 url.

**Comment by DanielnetoDotCom** [comment]
@clienttask if you google for **Fatal error: Uncaught Error: Call to undefined function simplexml_load_string** I am sure you will find a fix for this

**Comment by clienttask** [comment]
Hello,

Thanks, the error has been fixed after installing below:
sudo apt-get install php7.0-xml
sudo apt-get install php7.0-fpm

**Comment by DanielnetoDotCom** [comment]
Is it working now?

**Comment by clienttask** [comment]
Yes, is working fine.
Thanks.

**Comment by akhilleusuggo** [comment]
That tutorial it's really outdated for everything I use . The 7.0 is not working for me , I had to put 7.2 ; same with Nginx . Question of the ubuntu version you're using

**Comment by clienttask** [comment]
I'm using Ubuntu 16.04.6 LTS and php7.0. It works fine for me.

**Comment by akhilleusuggo** [comment]
@clienttask Yes for the 16.04 yes , it works
