### ISSUE TITLE
`ReferenceError: externalOptionsObject is not defined` error when saving videos

### ISSUE THREAD

**Issue by Teeeeemo** [WWBN/AVideo#2041]
Hello, I tried to upload a video and change its properties through the admin panel.
Otherwise, upon pressing the "Save" button (with and without changes), it loads indefinitely and throws `ReferenceError: externalOptionsObject is not defined error` at `mvideos line 48 > eval:1:1`

I have not installed any plugin. My YPT is currently running inside a docker container which I fetched from https://hub.docker.com/r/leejoneshane/youphptube. After pulling it, I removed the content inside the htdocs folder and re-pull everything from git.

**Comment by DanielnetoDotCom** [comment]
looks like something is missing the database.

probably you skip some update

**Comment by Teeeeemo** [comment]
hmm, but I dropped everything from the database and re-ran the installation. so I suppose it's the latest?

**Comment by DanielnetoDotCom** [comment]
if you rerun the installation make sure you have your plugins with the tables installed

BTW, you can post a more complete log here so we can understand where this come from

**Comment by Teeeeemo** [comment]
Yes, I have installed the tables.

Apparently, this is the only log I received.

`[17-Sep-2019 15:08:32 UTC] [aEC] JS-Err: ReferenceError: externalOptionsObject is not defined @ line 1 in file https://static-cdn.ddns.net/mvideos line 48 > eval at visit on /mvideos`

**Comment by Teeeeemo** [comment]
Yes, I have installed the tables.

Apparently, this is the only log I received.

[17-Sep-2019 15:08:32 UTC] [aEC] JS-Err: ReferenceError: externalOptionsObject is not defined @ line 1 in file https://<location>/mvideos line 48 > eval at visit on /mvideos

Disabling all plugins did not help either..

**Comment by Teeeeemo** [comment]
I have just realized that there may have been a problem upon encoding a video.
Here's what popped up in YPT.log:

`[17-Sep-2019 15:13:01 UTC] Start Login Request
[17-Sep-2019 15:13:01 UTC] redirectUri: 
[17-Sep-2019 15:13:01 UTC] sane redirectUri: https://static-cdn.ddns.net/
[17-Sep-2019 15:13:01 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:01 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:01 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:13 UTC] youPHPTubeEncoder.json: start
[17-Sep-2019 15:13:13 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:13 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:13 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ctype_space() in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Text.php:43
Stack trace:
#0 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Lexer/DirectLex.php(161): HTMLPurifier_Token_Text->__construct('lol')
#1 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier.php(215): HTMLPurifier_Lexer_DirectLex->tokenizeHTML('lol', Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/localhost/htdocs/objects/video.php(1401): HTMLPurifier->purify('lol')
#3 /var/www/localhost/htdocs/objects/youPHPTubeEncoder.json.php(54): Video->setDescription('lol')
#4 {main}
  thrown in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Text.php on line 43
[17-Sep-2019 15:13:22 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:22 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:22 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:22 UTC] ReceiveImage: Start receiving image
[17-Sep-2019 15:13:22 UTC] ReceiveImage: Encoder receiving post Array
(
    [image] => Array
        (
            [name] => 15_tmpFile.mp4.jpg
            [type] => application/octet-stream
            [tmp_name] => /tmp/phpjEbCKn
            [error] => 0
            [size] => 14089
        )

    [gifimage] => Array
        (
            [name] => 15_tmpFile.mp4.gif
            [type] => application/octet-stream
            [tmp_name] => /tmp/phpLCadBl
            [error] => 0
            [size] => 604403
        )

)

[17-Sep-2019 15:13:22 UTC] ReceiveImage: Files Received for video 4: 5d80f812d8f24
[17-Sep-2019 15:13:27 UTC] youPHPTubeEncoder.json: start
[17-Sep-2019 15:13:27 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:27 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:27 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ctype_lower() in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php:44
Stack trace:
#0 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Arborize.php(14): HTMLPurifier_Token_Tag->__construct('div')
#1 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/FixNesting.php(49): HTMLPurifier_Arborize::arborize(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/Composite.php(24): HTMLPurifier_Strategy_FixNesting->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#3 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier.php(218): HTMLPurifier_Strategy_Composite->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#4 /var/www/localhost/htdocs/objects/video.php(1401): HTMLPurifier->purify('')
#5 /var/www/localhost/htdocs/objects/youPHPTubeEncoder.json.php(54): Video->setDescription('')
#6 {mai in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php on line 44
[17-Sep-2019 15:13:28 UTC] youPHPTubeEncoder.json: start
[17-Sep-2019 15:13:28 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:28 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:28 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ctype_lower() in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php:44
Stack trace:
#0 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Arborize.php(14): HTMLPurifier_Token_Tag->__construct('div')
#1 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/FixNesting.php(49): HTMLPurifier_Arborize::arborize(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/Composite.php(24): HTMLPurifier_Strategy_FixNesting->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#3 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier.php(218): HTMLPurifier_Strategy_Composite->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#4 /var/www/localhost/htdocs/objects/video.php(1401): HTMLPurifier->purify('')
#5 /var/www/localhost/htdocs/objects/youPHPTubeEncoder.json.php(54): Video->setDescription('')
#6 {mai in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php on line 44
[17-Sep-2019 15:13:28 UTC] youPHPTubeEncoder.json: start
[17-Sep-2019 15:13:28 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[17-Sep-2019 15:13:28 UTC] encryptPasswordVerify: do not encrypt
[17-Sep-2019 15:13:28 UTC] user::login: Do login without cookie
[17-Sep-2019 15:13:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ctype_lower() in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php:44
Stack trace:
#0 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Arborize.php(14): HTMLPurifier_Token_Tag->__construct('div')
#1 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/FixNesting.php(49): HTMLPurifier_Arborize::arborize(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Strategy/Composite.php(24): HTMLPurifier_Strategy_FixNesting->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#3 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier.php(218): HTMLPurifier_Strategy_Composite->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#4 /var/www/localhost/htdocs/objects/video.php(1401): HTMLPurifier->purify('')
#5 /var/www/localhost/htdocs/objects/youPHPTubeEncoder.json.php(54): Video->setDescription('')
#6 {mai in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Tag.php on line 44
`

**Comment by DanielnetoDotCom** [comment]
For sure you must fix the PHP Fatal error

try to google for it's solution

**Comment by Teeeeemo** [comment]
Okay, I have fixed the PHP Fatal Errors (ctype).

Otherwise, the problem is still the same. Nothing what pops up on the log once I edited another video's metadata.

This is the log once I've successfully encoded a video:

`[18-Sep-2019 03:49:09 UTC] getVideosURL generated in 0.0013 seconds. fileName: _YPTuniqid_5d81a8e6143d99.86969122 
[18-Sep-2019 03:49:19 UTC] youPHPTubeEncoder.json: start
[18-Sep-2019 03:49:19 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:49:19 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:49:19 UTC] user::login: Do login without cookie
[18-Sep-2019 03:49:19 UTC] youPHPTubeEncoder.json: Encoder receiving post
[18-Sep-2019 03:49:19 UTC] Do not need update duration: {}
[18-Sep-2019 03:49:19 UTC] youPHPTubeEncoder.json: Files Received for video 7: hgg
[18-Sep-2019 03:49:25 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:49:25 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:49:25 UTC] user::login: Do login without cookie
[18-Sep-2019 03:49:25 UTC] ReceiveImage: Start receiving image
[18-Sep-2019 03:49:25 UTC] ReceiveImage: Encoder receiving post Array
(
    [image] => Array
        (
            [name] => 18_tmpFile.mp4.jpg
            [type] => application/octet-stream
            [tmp_name] => /tmp/phpCIgMEk
            [error] => 0
            [size] => 86055
        )

    [gifimage] => Array
        (
            [name] => 18_tmpFile.mp4.gif
            [type] => application/octet-stream
            [tmp_name] => /tmp/phpjMKDCc
            [error] => 0
            [size] => 500355
        )

)

[18-Sep-2019 03:49:25 UTC] ReceiveImage: Files Received for video 7: hgg
[18-Sep-2019 03:50:05 UTC] youPHPTubeEncoder.json: start
[18-Sep-2019 03:50:05 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:50:05 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:50:05 UTC] user::login: Do login without cookie
[18-Sep-2019 03:50:05 UTC] youPHPTubeEncoder.json: Encoder receiving post
[18-Sep-2019 03:50:05 UTC] youPHPTubeEncoder.json: receiving video upload to _YPTuniqid_5d81a93f3bb944.30699931_HD.mp4 {"video":{"name":"18_tmpFile_converted_HD.mp4","type":"application\/octet-stream","tmp_name":"\/tmp\/phpAbNenJ","error":0,"size":23730162}}
[18-Sep-2019 03:50:05 UTC] Do not need update duration: {"views_count_25":0,"views_count_50":0,"views_count_75":0,"views_count_100":0,"created":"2019-09-18 03:49:19","modified":"2019-09-18 03:49:25","order":1}
[18-Sep-2019 03:50:05 UTC] youPHPTubeEncoder.json: Files Received for video 7: hgg
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: start
[18-Sep-2019 03:50:06 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:50:06 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:50:06 UTC] user::login: Do login without cookie
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: Encoder receiving post
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: receiving video upload to _YPTuniqid_5d81a93f3bb944.30699931_SD.mp4 {"video":{"name":"18_tmpFile_converted_SD.mp4","type":"application\/octet-stream","tmp_name":"\/tmp\/phpKlhHFa","error":0,"size":15852474}}
[18-Sep-2019 03:50:06 UTC] Do not need update duration: {"views_count_25":0,"views_count_50":0,"views_count_75":0,"views_count_100":0,"created":"2019-09-18 03:49:19","modified":"2019-09-18 03:50:05","order":1}
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: Files Received for video 7: hgg
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: start
[18-Sep-2019 03:50:06 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:50:06 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:50:06 UTC] user::login: Do login without cookie
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: Encoder receiving post
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: receiving video upload to _YPTuniqid_5d81a93f3bb944.30699931_Low.mp4 {"video":{"name":"18_tmpFile_converted_Low.mp4","type":"application\/octet-stream","tmp_name":"\/tmp\/phphDPjhO","error":0,"size":9133329}}
[18-Sep-2019 03:50:06 UTC] Do not need update duration: {"views_count_25":0,"views_count_50":0,"views_count_75":0,"views_count_100":0,"created":"2019-09-18 03:49:19","modified":"2019-09-18 03:50:06","order":1}
[18-Sep-2019 03:50:06 UTC] youPHPTubeEncoder.json: Files Received for video 7: hgg
[18-Sep-2019 03:50:06 UTC] user::login: noPass = , encodedPass = 1, this->user, admin 172.17.0.1
[18-Sep-2019 03:50:06 UTC] encryptPasswordVerify: do not encrypt
[18-Sep-2019 03:50:06 UTC] user::login: Do login without cookie
[18-Sep-2019 03:50:06 UTC] Video is done notified 7: hgg
[18-Sep-2019 03:50:21 UTC] getVideosURL generated in 0.0014 seconds. fileName: _YPTuniqid_5d81a93f3bb944.30699931 
[18-Sep-2019 03:50:21 UTC] getVideosURL generated in 0.0013 seconds. fileName: _YPTuniqid_5d81a8e6143d99.86969122 `

**Comment by Teeeeemo** [comment]
After digging to the encoders log, I notice that this messages was printed:

	[18-Sep-2019 17:22:24 UTC] ERROR on get https://192.168.2.2:4443/plugin/CustomizeAdvanced/advancedCustom.json.php false
	[18-Sep-2019 17:22:24 UTC] PHP Warning:  Creating default object from empty value in /var/www/localhost/htdocs/view/index.php on line 233
	[18-Sep-2019 17:22:30 UTC] Upload.php will set format
	[18-Sep-2019 17:22:30 UTC] Upload.php will let function decide decideFormatOrder
	[18-Sep-2019 17:22:30 UTC] decideFormatOrder: {"file":"9GAG - Why So Serious-.mp4","audioOnly":"false","spectrum":"false","webm":"false","in	putHLS":"false","inputLow":"true","inputSD":"true","inputHD":"true","title":"asd","description":"gew","categories_id":"0"}
	[18-Sep-2019 17:22:30 UTC] decideFormatOrder: MP4 All
	[18-Sep-2019 17:22:30 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
	[18-Sep-2019 17:22:30 UTC] YouPHPTube-Encoder sending file to https://(hidden)/youPHPTubeEncoder.json
	[18-Sep-2019 17:22:30 UTC] YouPHPTube-Encoder reading file from 
	[18-Sep-2019 17:22:30 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:30 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"https:\/\/(hidden)\/	youPHPTubeEncoder.json","postFields":10,"response_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"video_id":11}}
	[18-Sep-2019 17:22:35 UTC] downloadFile: start queue_id = 23
	[18-Sep-2019 17:22:35 UTC] downloadFile: url = https://192.168.2.2:4444/videos/original_9GAGWhySoSerious_YPTuniqid_5d8267d677f8c6.35042361
	[18-Sep-2019 17:22:35 UTC] downloadFile:strpos global['webSiteRootURL'] = https://192.168.2.2:4444/
	[18-Sep-2019 17:22:35 UTC] downloadFile: this file was uploaded from file and thus is in the videos
	[18-Sep-2019 17:22:35 UTC] downloadFile: downloadedFile = /var/www/localhost/htdocs/videos/	original_9GAGWhySoSerious_YPTuniqid_5d8267d677f8c6.35042361 | url = https://192.168.2.2:4444/videos/	original_9GAGWhySoSerious_YPTuniqid_5d8267d677f8c6.35042361
	[18-Sep-2019 17:22:35 UTC] Try to get UTF8 URL https://192.168.2.2:4444/videos/original_9GAGWhySoSerious_YPTuniqid_5d8267d677f8c6.35042361
	[18-Sep-2019 17:22:35 UTC] Try to get UTF8 decode URL https://192.168.2.2:4444/videos/	original_9GAGWhySoSerious_YPTuniqid_5d8267d677f8c6.35042361
	[18-Sep-2019 17:22:35 UTC] downloadFile: success
	[18-Sep-2019 17:22:35 UTC] downloadFile: 	{"error":false,"filename":"23_tmpFile.mp4","pathFileName":"\/var\/www\/localhost\/htdocs\/videos\/23_tmpFile.mp4"}
	[18-Sep-2019 17:22:35 UTC] sendImages: Sending image to [11]
	[18-Sep-2019 17:22:35 UTC] Duration found: 0:00:02
	[18-Sep-2019 17:22:35 UTC] sendImages: YouPHPTube-Encoder sending file to https://(hidden)/objects/youPHPTubeEncoderReceiveImage.json.php
	[18-Sep-2019 17:22:35 UTC] sendImages: YouPHPTube-Encoder reading file from /var/www/localhost/htdocs/videos/23_tmpFile.mp4
	[18-Sep-2019 17:22:35 UTC] getImage: ffmpeg -ss 00:00:01 -i /var/www/localhost/htdocs/videos/23_tmpFile.mp4 -vframes 1 -y /var/www/localhost	/htdocs/videos/23_tmpFile.mp4.jpg
	[18-Sep-2019 17:22:35 UTC] getImage: takes 0.08650803565979 sec to complete
	[18-Sep-2019 17:22:35 UTC] getGifImage
	[18-Sep-2019 17:22:35 UTC] getGif: Starts
	[18-Sep-2019 17:22:36 UTC] getGif: takes 0.38899397850037 sec to complete
	[18-Sep-2019 17:22:36 UTC] sendImages: curl_init
	[18-Sep-2019 17:22:36 UTC] sendImages: curl_exec
	[18-Sep-2019 17:22:36 UTC] sendImages: YouPHPTube-Streamer answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:36 UTC] {"error":false,"file":"\/var\/www\/localhost\/htdocs\/videos\/23_tmpFile.mp4","target":"https:\/\/(hidden)\/objec	ts\/youPHPTubeEncoderReceiveImage.json.php","postFields":6,"response_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"vid	eo_id":11}}
	[18-Sep-2019 17:22:36 UTC] run:runMultiResolution
	[18-Sep-2019 17:22:36 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/localhost/htdocs/videos/23_tmpFile.mp4 -vf scale=-2:720 	-movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /var/www/localhost/htdocs/videos/23_tmpFile_converted_HD.mp4] 
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/localhost/htdocs/videos/23_tmpFile.mp4 -vf scale=-2:540 	-movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /var/www/localhost/htdocs/videos/23_tmpFile_converted_SD.mp4] 
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/localhost/htdocs/videos/23_tmpFile.mp4 -vf scale=-2:360 	-movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /var/www/localhost/htdocs/videos/23_tmpFile_converted_Low.mp4] 
	[18-Sep-2019 17:22:37 UTC] Duration found: 0:00:02
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder sending file to https://(hidden)/youPHPTubeEncoder.json
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder reading file from /var/www/localhost/htdocs/videos/23_tmpFile_converted_HD.mp4
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:37 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/localhost\/htdocs\/videos\/23_tmpFile_converted_HD.mp4","resolu	tion":"HD","videoDownloadedLink":null,"target":"https:\/\/(hidden)\/youPHPTubeEncoder.json","postFields":11,"videoFileSize":"333.20KB","resp	onse_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"video_id":11}}
	[18-Sep-2019 17:22:37 UTC] Duration found: 0:00:02
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder sending file to https://(hidden)/youPHPTubeEncoder.json
	[18-Sep-2019 17:22:37 UTC] YouPHPTube-Encoder reading file from /var/www/localhost/htdocs/videos/23_tmpFile_converted_SD.mp4
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:38 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/localhost\/htdocs\/videos\/23_tmpFile_converted_SD.mp4","resolu	tion":"SD","videoDownloadedLink":null,"target":"https:\/\/(hidden)\/youPHPTubeEncoder.json","postFields":11,"videoFileSize":"225.95KB","resp	onse_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"video_id":11}}
	[18-Sep-2019 17:22:38 UTC] Duration found: 0:00:02
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Encoder sending file to https://(hidden)/youPHPTubeEncoder.json
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Encoder reading file from /var/www/localhost/htdocs/videos/23_tmpFile_converted_Low.mp4
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:38 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/localhost\/htdocs\/videos\/23_tmpFile_converted_Low.mp4","resol	ution":"Low","videoDownloadedLink":null,"target":"https:\/\/(hidden)\/youPHPTubeEncoder.json","postFields":11,"videoFileSize":"123.47KB","re	sponse_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"video_id":11}}
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Encoder sending confirmation to https://(hidden)/objects/youPHPTubeEncoderNotifyIsDone.json.php
	[18-Sep-2019 17:22:38 UTC] YouPHPTube-Streamer confirmation answer {"error":false,"video_id":11}
	[18-Sep-2019 17:22:38 UTC] {"error":false,"target":"https:\/\/(hidden)\/objects\/youPHPTubeEncoderNotifyIsDone.json.php","postFields":{"vide	os_id":11,"user":"admin","password":"(my encoded 	pw)","fail":0},"response_raw":"{\"error\":false,\"video_id\":11}","response":{"error":false,"video_id":11}}

do you have any idea what may have gone wrong?

**Comment by DanielnetoDotCom** [comment]
I just notice you are showing a JS error not a PHP error, what problem is it causing?

**Comment by Teeeeemo** [comment]
Yes, I think there is no PHP error at the moment.
It currently showing a progress bar, indefinitely, after I changed a video's metadata (title, description, etc) through the YPT's My Videos. It also throws this error on console:
`ReferenceError: externalOptionsObject is not defined error at mvideos line 48 > eval:1:1`

**Comment by DanielnetoDotCom** [comment]
the problem is, if I can not reproduce this error will be hard for me to fix it.

**Comment by Teeeeemo** [comment]
true.
Would it be a trouble for you to confirm it by testing these docker containers?
https://hub.docker.com/r/leejoneshane/youphptube
https://hub.docker.com/r/leejoneshane/youphptube-encoder

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not familiar with docker, someone else did the docker part.

**Comment by Teeeeemo** [comment]
Okay, so I did something and this seem to work.
I changed Line 1075: `var externalOptions = {}` to `externalOptions = {};`
I know I have made it into a global variable and is not that safe.
