### ISSUE TITLE
AWS S3 plugin issue

### ISSUE THREAD

**Issue by x3kiwi** [WWBN/AVideo#2187]
Hi,

Just purchased AWS S3 plugin, however it seems not working. Here is the error log:

[25-Oct-2019 15:36:20 Asia/Shanghai] ReceiveImage: Files Received for video 1552: test
[25-Oct-2019 15:36:23 Asia/Shanghai] Encoder receiving post
[25-Oct-2019 15:36:23 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type_per_filename() in /home/media/vidaero/www/plugin/AWS_S3/AWS_S3.php(14) : eval()'d code(1) : eval()'d code:154
Stack trace:
#0 /home/media/vidaero/www/plugin/AWS_S3/AWS_S3.php(14) : eval()'d code(1) : eval()'d code(141): AWS_S3->copy_to_s3('/tmp/phpKLImaJ', '_YPTuniqid_5db2...')
#1 /home/media/vidaero/www/objects/functions.php(907): AWS_S3->move_uploaded_file('/tmp/phpKLImaJ', '_YPTuniqid_5db2...')
#2 /home/media/vidaero/www/objects/youPHPTubeEncoder.json.php(88): decideMoveUploadedToVideos('/tmp/phpKLImaJ', '_YPTuniqid_5db2...')
#3 {main}
  thrown in /home/media/vidaero/www/plugin/AWS_S3/AWS_S3.php(14) : eval()'d code(1) : eval()'d code on line 154
[25-Oct-2019 15:36:24 Asia/Shanghai] Video is done notified 1552: test

**Comment by DanielnetoDotCom** [comment]
Hi,

For sure the error is here ` [25-Oct-2019 15:36:23 Asia/Shanghai] PHP Fatal error: Uncaught Error: Call to undefined function mime_content_type_per_filename() in /home/media/vidaero/www/plugin/AWS_S3/AWS_S3.php(14) : eval()'d code(1) : eval()'d code:154`

Are you sure you are running the latest version (v7.7) and you have uploaded all the files correctly?

The function exists here:

https://github.com/YouPHPTube/YouPHPTube/blob/5d2113f21834613a924d2805d008c1035625f219/objects/functions.php#L1470
