### ISSUE TITLE
b2 BackBlaze issue since update

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2559]
Hi,

since updating everything I have found that when I enable b2 backblaze the videos do not get copied accross even tho the test works fine.

here's the log:
[24-Jan-2020 15:45:56 UTC] decideMoveUploadedToVideos: 1280_5e2b11343edad9.15653258.webm
[24-Jan-2020 15:45:56 UTC] decideMoveUploadedToVideos: NOT ZIp file 1280_5e2b11343edad9.15653258.webm
[24-Jan-2020 15:45:56 UTC] decideMoveUploadedToVideos: B2 1280_5e2b11343edad9.15653258.webm
[24-Jan-2020 15:45:56 UTC] copy_to_B2 Start 1280_5e2b11343edad9.15653258.webm
[24-Jan-2020 15:46:04 UTC] copy_to_B2 done 1280_5e2b11343edad9.15653258.webm {}
[24-Jan-2020 15:46:04 UTC] MP4ThumbsAndGif: (1280_5e2b11343edad9.15653258), jpg
[24-Jan-2020 15:46:04 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[24-Jan-2020 15:46:04 UTC] MP4ThumbsAndGif: Video Not found (1280_5e2b11343edad9.15653258), jpg
[24-Jan-2020 15:46:04 UTC] MP4ThumbsAndGif: (1280_5e2b11343edad9.15653258), gif
[24-Jan-2020 15:46:04 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[24-Jan-2020 15:46:04 UTC] MP4ThumbsAndGif: Video Not found (1280_5e2b11343edad9.15653258), gif

also getting:
[24-Jan-2020 17:33:11 UTC] removeHLSFiles: /var/www/html/videos/1280_5e2b29a999acc7.26598743
[24-Jan-2020 17:33:11 UTC] PHP Warning:  scandir(/var/www/html/videos/1280_5e2b29a999acc7.26598743): failed to open dir: No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
[24-Jan-2020 17:33:11 UTC] PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
[24-Jan-2020 17:33:11 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 226

is there a way to uninstall and re-install the plugin?

**Comment by millzee01** [comment]
Hi, 
quick update: the videos do get copied across but dont appear on my bucket for at least 20 mins.  

Therefor the thumbs don't get created.  

Is this something you have seen before?

My settings are:
bucket_name: vid-domain
accountid: xxxxxxxxxxxxx
keyid: xxxxxxxxxxxxxxxxxxxx
applicationkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
cdn_link:  (this is blank)
useDirectLink: checked
timeout: 43200
usePublicBucker: checked

If i turn off B2 plugin then the files get copied to my videos folder and the thumbs get created fine.

**Comment by millzee01** [comment]
Hi, 
When the backblaze plugin is enabled and i upload via the encoder I get the following message in the log:

The video is uploaded somewhere but not added.

[24-Jan-2020 18:35:29 UTC] Bot Detected, NOT showing the cache (/youPHPTubeEncoder.json) FROM: xxx.xxx.xxx.xxx Browser: 
[24-Jan-2020 18:35:32 UTC] Bot Detected, NOT showing the cache (/objects/youPHPTubeEncoderReceiveImage.json.php) FROM: xxx.xxx.xxx.xxx Browser: 
[24-Jan-2020 18:35:40 UTC] Bot Detected, NOT showing the cache (/youPHPTubeEncoder.json) FROM: xxx.xxx.xxx.xxx Browser: 

The ip address is my server, so I wonder if i need to open any ports?

**Comment by JoshWho** [comment]
Turn off StopBotsFromNonCachedPages

It is located in your Cache Plugin.

**Comment by millzee01** [comment]
Tried that thanks @JoshWho i don't see any bot errors now but don't think its the main root of my problem.

because the file is being copied somewhere however it doesn't show in my bucket for about 5/10 mins.  
Its the same when the test file gets copied as well,  it doesn't show up in my bucket for about 5/10 mins.

here's aVideo.log:
[25-Jan-2020 13:25:24 UTC] copy_to_B2 Start SoccerDrills3BeginnerDrillsforYouthPlayers_5e2c41c4800f29.95088485.mp4

Does anyone know if I can show the destination on the log as well and maybe the B2 response?

[25-Jan-2020 13:25:32 UTC] copy_to_B2 done 

The dummy file is created fine on my /videos folder 

SoccerDrills3BeginnerDrillsforYouthPlayers_5e2c41c4800f29.95088485.mp4 {}
[25-Jan-2020 13:25:32 UTC] MP4ThumbsAndGif: 

(SoccerDrills3BeginnerDrillsforYouthPlayers_5e2c41c4800f29.95088485), jpg
[25-Jan-2020 13:25:32 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}

Have contacted backblaze because I think the API is at fault here.

**Comment by DanielnetoDotCom** [comment]
Hi, @millzee01 

Maybe it is not a BackBlaze fault.

are you sure the video was copied from encoder to the streamer?

the error in our logs is regarding the file to move to backblaze does not exists.

if you disable backblaze the video is successfuly transfered?

**Comment by millzee01** [comment]
Hi, the video gets transferred but it takes a while.

10k dummy video files gets created as well.

I think i need to find a way to see where the video is copied to in case its a b2 issue

**Comment by millzee01** [comment]
Am now seeing this in the log when trying a direct upload:

[27-Jan-2020 13:13:28 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: pod-000-1064-14.backblaze.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/plugin/Blackblaze_B2/v in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185
[27-Jan-2020 13:13:54 UTC] Plugin Not Found: Statistics
[27-Jan-2020 13:14:21 UTC] removeHLSFiles: /var/www/html/videos/1280_5e2ee1e2dad365.42554937
[27-Jan-2020 13:14:21 UTC] PHP Warning:  scandir(/var/www/html/videos/1280_5e2ee1e2dad365.42554937): failed to open dir: No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
[27-Jan-2020 13:14:21 UTC] PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
[27-Jan-2020 13:14:21 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 226


might mean something

**Comment by DanielnetoDotCom** [comment]
I see, this error is in the officeial Backblaze API

can you make sure you can ping on this server?   pod-000-1064-14.backblaze.com

**Comment by millzee01** [comment]
ah, I disable icmp on my server so wewont get a reply using ping,  do I need to allow icmp through for the plugin?

client is fine and I can ping pod-000-1064-14.backblaze.com ok.

**Comment by DanielnetoDotCom** [comment]
I am not sure, but your PHP could not reach Backblaze server

`PHP Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: pod-000-1064-14.backblaze.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler`

**Comment by millzee01** [comment]
hmm, 

The message "Could not resolve host: pod-000-1064-14.backblaze.com" seems to have fixed itself so it might be a name resolution issue.  

if might be because i took off useDirectLink and tested.

my bucket is on f000.backblazeb2.com (104.153.233.177) 
so i'm baffled why its trying to communicate with 
pod-000-1064-14.backblaze.com (206.190.213.164)

do i need to have the cdn_link set?

**Comment by DanielnetoDotCom** [comment]
CDN is not mandatory, you should only ser if you have it properly configured with your Backblaze

is it working now?

**Comment by millzee01** [comment]
strange,

I created a brand new b2 account, new bucket and dropped my settings in the plugin config.
Hit the test button, The page comes up after a couple of seconds and i can click on the test file link and it opens the file fine.  If i log onto backblaze, go to my bucket the test file is not there.

If i wait 10 mins and check my bucket the test file appears as well as my uploaded video.

Because the video is not available immediately the thumb that gets created is blank.  

I think youPHPTube is doing everything as it should however the API for backblaze i think is a little dodgy.
