### ISSUE TITLE
Plugins bug ( after update 8.4 )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2573]
Plugins not working ( not displayed anymore )
`No results found!`

**Comment by DanielnetoDotCom** [comment]
what plugin?

can you please provide a screenshot and a log?

**Comment by vielsaitig** [comment]
![image](https://user-images.githubusercontent.com/59013822/73445792-c0907900-435b-11ea-978e-2b7df5055921.png)

**Comment by vielsaitig** [comment]
[30-Jan-2020 11:59:20 Europe/Berlin] avideo.log deleted by update
[30-Jan-2020 12:01:26 Europe/Berlin] Start Login Request
[30-Jan-2020 12:01:26 Europe/Berlin] redirectUri: 
[30-Jan-2020 12:01:26 Europe/Berlin] same redirectUri: https://mediathek.ztv.tirol/
[30-Jan-2020 12:01:26 Europe/Berlin] user::login: noPass = , encodedPass = true, this->user, XXXXXX 88.99.125.15
[30-Jan-2020 12:01:26 Europe/Berlin] encryptPasswordVerify: do not encrypt
[30-Jan-2020 12:01:26 Europe/Berlin] user::login: Do login without cookie
[30-Jan-2020 12:03:24 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:05:05 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:05:17 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:05:40 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:05:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:05:59 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:06:01 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:07:49 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:08:04 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:08:15 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:08:39 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:08:46 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:09:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:09:36 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /home/zflix/public_html/YouPHPTube/admin/functions.php on line 6
[30-Jan-2020 12:09:44 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /home/zflix/public_html/YouPHPTube/admin/functions.php on line 6
[30-Jan-2020 12:09:44 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /home/zflix/public_html/YouPHPTube/admin/functions.php on line 6
[30-Jan-2020 12:09:44 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /home/zflix/public_html/YouPHPTube/admin/functions.php on line 6
[30-Jan-2020 12:13:19 Europe/Berlin] VastCampaignsVideos has not a valid link: 
[30-Jan-2020 12:19:43 Europe/Berlin] Live:getImage  start
[30-Jan-2020 12:19:43 Europe/Berlin] Live:getImage https://mediathek.ztv.tirol/upload/getImage/aHR0cHM6Ly9tZWRpYXRoZWsuenR2LnRpcm9sOjQ0NC9saXZlLzVkZjlmYTBjNDhlNjgvaW5kZXgubTN1OA==/gif
[30-Jan-2020 12:19:43 Europe/Berlin] Live:getImage  start
[30-Jan-2020 12:19:43 Europe/Berlin] Live:getImage https://mediathek.ztv.tirol/upload/getImage/aHR0cHM6Ly9tZWRpYXRoZWsuenR2LnRpcm9sOjQ0NC9saXZlLzVkZjlmYTBjNDhlNjgvaW5kZXgubTN1OA==/jpg
[30-Jan-2020 12:19:44 Europe/Berlin] Live:getImage  Image Expired in 01/01/1970 01:00:00 NOW is 30/01/2020 12:19:44
[30-Jan-2020 12:19:44 Europe/Berlin] Live:getImage  New Image will Expired in 30/01/2020 12:21:44 NOW is 30/01/2020 12:19:44
[30-Jan-2020 12:19:44 Europe/Berlin] Live:getImage  Cached Good until 30/01/2020 12:21:44 NOW is 30/01/2020 12:19:44
[30-Jan-2020 12:19:47 Europe/Berlin] Live:getImage  Image Expired in 01/01/1970 01:00:00 NOW is 30/01/2020 12:19:47
[30-Jan-2020 12:19:47 Europe/Berlin] Live:getImage  New Image will Expired in 30/01/2020 12:21:47 NOW is 30/01/2020 12:19:47
[30-Jan-2020 12:19:47 Europe/Berlin] Live:getImage  Cached Good until 30/01/2020 12:21:47 NOW is 30/01/2020 12:19:47
[30-Jan-2020 12:20:17 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18
[30-Jan-2020 12:26:06 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getPluginVersion() on boolean in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php:18
Stack trace:
#0 /home/zflix/public_html/YouPHPTube/objects/plugin.php(186): RazorPayYPT->getDescription()
#1 /home/zflix/public_html/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /home/zflix/public_html/YouPHPTube/plugin/RazorPayYPT/RazorPayYPT.php on line 18

**Comment by DanielnetoDotCom** [comment]
When did you update?

Did you checked if you did not miss any update?

Looks like for me you update during the version transition.

**Comment by vielsaitig** [comment]
Updated about an hour ago!

Definitely did not miss any update. 

Should I pull the files again ???

Thanks, tom

**Comment by DanielnetoDotCom** [comment]
Hi

I just did an update on demo site.

And it is working fine, not sure what is the difference from yours.

are you using` git pull` to update?

**Comment by DanielnetoDotCom** [comment]
Sorry, issue found and fixed

**Comment by vielsaitig** [comment]
Perfect!
