### ISSUE TITLE
Stuck at 100.0% ETA: 1 second

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3403]
![image](https://user-images.githubusercontent.com/52116577/87662686-3f8f3780-c76b-11ea-8fd5-c1833f904f1b.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
Any fix ?
A fresh installation and still having this issue . Does not even update in witch Storage server the videos are hosted at . Stuck .

**Comment by DanielnetoDotCom** [comment]
Just co confirm, the video was transferred but still displaying the progress correct?

**Comment by akhilleusuggo** [comment]
YES

**Comment by akhilleusuggo** [comment]
Not sure if you did something but fixed after last update

**Comment by akhilleusuggo** [comment]
ok , no . Only old videos got fixed , the new ones are still under the same bug

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/89326412-eabc4e00-d692-11ea-8b95-665da44d440a.png)

Still same error when moving videos manually .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I found the issue . Is the cache . When I clear the cache I can proceed . If I don't clear the cache , the server at some point crashes and the log chat goes crazy .

**Comment by DanielnetoDotCom** [comment]
humm, clear the cache before transfer?

**Comment by akhilleusuggo** [comment]
Clear the cache after transfer .

**Comment by akhilleusuggo** [comment]
can we just not cache the storage tag ?

**Comment by DanielnetoDotCom** [comment]
so when you clear the cache the spinning 100% transfer goes away and the transfer is completed?

**Comment by akhilleusuggo** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the Streamer and one to the Storage plugin

You need to update both

**Comment by akhilleusuggo** [comment]
not working anymore 
My both server crashed .........

```
#0 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1) : eval()'d code(79): YPTStorage::movingIsDone(3125)
#1 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1): eval()
#2 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14): eval()
#3 {main}
  thrown in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code on line 875
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage getFileInfo end {"error":false,"filename":"_ID_5f30d64811b999.67310505","size":1494942,"msg":""} SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage::getFileSize(3118, 3) = 1494942 (_ID_5f30d64811b999.67310505) Remote SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage: log(3118): Start (Site to Site) Transfer of (3118)  Colonel Squid SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage: log(3118): moveFromSiteToSite: No need to move, already on site 3 SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage getFileInfo end {"error":false,"filename":"_ID_5f30d659dcf119.57599280","size":21329814,"msg":""} SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage::getFileSize(3126, 3) = 21329814 (_ID_5f30d659dcf998.57599280) Remote SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Video::deleteSessionCache() in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:875
Stack trace:
#0 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1) : eval()'d code(79): YPTStorage::movingIsDone(3118)
#1 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1): eval()
#2 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14): eval()
#3 {main}
  thrown in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code on line 875
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage: log(3126): Start (Site to Site) Transfer of (3126) CLIP Hakim are you going to take that! SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] AVideoLog::DEBUG: YPTStorage: log(3126): moveFromSiteToSite: No need to move, already on site 3 SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTStorage/move.json.php
[10-Aug-2020 17:18:53 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Video::deleteSessionCache() in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:875
Stack trace:
#0 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1) : eval()'d code(79): YPTStorage::movingIsDone(3126)
#1 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14) : eval()'d code(1): eval()
#2 /var/www/html/AVideo/plugin/YPTStorage/move.json.php(14): eval()
#3 {main}
  thrown in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code on line 875
[10-Aug-2020 17:18:54 UTC] AVideoLog::DEBUG: getUsageFromURL: response header HTTP/1.1 200 OK
Date: Mon, 10 Aug 2020 17:18:52 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: e975b236d8d98b28dqsdq652bbb1790f=m0jm444dqsdqsgjh9rvisdapk3; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: max-age=1, private, must-revalidate
Pragma: no-cache
Set-Cookie: e975b236d8d98b28b6dfe652bbb1790f=m0jm444pt2hb2gjh9rvisdapk3; path=/
Access-Control-Allow-Origin: *
Last-Modified: Mon, 10 Aug 2020 06:48:26 GMT
ETag: "50654f-5ac80576b6280"
Content-Length: 5268815
Content-Type: video/mp4

 SCRIPT_NAME: /plugin/CustomizeAdvanced/updateDiskUsage.php
```

`PHP Fatal error:  Uncaught Error: Call to undefined method Video::deleteSessionCache() in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:875`

Also still the error : 

![image](https://user-images.githubusercontent.com/52116577/89812300-93adf180-db48-11ea-9e28-cb7bc0bf96f1.png)

Now is not caching the progress transfer , I can see 2% , 5% etc , but when hits 100% , it's stuck

**Comment by DanielnetoDotCom** [comment]
Did you also update the streamer?

**Comment by akhilleusuggo** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
I can see this in your code:

`[10-Aug-2020 17:18:53 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Video::deleteSessionCache() in /var/www/html/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:875`

And this on the code https://github.com/WWBN/AVideo/blob/d9a8c292e9b5faef714ea25e2fd475e1a1e0358e/objects/video.php#L3184

Please double-check it.

**Comment by DanielnetoDotCom** [comment]
Nevermind, confirmed, I miss something

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the Storage plugin, please update it v2.2

**Comment by akhilleusuggo** [comment]
Does not show the progress , but I'm fine with it . At the least does not stuck .
And btw , the pages now load slower ( I guess it's normal due to non-cache )

**Comment by DanielnetoDotCom** [comment]
What page is slower?

this should only clear the cache when finish to transfer. and then maybe the first access will be slower, not the subsequent.

**Comment by akhilleusuggo** [comment]
Pages are slow when browsing between pages on MyVideos

![image](https://user-images.githubusercontent.com/52116577/89819815-ae866300-db54-11ea-8fd4-8a0ec637cf7b.png)

**Comment by DanielnetoDotCom** [comment]
do you mean on the main page?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/89820084-1a68cb80-db55-11ea-9875-6185ec4af8fc.png)

**Comment by DanielnetoDotCom** [comment]
I am not caching and I could not see much difference.
anything on the log?

**Comment by akhilleusuggo** [comment]
```
[10-Aug-2020 19:07:27 UTC] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category,c.description as category_description, v.created as videoCreation, v.modified as videoModified,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes  FROM videos as v  LEFT JOIN categories c ON categories_id = c.id  LEFT JOIN users u ON v.users_id = u.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') ORDER BY FIND_IN_SET(v.id, '9,13,20,18,21,19,4,23,22,16,2,1') DESC, likes DESC  LIMIT 0, 12 ], , [], ] On  Line mysql_dal takes 2.9242 seconds to complete. /var/www/html/AVideo/view/index.php SCRIPT_NAME: /view/index.php
[10-Aug-2020 19:07:29 UTC] AVideoLog::DEBUG: Page generated in 9.122 seconds. User: BLABLA BLA
```

**Comment by akhilleusuggo** [comment]
This last log from welcome page ( 10s to load )

**Comment by DanielnetoDotCom** [comment]
that is an important log information, 1 min, let me analyze it.

**Comment by DanielnetoDotCom** [comment]
how many videos do you have?

**Comment by akhilleusuggo** [comment]
Sure , and when checking the My Videos page , a lot of logs .. Just a lot . This is only a small part of the log : 

```
[1] => Array
        (
            [file] => /var/www/html/AVideo/objects/video.php
            [line] => 752
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , 0 as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND v.id = 4183 LIMIT 1 LIMIT 1
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/AVideo/plugin/CustomizeAdvanced/CustomizeAdvanced.php
            [line] => 191
            [function] => getVideo
            [class] => Video
            [type] => ::
            [args] => Array
                (
                    [0] => 0
                    [1] => viewable
                    [2] => 1
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/AVideo/plugin/AVideoPlugin.php
            [line] => 630
            [function] => getModeYouTube
            [class] => CustomizeAdvanced
            [object] => CustomizeAdvanced Object
                (
                )

            [type] => ->
            [args] => Array
                (
                    [0] => 
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/AVideo/view/modeYoutube.php
            [line] => 282
            [function] => getModeYouTube
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => 
                )

        )

    [5] => Array
        (
            [file] => /var/www/html/AVideo/view/index.php
            [line] => 25
            [args] => Array
                (
                    [0] => /var/www/html/AVideo/view/modeYoutube.php
                )

            [function] => require
        )

)
 SCRIPT_NAME: /view/index.php
[10-Aug-2020 19:10:27 UTC] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1<br>
SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , 0 as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND v.id = 4183 LIMIT 1 LIMIT 1 SCRIPT_NAME: /view/index.php
```

**Comment by akhilleusuggo** [comment]
I have around 4000 videos

**Comment by akhilleusuggo** [comment]
I've lost around 30 after the update on the crash ( because they were on transfer )

**Comment by akhilleusuggo** [comment]
`[10-Aug-2020 19:14:04 UTC] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1130 takes 20.4104 seconds to complete. /var/www/html/AVideo/view/charts.php SCRIPT_NAME: /view/charts.php`

20s xD

**Comment by DanielnetoDotCom** [comment]
this this update

Slowness on charts.php is expected

**Comment by akhilleusuggo** [comment]
I'll leave a feedback on 5mn . I need to reboot the server before it crashes again ... 30gb RAM/32 used
