### ISSUE TITLE
Site Broke after Update

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3718]
After taking todays upload, I now just get a white screen.

avideo.log

[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 134
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'AVideo.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1 - format=s values=["IP_ADDRESS"]
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/Objects/IP2Location.php
            [line] => 29
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
                    [1] => s
                    [2] => Array
                        (
                            [0] => IP_ADDRESS
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/User_Location.php
            [line] => 68
            [function] => getLocation
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                    [0] => IP_ADDRESS
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 327
            [function] => getThisUserLocation
            [class] => User_Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 342
            [function] => getCacheDir
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 289
            [function] => getCacheFileName
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [6] => Array
        (
            [file] => /var/www/AVideo/objects/plugin.php
            [line] => 136
            [function] => getCache
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                    [1] => 0
                )

        )

    [7] => Array
        (
            [file] => /var/www/AVideo/plugin/Plugin.abstract.php
            [line] => 101
            [function] => getPluginByUUID
            [class] => Plugin
            [type] => ::
            [args] => Array
                (
                    [0] => 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [8] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 322
            [function] => getDataObject
            [class] => PluginAbstract
            [object] => CustomizeAdvanced Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [9] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 309
            [function] => getDataObject
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [10] => Array
        (
            [file] => /var/www/AVideo/objects/include_config.php
            [line] => 124
            [function] => getObjectData
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [11] => Array
        (
            [file] => /var/www/AVideo/videos/configuration.php
            [line] => 44
            [args] => Array
                (
                    [0] => /var/www/AVideo/objects/include_config.php
                )

            [function] => require_once
        )

    [12] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 12
            [args] => Array
                (
                    [0] => /var/www/AVideo/videos/configuration.php
                )

            [function] => require_once
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'AVideo.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1 - format=s values=["IP_ADDRESS"] SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 135
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] trying close and reconnect
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/Objects/IP2Location.php
            [line] => 29
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
                    [1] => s
                    [2] => Array
                        (
                            [0] => IP_ADDRESS
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/User_Location.php
            [line] => 68
            [function] => getLocation
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                    [0] => IP_ADDRESS
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 327
            [function] => getThisUserLocation
            [class] => User_Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 342
            [function] => getCacheDir
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 289
            [function] => getCacheFileName
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [6] => Array
        (
            [file] => /var/www/AVideo/objects/plugin.php
            [line] => 136
            [function] => getCache
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                    [1] => 0
                )

        )

    [7] => Array
        (
            [file] => /var/www/AVideo/plugin/Plugin.abstract.php
            [line] => 101
            [function] => getPluginByUUID
            [class] => Plugin
            [type] => ::
            [args] => Array
                (
                    [0] => 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [8] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 322
            [function] => getDataObject
            [class] => PluginAbstract
            [object] => CustomizeAdvanced Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [9] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 309
            [function] => getDataObject
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [10] => Array
        (
            [file] => /var/www/AVideo/objects/include_config.php
            [line] => 124
            [function] => getObjectData
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [11] => Array
        (
            [file] => /var/www/AVideo/videos/configuration.php
            [line] => 44
            [args] => Array
                (
                    [0] => /var/www/AVideo/objects/include_config.php
                )

            [function] => require_once
        )

    [12] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 12
            [args] => Array
                (
                    [0] => /var/www/AVideo/videos/configuration.php
                )

            [function] => require_once
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: [sqlDAL::readSql] trying close and reconnect SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 140
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed again return false
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/Objects/IP2Location.php
            [line] => 29
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
                    [1] => s
                    [2] => Array
                        (
                            [0] => IP_ADDRESS
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/User_Location.php
            [line] => 68
            [function] => getLocation
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                    [0] => IP_ADDRESS
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 327
            [function] => getThisUserLocation
            [class] => User_Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 342
            [function] => getCacheDir
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 289
            [function] => getCacheFileName
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [6] => Array
        (
            [file] => /var/www/AVideo/objects/plugin.php
            [line] => 136
            [function] => getCache
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                    [1] => 0
                )

        )

    [7] => Array
        (
            [file] => /var/www/AVideo/plugin/Plugin.abstract.php
            [line] => 101
            [function] => getPluginByUUID
            [class] => Plugin
            [type] => ::
            [args] => Array
                (
                    [0] => 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                )

        )

    [8] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 322
            [function] => getDataObject
            [class] => PluginAbstract
            [object] => CustomizeAdvanced Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [9] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 309
            [function] => getDataObject
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [10] => Array
        (
            [file] => /var/www/AVideo/objects/include_config.php
            [line] => 124
            [function] => getObjectData
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                    [0] => CustomizeAdvanced
                )

        )

    [11] => Array
        (
            [file] => /var/www/AVideo/videos/configuration.php
            [line] => 44
            [args] => Array
                (
                    [0] => /var/www/AVideo/objects/include_config.php
                )

            [function] => require_once
        )

    [12] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 12
            [args] => Array
                (
                    [0] => /var/www/AVideo/videos/configuration.php
                )

            [function] => require_once
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Undefined index: country_code in /var/www/AVideo/objects/Object.php on line 329
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 153
            [function] => log_error
            [args] => Array
                (
                    [0] => Error in readSql (mysqlnd): (1146) Table 'AVideo.videos_reported' doesn't exist, SQL-CMD:SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id';
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/plugin/ReportVideo/Objects/videos_reported.php
            [line] => 55
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id';
                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/ReportVideo/ReportVideo.php
            [line] => 252
            [function] => getAllReportedUsersIdFromUser
            [class] => VideosReported
            [type] => ::
            [args] => Array
                (
                    [0] => 1
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/objects/user.php
            [line] => 2083
            [function] => isBlocked
            [class] => ReportVideo
            [type] => ::
            [args] => Array
                (
                    [0] => 3
                    [1] => 1
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/view/modeYoutube.php
            [line] => 331
            [function] => hasBlockedUser
            [class] => User
            [type] => ::
            [args] => Array
                (
                    [0] => 3
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 25
            [args] => Array
                (
                    [0] => /var/www/AVideo/view/modeYoutube.php
                )

            [function] => require
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Error in readSql (mysqlnd): (1146) Table 'AVideo.videos_reported' doesn't exist, SQL-CMD:SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id'; SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 210
            [function] => log_error
            [args] => Array
                (
                    [0] => Error in readSql (no mysqlnd): (1146) Table 'AVideo.videos_reported' doesn't exist, SQL-CMD:SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id';
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 157
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id';
                    [1] =>
                    [2] => Array
                        (
                        )

                    [3] =>
                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/ReportVideo/Objects/videos_reported.php
            [line] => 55
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id';
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/plugin/ReportVideo/ReportVideo.php
            [line] => 252
            [function] => getAllReportedUsersIdFromUser
            [class] => VideosReported
            [type] => ::
            [args] => Array
                (
                    [0] => 1
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/objects/user.php
            [line] => 2083
            [function] => isBlocked
            [class] => ReportVideo
            [type] => ::
            [args] => Array
                (
                    [0] => 3
                    [1] => 1
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/view/modeYoutube.php
            [line] => 331
            [function] => hasBlockedUser
            [class] => User
            [type] => ::
            [args] => Array
                (
                    [0] => 3
                )

        )

    [6] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 25
            [args] => Array
                (
                    [0] => /var/www/AVideo/view/modeYoutube.php
                )

            [function] => require
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Error in readSql (no mysqlnd): (1146) Table 'AVideo.videos_reported' doesn't exist, SQL-CMD:SHOW COLUMNS FROM `videos_reported` LIKE 'reported_users_id'; SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Trying to get property 'nCols' of non-object in /var/www/AVideo/objects/mysql_dal.php on line 391
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Trying to get property 'stmt' of non-object in /var/www/AVideo/objects/mysql_dal.php(397) : eval()'d code on line 1
[26-Sep-2020 11:18:57 America/Halifax] PHP Warning:  mysqli_stmt_bind_result() expects at least 2 parameters, 1 given in /var/www/AVideo/objects/mysql_dal.php(397) : eval()'d code on line 1
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: Array
(
    [0] => Array
        (
            [file] => /var/www/AVideo/objects/mysql_dal.php
            [line] => 198
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (no mysqlnd) Prepare failed: (1146) Table 'AVideo.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
                )

        )

    [1] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/Objects/IP2Location.php
            [line] => 29
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
                    [1] => s
                    [2] => Array
                        (
                            [0] => IP_ADDRESS
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/AVideo/plugin/User_Location/User_Location.php
            [line] => 68
            [function] => getLocation
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                    [0] => IP_ADDRESS
                )

        )

    [3] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 327
            [function] => getThisUserLocation
            [class] => User_Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 342
            [function] => getCacheDir
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/AVideo/objects/Object.php
            [line] => 289
            [function] => getCacheFileName
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin_getallenabled
                )

        )

    [6] => Array
        (
            [file] => /var/www/AVideo/objects/plugin.php
            [line] => 281
            [function] => getCache
            [class] => ObjectYPT
            [type] => ::
            [args] => Array
                (
                    [0] => plugin::getAllEnabled
                    [1] => 3600
                )

        )

    [7] => Array
        (
            [file] => /var/www/AVideo/plugin/AVideoPlugin.php
            [line] => 56
            [function] => getAllEnabled
            [class] => Plugin
            [type] => ::
            [args] => Array
                (
                )

        )

    [8] => Array
        (
            [file] => /var/www/AVideo/view/include/head.php
            [line] => 3
            [function] => getHeadCode
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                )

        )

    [9] => Array
        (
            [file] => /var/www/AVideo/view/modeYoutube.php
            [line] => 343
            [args] => Array
                (
                    [0] => /var/www/AVideo/view/include/head.php
                )

            [function] => include
        )

    [10] => Array
        (
            [file] => /var/www/AVideo/view/index.php
            [line] => 25
            [args] => Array
                (
                    [0] => /var/www/AVideo/view/modeYoutube.php
                )

            [function] => require
        )

)
 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] AVideoLog::ERROR: [sqlDAL::readSql] (no mysqlnd) Prepare failed: (1146) Table 'AVideo.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1 SCRIPT_NAME: /view/index.php
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Trying to get property 'nCols' of non-object in /var/www/AVideo/objects/mysql_dal.php on line 391
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Trying to get property 'stmt' of non-object in /var/www/AVideo/objects/mysql_dal.php(397) : eval()'d code on line 1
[26-Sep-2020 11:18:57 America/Halifax] PHP Warning:  mysqli_stmt_bind_result() expects at least 2 parameters, 1 given in /var/www/AVideo/objects/mysql_dal.php(397) : eval()'d code on line 1
[26-Sep-2020 11:18:57 America/Halifax] PHP Notice:  Trying to get property 'stmt' of non-object in /var/www/AVideo/objects/mysql_dal.php on line 228
[26-Sep-2020 11:18:57 America/Halifax] PHP Fatal error:  Uncaught Error: Call to a member function close() on null in /var/www/AVideo/objects/mysql_dal.php:228
Stack trace:
#0 /var/www/AVideo/plugin/User_Location/Objects/IP2Location.php(31): sqlDAL::close(false)
#1 /var/www/AVideo/plugin/User_Location/User_Location.php(68): IP2Location::getLocation('IP_ADDRESS')
#2 /var/www/AVideo/objects/Object.php(327): User_Location::getThisUserLocation()
#3 /var/www/AVideo/objects/Object.php(342): ObjectYPT::getCacheDir()
#4 /var/www/AVideo/objects/Object.php(289): ObjectYPT::getCacheFileName('plugin_getallen...')
#5 /var/www/AVideo/objects/plugin.php(281): ObjectYPT::getCache('plugin::getAllE...', 3600)
#6 /var/www/AVideo/plugin/AVideoPlugin.php(56): Plugin::getAllEnabled()
#7 /var/www/AVideo/view/include/head.php(3): AVideoPlugin::getHeadCode()
#8 /var/www/AVideo/view/modeYoutube.php(343): include('/var/www/AVideo...')
#9 /var/www/AVideo/view/index.php(25): require('/var/www/AVideo...')
#10 {main}
  thrown in /var/www/AVideo/objects/mysql_dal.php on line 228

Thanks

**Comment by DanielnetoDotCom** [comment]
I can see you are missing to install some tables.

Make sure you disable the plugin or install the user_location tables

**Comment by D-Spayre** [comment]
That seemed to fix it.

Thank you
