### ISSUE TITLE
Install a plugin but got error

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#4407]
We installed a plugin but get the following error:

[20-Jan-2021 08:14:59 US/Central] AVideoLog::DEBUG: user::login: noPass = , encodedPass = 1, this->user, admin 14.199.99.200 SCRIPT_NAME: /view/managerPlugins.php
[20-Jan-2021 08:14:59 US/Central] AVideoLog::DEBUG: encryptPasswordVerify: do not encrypt SCRIPT_NAME: /view/managerPlugins.php
[20-Jan-2021 08:14:59 US/Central] AVideoLog::DEBUG: user::login: onUserSignIn Done SCRIPT_NAME: /view/managerPlugins.php
[20-Jan-2021 08:14:59 US/Central] AVideoLog::DEBUG: user::recreateLoginFromCookie: do cookie-login: admin   result: 0 SCRIPT_NAME: /view/managerPlugins.php
[20-Jan-2021 08:14:59 US/Central] AVideoLog::DEBUG: success 1 SCRIPT_NAME: /view/managerPlugins.php
[20-Jan-2021 08:15:14 US/Central] PHP Fatal error:  Uncaught Error: Class 'PluginTags' not found in /var/www/YouPHPTube/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(14) : eval()'d code(1) : eval()'d code:10
Stack trace:
#0 /var/www/YouPHPTube/objects/plugin.php(211): VideoResolutionSwitcher->getTags()
#1 /var/www/YouPHPTube/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins(true)
#2 {main}
  thrown in /var/www/YouPHPTube/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(14) : eval()'d code(1) : eval()'d code on line 10

**Comment by akhilleusuggo** [comment]
Reupload the plugin , clear the cache , and **make sure** you **install** the update ! You should see a yellow bouton that allows you to install the new version of the plugin
