### ISSUE TITLE
Under Maintanance 

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4408]
I did a new installation and when I am on the site I have this message

![image](https://user-images.githubusercontent.com/39193219/105198800-58274280-5b3e-11eb-83e6-919496014f89.png)

![image](https://user-images.githubusercontent.com/39193219/105198756-46de3600-5b3e-11eb-8472-e067be8a3289.png)

```
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID CustomizeUser 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3 SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByName CustomizeUser SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID CustomizeAdvanced 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033 SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByName CustomizeAdvanced SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID Layout layout84-8f5a-4d1b-b912-172c608bf9e3 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID layout84-8f5a-4d1b-b912-172c608bf9e3 SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByName Layout SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID PlayerSkins e9a568e6-ef61-4dcc-aad0-0109e9be8e36 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID e9a568e6-ef61-4dcc-aad0-0109e9be8e36 SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByName PlayerSkins SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID Permissions Permissions-5ee8405eaaa16 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID Permissions-5ee8405eaaa16 SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: Plugin:deleteByName Permissions SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:15 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[20-Jan-2021 15:34:17 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:34:17 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:34:41 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:34:41 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:34:57 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:34:57 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:36:13 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:36:13 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:36:20 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:36:20 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:36:24 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/view/img/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_60084df8448a7.jpg, 100 SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:36:24 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_60084df8448a7.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:36:24 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_60084df8448a7.jpg SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:36:24 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_60084df8448a7.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2907
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: Start Login Request SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: redirectUri:  SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: same redirectUri: https://my site.tv/ SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: Password check new hash pass does not match, trying MD5 SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: Password check Old not encoded pass SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:31 Africa/Abidjan] AVideoLog::DEBUG: Password check Old found SCRIPT_NAME: /objects/login.json.php
[20-Jan-2021 15:36:32 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:36:32 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[20-Jan-2021 15:37:16 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/view/img/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_60084e2c521a1.jpg, 100 SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:37:16 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_60084e2c521a1.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:37:16 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_60084e2c521a1.jpg SCRIPT_NAME: /view/user.php
[20-Jan-2021 15:37:16 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_60084e2c521a1.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2907
[20-Jan-2021 15:37:22 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/view/img/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_60084e32036d2.jpg, 100 SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:22 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_60084e32036d2.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:22 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_60084e32036d2.jpg SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:22 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_60084e32036d2.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2907
[20-Jan-2021 15:37:22 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1004
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(1335): Video::getAllVideos()
#1 /var/www/html/AVideo/view/charts_head.php(26): Video::getAllVideosAsync()
#2 /var/www/html/AVideo/admin/index.php(181): include('...')
#3 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1004
[20-Jan-2021 15:37:22 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1004\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(1335): Video::getAllVideos()\n#1 \/var\/www\/html\/AVideo\/view\/charts_head.php(26): Video::getAllVideosAsync()\n#2 \/var\/www\/html\/AVideo\/admin\/index.php(181): include('...')\n#3 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1004} SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:27 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/view/img/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_60084e378f5dd.jpg, 100 SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:27 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_60084e378f5dd.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:27 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_60084e378f5dd.jpg SCRIPT_NAME: /admin/index.php
[20-Jan-2021 15:37:27 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_60084e378f5dd.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2907
[20-Jan-2021 15:37:27 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/view/charts_head.php(29): Video::getTotalVideos()
#1 /var/www/html/AVideo/admin/index.php(181): include('...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[20-Jan-2021 15:37:27 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/charts_head.php(29): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/admin\/index.php(181): include('...')\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /admin/index.php
```

**Comment by syldri** [comment]
I found the site is not compatible with PHP 8.1
