### ISSUE TITLE
undermaintanence

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4427]
hello @DanielnetoDotCom  I want to test with the php8.0 vertion I have this message

![image](https://user-images.githubusercontent.com/39193219/105567846-583d6300-5d35-11eb-8ace-5956c0a41f60.png)

```
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID CustomizeUser 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3 SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByName CustomizeUser SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID CustomizeAdvanced 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033 SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByName CustomizeAdvanced SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID Layout layout84-8f5a-4d1b-b912-172c608bf9e3 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID layout84-8f5a-4d1b-b912-172c608bf9e3 SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByName Layout SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID PlayerSkins e9a568e6-ef61-4dcc-aad0-0109e9be8e36 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID e9a568e6-ef61-4dcc-aad0-0109e9be8e36 SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByName PlayerSkins SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: plugin::getPluginByUUID Permissions Permissions-5ee8405eaaa16 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByUUID Permissions-5ee8405eaaa16 SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: Plugin:deleteByName Permissions SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:07 UTC] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /install/index.php
[23-Jan-2021 03:40:09 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[23-Jan-2021 03:40:09 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
[23-Jan-2021 03:40:50 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/view/img/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_600b9ac201164.jpg, 100 SCRIPT_NAME: /view/user.php
[23-Jan-2021 03:40:50 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_600b9ac201164.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/user.php
[23-Jan-2021 03:40:50 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_600b9ac201164.jpg SCRIPT_NAME: /view/user.php
[23-Jan-2021 03:40:50 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_600b9ac201164.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2910
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: Start Login Request SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: redirectUri:  SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: same redirectUri: https://my site.tv/ SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: Password check new hash pass does not match, trying MD5 SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: Password check Old not encoded pass SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::DEBUG: Password check Old found SCRIPT_NAME: /objects/login.json.php
[23-Jan-2021 03:40:54 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in /var/www/html/AVideo/objects/video.php:1464
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(797): Video::getTotalVideos()
#1 /var/www/html/AVideo/plugin/Gallery/view/topLogic.php(41): Video::getVideo()
#2 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(2): include('...')
#3 /var/www/html/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in /var/www/html/AVideo/objects/video.php on line 1464
[23-Jan-2021 03:40:54 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Video::getBlockedUsersIdsArray() cannot be called statically in \/var\/www\/html\/AVideo\/objects\/video.php:1464\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(797): Video::getTotalVideos()\n#1 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/topLogic.php(41): Video::getVideo()\n#2 \/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(2): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index.php(30): require('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1464} SCRIPT_NAME: /view/index.php
```

**Comment by DanielnetoDotCom** [comment]
Please try this

**Comment by syldri** [comment]
now I don't have access to the plugin

![image](https://user-images.githubusercontent.com/39193219/105568369-1f9f8880-5d39-11eb-8d77-569b11bd774d.png)

![image](https://user-images.githubusercontent.com/39193219/105568434-7c9b3e80-5d39-11eb-9f98-6578ab8473fc.png)

**Comment by syldri** [comment]
@DanielnetoDotCom I found the problem I renamed the plugin Socket

now I see all the plugins

![image](https://user-images.githubusercontent.com/39193219/105568668-7b6b1100-5d3b-11eb-86ad-b325cbee5180.png)

**Comment by syldri** [comment]
@DanielnetoDotCom  when i click on live again the problem under maintanence 

![image](https://user-images.githubusercontent.com/39193219/105568933-c7b75080-5d3d-11eb-94d4-08c33054396a.png)

**Comment by DanielnetoDotCom** [comment]
I see, probably Socket is a reserved word on PHP8.

I will refactor this plugin

**Comment by DanielnetoDotCom** [comment]
NVM, I will not refactor it.

The error seems to me is because you renamed the folder.

make a git pull again this error should go away, then update your LiveUsers plugin

your problem is the same as this https://github.com/WWBN/AVideo/issues/4426

**Comment by syldri** [comment]
I updated everything nothing changes

there is still this maintenance problem

![image](https://user-images.githubusercontent.com/39193219/105610970-f6234300-5db2-11eb-92a0-c6bf77acb384.png)

**Comment by DanielnetoDotCom** [comment]
This error is new to me, I am not sure where does it come from.

clear your cache, 
tell me in what exactly URL you are 
provide a more complete log

**Comment by syldri** [comment]
I put the log here

https://github.com/WWBN/AVideo/issues/4428#issuecomment-766178412

**Comment by syldri** [comment]
when I click on a video I have this


![image](https://user-images.githubusercontent.com/39193219/105616387-c6863200-5dd6-11eb-95f9-a806bbfcca44.png)



```
thrown in /var/www/html/AVideo/plugin/Live/report.php on line 11
[23-Jan-2021 22:38:06 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method LiveTransmitionHistory::getAllFromUser() cannot be called statically in \/var\/www\/html\/AVideo\/plugin\/Live\/report.php:11\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/Live\/Live.php(640): include()\n#1 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(97): Live->getChartContent()\n#2 \/var\/www\/html\/AVideo\/view\/charts_body.php(33): AVideoPlugin::getChartContent()\n#3 \/var\/www\/html\/AVideo\/admin\/index.php(281): include('...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/Live\/report.php","line":11} SCRIPT_NAME: /admin/index.php
[23-Jan-2021 22:53:53 UTC] AVideoLog::DEBUG: Cache::isREQUEST_URIWhitelisted: (plugin/Live/on_) is whitelisted SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish POST: {"app":"live","flashver":"FMLE\/3.0 (compatible; FMSc\/1.0)","swfurl":"rtmp:\/\/my site.tv\/live?p=4b6c4104654e0359ecf7a43822c4a764","tcurl":"rtmp:\/\/my site.tv\/live?p=4b6c4104654e0359ecf7a43822c4a764","pageurl":"","addr":"90.15.163.216","clientid":"29","call":"publish","name":"600ba8e7b2f93","type":"live","redirectUri":""} SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish GET: [] SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish php://inputapp=live&flashver=FMLE/3.0%20(compatible%3B%20FMSc/1.0)&swfurl=rtmp://my site.tv/live%3Fp=4b6c4104654e0359ecf7a43822c4a764&tcurl=rtmp://my site.tv/live%3Fp=4b6c4104654e0359ecf7a43822c4a764&pageurl=&addr=90.15.163.216&clientid=29&call=publish&name=600ba8e7b2f93&type=live SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish parse_url: {"scheme":"rtmp","host":"my site.tv","path":"\/live","query":"p=4b6c4104654e0359ecf7a43822c4a764"} SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish parse_str: {"p":"4b6c4104654e0359ecf7a43822c4a764"} SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish check if key exists (600ba8e7b2f93) SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish key exists return {"id":1,"user":"admin","name":"","email":"my site@gmail.com","password":"4b6c4104654e0359ecf7a43822c4a764","created":"2021-01-23 04:41:11","modified":"2021-01-23 22:47:03","isAdmin":1,"status":"a","photoURL":null,"lastLogin":"2021-01-23 20:45:49","recoverPass":null,"backgroundURL":null,"canStream":0,"canUpload":0,"canCreateMeet":null,"canViewChart":0,"about":"","channelName":"my site","emailVerified":0,"analyticsCode":null,"externalOptions":null,"first_name":null,"last_name":null,"address":null,"zip_code":null,"country":null,"region":null,"city":null,"donationLink":"","extra_info":null,"title":"Empty Title","public":1,"saveTransmition":0,"key":"600ba8e7b2f93","description":"","users_id":1,"categories_id":2,"showOnTV":0} SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish new User(1) SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish get LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish saving LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish saved LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish deciding ... SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: NGINX ON Publish success SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: Live:restream (https://demo-site.my site.tv/plugin/Live/standAloneFiles/restreamer.json.php) {"m3u8":"https:\/\/my site.tv:1978\/live\/600ba8e7b2f93\/index.m3u8","restreamerURL":"https:\/\/demo-site.my site.tv\/plugin\/Live\/standAloneFiles\/restreamer.json.php","restreamsDestinations":[],"token":"SUtEUktxd2doOHJaWENhTEU5cDYxK1JzckFNQURNTGNmMHRtOERQUkJ1bXNxaDhEVTZmcHVTWUp5c0NKZUNrWlFIN2E1R1F4OElQbnBxRktRQ0tockE9PQ==","users_id":1} SCRIPT_NAME: /plugin/Live/on_publish.php
[23-Jan-2021 22:53:53 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/m3u8.php?live_servers_id=1&uuid=b1N2YXU4N3pnMC83R2czejZqVUxUZz09) FROM: 185.41.152.161 Browser:  SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://my site.tv:1978/live/600ba8e7b2f93/index.m3u8, /var/www/html/AVideo/videos/cache/YPTurl_get_contents/968ec3c5feba6011e40715a5a8ecd729 SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:53:53 Africa/Abidjan] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://my site.tv:1978/live/600ba8e7b2f93.m3u8, /var/www/html/AVideo/videos/cache/YPTurl_get_contents/b3d612a8060ee19d389c7db73a31713c SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:53:53 Africa/Abidjan] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0
[23-Jan-2021 22:54:03 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/m3u8.php?live_servers_id=1&uuid=b1N2YXU4N3pnMC83R2czejZqVUxUZz09) FROM: 185.41.152.161 Browser:  SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:54:03 Africa/Abidjan] PHP Warning:  Undefined array key "live_servers_id" in /var/www/html/AVideo/plugin/Live/Live.php on line 1112
[23-Jan-2021 22:54:03 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/m3u8.php?live_servers_id=1&uuid=b1N2YXU4N3pnMC83R2czejZqVUxUZz09) FROM: 185.41.152.161 Browser:  SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:54:03 Africa/Abidjan] AVideoLog::DEBUG: isLiveFromKey:  SCRIPT_NAME: /plugin/Live/index.php
[23-Jan-2021 22:54:03 Africa/Abidjan] AVideoLog::DEBUG: m3u8: https://my site.tv/plugin/Live/m3u8.php?live_servers_id=1&uuid=b1N2YXU4N3pnMC83R2czejZqVUxUZz09 SCRIPT_NAME: /plugin/Live/index.php
[23-Jan-2021 22:54:03 Africa/Abidjan] AVideoLog::DEBUG: is200: 1 SCRIPT_NAME: /plugin/Live/index.php
[23-Jan-2021 22:54:05 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/m3u8.php?live_servers_id=1&uuid=b1N2YXU4N3pnMC83R2czejZqVUxUZz09) FROM: 185.41.152.161 Browser:  SCRIPT_NAME: /plugin/Live/m3u8.php
[23-Jan-2021 22:54:16 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/videos/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_600ca9184586a.jpg, 100 SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:16 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_600ca9184586a.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:16 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_600ca9184586a.jpg SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:16 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_600ca9184586a.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2910
[23-Jan-2021 22:54:20 Africa/Abidjan] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in /var/www/html/AVideo/objects/user.php on line 417
[23-Jan-2021 22:54:20 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 10 seconds exceeded","file":"\/var\/www\/html\/AVideo\/objects\/user.php","line":417} SCRIPT_NAME: /plugin/Live/stats.json.php
[23-Jan-2021 22:54:26 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/videos/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_600ca92282461.jpg, 100 SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:26 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_600ca92282461.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:26 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_600ca92282461.jpg SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:26 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_600ca92282461.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2910
[23-Jan-2021 22:54:32 Africa/Abidjan] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in /var/www/html/AVideo/objects/mysql_dal.php on line 133
[23-Jan-2021 22:54:32 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 10 seconds exceeded","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":133} SCRIPT_NAME: /plugin/Live/stats.json.php
[23-Jan-2021 22:54:33 Africa/Abidjan] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/AVideo/videos/favicon.png, /var/www/html/AVideo/videos/cache/_jpg_600ca9299e6b2.jpg, 100 SCRIPT_NAME: /view/channels.php
[23-Jan-2021 22:54:33 Africa/Abidjan] AVideoLog::DEBUG: im_resizeV2: /var/www/html/AVideo/videos/cache/_jpg_600ca9299e6b2.jpg, /var/www/html/AVideo/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/channels.php
[23-Jan-2021 22:54:33 Africa/Abidjan] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/AVideo/videos/cache/_jpg_600ca9299e6b2.jpg SCRIPT_NAME: /view/channels.php
[23-Jan-2021 22:54:33 Africa/Abidjan] PHP Warning:  unlink(/var/www/html/AVideo/videos/cache/_jpg_600ca9299e6b2.jpg): No such file or directory in /var/www/html/AVideo/objects/functions.php on line 2910
[23-Jan-2021 22:54:36 UTC] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /var/www/html/AVideo/objects/functions.php:3388
Stack trace:
#0 /var/www/html/AVideo/objects/functions.php(3388): mysqli->ping()
#1 /var/www/html/AVideo/objects/video.php(953): _mysql_connect()
#2 /var/www/html/AVideo/plugin/PlayLists/PlayLists.php(230): Video::getVideoFromCleanTitle()
#3 /var/www/html/AVideo/plugin/AVideoPlugin.php(541): PlayLists->getStart()
#4 /var/www/html/AVideo/objects/include_config.php(120): AVideoPlugin::getStart()
#5 /var/www/html/AVideo/videos/configuration.php(44): require_once('...')
#6 /var/www/html/AVideo/view/index.php(12): require_once('...')
#7 {main}
  thrown in /var/www/html/AVideo/objects/functions.php on line 3388
[23-Jan-2021 22:54:36 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: mysqli object is already closed in \/var\/www\/html\/AVideo\/objects\/functions.php:3388\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(3388): mysqli->ping()\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(953): _mysql_connect()\n#2 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(230): Video::getVideoFromCleanTitle()\n#3 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(541): PlayLists->getStart()\n#4 \/var\/www\/html\/AVideo\/objects\/include_config.php(120): AVideoPlugin::getStart()\n#5 \/var\/www\/html\/AVideo\/videos\/configuration.php(44): require_once('...')\n#6 \/var\/www\/html\/AVideo\/view\/index.php(12): require_once('...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":3388} SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:40 UTC] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /var/www/html/AVideo/objects/functions.php:3388
Stack trace:
#0 /var/www/html/AVideo/objects/functions.php(3388): mysqli->ping()
#1 /var/www/html/AVideo/objects/video.php(953): _mysql_connect()
#2 /var/www/html/AVideo/plugin/PlayLists/PlayLists.php(230): Video::getVideoFromCleanTitle()
#3 /var/www/html/AVideo/plugin/AVideoPlugin.php(541): PlayLists->getStart()
#4 /var/www/html/AVideo/objects/include_config.php(120): AVideoPlugin::getStart()
#5 /var/www/html/AVideo/videos/configuration.php(44): require_once('...')
#6 /var/www/html/AVideo/view/index.php(12): require_once('...')
#7 {main}
  thrown in /var/www/html/AVideo/objects/functions.php on line 3388
[23-Jan-2021 22:54:40 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: mysqli object is already closed in \/var\/www\/html\/AVideo\/objects\/functions.php:3388\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(3388): mysqli->ping()\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(953): _mysql_connect()\n#2 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(230): Video::getVideoFromCleanTitle()\n#3 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(541): PlayLists->getStart()\n#4 \/var\/www\/html\/AVideo\/objects\/include_config.php(120): AVideoPlugin::getStart()\n#5 \/var\/www\/html\/AVideo\/videos\/configuration.php(44): require_once('...')\n#6 \/var\/www\/html\/AVideo\/view\/index.php(12): require_once('...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":3388} SCRIPT_NAME: /view/index.php
[23-Jan-2021 22:54:42 Africa/Abidjan] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in /var/www/html/AVideo/objects/Object.php on line 350
[23-Jan-2021 22:54:42 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 10 seconds exceeded","file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":350} SCRIPT_NAME: /plugin/Live/stats.json.php
[23-Jan-2021 22:54:49 Africa/Abidjan] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in /var/www/html/AVideo/objects/functions.php on line 334
[23-Jan-2021 22:54:49 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 10 seconds exceeded","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":334} SCRIPT_NAME: /plugin/Live/stats.json.php
[23-Jan-2021 22:54:55 Africa/Abidjan] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in /var/www/html/AVideo/plugin/Live/Live.php on line 952
[23-Jan-2021 22:54:55 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 10 seconds exceeded","file":"\/var\/www\/html\/AVideo\/plugin\/Live\/Live.php","line":952} SCRIPT_NAME: /plugin/Live/stats.json.php
```
