### ISSUE TITLE
Upload via encoder doesn't work anymore after your last remote session

### ISSUE THREAD

**Issue by smartweekend** [WWBN/AVideo#4514]
Hi Daniel. I's smarty from Rap***.tv  streamer and encoder are on on "cloudflare"and yes it opens: https://jquery-file-upload.appspot.com. But Even if i'm trying to upload 9MB file. i get: {"files":[{"error":"File is too big","type":"video/mp4","name":"rapt***_ad3.mp4","size":9940433}]} or if im logging via IP and http - the screen shows normal upload screen with square icon, but nothing happens after i press upload
any solution on your min?

log from encoder:
tail -n 200 -f /var/www/html/videos/avideo.log
[07-Feb-2021 14:20:54 America/New_York] logoff:: done session_id = vhlaec98q709c4tm4v4i2o27kt
[07-Feb-2021 14:20:54 America/New_York] https://beta.****/ == https://beta.****/
[07-Feb-2021 14:20:54 America/New_York] login.json: Login::run
[07-Feb-2021 14:20:54 America/New_York] Login::run (smartweekend, ***, https://beta.****/, true)
[07-Feb-2021 14:20:55 America/New_York] Login::run got an object
[07-Feb-2021 14:20:55 America/New_York] createIfNotExists:: s***
[07-Feb-2021 14:20:55 America/New_York] Verification Start https://beta.****/
[07-Feb-2021 14:20:55 America/New_York] Verification Creating the Cache https://beta.****/
[07-Feb-2021 14:20:55 America/New_York] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fbeta.*****%2F): {"msg":["Start","https:\/\/*****\/ Site verified"],"verified":true,"status":"a"}
[07-Feb-2021 14:20:55 America/New_York] Login:: almost done
[07-Feb-2021 14:20:55 America/New_York] Login:: done session_id = vhlaec98q709c4tm4v4i2o27kt session_login true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:20:55 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] http://69.***.188/ == https://beta.r**.tv/
[07-Feb-2021 14:23:13 America/New_York] http://69.***.188/ == http://69.***.188/
[07-Feb-2021 14:23:13 America/New_York] login.json: Login::run
[07-Feb-2021 14:23:13 America/New_York] Login::run (s***, ***, http://69.***.188, false)
[07-Feb-2021 14:23:13 America/New_York] Login::run got an object
[07-Feb-2021 14:23:13 America/New_York] createIfNotExists:: s***
[07-Feb-2021 14:23:13 America/New_York] Verification Start http://69.***.188/
[07-Feb-2021 14:23:13 America/New_York] Verification Creating the Cache http://69.***.188/
[07-Feb-2021 14:23:13 America/New_York] Verification Response (https://search.avideo.com/verify.php?url=http%3A%2F%2F69.***.188%2F): {"msg":["Start","http:\/\/69.***188\/ Site verified"],"verified":true,"status":"a"}
[07-Feb-2021 14:23:13 America/New_York] Login:: almost done
[07-Feb-2021 14:23:13 America/New_York] Login:: done session_id = ov1h8q969n2dpu3ts9caal1se2 session_login true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:13 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:23:34 America/New_York] Upload.php will set format
[07-Feb-2021 14:23:34 America/New_York] Upload.php will let function decide decideFormatOrder
[07-Feb-2021 14:23:34 America/New_York] decideFormatOrder: {"file":"ra***_ad3.mp4","audioOnly":"false","spectrum":"false","webm":"false","inputHLS":"false","inputLow":"false","inputSD":"false","inputHD":"false","inputAutoHLS":"false","inputAutoMP4":"true","inputAutoWebm":"false","inputAutoAudio":"false","title":"test test test","description":"atest","categories_id":27,"PHPSESSID":"ov1h8q969n2dpu3ts9caal1se2"}
[07-Feb-2021 14:23:34 America/New_York] decideFormatOrder: auto MP4
[07-Feb-2021 14:23:34 America/New_York] AVideo-Encoder Format::getFromOrder(7)
[07-Feb-2021 14:23:34 America/New_York] Encoder::sendFile videos_id=0, format=mp4
[07-Feb-2021 14:23:34 America/New_York] Encoder::sendFile sending file to http://69.******.188/aVideoEncoder.json
[07-Feb-2021 14:23:34 America/New_York] Encoder::sendFile reading file from 
[07-Feb-2021 14:23:34 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/objects/Encoder.php:932
Stack trace:
#0 /var/www/html/view/upload.php(101): Encoder::sendFile()
#1 /var/www/html/view/jquery-file-upload/server/php/fileuploadchunkdone.php(30): require_once('/var/www/html/v...')
#2 {main}
  thrown in /var/www/html/objects/Encoder.php on line 932
[07-Feb-2021 14:24:40 America/New_York] logoff:: done session_id = vhlaec98q709c4tm4v4i2o27kt
[07-Feb-2021 14:24:40 America/New_York] https://beta.r**.tv/ == https://beta.r**.tv/
[07-Feb-2021 14:24:40 America/New_York] login.json: Login::run
[07-Feb-2021 14:24:40 America/New_York] Login::run (s******, ***, https://beta.r**.tv/, true)
[07-Feb-2021 14:24:41 America/New_York] Login::run got an object
[07-Feb-2021 14:24:41 America/New_York] createIfNotExists:: s***
[07-Feb-2021 14:24:41 America/New_York] Verification Start https://beta.r**.tv/
[07-Feb-2021 14:24:41 America/New_York] Verification GetFrom Cache https://beta.r**.tv/
[07-Feb-2021 14:24:41 America/New_York] Verification Response (): {"msg":["Start","https:\/\/******\/ Site verified"],"verified":true,"status":"a"}
[07-Feb-2021 14:24:41 America/New_York] Login:: almost done
[07-Feb-2021 14:24:41 America/New_York] Login:: done session_id = vhlaec98q709c4tm4v4i2o27kt session_login true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true
[07-Feb-2021 14:24:41 America/New_York] isLogged:: session_login = true

**Comment by DanielnetoDotCom** [comment]
Fix this 

`PHP Fatal error: Uncaught Error: Call to undefined function curl_init()`

use Google to find a fix.
