### ISSUE TITLE
Uncaught Error: mysqli object is already closed

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4530]
So suddenly my encoder was able to connect to the streamer site and now when I try to view a video, I get an under maintenance screen and then see this in the logs...

```
 [09-Feb-2021 02:39:23 America/Chicago] AVideoLog::DEBUG: im_resize: Source not found: /var/www/vhosts/www.mysite.com/httpdocs/videos/cache/_jpg_60224a3bf2f0d.jpg SCRIPT_NAME: /view/iframe.php

 [09-Feb-2021 02:39:23 America/Chicago] AVideoLog::DEBUG: im_resizeV2: /var/www/vhosts/www.mysite.com/httpdocs/videos/cache/_jpg_60224a3bf2f0d.jpg, /var/www/vhosts/www.mysite.com/httpdocs/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/iframe.php

 [09-Feb-2021 02:39:23 America/Chicago] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/vhosts/www.mysite.com/httpdocs/videos/favicon.png, /var/www/vhosts/www.mysite.com/httpdocs/videos/cache/_jpg_60224a3bf2f0d.jpg, 100 SCRIPT_NAME: /view/iframe.php

[09-Feb-2021 02:39:23 America/Chicago] PHP Warning:  unlink(/var/www/vhosts/www.mysite.com/httpdocs/videos/cache/_jpg_60224a3bf2f0d.jpg): No such file or directory in /var/www/vhosts/www.mysite.com/httpdocs/objects/functions.php on line 2931

 [09-Feb-2021 02:39:12 America/Chicago] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: mysqli object is already closed in \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/functions.php:3410\nStack trace:\n#0 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/functions.php(3410): mysqli->ping()\n#1 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(952): _mysql_connect()\n#2 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(2490): Video::getVideoFromCleanTitle()\n#3 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(1619): Video::isOwnerFromCleanTitle()\n#4 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(1477): Video::getViewableStatus()\n#5 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(791): Video::getTotalVideos()\n#6 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/video.php(2554): Video::getVideo()\n#7 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/view\/modeYoutube.php(201): Video::getRandom()\n#8 \/var\/www\/vhosts\/www.mysite.com\/httpdocs\/view\/index.php(28): require('...')\n#9 {main}\n  thrown","file":"\/var\/www\/vhosts\/www.mysite.com\/httpdocs\/objects\/functions.php","line":3410} SCRIPT_NAME: /view/index.php
```

**Comment by KamillaPup** [comment]
So I switched back to PHP 7.4.15 and it works now. Is 8.0.2 officially supported yet?

**Comment by DanielnetoDotCom** [comment]
at least on my side it is not fully tested on PHP v8

**Comment by Oswal-1** [comment]
ayuda
