### ISSUE TITLE
Enabling LiveLinks Plugin crashes site

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4871]
After enabling the LiveLinks plugin the first site doesn't load anymore.

Here is the log:

[04-Apr-2021 22:54:13 Europe/Berlin] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method LiveUsers::getWatchingNowLabel() in \/var\/www\/AVideo\/objects\/functions.php:6159\nStack trace:\n#0 \/var\/www\/AVideo\/plugin\/LiveLinks\/LiveLinks.php(151): getLiveUsersLabelLiveLinks()\n#1 \/var\/www\/AVideo\/plugin\/AVideoPlugin.php(729): LiveLinks->getLiveApplicationArray()\n#2 \/var\/www\/AVideo\/objects\/functions.php(6065): AVideoPlugin::getLiveApplicationArray()\n#3 \/var\/www\/AVideo\/plugin\/Live\/view\/menuRight.php(441): getStatsNotifications()\n#4 \/var\/www\/AVideo\/plugin\/Live\/Live.php(49): include('\/var\/www\/AVideo...')\n#5 \/var\/www\/AVideo\/plugin\/AVideoPlugin.php(238): Live->getHTMLMenuRight()\n#6 \/var\/www\/AVideo\/view\/include\/navbar.php(421): AVideoPlugin::getHTMLMenuRight()\n#7 \/var\/www\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(15): include('\/var\/www\/AVideo...')\n#8 \/var\/www\/AVideo\/view\/index.php(30): require('\/var\/www\/AVideo...')\n#9 {main}\n  thrown","file":"\/var\/www\/AVideo\/objects\/functions.php","line":6159} SCRIPT_NAME: /view/index.php

**Comment by DanielnetoDotCom** [comment]
Do you have the LiveUsers plugin? if does, please update it.

**Comment by morbificagent** [comment]
Oh yes, haven't seen that there was an update for that plugin. Sorry.

But eventually it would be helpful if there would be some check-routine that catches such dependency's before the site gets blank
 ;-)
