### ISSUE TITLE
getCDN error in VideoResolutionSwitcher plugin

### ISSUE THREAD

**Issue by denibal** [WWBN/AVideo#4894]
I purchased the VideoResolutionSwitcher plugin and uploaded it to Avideo inside localhost under Debian 10.9. When you enable the plugin and try to watch the video on the hosting, the inscription "Under Maintanance" is displayed. 
In the logs I see the following:

`[08-Apr-2021 12:18:45 Africa/Abidjan] AVideoLog::DEBUG: plugin::setCurrentVersionByUuid 4b9142c0-f0c3-42be-8fe5-a4775111239c, 2.6 SCRIPT_NAME: /AVideo/objects/pluginSwitch.json.php
[08-Apr-2021 12:18:45 Africa/Abidjan] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /AVideo/objects/plug
inSwitch.json.php
[08-Apr-2021 12:18:57 Africa/Abidjan] AVideoLog::DEBUG: plugin::setCurrentVersionByUuid 4b9142c0-f0c3-42be-8fe5-a4775111239c, 2.6 SCRIPT_NAME: /AVideo/objects/pluginSwitch.json.php
[08-Apr-2021 12:18:57 Africa/Abidjan] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /AVideo/objects/plug
inSwitch.json.php
[08-Apr-2021 12:19:08 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Call to undefined function getCDN() in /var/www/html/AVideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.ph
p(18) : eval()'d code(1) : eval()'d code:38
Stack trace:
#0 /var/www/html/AVideo/plugin/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode()
#1 /var/www/html/AVideo/view/include/head.php(3): AVideoPlugin::getHeadCode()
#2 /var/www/html/AVideo/view/modeYoutube.php(356): include('/var/www/html/A...')
#3 /var/www/html/AVideo/view/index.php(28): require('/var/www/html/A...')
#4 {main}
  thrown in /var/www/html/AVideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code on line 38
[08-Apr-2021 12:19:08 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function getCDN() in \/var\/www\/html\/AVideo\/plugin\/VideoResolutionSwitcher
\/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code:38\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode()\n#1
\/var\/www\/html\/AVideo\/view\/include\/head.php(3): AVideoPlugin::getHeadCode()\n#2 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(356): include('\/var\/www\/html\/A...')\n#3 \/var\/www\
/html\/AVideo\/view\/index.php(28): require('\/var\/www\/html\/A...')\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/VideoResolutionSwitcher\/VideoResolutionSwitcher.php(18
) : eval()'d code(1) : eval()'d code","line":38} SCRIPT_NAME: /AVideo/view/index.php
`
I don't understand how to fix this, please help?

**Comment by DanielnetoDotCom** [comment]
I see, please update your streamer, this is a recent function.

**Comment by denibal** [comment]
Thanks, the git pull command helped!!!
![091201](https://user-images.githubusercontent.com/82157459/114127392-c4326f00-9913-11eb-8961-1aea3db1044c.png)

**Comment by denibal** [comment]
However, there is a problem, for some reason, if the user is not logged in, then there is no way to select the video quality. I couldn't find anything in the settings.

**Comment by DanielnetoDotCom** [comment]
Please clear the cache and try again

**Comment by denibal** [comment]
> Please clear the cache and try again

Thank you very much!
