### ISSUE TITLE
Customize plugin error

### ISSUE THREAD

**Issue by frgds** [WWBN/AVideo#4896]
hello i have problem with this plugin just installed  :
When i clic the customize Site  it go on  screen with  2 turning toothed wheels but nothing more append and in the log i ve this errors 

[08-Apr-2021 19:39:09 Africa/Abidjan] PHP Fatal error:  Uncaught Error: Call to undefined function getCDN() in /var/www/html/plugin/Customize/page/editor.php(18) : eval()'d code(1) : eval()'d code:20
Stack trace:
#0 /var/www/html/plugin/Customize/page/editor.php(18) : eval()'d code(1): eval()
#1 /var/www/html/plugin/Customize/page/editor.php(18): eval()
#2 {main}
  thrown in /var/www/html/plugin/Customize/page/editor.php(18) : eval()'d code(1) : eval()'d code on line 20
[08-Apr-2021 19:39:09 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function getCDN() in \/var\/www\/html\/plugin\/Customize\/page\/editor.php(18) : eval()'d code(1) : eval()'d code:20\nStack trace:\n#0 \/var\/www\/html\/plugin\/Customize\/page\/editor.php(18) : eval()'d code(1): eval()\n#1 \/var\/www\/html\/plugin\/Customize\/page\/editor.php(18): eval()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/plugin\/Customize\/page\/editor.php(18) : eval()'d code(1) : eval()'d code","line":20} SCRIPT_NAME: /plugin/Customize/page/editor.php.

**Comment by DanielnetoDotCom** [comment]
Update your streamer and you should be fine

**Comment by frgds** [comment]
What do you mean ? update the avideo script  ? my release  is 10.5.

**Comment by DanielnetoDotCom** [comment]
yes, make a git pull, there are updates to fix this

**Comment by frgds** [comment]
ok i will try

**Comment by frgds** [comment]
It's ok now thank
