### ISSUE TITLE
Plugins empty

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5085]
Hi,

I have migrated YouPHPTube to a new server and it seems to be working fine.

The only problem i'm facing is the plugins are not showing.  I only get the option to upload a plugin and visit the plugin store.

Nothing else is displayed where the plugins are normally displayed.   I suspect its a permission issue.

This is what I get in my error.log:
[07-May-2021 10:58:56 Europe/London] PHP Fatal error:  Uncaught Error: Class 'PluginTags' not found in /var/www/html/plugin/CDN/CDN.php:9
Stack trace:
#0 /var/www/html/objects/plugin.php(193): CDN->getTags()
#1 /var/www/html/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /var/www/html/plugin/CDN/CDN.php on line 9

my plugins folder perms are:
drwxr-xr-x+ 73 www-data www-data   4096 May  6 16:24 plugin

and all folders inside the plugins folder are owned by root, apart from MP4ThumbsAndGif and Blackblaze_B2 plugins which are owned by www-data www-data

The only thing is i'm using 8.3 at the moment because when i tested the latest version it runs really really slow and don't have time to look into why it's so slow atm.

**Comment by DanielnetoDotCom** [comment]
Hi, did you use git clone and git pull?

looks like you are missing some files.

also make sure you do not enable the CDN plugin yet

I strongly recommend you to stay on the laest version. (BTW, version 11 is much faster now)

**Comment by millzee01** [comment]
Hi, i used git clone.

On my old platform (which has been stable for a long time, i don't get this issue.

I don't use CDN_Link as I use b2_backblaze.

Is the latest version ok with b2_backblaze?  if so, i'll upgrade and test on my test server.  

What i dont get is that the server is working fine.  Just can't install the backup plugin :-)

**Comment by millzee01** [comment]
I don't think I can get it because my new account doesn't show it available for download.

For now, i just want to get my live server plugins to display then i'll be upgrade testing.

**Comment by millzee01** [comment]
@DanielnetoDotCom 

if https://newserver.mydomain.com/objects/pluginsAvailable.json.php is called, does it need to query an external source?

because I am testing a server migration in a dmz which doesn't allow external access.

If i call this script on my live server, i get a response.

If I call it on my new server (which is blocked from outside access) i get:

newserver.mydomain.com is currently unable to handle this request.
HTTP ERROR 500

Looking at the console, its trying to call the following endpoint:
https://plugins.avideo.com/plugins.json?jsonp=1&callback=jQuery33107599199231752848_1620395768418&_=1620395768419

which results in:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Is this by design?

**Comment by DanielnetoDotCom** [comment]
We need to query it to check for updates.

is not extemily necessary but that is how I can inform you if you need to update something.

**Comment by DanielnetoDotCom** [comment]
Not really. this is something you will need to manage in your network

**Comment by DanielnetoDotCom** [comment]
I guess the error 500 is something else.

 `PHP Fatal error: Uncaught Error: Class 'PluginTags' not found in /var/www/html/plugin/CDN/CDN.php:9`

The class exists check if you have the correct files

https://github.com/WWBN/AVideo/blob/de48e924fcb536e9b148191c2e5b3cb3fbc88f72/objects/plugin.php#L524-L542

**Comment by millzee01** [comment]
yeah, the class exists.  i'm going to move it to a live network and see if I get the same error.
