### ISSUE TITLE
After updating plugins, site is COMPLETELY DEAD please advise

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5087]
**Describe the bug**
Updated plug-ins as per documentation.
Site is now stone cold dead.
Displays "Maintenance mode" when maintenance mode is off.
Toggling "Maintenance mode" has no effect.

**To Reproduce**
1. Update plug-ins
2. Load site home page
3. !@#$%^&*()
4. Toggle maintenance mode
5. !@#$%^&*()_

**Expected behavior**
1. The !@#$%^&ing thing to work. 

**Actual behavior**

![Screen Shot 2021-05-07 at 3 14 01 PM](https://user-images.githubusercontent.com/11711050/117513590-e33e1400-af46-11eb-90a5-9ed8bc037e08.png)
![Screen Shot 2021-05-07 at 3 15 37 PM](https://user-images.githubusercontent.com/11711050/117513713-2b5d3680-af47-11eb-9cac-7ee537993ab2.png)
![Screen Shot 2021-05-07 at 3 15 43 PM](https://user-images.githubusercontent.com/11711050/117513721-2d26fa00-af47-11eb-87f9-3d9505f74206.png)
![Screen Shot 2021-05-07 at 3 15 48 PM](https://user-images.githubusercontent.com/11711050/117513725-2f895400-af47-11eb-986b-2aeec65ec1e6.png)
![Screen Shot 2021-05-07 at 3 15 58 PM](https://user-images.githubusercontent.com/11711050/117513728-30ba8100-af47-11eb-8e5a-21754db4026e.png)

**Comment by walt93** [comment]
How TF do you fix this?

I've got an old copy of the plug-ins directory, but, I've run all the plug-in scripts to update the database.

I updated like more than a dozen plug-ins.

This is <expletive deleted>

**Comment by walt93** [comment]
Looking around the admin pages, I can see that the database is *expletive deleted*, its randomly throwing errors.

![Screen Shot 2021-05-07 at 3 23 17 PM](https://user-images.githubusercontent.com/11711050/117514232-3cf30e00-af48-11eb-8ccf-423c11d119bc.png)

**Comment by walt93** [comment]
![Screen Shot 2021-05-07 at 3 27 06 PM](https://user-images.githubusercontent.com/11711050/117514469-c3a7eb00-af48-11eb-9488-56f345af9a06.png)

No idea what it's going on about. Websocket code is *expletive deleted*. Possibly orthogonal to the "maintenance mode" issue, given the stability issues, seems probable that I'm hitting multiple issues.

**Comment by walt93** [comment]
Disabling "Live" features (LiveLinks, LiveSearch, LiveUsers) does not change the above warning. It's fired every time opening the dashboard.

**Comment by walt93** [comment]
Cargo cult mentality doesn't help, honoring the ritual of Clear First Page Cache/Clear Cache Directory/Generate Sitemap actually seems to have *expletive deleted* the site even harder.

Generate Sitemap is not completing, still running the screensaver after five minutes.

Now I can no longer get to any administrative function, the site will not load the menu. Prior to *expletive deleted*ing the sitemap, I was able to get the top menu to display after a page reload. Now? Nothing. Nil. Null Zip. Zero. Zilch.

**Comment by walt93** [comment]
Logfile says the subtitle switcher is broken.

Rebuilding the sitemap completely *expletive deleted* my site. Now I cannot get back to the admin menu, cannot try to disable this plug-in.

[07-May-2021 22:38:52 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/video/4765/day-3_4_steven-lin_the-dental-diet-grow-a-happy-healthy-child?yptDeviceID=04897c9e-447f-4eb4-a589-2988d2878870&channelName=Conspyre) FROM: 5.9.70.117 Browser: Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/) SCRIPT_NAME: /view/index.php
[07-May-2021 22:38:52 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method Video::getPaths() in \/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code:125\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/SubtitleSwitcher.php(18) : eval()'d code(1) : eval()'d code(71): getVTTTracks('_YPTuniqid_606a...', true)\n#1 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1351): SubtitleSwitcher::getVideoTags(4765)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(2293): AVideoPlugin::getVideoTags(4765)\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(2077): Video::getTags_(4765, '')\n#4 \/var\/www\/html\/AVideo\/objects\/video.php(767): Video::getTags(4765)\n#5 \/var\/www\/html\/AVideo\/objects\/video.php(874): Video::getVideo(4765, '', true, false, false, true)\n#6 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(242): Video::getVideoFromCleanTitle('day-3_4_steven-...')\n#7 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(550): PlayLists->getStart()\n#8 \/var\/www\/html\/AVideo\/objects\/include_config.php(143): AVideoPlugin::getStart()\n#9 \/","file":"\/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code","line":125} SCRIPT_NAME: /view/index.php

**Comment by walt93** [comment]
!@#$%^&*()_ After an inordinate amount of *expletive deleted* I was able to get to the admin page. Literally crawling through directories looking for a foo.php that I could open by URL. Finally found one. Got in. Disabled SubtitleSwitcher. The site now seems to be working, I need to go thoroughly test everything now.

Trust with downloading updates is seriously just plain gone, man, it's gone…

**Comment by walt93** [comment]
https://user-images.githubusercontent.com/11711050/117516027-bf7dcc80-af4c-11eb-92b3-70c151701086.mov

**Comment by walt93** [comment]
No idea what in the *expletive deleted* is going on, but, the above recording resulted in the following log. Looks like disabling subtitle switcher, doesn't prevent your code from calling subtitle switcher, and since subtitle switcher is *expletive deleted*....

[07-May-2021 22:56:50 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/video/4868/human-rights-attorney-gives-3-min-of-vax-covid-jaw-dropping-truth?channelName=Conspyre) FROM: 207.46.13.37 Browser: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) SCRIPT_NAME: /view/index.php
[07-May-2021 15:56:51 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method Video::getPaths() in \/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code:125\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1400): getVTTTracks('_YPTuniqid_6059...', true)\n#1 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(276): getSources('_YPTuniqid_6059...', true)\n#2 \/var\/www\/html\/AVideo\/view\/index.php(36): require('\/var\/www\/html\/A...')\n#3 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code","line":125} SCRIPT_NAME: /view/index.php
[07-May-2021 15:56:52 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1157 takes 0.5497 seconds to complete, Limit (0.2). /var/www/html/AVideo/view/index.php SCRIPT_NAME: /view/index.php
[07-May-2021 15:56:53 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1157 takes 0.62 seconds to complete, Limit (0.24). /var/www/html/AVideo/view/index.php SCRIPT_NAME: /view/index.php
[07-May-2021 15:57:12 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method Video::getPaths() in \/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code:125\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1400): getVTTTracks('_YPTuniqid_604e...', true)\n#1 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(276): getSources('_YPTuniqid_604e...', true)\n#2 \/var\/www\/html\/AVideo\/view\/index.php(36): require('\/var\/www\/html\/A...')\n#3 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code","line":125} SCRIPT_NAME: /view/index.php

**Comment by DanielnetoDotCom** [comment]
`Uncaught Error: Call to undefined method Video::getPaths() `

means you are not running AVideo version 11 (https://github.com/WWBN/AVideo/issues/5075)

make a git pull

Then run the moveFilesToFolder.php (it will move all the files to its specific folder)

```
cd /var/www/html/AVideo/install
php moveFilesToFolder.php
```

Then remove the unused files (it will free some space)

```
cd /var/www/html/AVideo/install
php deleteOrphanFiles.php
```

**Comment by walt93** [comment]
Greatly relieved. 😅
