### ISSUE TITLE
All shared links are showing under maintenance 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5274]
@DanielnetoDotCom 
Major problems after latest git pull.
![Screenshot_20210606-182041_Samsung Internet](https://user-images.githubusercontent.com/70327833/120944897-27facd80-c6f4-11eb-9e53-08ae64aa03de.jpg)

**Comment by milehighkaraoke** [comment]
And the site is now super slow. This last pull has created some serious hiccups.....

**Comment by milehighkaraoke** [comment]
[06-Jun-2021 23:53:17 America/Denver] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/MHKTube/videos/favicon.png, /var/www/MHKTube/videos/cache/_jpg_60bdb44ddec5a.jpg, 100 SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:17 America/Denver] AVideoLog::DEBUG: im_resizeV2: /var/www/MHKTube/videos/cache/_jpg_60bdb44ddec5a.jpg, /var/www/MHKTube/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:17 America/Denver] AVideoLog::DEBUG: im_resize: Source not found: /var/www/MHKTube/videos/cache/_jpg_60bdb44ddec5a.jpg SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:17 America/Denver] PHP Warning:  unlink(/var/www/MHKTube/videos/cache/_jpg_60bdb44ddec5a.jpg): No such file or directory in /var/www/MHKTube/objects/functions.php on line 3140
[06-Jun-2021 23:53:17 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] AVideoLog::DEBUG: Video::getSourceFile(_YPTuniqid_607da4bdab26e0.67200556_1200, .mp4, ) ERROR video not found (_YPTuniqid_607da4bdab26e0.67200556_1200) SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] AVideoLog::DEBUG: Video::getSourceFile(_YPTuniqid_607da4c2d7b792.14530885_1200, .mp4, ) ERROR video not found (_YPTuniqid_607da4c2d7b792.14530885_1200) SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] AVideoLog::DEBUG: Video::getSourceFile(_YPTuniqid_607da4c4626053.79762639_1200, .mp4, ) ERROR video not found (_YPTuniqid_607da4c4626053.79762639_1200) SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] AVideoLog::DEBUG: Video::getSourceFile(_YPTuniqid_607fd8fe0beea4.61063310_1072, .mp4, ) ERROR video not found (_YPTuniqid_607fd8fe0beea4.61063310_1072) SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:19 America/Denver] PHP Warning:  Undefined variable $getStatistcs in /var/www/MHKTube/objects/video.php on line 759
[06-Jun-2021 23:53:20 America/Denver] AVideoLog::DEBUG: getStatsNotifications: 1 [{"file":"\/var\/www\/MHKTube\/plugin\/Live\/stats.json.php","line":26,"function":"getStatsNotifications","args":[]}] SCRIPT_NAME: /plugin/Live/stats.json.php
[06-Jun-2021 23:53:20 America/Denver] AVideoLog::DEBUG: Live::getStatsObject[0] 4: cache not found SCRIPT_NAME: /plugin/Live/stats.json.php
[06-Jun-2021 23:53:20 America/Denver] AVideoLog::DEBUG: Live::getStatsObject[0]: Creating a waitfile /var/www/MHKTube/videos/cache/a84fdc425fca22fe1f87e4a7a8db29b9 SCRIPT_NAME: /plugin/Live/stats.json.php
[06-Jun-2021 23:53:20 America/Denver] AVideoLog::DEBUG: 
***
Live::get_data(https://mhktube.com:444/stat, 4)
function: _error_log_debug Line: {755} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: get_data Line: {721} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: getStatsObject Line: {1167} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: _getStats Line: {968} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: getStats Line: {6228} File: {/var/www/MHKTube/objects/functions.php}
function: getStatsNotifications Line: {26} File: {/var/www/MHKTube/plugin/Live/stats.json.php}
*** SCRIPT_NAME: /plugin/Live/stats.json.php
[06-Jun-2021 23:53:20 America/Denver] AVideoLog::DEBUG: Live::createStatsCache {"bytes":155,"cachefile":"\/var\/www\/MHKTube\/videos\/cache\/YPTObjectCache\/getstats\/getstatsnotifications\/mhktube.com\/https\/admin_cc51034c46ce0a8b6c34d10a60b0f088\/58979bb35fe5df99900206b60a03e953.cache"} SCRIPT_NAME: /plugin/Live/stats.json.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::DEBUG: getStatsNotifications: 1 [{"file":"\/var\/www\/MHKTube\/plugin\/Live\/view\/menuRight.php","line":448,"function":"getStatsNotifications","args":[]},{"file":"\/var\/www\/MHKTube\/plugin\/Live\/Live.php","line":49,"args":["\/var\/www\/MHKTube\/plugin\/Live\/view\/menuRight.php"],"function":"include"},{"file":"\/var\/www\/MHKTube\/plugin\/AVideoPlugin.php","line":238,"function":"getHTMLMenuRight","class":"Live","object":{},"type":"->","args":[]},{"file":"\/var\/www\/MHKTube\/view\/include\/navbar.php","line":429,"function":"getHTMLMenuRight","class":"AVideoPlugin","type":"::","args":[]},{"file":"\/var\/www\/MHKTube\/view\/modeYoutube.php","line":373,"args":["\/var\/www\/MHKTube\/view\/include\/navbar.php"],"function":"include"},{"file":"\/var\/www\/MHKTube\/view\/index.php","line":36,"args":["\/var\/www\/MHKTube\/view\/modeYoutube.php"],"function":"require"}] SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::DEBUG: Live::getStatsObject[0] 4: cache not found SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::DEBUG: Live::getStatsObject[0]: Creating a waitfile /var/www/MHKTube/videos/cache/a84fdc425fca22fe1f87e4a7a8db29b9 SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::DEBUG: 
***
Live::get_data(https://mhktube.com:444/stat, 4)
function: _error_log_debug Line: {755} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: get_data Line: {721} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: getStatsObject Line: {1167} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: _getStats Line: {968} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: getStats Line: {6228} File: {/var/www/MHKTube/objects/functions.php}
function: getStatsNotifications Line: {448} File: {/var/www/MHKTube/plugin/Live/view/menuRight.php}
function: include Line: {49} File: {/var/www/MHKTube/plugin/Live/Live.php}
function: getHTMLMenuRight Line: {238} File: {/var/www/MHKTube/plugin/AVideoPlugin.php}
function: getHTMLMenuRight Line: {429} File: {/var/www/MHKTube/view/include/navbar.php}
function: include Line: {373} File: {/var/www/MHKTube/view/modeYoutube.php}
function: require Line: {36} File: {/var/www/MHKTube/view/index.php}
*** SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::DEBUG: Live::createStatsCache {"bytes":155,"cachefile":"\/var\/www\/MHKTube\/videos\/cache\/YPTObjectCache\/getstats\/getstatsnotifications\/mhktube.com\/https\/notlogged_f82e0d0d9d8d801bd12c0cfd0d54618d\/58979bb35fe5df99900206b60a03e953.cache"} SCRIPT_NAME: /view/index.php
[06-Jun-2021 23:53:32 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Attempt to assign property \"videoStartSeconds\" on string in \/var\/www\/MHKTube\/plugin\/PlayerSkins\/PlayerSkins.php:77\nStack trace:\n#0 \/var\/www\/MHKTube\/view\/include\/video.php(6): PlayerSkins::getMediaTag()\n#1 \/var\/www\/MHKTube\/view\/modeYoutubeTop.php(23): require('...')\n#2 \/var\/www\/MHKTube\/view\/modeYoutubeBundle.php(8): require('...')\n#3 \/var\/www\/MHKTube\/view\/modeYoutube.php(390): require('...')\n#4 \/var\/www\/MHKTube\/view\/index.php(36): require('...')\n#5 {main}\n  thrown","file":"\/var\/www\/MHKTube\/plugin\/PlayerSkins\/PlayerSkins.php","line":77} SCRIPT_NAME: /view/index.php

**Comment by milehighkaraoke** [comment]
https://www.mhktube.com/video/26/ac-dc-live-at-donington-1992-1080p?channelName=_607d8f37e6e2d

**Comment by Maikuolan** [comment]
Problem seems to originate from:

https://github.com/WWBN/AVideo/blob/a079ba0444756310f80c73da84876e01dace926d/objects/video.php#L759

*Commit: https://github.com/WWBN/AVideo/commit/a079ba0444756310f80c73da84876e01dace926d [[Git Blame](https://github.com/WWBN/AVideo/blame/master/objects/video.php#L759)].*

It seems, `public static function getVideo()` doesn't define `$getStatistcs` anywhere (other methods define it, but not that particular method). Probably need to just pull the necessary information from somewhere for that method, like with the others. I'm not sure exactly where it should be pulled from though.

**Comment by DanielnetoDotCom** [comment]
I just sent an update, can you please check?

**Comment by milehighkaraoke** [comment]
That fixed it. Thank you
