### ISSUE TITLE
não consigo sair do modo maintanance

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#5345]
Olá eu transferi os arquivos para um outro servidor e está me voltando esse erro. 

![maintanance](https://user-images.githubusercontent.com/7960434/123328601-29106500-d512-11eb-8766-880085c650ea.PNG)

e tambem tentei dar git pull e está achando o diretório.

![asdasdasd](https://user-images.githubusercontent.com/7960434/123328672-3fb6bc00-d512-11eb-845e-d46662eac7a0.PNG)

**Comment by DanielnetoDotCom** [comment]
parece que você não instalou usando o `git clone`, recomendo voce instalar novamente.

para encontrar errors use isto aqui https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by gabrielmais** [comment]
sim fiz a instalação pelo git clone

**Comment by DanielnetoDotCom** [comment]
então o git pull deveria funcionar  e o diretorio .git deveria existir.

por favor revise sua instalação

**Comment by gabrielmais** [comment]
[24-Jun-2021 20:15:42 UTC] AVideoLog::DEBUG: Plugin:deleteByName Scheduler SCRIPT_NAME: /imperialrecord/install/index.php
[24-Jun-2021 17:15:53 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in \/var\/www\/html\/imperialrecord\/objects\/functions.php:1755\nStack trace:\n#0 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3140): convertImage()\n#1 \/var\/www\/html\/imperialrecord\/objects\/configuration.php(251): convertImageToOG()\n#2 \/var\/www\/html\/imperialrecord\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3180): include('\/var\/www\/html\/i...')\n#4 \/var\/www\/html\/imperialrecord\/view\/include\/head.php(183): ogSite()\n#5 \/var\/www\/html\/imperialrecord\/plugin\/Gallery\/view\/modeGallery.php(11): include('\/var\/www\/html\/i...')\n#6 \/var\/www\/html\/imperialrecord\/view\/index.php(38): require('\/var\/www\/html\/i...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/imperialrecord\/objects\/functions.php","line":1755} SCRIPT_NAME: /imperialrecord/view/index.php
[24-Jun-2021 17:38:49 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in \/var\/www\/html\/imperialrecord\/objects\/functions.php:1755\nStack trace:\n#0 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3140): convertImage()\n#1 \/var\/www\/html\/imperialrecord\/objects\/configuration.php(251): convertImageToOG()\n#2 \/var\/www\/html\/imperialrecord\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3180): include('\/var\/www\/html\/i...')\n#4 \/var\/www\/html\/imperialrecord\/view\/include\/head.php(183): ogSite()\n#5 \/var\/www\/html\/imperialrecord\/plugin\/Gallery\/view\/modeGallery.php(11): include('\/var\/www\/html\/i...')\n#6 \/var\/www\/html\/imperialrecord\/view\/index.php(38): require('\/var\/www\/html\/i...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/imperialrecord\/objects\/functions.php","line":1755} SCRIPT_NAME: /imperialrecord/view/index.php
[24-Jun-2021 18:04:32 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in \/var\/www\/html\/imperialrecord\/objects\/functions.php:1755\nStack trace:\n#0 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3140): convertImage()\n#1 \/var\/www\/html\/imperialrecord\/objects\/configuration.php(251): convertImageToOG()\n#2 \/var\/www\/html\/imperialrecord\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3180): include('\/var\/www\/html\/i...')\n#4 \/var\/www\/html\/imperialrecord\/view\/include\/head.php(183): ogSite()\n#5 \/var\/www\/html\/imperialrecord\/plugin\/Gallery\/view\/modeGallery.php(11): include('\/var\/www\/html\/i...')\n#6 \/var\/www\/html\/imperialrecord\/view\/index.php(38): require('\/var\/www\/html\/i...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/imperialrecord\/objects\/functions.php","line":1755} SCRIPT_NAME: /imperialrecord/view/index.php
[24-Jun-2021 18:07:06 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in \/var\/www\/html\/imperialrecord\/objects\/functions.php:1755\nStack trace:\n#0 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3140): convertImage()\n#1 \/var\/www\/html\/imperialrecord\/objects\/configuration.php(251): convertImageToOG()\n#2 \/var\/www\/html\/imperialrecord\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/html\/imperialrecord\/objects\/functions.php(3180): include('\/var\/www\/html\/i...')\n#4 \/var\/www\/html\/imperialrecord\/view\/include\/head.php(183): ogSite()\n#5 \/var\/www\/html\/imperialrecord\/plugin\/Gallery\/view\/modeGallery.php(11): include('\/var\/www\/html\/i...')\n#6 \/var\/www\/html\/imperialrecord\/view\/index.php(38): require('\/var\/www\/html\/i...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/imperialrecord\/objects\/functions.php","line":1755} SCRIPT_NAME: /imperialrecord/view/index.php

**Comment by DanielnetoDotCom** [comment]
pre começar procure por este erro no google

`Uncaught Error: Call to undefined function imagecreatefrompng()`

aparentemente sua instalação do PHP está faltando algumas bibliotecas

**Comment by gabrielmais** [comment]
Consegui resolver o problema agora so tenho uma ultima coisa 
como eu reenstalei o avideo eu mudei o pasta raiz para uma dentro do "site" em especifico.... nas configurações de instalação eu coloquei tudo certinho o site "http://imperialtv.com.br/imperialrecord/ porem ele nao acha as "/" barras e fica como esta na imagem

![asfasf](https://user-images.githubusercontent.com/7960434/123342683-9f1ec700-d526-11eb-86ed-e9b975b94dec.PNG)

**Comment by DanielnetoDotCom** [comment]
O erro agora está duplicado https://github.com/WWBN/AVideo/issues/5345#issuecomment-868014649
