### ISSUE TITLE
Seeing a lot of "stuck" downloads for last two weeks in my encode queue

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5555]
**Describe the bug**
Perhaps 10% of the time encoding videos from YouTube and BitChute get stuck in the download phase and will never complete; must be manually cancelled.

**To Reproduce**
1. Stick ten YouTube/bitchute videos in the encode queue
2. Wait
3. Observe your encode queue stuck on downloading phase

**Expected behavior**
It not do that. Retry. Fail. Something. Not just sit there…

**Error Logs**
Here is the file that stalled

[14-Aug-2021 05:44:50 UTC] getTitleFromLink: Get Title: LC_ALL=en_US.UTF-8 /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --skip-download -e "https://www.youtube.com/watch?v=Kjz2HQtIZ1k"
Array
(
    [0] => WARNING: Writing cache to u'/var/www/.cache/youtube-dl/youtube-sigfuncs/js_50e823fc_105.json' failed: Traceback (most recent call last):
    [1] =>   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/cache.py", line 49, in store
    [2] =>     os.makedirs(os.path.dirname(fn))
    [3] =>   File "/usr/lib/python2.7/os.py", line 150, in makedirs
    [4] =>     makedirs(head, mode)
    [5] =>   File "/usr/lib/python2.7/os.py", line 150, in makedirs
    [6] =>     makedirs(head, mode)
    [7] =>   File "/usr/lib/python2.7/os.py", line 157, in makedirs
    [8] =>     mkdir(name, mode)
    [9] => OSError: [Errno 13] Permission denied: '/var/www/.cache'
    [10] =>
    [11] => Secret Mysteries of Americas Beginnings  Volume 2 - Riddles in Stone
)

[14-Aug-2021 05:44:50 UTC] decideFormatOrder: {"videoURL":"https:\/\/www.youtube.com\/watch?v=Kjz2HQtIZ1k","audioOnly":"false","spectrum":"false","webm":"false","override_status":"","update_video_id":"","inputHLS":"false","inputLow":"false","inputSD":"false","inputHD":"false","inputAutoHLS":"false","inputAutoMP4":"true","inputAutoWebm":"false","inputAutoAudio":"false","categories_id":16}
[14-Aug-2021 05:44:50 UTC] decideFormatOrder: auto MP4
[14-Aug-2021 05:44:50 UTC] AVideo-Encoder Format::getFromOrder(7)
[14-Aug-2021 05:44:50 UTC] Encoder::sendFile videos_id=0, format=mp4
[14-Aug-2021 05:44:53 UTC] Encoder::sendFile sending file to https://conspyre.tv/aVideoEncoder.json
[14-Aug-2021 05:44:53 UTC] Encoder::sendFile reading file from
[14-Aug-2021 05:44:53 UTC] AVideo-Streamer answer 1 {"error":false,"video_id":7948,"video_id_hash":"OU9qWnJlSDBwaUFUYTNwcm4zWWs5cERyS2RJaENJd1pKTEp2MXcwMmdDZz0="}
[14-Aug-2021 05:44:53 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Kjz2HQtIZ1k","target":"https:\/\/conspyre.tv\/aVideoEncoder.json","postFields":14,"response_raw":"{\"error\":false,\"video_id\":7948,\"video_id_hash\":\"OU9qWnJlSDBwaUFUYTNwcm4zWWs5cERyS2RJaENJd1pKTEp2MXcwMmdDZz0=\"}","response":{"error":false,"video_id":7948,"video_id_hash":"OU9qWnJlSDBwaUFUYTNwcm4zWWs5cERyS2RJaENJd1pKTEp2MXcwMmdDZz0="}}
[14-Aug-2021 05:44:53 UTC] Encoder::save id=() title=(Secret Mysteries of Americas Beginnings  Volume 2 - Riddles in Stone)
[14-Aug-2021 05:44:53 UTC] Encoder::save id=(249) title=(Secret Mysteries of Americas Beginnings  Volume 2 - Riddles in Stone)

**Comment by DanielnetoDotCom** [comment]
HI,

I can see this in your log 

`Permission denied: '/var/www/.cache'`

this is a youtube-dl error, try to give permission to this folder or maybe manually create it

check if you have enough free disks. otherwise, try to google a solution or try something on the youtube-dl page
