### ISSUE TITLE
Errors after latest pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5626]
[27-Aug-2021 15:54:18 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php:769\nStack trace:\n#0 \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php(769): array_merge()\n#1 \/var\/www\/myMySQLUser\/objects\/functions.php(6343): AVideoPlugin::getLiveApplicationArray()\n#2 \/var\/www\/myMySQLUser\/plugin\/Live\/view\/menuRight.php(353): getStatsNotifications()\n#3 \/var\/www\/myMySQLUser\/plugin\/Live\/Live.php(50): include('...')\n#4 \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php(238): Live->getHTMLMenuRight()\n#5 \/var\/www\/myMySQLUser\/view\/include\/navbar.php(435): AVideoPlugin::getHTMLMenuRight()\n#6 \/var\/www\/myMySQLUser\/plugin\/Gallery\/view\/modeGallery.php(16): include('...')\n#7 \/var\/www\/myMySQLUser\/view\/index.php(38): require('...')\n#8 {main}\n thrown","file":"\/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php","line":769} SCRIPT_NAME: /view/index.php

**Comment by milehighkaraoke** [comment]
Sorry that's old,  I believe
