### ISSUE TITLE
Stuck in Maintanance Mode after install

### ISSUE THREAD

**Issue by mesosq** [WWBN/AVideo#5657]
Error log only contains one line.

[07-Sep-2021 11:09:36 Europe/Budapest] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in C:\\xampp\\htdocs\\objects\\functions.php:1786\nStack trace:\n#0 C:\\xampp\\htdocs\\objects\\functions.php(3181): convertImage('C:\\\\xampp\\\\htdocs...', 'C:\\\\Users\\\\ADMINI...', 100)\n#1 C:\\xampp\\htdocs\\objects\\configuration.php(251): convertImageToOG('C:\\\\xampp\\\\htdocs...', 'C:\\\\xampp\\\\htdocs...')\n#2 C:\\xampp\\htdocs\\objects\\functionogSite.php(30): Configuration::getOGImage()\n#3 C:\\xampp\\htdocs\\objects\\functions.php(3221): include('C:\\\\xampp\\\\htdocs...')\n#4 C:\\xampp\\htdocs\\view\\include\\head.php(189): ogSite()\n#5 C:\\xampp\\htdocs\\view\\user.php(24): include('C:\\\\xampp\\\\htdocs...')\n#6 {main}\n  thrown","file":"C:\\xampp\\htdocs\\objects\\functions.php","line":1786} SCRIPT_NAME: /view/user.php

I have no idea what i did wrong... :/

**Comment by mesosq** [comment]
Okay, so I starting to sort this out., it does not like being on any other port than 80...

**Comment by DanielnetoDotCom** [comment]
Google for that and you will fix the problem 

`Uncaught Error: Call to undefined function imagecreatefrompng() `

**Comment by mesosq** [comment]
If anyone has the same issue -> go to php.ini -> look for line "extension=gd" -> delete the ";" mark from the start of the line
