### ISSUE TITLE
Backblaze update broke something videos not uploading after encoding 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5690]
[14-Sep-2021 03:40:58 America/Chicago] AVideoLog::ERROR: {"type":1,"message":"Uncaught BackblazeB2\\Exceptions\\B2Exception: Received error from B2: accountId invalid in \/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/ErrorHandler.php:36\nStack trace:\n#0 \/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/Http\/Client.php(28): BackblazeB2\\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\\Psr7\\Response))\n#1 \/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/Client.php(121): BackblazeB2\\Http\\Client->request('POST', 'https:\/\/api002....', Array)\n#2 \/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/Client.php(439): BackblazeB2\\Client->listBuckets()\n#3 \/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/Client.php(173): BackblazeB2\\Client->getBucketIdFromName('joshwhotv')\n#4 \/var\/www\/html\/YouPHPTube\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(358): BackblazeB2\\Client->upload(Array)\n#5 \/var\/www\/html\/YouPHPTube\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(299): Blackblaze_B2->copy_to_B2('\/var\/","file":"\/var\/www\/html\/YouPHPTube\/objects\/gliterd\/backblaze-b2\/src\/ErrorHandler.php","line":36} SCRIPT_NAME: /objects/aVideoEncoder.json.php

**Comment by DanielnetoDotCom** [comment]
It was fixed a couple days ago.

when did you updated your plugins?

can you please generate your credentials again and follow this. https://tutorials.avideo.com/video/111/how-to-configure-backblaze

**Comment by JoshWho** [comment]
I just updated it last night.

**Comment by JoshWho** [comment]
rolling back old plugin works. Newest latest one does not work

**Comment by DanielnetoDotCom** [comment]
make sure you delete the old plugin then upload the new one.

also, your AVideo must be up to date.

**Comment by JoshWho** [comment]
it is all updated. I did a full forced update last night

**Comment by DanielnetoDotCom** [comment]
Did you recreate the credentials?
again **make sure you delete the old plugin then upload the new one.**

**Comment by JoshWho** [comment]
Version: @3.1

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/133282557-5147f191-f355-45fb-887f-82f056c8cafe.png)

**Comment by JoshWho** [comment]
So the new plugin changes this info? I just re added it and it works again. Why does it have to be modified. It gave me a warning message saying by regenerating will cancel all my old keys.

**Comment by DanielnetoDotCom** [comment]
Not the new plugin but the new backplate API

**Comment by JoshWho** [comment]
So what I did was just regenerate a new master key but kept everything else the same like bucket and app and seems like it is working again
