### ISSUE TITLE
Urgeant issue with site!!! Error when opening any video from DB!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5765]
Don't know what happened but now I get this error whenever I wish to view a video on the site.

array(4) { ["type"]=> int(1) ["message"]=> string(679) "Uncaught Error: Call to undefined method Video::updateFilesizeFromFilename() in /var/www/html/AVideo/plugin/VideoThumbnails/VideoThumbnails.php(18) : eval()'d code(1) : eval()'d code:223 Stack trace: #0 /var/www/html/AVideo/plugin/VideoThumbnails/VideoThumbnails.php(18) : eval()'d code(1) : eval()'d code(56): VideoThumbnails->createStprits() #1 /var/www/html/AVideo/plugin/AVideoPlugin.php(62): VideoThumbnails->getHeadCode() #2 /var/www/html/AVideo/view/include/head.php(3): AVideoPlugin::getHeadCode() #3 /var/www/html/AVideo/view/modeYoutube.php(328): include('/var/www/html/A...') #4 /var/www/html/AVideo/view/index.php(36): require('/var/www/html/A...') #5 {main} thrown" ["file"]=> string(102) "/var/www/html/AVideo/plugin/VideoThumbnails/VideoThumbnails.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(223) }
![Screen Shot 5782-01-25 at 17 32 14](https://user-images.githubusercontent.com/58882903/135637999-3e51f822-2fd3-4464-9f25-342c1eee58e6.jpg)

**Comment by guymass** [comment]
OK I made a git pull and now things are back to normal. that was a quick fix haha.
