### ISSUE TITLE
Play Back Quality

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#5898]
It seems my playback on all videos are low quality.  How do I make it play highest quality based on ability?  I don't see any options to change the playback resolutions...  

All my videos show they are in HD either 720 or 1080 but they are not playing in those qualities.

**Comment by DanielnetoDotCom** [comment]
Hi

do you have the VideoResolutionSwitcher plugin from https://youphp.tube/marketplace/ ?

**Comment by techiesces** [comment]
It looks like I do not... Do I need this for the video to play anything other than low resolution?

**Comment by techiesces** [comment]
I have added it but now my videos all send to site under maintenance screen.

Also I got the backup plugin.  How do you recover using this plugin if needed?

**Comment by techiesces** [comment]
also 0 1 * * * php /var/www/AVideo/plugin/Backup/execBackup.json.php 5fc5ac4c25ace all produced a command not found and I took the 0 1 * * * off and it ran, but now I think I didn't setup the schedule haha  How do i fix that?

**Comment by DanielnetoDotCom** [comment]
Hi

can you please check your log file so we can find out the maintenance screen issue?

also please make sure you have the latest git pull

**Comment by techiesces** [comment]
[30-Oct-2021 20:44:59 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function getURL() in \/var\/www\/AVideo\/plugin\/VideoResolutionSwitcher\/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code:39\nStack trace:\n#0 \/var\/www\/AVideo\/plugin\/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode()\n#1 \/var\/www\/AVideo\/view\/include\/head.php(3): AVideoPlugin::getHeadCode()\n#2 \/var\/www\/AVideo\/view\/modeYoutube.php(355): include('\/var\/www\/AVideo...')\n#3 \/var\/www\/AVideo\/view\/index.php(36): require('\/var\/www\/AVideo...')\n#4 {main}\n  thrown","file":"\/var\/www\/AVideo\/plugin\/VideoResolutionSwitcher\/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code","line":39} SCRIPT_NAME: /view/index.php

Please remind me the git pull command

**Comment by techiesces** [comment]
Updating 131c3e037..b2cd687ba
error: Your local changes to the following files would be overwritten by merge:
        objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/README
Please commit your changes or stash them before you merge.
Aborting

**Comment by DanielnetoDotCom** [comment]
I guess you are running an old version

make sure you make a git pull and overwrite all your files 

Run this

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by techiesces** [comment]
Fixed!  and great resolution! thank you!
