### ISSUE TITLE
User can login without mail verified

### ISSUE THREAD

**Issue by timiti29** [WWBN/AVideo#6151]
**Describe the bug**
A user with unverified mail address can login successfully.
Parameters in general settings:
- userMustBeLoggedIn set to true
- sendVerificationMailAutomaic set to true
- unverifiedEmailsCanNOTLogin set to true

The user need correctly to be logged to access content, a new user receive correctly a automatic mail to verify the mail address but the user can be logged without verify the mail address.

**To Reproduce**
1. sign in with new user
2. Do not click on verify link sent by mail
3. Login into the website
4. User is connected

**Expected behavior**
User need to be not logged in and see a error "Your user is not verified, we sent you a new e-mail"

**Error Logs**
[05-Jan-2022 21:50:59 Europe/Paris] AVideoLog::DEBUG: Start Login Request redirectUri=https://mywebsite.com/ SCRIPT_NAME: /objects/login.json.php
[05-Jan-2022 21:50:59 Europe/Paris] AVideoLog::DEBUG: login.json.php trying to login SCRIPT_NAME: /objects/login.json.php
[05-Jan-2022 21:50:59 Europe/Paris] AVideoLog::DEBUG: login.json.php login respond something SCRIPT_NAME: /objects/login.json.php
[05-Jan-2022 21:50:59 Europe/Paris] AVideoLog::DEBUG: login.json.php is done SCRIPT_NAME: /objects/login.json.php

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 97.0.4692.71

**Additional context**
The version installed is git branch master / 66888dbe429f212aa44295dc02b070c771ddb0ac

**Comment by DanielnetoDotCom** [comment]
Thanks, I could confirm and find the issue. 

the code is updated now.

**Comment by timiti29** [comment]
Hi, thank you for take this case.

I can confirm that user is now rejected, i can see message "Your user is not verified, we sent you a new e-mail".
But the server send two mail to the user with different link to verify and only the last mail have a correct link, if the user click on link of first mail the server reject the user and send two more mail.

If the user click on the link of second mail all work fine.

i've check your commit and see two if condition who's testing the same variable "if (empty($advancedCustom))".

Best regards.

**Comment by timiti29** [comment]
Hi,

since the update 90cf970c8132088170afd857a12e3524cae1ff72 it's doesn't work.
when users without mail veriffied  trying to loggin can't loggin but doesn't have error message box and no mail is sent.

Best regards,

**Comment by DanielnetoDotCom** [comment]
I just tested locally and I did receive a message

![image](https://user-images.githubusercontent.com/18009293/151208962-57270ad5-d881-49dc-8a7a-fcb12df0cc8d.png)

**Comment by timiti29** [comment]
I've updated to 7f14c670f6089b9f6b9041af884a82773b79eede

When i try to connect with my unverified mail user it's stuck with turning logo and no error box.



i got error when loggin in avideo.log :

[26-Jan-2022 19:24:07 Europe/Berlin] AVideoLog::DEBUG: Sending SMTP Email SCRIPT_NAME: /objects/login.json.php
[26-Jan-2022 19:24:07 Europe/Berlin] AVideoLog::ERROR: {"type":1,"message":"Uncaught ArgumentCountError: 2 arguments are required, 1 given in \/var\/www\/mywebsite.com\/objects\/user.php:2078\nStack trace:\n#0 \/var\/www\/mywebsite.com\/objects\/user.php(2078): sprintf()\n#1 \/var\/www\/mywebsite.com\/objects\/user.php(880): User::sendVerificationLink()\n#2 \/var\/www\/mywebsite.com\/objects\/user.php(2283): User->login()\n#3 \/var\/www\/mywebsite.com\/plugin\/Live\/Live.php(15): User::loginFromRequest()\n#4 \/var\/www\/mywebsite.com\/plugin\/AVideoPlugin.php(296): require_once('...')\n#5 \/var\/www\/mywebsite.com\/plugin\/AVideoPlugin.php(596): AVideoPlugin::loadPlugin()\n#6 \/var\/www\/mywebsite.com\/objects\/include_config.php(167): AVideoPlugin::getStart()\n#7 \/var\/www\/mywebsite.com\/videos\/configuration.php(47): require_once('...')\n#8 \/var\/www\/mywebsite.com\/objects\/login.json.php(8): require_once('...')\n#9 {main}\n  thrown","file":"\/var\/www\/mywebsite.com\/objects\/user.php","line":2078} SCRIPT_NAME: /objects/login.json.php

Best regards,

**Comment by DanielnetoDotCom** [comment]
Can you please try this update?

**Comment by timiti29** [comment]
Hi,

Thank-you this is working fine now !

Best regards
