### ISSUE TITLE
page blank after login. when not logged in it is ok.

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6190]
@DanielnetoDotCom ,

Once I log in i get a frozen page. see below. 

i'm on the very latest git. please assist urgently. thank you.

![blank login](https://user-images.githubusercontent.com/65451390/149844405-355ed4bd-13cc-436f-89b0-ba958ce98731.jpeg)

that whole white space is a blank page.

once i log out however it shows properly.

please help.

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log

**Comment by DanielnetoDotCom** [comment]
did you find anything?

**Comment by jengajenga** [comment]
One sec let me look... even that is refusing to open

**Comment by DanielnetoDotCom** [comment]
you must check it using the command line

**Comment by jengajenga** [comment]
[18-Jan-2022 01:51:20 Africa/Nairobi] AVideoLog::DEBUG: getStart language: got from config  SCRIPT_NAME: /plugin/Chat2/getChatTotalNew.json.php
[18-Jan-2022 01:51:25 Africa/Nairobi] AVideoLog::DEBUG: verifyToken token timout time = 1642459885; obj->time = 1642416246;  obj->timeout = 1642459446 SCRIPT_NAME: /home/golive/web/goliveafrica.media/public_html/plugin/YPTSocket/server.php
[18-Jan-2022 01:51:26 Africa/Nairobi] AVideoLog::DEBUG: verifyToken token timout time = 1642459886; obj->time = 1642416245;  obj->timeout = 1642459445 SCRIPT_NAME: /home/golive/web/goliveafrica.media/public_html/plugin/YPTSocket/server.php
[18-Jan-2022 01:51:39 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 4: cache not found SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:51:39 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:51:39 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:51:39 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/menuRight.php(408): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(56): include('\/home\/golive\/we...')\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(254): Live->getHTMLMenuRight()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/include\/navbar.php(441): AVideoPlugin::getHTMLMenuRight()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Gallery\/view\/modeGallery.php(16): include('\/home\/golive\/we...')\n#16 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/index.php(52): require('\/home\/golive\/we...')\n#17 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:51:47 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 3: return cached result getStats/live_servers_id_1/getStatsObject [lifetime=60] SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:51:47 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:51:48 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:51:48 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/menuRight.php(408): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(56): include('\/home\/golive\/we...')\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(254): Live->getHTMLMenuRight()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/include\/navbar.php(441): AVideoPlugin::getHTMLMenuRight()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/user.php(35): include('\/home\/golive\/we...')\n#16 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:52:10 Africa/Nairobi] AVideoLog::DEBUG: setLanguage: File does not exists 1 /home/golive/web/goliveafrica.media/public_html/locale/FR.php SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:52:10 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 4: cache not found SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:52:10 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:52:11 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:52:11 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/menuRight.php(408): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(56): include('\/home\/golive\/we...')\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(254): Live->getHTMLMenuRight()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/include\/navbar.php(441): AVideoPlugin::getHTMLMenuRight()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Gallery\/view\/modeGallery.php(16): include('\/home\/golive\/we...')\n#16 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/index.php(52): require('\/home\/golive\/we...')\n#17 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:55:29 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 4: cache not found SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:55:29 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:55:29 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:55:29 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/menuRight.php(408): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(56): include('\/home\/golive\/we...')\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(254): Live->getHTMLMenuRight()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/include\/navbar.php(441): AVideoPlugin::getHTMLMenuRight()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/user.php(35): include('\/home\/golive\/we...')\n#16 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /view/user.php
[18-Jan-2022 01:56:39 Africa/Nairobi] AVideoLog::DEBUG: setLanguage: File does not exists 1 /home/golive/web/goliveafrica.media/public_html/locale/NL.php SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:56:39 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 4: cache not found SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:56:39 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:56:39 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:56:39 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/menuRight.php(408): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(56): include('\/home\/golive\/we...')\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(254): Live->getHTMLMenuRight()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/include\/navbar.php(441): AVideoPlugin::getHTMLMenuRight()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Gallery\/view\/modeGallery.php(16): include('\/home\/golive\/we...')\n#16 \/home\/golive\/web\/goliveafrica.media\/public_html\/view\/index.php(52): require('\/home\/golive\/we...')\n#17 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /view/index.php
[18-Jan-2022 01:59:28 Africa/Nairobi] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser() = false SCRIPT_NAME: /plugin/Live/index.php
[18-Jan-2022 01:59:28 Africa/Nairobi] AVideoLog::DEBUG: Live::getStatsObject[1] 3: return cached result getStats/live_servers_id_1/getStatsObject [lifetime=60] SCRIPT_NAME: /plugin/Live/index.php
[18-Jan-2022 01:59:28 Africa/Nairobi] AVideoLog::DEBUG: Live::_getStats cached result 1 undefined  SCRIPT_NAME: /plugin/Live/index.php
[18-Jan-2022 01:59:29 Africa/Nairobi] AVideoLog::DEBUG: getPoster(35, 1, ) SCRIPT_NAME: /plugin/Live/index.php
[18-Jan-2022 01:59:29 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php:2365\nStack trace:\n#0 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(247): Live::getPoster()\n#1 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/AVideoPlugin.php(862): Live->getLiveApplicationArray()\n#2 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7068): AVideoPlugin::getLiveApplicationArray()\n#3 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#4 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#5 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#6 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(614): Live::getCurrentLiveServersId()\n#7 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1307): Live::getServer()\n#8 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1737): Live::getApplicationName()\n#9 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1484): Live::_getStats()\n#10 \/home\/golive\/web\/goliveafrica.media\/public_html\/objects\/functions.php(7052): Live::getStats()\n#11 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1556): getStatsNotifications()\n#12 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1382): Live::getAvailableLiveServer()\n#13 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php(1417): Live::getAvailableLiveServersId()\n#14 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/onlineLabel.php(7): Live::getCurrentLiveServersId()\n#15 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/view\/videoEmbeded.php(89): include('\/home\/golive\/we...')\n#16 \/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/index.php(25): include('\/home\/golive\/we...')\n#17 {main}\n  thrown","file":"\/home\/golive\/web\/goliveafrica.media\/public_html\/plugin\/Live\/Live.php","line":2365} SCRIPT_NAME: /plugin/Live/index.php

**Comment by jengajenga** [comment]
sorry if it's too long

i also tried to revert to old git but it hasnt worked

**Comment by DanielnetoDotCom** [comment]
there is no error on this log.

are those the last lines?

**Comment by jengajenga** [comment]
yes. the last 50 lines.

**Comment by DanielnetoDotCom** [comment]
I found this in your log

`[18-Jan-2022 01:51:48 Africa/Nairobi] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Non-static method Live::getLivePosterImageRelativePath() cannot be called statically in`

I just sent an update to correct it. 

update and check if it resolves.

if fails please send me the new log files. also the apache log files

**Comment by jengajenga** [comment]
Ok. Doing the update  now...

**Comment by jengajenga** [comment]
@DanielnetoDotCom may Jesus continue to bless the work of your hands.

It's working!! 

I'll delete the log since it has a lot of infor.

thank you so so much.

**Comment by jengajenga** [comment]
![menu](https://user-images.githubusercontent.com/65451390/149846647-6ec8473d-d0fe-49c7-becf-8793c9d0053d.PNG)

@DanielnetoDotCom , sorry but now the menu in admin cannot be accessed.

**Comment by DanielnetoDotCom** [comment]
this may be something else.

can you please check if you update all your plugins?

also check your js console

**Comment by jengajenga** [comment]
on it. though on three of my instances i'm getting the same thing.

**Comment by jengajenga** [comment]
looks good. all plugins updated. if anything changes i'll reopen another.

again thank you so much.
