### ISSUE TITLE
Backblaze Stopped working after latest Upgrade to 11.6

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6304]
Received error from B2: /b2api/v1//b2_authorize_account
#0 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Http/Client.php(34): BackblazeB2\ErrorHandler::handleErrorResponse() #1 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(538): BackblazeB2\Http\Client->guzzleRequest() #2 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(793): BackblazeB2\Client->authorizeAccount() #3 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(126): BackblazeB2\Client->sendAuthorizedRequest() #4 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(557): BackblazeB2\Client->listBuckets() #5 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(178): BackblazeB2\Client->getBucketIdFromName() #6 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(365): BackblazeB2\Client->upload() #7 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #8 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #9 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18): eval() #10 {main}

**Comment by DanielnetoDotCom** [comment]
Backblaze changed some things 

you need to recreate the api credentials 

check this https://tutorials.wwbn.net/video/111/how-to-configure-backblaze

make sure you update the plugin

**Comment by JoshWho** [comment]
I cant get that video to play, already did this a few months ago

**Comment by JoshWho** [comment]
Same error with new master key

**Comment by JoshWho** [comment]
@DanielnetoDotCom I just dmd u

**Comment by DanielnetoDotCom** [comment]
I am away from pc now

please share more from your log

try to click on the test button

**Comment by JoshWho** [comment]
It is not the key it is the plugin. The key and app id works fine with curl

**Comment by JoshWho** [comment]
I pmd you my app key id and info

**Comment by JoshWho** [comment]
Test button is what gives me the error i posted

**Comment by JoshWho** [comment]
Should I do a rollback?

**Comment by DanielnetoDotCom** [comment]
No, make a test and share the log here 

get the log from avideo.log file to not miss anything

**Comment by JoshWho** [comment]
I see no errors

```
[25-Feb-2022 05:23:36 America/Chicago] AVideoLog::DEBUG: copy_to_B2 Start test.txt SCRIPT_NAME: /plugin/Blackblaze_B2/test.php
 [25-Feb-2022 05:23:34 America/Chicago] AVideoLog::DEBUG: getStart language: got from config  SCRIPT_NAME: /view/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49590 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49590,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49593 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49593,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49617 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49617,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49619 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49619,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49636 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49636,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49637 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49637,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49675 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49675,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49725 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49725,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49790 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49790,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49978 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49978,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49985 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49985, EE:EE:EE SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=49991 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 49991,  SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=50026 type=embed SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video::updateDurationInSeconds empty duration 50026, EE:EE:EE SCRIPT_NAME: /feed/index.php
 [25-Feb-2022 05:23:27 America/Chicago] AVideoLog::DEBUG: Video duration_in_seconds not updated: id=50027 type=embed SCRIPT_NAME: /feed/index.php
```

**Comment by JoshWho** [comment]
Test page Shows

```
Received error from B2: /b2api/v1//b2_authorize_account
#0 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Http/Client.php(34): BackblazeB2\ErrorHandler::handleErrorResponse() #1 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(538): BackblazeB2\Http\Client->guzzleRequest() #2 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(793): BackblazeB2\Client->authorizeAccount() #3 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(126): BackblazeB2\Client->sendAuthorizedRequest() #4 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(557): BackblazeB2\Client->listBuckets() #5 /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/Client.php(178): BackblazeB2\Client->getBucketIdFromName() #6 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(365): BackblazeB2\Client->upload() #7 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #8 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #9 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18): eval() #10 {main}
```

**Comment by JoshWho** [comment]
Just a guess here noot 100% sure but I know the Log4j Patching is removing the use of : in almost all lines for urls

**Comment by JoshWho** [comment]
> No, make a test and share the log here
> 
> get the log from avideo.log file to not miss anything

I ask because my site is really active and this is bottlenecking downloads. I just had to delete a lot

**Comment by JoshWho** [comment]
oops accidently closed it

**Comment by DanielnetoDotCom** [comment]
I will check your server directly 

are you sure your B2 credentials are correct right?

**Comment by JoshWho** [comment]
yes I dmd you the keys in hangouts

**Comment by JoshWho** [comment]
Issue was found on the vendor code of the bb and has been updated.
