### ISSUE TITLE
Backblaze Plugin

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#6305]
**Describe the bug**
No longer can upload to the backblaze s3 bucket

**To Reproduce**
Cant upload videos to my s3 bucket but I can view the videos just fine. 
reset the key and tested.
rebooted the server, cleared the cache

went to backblaze and they have a blog out about a new api system, don't know if that is the issue.
https://www.backblaze.com/blog/explore-the-backblaze-s3-compatible-api-with-our-new-postman-collection/

**Error Logs**
 [25-Feb-2022 20:36:57 Europe/Amsterdam] AVideoLog::ERROR: {"type":1,"message":"Uncaught BackblazeB2\\Exceptions\\NotFoundException: Received error from B2: \/b2api\/v1\/\/b2_authorize_account in \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/ErrorHandler.php:43\nStack trace:\n#0 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Http\/Client.php(34): BackblazeB2\\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\\Psr7\\Response))\n#1 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(538): BackblazeB2\\Http\\Client->guzzleRequest('GET', 'https:\/\/api.bac...', Array)\n#2 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(793): BackblazeB2\\Client->authorizeAccount()\n#3 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(126): BackblazeB2\\Client->sendAuthorizedRequest('POST', 'b2_list_buckets', Array)\n#4 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(557): BackblazeB2\\Client->listBuckets()\n#5 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(178): BackblazeB2\\Client->getBucketIdFromName('tellaversion2')\n#6 \/var\/www\/html\/AVideo\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(365): BackblazeB2\\Client->upload(Array)\n#7 \/var\/www\/html\/AVideo\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(306): Blackblaze_B2->copy_to_B2('\/var\/www\/html\/A...', 'video_220225203...')\n#8 \/var\/www\/html\/AVideo\/objects\/functions.php(1937): Blackblaze_B2->move_uploaded_file('\/var\/www\/html\/A...', 'video_220225203...')\n#9 \/var\/www\/html\/AVideo\/objects\/aVideoEncoder.json.php(138): decideMoveUploadedToVideos('\/var\/www\/html\/A...', 'video_220225203...')\n#10 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/ErrorHandler.php","line":43} SCRIPT_NAME: /objects/aVideoEncoder.json.php

**Comment by DanielnetoDotCom** [comment]
We just fixed something regarding this today https://github.com/WWBN/AVideo/issues/6304

can you please make a git pull

**Comment by karlkunc** [comment]
> We just fixed something regarding this today #6304
> 
> can you please make a git pull

I did do a git pull and have the same issue. Plus chat2 broke after the git pull.  I did notice nothing updated in the backblaze plugin dir. here is the error 

 [27-Feb-2022 03:54:59 Europe/Amsterdam] AVideoLog::ERROR: {"type":1,"message":"Uncaught BackblazeB2\\Exceptions\\B2Exception: Received error from B2:  in \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/ErrorHandler.php:43\nStack trace:\n#0 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Http\/Client.php(34): BackblazeB2\\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\\Psr7\\Response))\n#1 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(538): BackblazeB2\\Http\\Client->guzzleRequest('GET', 'https:\/\/api.bac...', Array)\n#2 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(793): BackblazeB2\\Client->authorizeAccount()\n#3 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(126): BackblazeB2\\Client->sendAuthorizedRequest('POST', 'b2_list_buckets', Array)\n#4 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(557): BackblazeB2\\Client->listBuckets()\n#5 \/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/Client.php(178): BackblazeB2\\Client->getBucketIdFromName('tellaversion2')\n#6 \/var\/www\/html\/AVideo\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(365): BackblazeB2\\Client->upload(Array)\n#7 \/var\/www\/html\/AVideo\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(306): Blackblaze_B2->copy_to_B2('\/var\/www\/html\/A...', 'video_220227035...')\n#8 \/var\/www\/html\/AVideo\/objects\/functions.php(1942): Blackblaze_B2->move_uploaded_file('\/var\/www\/html\/A...', 'video_220227035...')\n#9 \/var\/www\/html\/AVideo\/objects\/aVideoEncoder.json.php(138): decideMoveUploadedToVideos('\/var\/www\/html\/A...', 'video_220227035...')\n#10 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/vendor\/gliterd\/backblaze-b2\/src\/ErrorHandler.php","line":43} SCRIPT_NAME: /objects/aVideoEncoder.json.php

**Comment by karlkunc** [comment]
Any ideas what else I can do other than get rid of backblaze and run my own storage. site is still offline.

**Comment by DanielnetoDotCom** [comment]
Did you update the B2 plugin?

did you recreate the api key ?

check https://tutorials.wwbn.net/video/111/how-to-configure-backblaze

**Comment by karlkunc** [comment]
just manually updated the plugin and recreated the key. working now. Thank you!
