### ISSUE TITLE
Video player not working when logged in

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#6404]
**Describe the bug**
you can view videos when you are not logged into the system but can't when you log on

When I inspect the page when the video should be playing I see these errors. any Ideas what I should look for?

Uncaught ReferenceError: avideoSocketIsActive is not defined
    at HTMLDocument.<anonymous> (the-official-animal-rights-march-2019-washington-dc:783:13)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)
jquery.min.js?cache=1644425936_1644425936:2 Uncaught ReferenceError: BootstrapMenu is not defined
    at HTMLDocument.<anonymous> (the-official-animal-rights-march-2019-washington-dc:1550:20)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)
the-official-animal-rights-march-2019-washington-dc:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by DanielnetoDotCom** [comment]
Please check your avideo error log file

**Comment by karlkunc** [comment]
I have fixed the issue. Donations were turned on in customize user and the wallet was not. once I turned donations off it started to work.
