### ISSUE TITLE
socket will not stay on

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6519]
My socket will never stay on for even 10 minutes. i have implemented load balancing and i have also been forced to disable the liveUsers plugin which make the site unusable because of the constant db queries.

so now the load is not so much but why oh why is the socket not staying on?

I ran the socket in the foreground and this is what it said when it disconnected

@DanielnetoDotCom can you figure it out and see where to help me? Thank you

2022-04-20 15:15:42 msgToResourceId: resourceId=(7662) NEW_DISCONNECTION
[2022-04-20 15:15:42] AVideoLog::DEBUG: #0 /var/www/xxxxx/objects/functions.php(3918): mysqli-                                                                   >__construct()
#1 /var/www/xxxxx/plugin/YPTSocket/Message.php(483): _mysql_connect()
#2 /var/www/xxxxx/plugin/YPTSocket/Message.php(175): Socket\Message->msgToAllSameLive()
#3 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(164): Socket\Messag                                                                   e->onClose()
#4 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(62): Ratchet\WebSocket                                                                   \WsServer->onClose()
#5 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(124): Ratchet\Http\Htt                                                                   pServer->onClose()
#6 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(98): Ratchet\Server\Io                                                                   Server->handleEnd()
#7 /var/www/xxxxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet                                                                   \Server\IoServer->Ratchet\Server\{closure}()
#8 /var/www/xxxxx/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#9 /var/www/xxxxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\S                                                                   tream\Util::React\Stream\{closure}()
#10 /var/www/xxxxx/vendor/react/stream/src/DuplexResourceStream.php(141): Evenement\EventEmitt                                                                   er->emit()
#11 /var/www/xxxxx/vendor/react/stream/src/DuplexResourceStream.php(200): React\Stream\DuplexR                                                                   esourceStream->close()
#12 /var/www/xxxxx/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexR                                                                   esourceStream->handleData()
#13 /var/www/xxxxx/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\Stre                                                                   amSelectLoop->waitForStreamActivity()
#14 /var/www/xxxxx/plugin/YPTSocket/server.php(86): React\EventLoop\StreamSelectLoop->run()
#15 {main} SCRIPT_NAME: /var/www/xxxxx/plugin/YPTSocket/server.php
AVideoLog::DEBUG: #0 /var/www/xxxxx/objects/functions.php(3918): mysqli->__construct()
#1 /var/www/xxxxx/plugin/YPTSocket/Message.php(483): _mysql_connect()
#2 /var/www/xxxxx/plugin/YPTSocket/Message.php(175): Socket\Message->msgToAllSameLive()
#3 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(164): Socket\Messag                                                                   e->onClose()
#4 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(62): Ratchet\WebSocket                                                                   \WsServer->onClose()
#5 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(124): Ratchet\Http\Htt                                                                   pServer->onClose()
#6 /var/www/xxxxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(98): Ratchet\Server\Io                                                                   Server->handleEnd()
#7 /var/www/xxxxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet                                                                   \Server\IoServer->Ratchet\Server\{closure}()
#8 /var/www/xxxxx/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#9 /var/www/xxxxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\S                                                                   tream\Util::React\Stream\{closure}()
#10 /var/www/xxxxx/vendor/react/stream/src/DuplexResourceStream.php(141): Evenement\EventEmitt                                                                   er->emit()
#11 /var/www/xxxxx/vendor/react/stream/src/DuplexResourceStream.php(200): React\Stream\DuplexR                                                                   esourceStream->close()
#12 /var/www/xxxxx/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexR                                                                   esourceStream->handleData()
#13 /var/www/xxxxx/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\Stre                                                                   amSelectLoop->waitForStreamActivity()
#14 /var/www/xxxxx/plugin/YPTSocket/server.php(86): React\EventLoop\StreamSelectLoop->run()
#15 {main} SCRIPT_NAME: /var/www/xxxxx/plugin/YPTSocket/server.php
PHP Warning:  include(/var/www/xxxxx/view/include/offlinePage.php): Failed to open stream: Too                                                                    many open files in /var/www/xxxxx/objects/functions.php on line 3928

Warning: include(/var/www/xxxxx/view/include/offlinePage.php): Failed to open stream: Too many                                                                    open files in /var/www/xxxxx/objects/functions.php on line 3928
PHP Warning:  include(): Failed opening '/var/www/xxxxx/view/include/offlinePage.php' for incl                                                                   usion (include_path='.:/usr/share/php') in /var/www/xxxxx/objects/functions.php on line 3928

Warning: include(): Failed opening '/var/www/xxxxx/view/include/offlinePage.php' for inclusion                                                                    (include_path='.:/usr/share/php') in /var/www/xxxxx/objects/functions.php on line 3928
root@v2202111159864167653:~#

**Comment by jengajenga** [comment]
root@me:~# php /var/www/xxxxx/plugin/YPTSocket/test.php
[2022-04-20 14:20:14] AVideoLog::DEBUG: _mysql_connect HOST=localhost,DB=mydatabase SCRIPT_NAME: /var/www/xxxxx/plugin/YPTSocket/test.php
[2022-04-20 14:20:14] AVideoLog::DEBUG: getStart language: got from config  SCRIPT_NAME: /var/www/xxxxx/plugin/YPTSocket/test.php
[2022-04-20 15:20:14] ** Starting socket test **

Warning: Cannot modify header information - headers already sent by (output started at /var/www/xxxxx/objects/functions.php:3841) in /var/www/xxxxx/plugin/YPTSocket/test.php on line 115
[2022-04-20 15:20:14] Testing connection with [0]: ws://localhost:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14] Testing connection with [1]: wss://localhost:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14] Testing connection with [2]: ws://127.0.0.1:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14] Testing connection with [3]: wss://127.0.0.1:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14] Testing connection with [4]: ws://my.domain.tld:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14] Testing connection with [5]: wss://my.domain.tld:myport on 2022/04/20 15:20:14
[2022-04-20 15:20:14]  NOT SECURE CONNECTION  CONNECTION FAIL ws://localhost:myport Connection to tcp://localhost:myport failed: Last error for IPv4: Connection to tcp://127.0.0.1:myport failed: Connection refused (ECONNREFUSED). Previous error for IPv6: Connection to tcp://[::1]:myport failed: Connection refused (ECONNREFUSED)
[2022-04-20 15:20:14]    SECURE CONNECTION    CONNECTION FAIL wss://localhost:myport Connection to tls://localhost:myport failed: Last error for IPv4: Connection to tcp://127.0.0.1:myport failed: Connection refused (ECONNREFUSED). Previous error for IPv6: Connection to tcp://[::1]:myport failed: Connection refused (ECONNREFUSED)
[2022-04-20 15:20:14]  NOT SECURE CONNECTION  CONNECTION FAIL ws://127.0.0.1:myport Connection to tcp://127.0.0.1:myport failed: Connection refused (ECONNREFUSED)
[2022-04-20 15:20:14]    SECURE CONNECTION    CONNECTION FAIL wss://127.0.0.1:myport Connection to tls://127.0.0.1:myport failed: Connection refused (ECONNREFUSED)
[2022-04-20 15:20:14]  NOT SECURE CONNECTION  CONNECTION FAIL ws://my.domain.tld:myport Connection to tcp://my.domain.tld:myport failed: Last error for IPv4: Connection to tcp://202.61.239.86:myport failed: Connection refused (ECONNREFUSED). Previous error for IPv6: DNS query for my.domain.tld (AAAA) did not return a valid answer (NOERROR / NODATA)
[2022-04-20 15:20:14]    SECURE CONNECTION    CONNECTION FAIL wss://my.domain.tld:myport Connection to tls://my.domain.tld:myport failed: Last error for IPv4: Connection to tcp://202.61.239.86:myport failed: Connection refused (ECONNREFUSED). Previous error for IPv6: DNS query for my.domain.tld (AAAA) did not return a valid answer (NOERROR / NODATA)
[2022-04-20 15:20:14]  We found 0 possible configurations:

**Comment by DanielnetoDotCom** [comment]
seems to be a MySQL problem. looks like it is not handling all the connections.

I suspect you are having a high audience.

did you try to run the MySQLTuner script?

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script

**Comment by jengajenga** [comment]
This MAY have worked. I'll keep you posted. Increased max connections from 500 to 2500. Let's see if it holds.
