### ISSUE TITLE
new installation

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6559]
hi Daniel, I have installed AVideo on a new server and I have such errors

` [04-May-2022 08:19:03 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.CachesInDB' doesn't exist in \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php:97\nStack trace:\n#0 \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php(97): mysqli->prepare()\n#1 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Objects\/CachesInDB.php(177): sqlDAL::writeSql()\n#2 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Cache.php(369): CachesInDB::_deleteCache()\n#3 \/var\/www\/vodtube.pl\/public_html\/objects\/Object.php(569): Cache::deleteCache()\n#4 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(4390): ObjectYPT::deleteCache()\n#5 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(5169): Video::clearCache()\n#6 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(5155): Video::updateLikesDislikes()\n#7 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(1300): Video::updateLikesDislikes()\n#8 \/var\/www\/vodtube.pl\/public_html\/view\/info.php(35): Video::getAllVideos()\n#9 {main}\n  thrown","file":"\/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php","line":97} SCRIPT_NAME: /view/info.php`

`[03-May-2022 22:40:00 Europe/Warsaw] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.CachesInDB' doesn't exist in \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php:97\nStack trace:\n#0 \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php(97): mysqli->prepare()\n#1 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Objects\/CachesInDB.php(177): sqlDAL::writeSql()\n#2 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Cache.php(369): CachesInDB::_deleteCache()\n#3 \/var\/www\/vodtube.pl\/public_html\/plugin\/AVideoPlugin.php(1583): Cache::deleteCache()\n#4 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(4414): AVideoPlugin::deleteVideoTags()\n#5 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(5169): Video::clearCache()\n#6 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(5155): Video::updateLikesDislikes()\n#7 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(1300): Video::updateLikesDislikes()\n#8 \/var\/www\/vodtube.pl\/public_html\/objects\/videos.json.php(40): Video::getAllVideos()\n#9 {main}\n  thrown","file":"\/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php","line":97} SCRIPT_NAME: /objects/videos.json.php`

` [03-May-2022 20:31:04 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.CachesInDB' doesn't exist in \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php:97\nStack trace:\n#0 \/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php(97): mysqli->prepare()\n#1 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Objects\/CachesInDB.php(177): sqlDAL::writeSql()\n#2 \/var\/www\/vodtube.pl\/public_html\/plugin\/Cache\/Cache.php(369): CachesInDB::_deleteCache()\n#3 \/var\/www\/vodtube.pl\/public_html\/objects\/Object.php(569): Cache::deleteCache()\n#4 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(452): ObjectYPT::deleteCache()\n#5 \/var\/www\/vodtube.pl\/public_html\/objects\/aVideoEncoder.json.php(166): Video->save()\n#6 {main}\n  thrown","file":"\/var\/www\/vodtube.pl\/public_html\/objects\/mysql_dal.php","line":97} SCRIPT_NAME: /objects/aVideoEncoder.json.php`

**Comment by DanielnetoDotCom** [comment]
that means the Cache plugin tables are not installed

**Comment by DanielnetoDotCom** [comment]
This update should avoid those errors

**Comment by KrzysioMisio** [comment]
I cleaned the log file and I have such an error
` [04-May-2022 14:35:25 Europe/Warsaw] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.videos_VR360' doesn't exist in \/var\/www\/vodtube.pl\/public_html\/plugin\/VR360\/Objects\/VideosVR360.php:48\nStack trace:\n#0 \/var\/www\/vodtube.pl\/public_html\/plugin\/VR360\/Objects\/VideosVR360.php(48): mysqli->query()\n#1 \/var\/www\/vodtube.pl\/public_html\/plugin\/VR360\/Objects\/VideosVR360.php(32): VideosVR360::getFromVideoDb()\n#2 \/var\/www\/vodtube.pl\/public_html\/plugin\/VR360\/Objects\/VideosVR360.php(59): VideosVR360->loadFromVideo()\n#3 \/var\/www\/vodtube.pl\/public_html\/objects\/functions.php(896): VideosVR360::isVR360Enabled()\n#4 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(3121): canUseCDN()\n#5 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(3733): Video::getSourceFile()\n#6 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(4500): Video::getVideosPaths()\n#7 \/var\/www\/vodtube.pl\/public_html\/objects\/video.php(4513): Video::getVideoType()\n#8 \/var\/www\/vodtube.pl\/public_html\/objects\/videos.json.php(57): Video::getVideoTypeLabels()\n#9 {main}\n  thrown","file":"\/var\/www\/vodtube.pl\/public_html\/plugin\/VR360\/Objects\/VideosVR360.php","line":48} SCRIPT_NAME: /objects/videos.json.php`

**Comment by DanielnetoDotCom** [comment]
Seems to me you enabled a lot of plugins without installing the required tables.

please review your plugin page and install all missing tables.

**Comment by DevClaudemir** [comment]
me ajudem...depois que eu instalo e executo o site em localhost, aparece varias linhas de codigo indicando erros, eu imagino, e abaixo aparece a seguinte mensagem: 
under maintenance
sorry for the incovenience

alguem poderia me ajudar?
vou anexar um print pra melhor visualização do problema
![erro](https://user-images.githubusercontent.com/87725175/166721959-44a36958-d602-4500-b2bb-6918899b3c1b.png)

**Comment by DanielnetoDotCom** [comment]
@DevClaudemir 
You should first google for this error (you are missing the PHP GD)

you should open a new issue regarding this, because your issue has nothing to do with this thread

**Comment by DanielnetoDotCom** [comment]
@KrzysioMisio I am not seeing any error

**Comment by KrzysioMisio** [comment]
I have a video and a photo of the error

![2022-05-04_181709](https://user-images.githubusercontent.com/93145787/166725602-b8d1e43f-4e35-4a02-b4b5-e2d296a61cc5.png)


https://user-images.githubusercontent.com/93145787/166725688-18d54f53-8ac5-4775-a135-5d3303459980.mp4

**Comment by DanielnetoDotCom** [comment]
Those are not errors

**Comment by KrzysioMisio** [comment]
I don't know why but you can't add movies via the encoder
see for yourself
pass: qwert
login: qwert

**Comment by DanielnetoDotCom** [comment]
I can only provide direct support under a paid support.

from here you have to share some clues on your logs

**Comment by KrzysioMisio** [comment]
I wanted you to see as a user that you cannot add videos 
please try 
https://www.vodtube.pl/
pass: qwert
login: qwert

**Comment by DanielnetoDotCom** [comment]
For direct support please hire me for 1 hour, so I can direct look into your installation.

you can purchase the hour support here https://youphp.tube/marketplace/

**Comment by KrzysioMisio** [comment]
ok, I'll hire you if it's a problem on my side
I think it is a problem in the encoder code because I have PHP8.1.5 installed
look at the log file

`[07-May-2022 13:11:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 130`
`[07-May-2022 13:11:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 131`
`[07-May-2022 13:11:43 UTC] PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Configuration.php on line 52`
`[07-May-2022 13:11:43 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:11:43 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1242`
`[07-May-2022 13:11:43 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:11:43 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335`
`[07-May-2022 13:11:56 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:11:56 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:11:56 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335`
`[07-May-2022 13:12:12 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:12:12 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470`
`[07-May-2022 13:12:12 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335`

**Comment by DanielnetoDotCom** [comment]
Those warnings are not errors 

I guess I really need to check it more carefully

**Comment by KrzysioMisio** [comment]
information is about these functions
 basename()
stripslashes()
setcookie()

I have the latest PHP 8.1.5

**Comment by KrzysioMisio** [comment]
see that in php8 there is a change
https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

**Comment by DanielnetoDotCom** [comment]
AGAIN, deprecated is not an ERROR

**Comment by KrzysioMisio** [comment]
I know this is not a error,
but the encoder doesn't work with PHP8.1
have you been to my site and tried to add some video?

**Comment by KrzysioMisio** [comment]
I don't want you to configure my site, I just want you to check why you can't add videos
I think the php code is not compatible with PHP8.1
If there is a problem with PHP8.1 then I will install PHP7
no problem

**Comment by DanielnetoDotCom** [comment]
I use php8.1 in most of my installations

Tô find the error you must share the proper log

the encoder log and streamer log

**Comment by KrzysioMisio** [comment]
there are no errors in streamer
in the encoder there is this information
`[07-May-2022 13:11:42 UTC] logoff:: done session_id = 17p7fot63huajur1aunu52pho0
[07-May-2022 13:11:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 130
[07-May-2022 13:11:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 131
[07-May-2022 13:11:43 UTC] https://www.vodtube.pl/ == https://www.vodtube.pl/
[07-May-2022 13:11:43 UTC] login.json: Login::run
[07-May-2022 13:11:43 UTC] Login::run (admin, ***, https://www.vodtube.pl/, true)
[07-May-2022 13:11:43 UTC] Login::run request login user (admin)
[07-May-2022 13:11:43 UTC] Login::run request login complete user (admin)
[07-May-2022 13:11:43 UTC] Login::run got an object
[07-May-2022 13:11:43 UTC] createIfNotExists:: admin
[07-May-2022 13:11:43 UTC] Verification Start https://www.vodtube.pl/
[07-May-2022 13:11:43 UTC] Verification GetFrom Cache https://www.vodtube.pl/
[07-May-2022 13:11:43 UTC] Verification Response (): {"msg":["https:\/\/www.vodtube.pl\/ Site was inactive"],"isPrivate":false,"verified":true,"status":"i"}
[07-May-2022 13:11:43 UTC] Login:: almost done
[07-May-2022 13:11:43 UTC] Login:: done session_id = 17p7fot63huajur1aunu52pho0 session_login 
[07-May-2022 13:11:43 UTC] PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Configuration.php on line 52
[07-May-2022 13:11:43 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:11:43 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1242
[07-May-2022 13:11:43 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:11:43 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
[07-May-2022 13:11:56 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:11:56 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:11:56 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
[07-May-2022 13:12:12 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:12:12 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 13:12:12 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
[07-May-2022 21:19:42 UTC] logoff:: done session_id = jhuj64hru42q0foaf350i4955f
[07-May-2022 21:19:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 130
[07-May-2022 21:19:42 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 131
[07-May-2022 21:19:43 UTC] https://www.vodtube.pl/ == https://www.vodtube.pl/
[07-May-2022 21:19:43 UTC] login.json: Login::run
[07-May-2022 21:19:43 UTC] Login::run (admin, ***, https://www.vodtube.pl/, true)
[07-May-2022 21:19:43 UTC] Login::run request login user (admin)
[07-May-2022 21:19:43 UTC] Login::run request login complete user (admin)
[07-May-2022 21:19:43 UTC] Login::run got an object
[07-May-2022 21:19:43 UTC] createIfNotExists:: admin
[07-May-2022 21:19:43 UTC] Verification Start https://www.vodtube.pl/
[07-May-2022 21:19:43 UTC] Verification Creating the Cache https://www.vodtube.pl/
[07-May-2022 21:19:44 UTC] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fwww.vodtube.pl%2F): {"msg":["https:\/\/www.vodtube.pl\/ Site verified"],"isPrivate":false,"verified":true,"status":"a"}
[07-May-2022 21:19:44 UTC] Login:: almost done
[07-May-2022 21:19:44 UTC] Login:: done session_id = 2c7g5hl6k2teqen9q1qvgp6uqj session_login 
[07-May-2022 21:19:44 UTC] PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Configuration.php on line 52
[07-May-2022 21:19:45 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 21:19:45 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1242
[07-May-2022 21:19:45 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[07-May-2022 21:19:45 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
[08-May-2022 11:54:41 UTC] logoff:: done session_id = 2c7g5hl6k2teqen9q1qvgp6uqj
[08-May-2022 11:54:41 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 130
[08-May-2022 11:54:41 UTC] PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Login.php on line 131
[08-May-2022 11:54:41 UTC] https://www.vodtube.pl/ == https://www.vodtube.pl/
[08-May-2022 11:54:41 UTC] login.json: Login::run
[08-May-2022 11:54:41 UTC] Login::run (admin, ***, https://www.vodtube.pl/, true)
[08-May-2022 11:54:41 UTC] Login::run request login user (admin)
[08-May-2022 11:54:41 UTC] Login::run request login complete user (admin)
[08-May-2022 11:54:41 UTC] Login::run got an object
[08-May-2022 11:54:41 UTC] createIfNotExists:: admin
[08-May-2022 11:54:41 UTC] Verification Start https://www.vodtube.pl/
[08-May-2022 11:54:41 UTC] Verification Creating the Cache https://www.vodtube.pl/
[08-May-2022 11:54:42 UTC] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fwww.vodtube.pl%2F): {"msg":["https:\/\/www.vodtube.pl\/ Site verified"],"isPrivate":false,"verified":true,"status":"a"}
[08-May-2022 11:54:42 UTC] Login:: almost done
[08-May-2022 11:54:42 UTC] Login:: done session_id = 2c7g5hl6k2teqen9q1qvgp6uqj session_login 
[08-May-2022 11:54:42 UTC] PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/objects/Configuration.php on line 52
[08-May-2022 11:54:42 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[08-May-2022 11:54:42 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1242
[08-May-2022 11:54:42 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[08-May-2022 11:54:42 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
[08-May-2022 11:54:47 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[08-May-2022 11:54:47 UTC] PHP Deprecated:  basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1470
[08-May-2022 11:54:47 UTC] PHP Deprecated:  stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/view/jquery-file-upload/server/php/UploadHandler.php on line 1335
`

please log in and see that the encoder does not download movies 
(log: qwert, pass: qwert) this is a minute

**Comment by DanielnetoDotCom** [comment]
I cannot see any error on your log

you may want to try to disable the deprecated notifications in your php.ini file and get new logs

if it is not downloading videos from YouTube and other sites , you may want to check your youtube-dl

**Comment by KrzysioMisio** [comment]
I see you don't want to go to my site and check if the encoder works, 
the encoder is not downloading files from the disk. 
Instead of wasting your time writing with me you would have seen it yourself long time ago
encoder not working with PHP8.1.5
thank you for your time and unfortunately I am forced to install PHP7.4 to make it work

**Comment by KrzysioMisio** [comment]
modules are not missing this is my phpinfo https://www.vodtube.pl/phpinfo.php
streamer page works
Only encoder is not working
see that other sites also had problems with it 
https://github.com/textpattern/textpattern/issues/1699
https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation
read for yourself that many changes have been made
https://www.hostinger.com/tutorials/php-8-1

**Comment by DanielnetoDotCom** [comment]
I have a lot of installation on the latest PHP.8.1

**Comment by DanielnetoDotCom** [comment]
This is the tutorials site health check 
![8CBF2279-8B81-4C4B-957D-704F7D9C1242](https://user-images.githubusercontent.com/18009293/167306404-2e2e4237-a8a7-4acb-bfe8-fd4a4b53a969.jpeg)

**Comment by KrzysioMisio** [comment]
please watch this video again
why is this information displayed?
Why doesn't the upload work?
Why the video doesn't load?
in the log file it is written that in the php code there are outdated functions, that is why it does not work
`PHP Deprecated: setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/vodtube.pl/public_html/encoder/**objects/Login.php on line 131**`
ok, if you install a new Linux system and php8.1.5 and you have the same thing then fix it. 
The topic can be closed,
 And I install php7.4

https://user-images.githubusercontent.com/93145787/167308227-706ef325-6395-4510-9710-e91d2ae6e257.mp4

**Comment by DanielnetoDotCom** [comment]
Again

deprecated is not an error and cannot cause that. In my opinion this log information is useless

**Comment by DanielnetoDotCom** [comment]
If you insist the error is regarding version 8.1.5, fall back to version 8.1.0 because that is the same I am using in tutorials site and also the public  encoders 1 and 2

**Comment by KrzysioMisio** [comment]
I have a new installation of ubuntu and the php8.1.0 version is not available in the repo
there is only php7.4 or 8.1.5

**Comment by DanielnetoDotCom** [comment]
What Ubuntu are you using?

**Comment by KrzysioMisio** [comment]
Ubuntu 20.04.4 LTS

**Comment by DanielnetoDotCom** [comment]
I just update the tutorial site and encoders to php8.1.5 and they are working fine

**Comment by DanielnetoDotCom** [comment]
![C26751CF-E54A-4531-8924-1A45AC01E263](https://user-images.githubusercontent.com/18009293/167309498-6db2f5d3-24f3-4b52-91c5-15661a809d38.png)

**Comment by KrzysioMisio** [comment]
Can you add a movie from a disk through an encoder ?
because the page works for me too, but you cannot add a film, it does not load 
like the video I showed

**Comment by DanielnetoDotCom** [comment]
you can try to use the demo site

use https://encoder2.wwbn.net/

site https://demo.avideo.com/

user: admin
pass: 123

**Comment by KrzysioMisio** [comment]
on demo.avideo.com you have 
![demo](https://user-images.githubusercontent.com/93145787/167312537-7e0288de-e0d1-49e3-a482-8e6133f43818.png)

**Comment by DanielnetoDotCom** [comment]
But the encoder is 8.1.5

Demo is ubuntu 16 I cannot update it.

The tutorials site is PHP v8.1.5 and it is working fine.

Sorry, I can just tell you you are looking for the error in the wrong place and it works without any problem on PHP 8..1.5, I cannot continue this post without new information.
