### ISSUE TITLE
Uncaught mysqli_sql_exception: - What does it mean ?

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#6760]
Hi 

Not sure what this means below. This error has come up a few times. 

Whats the best thing to do ?
Regards 

 [21-Jun-2022 09:22:45 Europe/London] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1000, 1000' at line 1 in \/var\/www\/html\/AVideo\/objects\/mysql_dal.php:160\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/mysql_dal.php(160): mysqli->prepare()\n#1 \/var\/www\/html\/AVideo\/objects\/category.php(420): sqlDAL::readSql()\n#2 \/var\/www\/html\/AVideo\/plugin\/Layout\/categoriesTopButtons.php(20): Category::getAllCategories()\n#3 \/var\/www\/html\/AVideo\/plugin\/Layout\/Layout.php(501): include('...')\n#4 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1094): Layout->navBarAfter()\n#5 \/var\/www\/html\/AVideo\/view\/include\/navbar.php(1445): AVideoPlugin::navBarAfter()\n#6 \/var\/www\/html\/AVideo\/view\/trending.php(45): include('...')\n#7 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":160} SCRIPT_NAME: /view/trending.php

**Comment by kollossus55** [comment]
Also notice this has now come up:

YouTubeAPI Error
The developer_key1 is empty and we could not use.

I do have one in the first box..
Regards

**Comment by DanielnetoDotCom** [comment]
I am not sure where it comes from but looks like you have some plugins misconfigured.

you should only enable the plugins that you are sure are correct. 

start disabeling the plugins you are not sure how works, then enable one by one making sure they are working properly
