### ISSUE TITLE
Fatal error in Websocket

### ISSUE THREAD

**Issue by lerd2805** [WWBN/AVideo#6772]
Hi dear friend @DanielnetoDotCom, i have the following error when i start the websocket 3 seconds later it unexpectedly closes. Could you help with this?

[2022-06-22 18:04:26] AVideoLog::DEBUG: _mysql_connect HOST=wd_dreamax_db,DB=avideodb SCRIPT_NAME: /var/www/html/plugin/YPTSocket/server.php
[2022-06-22 18:04:27] AVideoLog::DEBUG: getStart language: got from config  SCRIPT_NAME: /var/www/html/plugin/YPTSocket/server.php
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/objects/functions.php:3876) in /var/www/html/plugin/YPTSocket/server.php on line 26
[2022-06-22 13:04:27] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/plugin/YPTSocket/server.php
Starting AVideo Socket server version 3.3 on port 2053
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/dreamax.tv/fullchain.pem 
Parameter [local_pk]: /etc/letsencrypt/live/dreamax.tv/privkey.pem 
Parameter [allow_self_signed]: 1 
Parameter [verify_peer]:  
Parameter [verify_peer_name]:  
Parameter [security_level]: 0 
2022-06-22 13:04:27 Construct
2022-06-22 13:04:37 New connection (180) ypt-Chrome-Windows_10-e9dcf39216adba705808d8639899d384-8b11e0a1c25a29ca8cd6b530e64c5294-0 https://dreamax.tv/view/?v=67&channelName=Nevo Chrome
2022-06-22 13:04:37 msgToAll FROM (180) NEW_CONNECTION Total Clients: 1

Fatal error: Uncaught Error: Class 'Live' not found in /var/www/html/objects/functions.php:7082

Stack trace:
#0 /var/www/html/plugin/YPTSocket/Message.php(495): getStatsNotifications()
#1 /var/www/html/plugin/YPTSocket/Message.php(485): Socket\Message->getLivesTotal()
#2 /var/www/html/plugin/YPTSocket/Message.php(335): Socket\Message->getTotals()
#3 /var/www/html/plugin/YPTSocket/Message.php(553): Socket\Message->msgToResourceId()
#4 /var/www/html/plugin/YPTSocket/Message.php(122): Socket\Message->msgToAll()
#5 /var/www/html/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(142): Socket\Message->onOpen()
#6 /var/www/html/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(51): Ratchet\WebSocket\WsServer->onOpen()
#7 /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(112): Ratchet\Http\HttpServer->onMessage()
#8 /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(95): Ratchet\Server\IoServer->handleData()
#9 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.p in /var/www/html/objects/functions.php on line 7082

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that, I am sending an update soon

**Comment by lerd2805** [comment]
I confirm that it works now. Thanks a lot @DanielnetoDotCom!!!
