### ISSUE TITLE
Can not display first page

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#6831]
8-Jul-2020 8:40(JST) We update AVideo
We rebooted AVideo Server(Ubuntu18.04)
I access AVideo login page form Firefox or Chrome.
I login admin. But first page does not display.

AVideo.log next
[08-Jul-2022 09:36:41 Asia/Tokyo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: fgets(): Argument #1 ($stream) must be of type resource, bool given in \/var\/www\/html\/AVideo\/objects\/functions.php:8858\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(8858): fgets()\n#1 \/var\/www\/html\/AVideo\/objects\/functions.php(8840): getHtaccessForVideoVersion()\n#2 \/var\/www\/html\/AVideo\/objects\/include_config.php(151): adminSecurityCheck()\n#3 \/var\/www\/html\/AVideo\/videos\/configuration.php(44): require_once('...')\n#4 \/var\/www\/html\/AVideo\/view\/index.php(26): require_once('...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":8858} SCRIPT_NAME: /AVideo/view/index.php

![AVideoerro](https://user-images.githubusercontent.com/46562199/177894144-5097f43b-e7ab-44e6-8bc5-0dcab6814a2a.png)

What do we fix this problem.

**Comment by hnagasawa** [comment]
I see #6828. But This problem does not fix.

**Comment by hnagasawa** [comment]
First page design is Netfflix

**Comment by DanielnetoDotCom** [comment]
can u please update and try again?

**Comment by hnagasawa** [comment]
I tried update again. Already update messages display

**Comment by hnagasawa** [comment]
I retry update. This problem fix. Why ?

**Comment by DanielnetoDotCom** [comment]
because I just sent new updates
