### ISSUE TITLE
New Errors after latest git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6833]
[08-Jul-2022 01:02:41 America/Denver] AVideoLog::SECURITY: isUntrustedRequest: "SAVE videos" SCRIPT_NAME: /plugin/Live/on_record_done.php

[08-Jul-2022 00:58:58 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Attempt to assign property \"title\" on bool in \/var\/www\/myMySQLUser\/objects\/functions.php:8417\nStack trace:\n#0 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/mediaSession.php(6): getMediaSession()\n#1 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/PlayerSkins.php(335): include('...')\n#2 \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php(179): PlayerSkins->getFooterCode()\n#3 \/var\/www\/myMySQLUser\/view\/include\/footer.php(90): AVideoPlugin::getFooterCode()\n#4 \/var\/www\/myMySQLUser\/view\/videoNotFound.php(47): include('...')\n#5 \/var\/www\/myMySQLUser\/objects\/functions.php(5982): include('...')\n#6 \/var\/www\/myMySQLUser\/view\/modeYoutube.php(271): videoNotFound()\n#7 \/var\/www\/myMySQLUser\/view\/index.php(50): require('...')\n#8 {main}\n  thrown","file":"\/var\/www\/myMySQLUser\/objects\/functions.php","line":8417} SCRIPT_NAME: /view/index.php

[08-Jul-2022 00:15:59 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, bool given in \/var\/www\/myMySQLUser\/objects\/functions.php:1644\nStack trace:\n#0 \/var\/www\/myMySQLUser\/objects\/functions.php(1644): imagesx()\n#1 \/var\/www\/myMySQLUser\/objects\/functions.php(1706): im_resize()\n#2 \/var\/www\/myMySQLUser\/plugin\/Live\/getImage.php(123): im_resizeV2()\n#3 {main}\n  thrown","file":"\/var\/www\/myMySQLUser\/objects\/functions.php","line":1644} SCRIPT_NAME: /plugin/Live/getImage.php

[07-Jul-2022 23:40:50 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":116,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/user.php","line":727,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/objects\/userAddNew.json.php","line":86,"function":"save","class":"User","type":"->"}] SCRIPT_NAME: /objects/userAddNew.json.php

[07-Jul-2022 23:40:50 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":112,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/user.php","line":727,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/objects\/userAddNew.json.php","line":86,"function":"save","class":"User","type":"->"}] SCRIPT_NAME: /objects/userAddNew.json.php

[07-Jul-2022 23:40:50 America/Denver] AVideoLog::ERROR: #0 path/to/my/streamer/site/objects/mysql_dal.php(109): mysqli_stmt->execute()

[07-Jul-2022 20:26:44 America/Denver] PHP Warning:  Cannot modify header information - headers already sent by (output started at path/to/my/streamer/site/objects/functions.php:3986) in path/to/my/streamer/site/plugin/YPTSocket/server.php on line 26

**Comment by DanielnetoDotCom** [comment]
Just fixed, please update again

**Comment by DanielnetoDotCom** [comment]
strange, I just tested and it works here.

can you please share more from your log?

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 

[08-Jul-2022 19:32:56 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":116,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/user.php","line":727,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/objects\/userAddNew.json.php","line":86,"function":"save","class":"User","type":"->"}] SCRIPT_NAME: /objects/userAddNew.json.php

**Comment by milehighkaraoke** [comment]
This is the error I get when I try to create a user...

**Comment by DanielnetoDotCom** [comment]
try to share the log directly from the avideo.log file

get it around this time 08-Jul-2022 19:32:5

I need more information. right now I do not know what is the error yet
