### ISSUE TITLE
Live stream not working after new update..... THIS UPDATE IS A MESS

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6837]
[08-Jul-2022 19:32:56 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":116,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/user.php","line":727,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/objects\/userAddNew.json.php","line":86,"function":"save","class":"User","type":"->"}] SCRIPT_NAME: /objects/userAddNew.json.php
[08-Jul-2022 19:32:56 America/Denver] AVideoLog::ERROR: #0 path/to/my/streamer/site/objects/mysql_dal.php(109): mysqli_stmt->execute(

[08-Jul-2022 11:37:14 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Attempt to assign property \"title\" on bool in \/var\/www\/myMySQLUser\/objects\/functions.php:8424\nStack trace:\n#0 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/mediaSession.php(6): getMediaSession()\n#1 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/PlayerSkins.php(335): include('...')\n#2 \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php(179): PlayerSkins->getFooterCode()\n#3 \/var\/www\/myMySQLUser\/view\/include\/footer.php(90): AVideoPlugin::getFooterCode()\n#4 \/var\/www\/myMySQLUser\/view\/videoNotFound.php(47): include('...')\n#5 \/var\/www\/myMySQLUser\/objects\/functions.php(5989): include('...')\n#6 \/var\/www\/myMySQLUser\/view\/modeYoutube.php(271): videoNotFound()\n#7 \/var\/www\/myMySQLUser\/view\/index.php(50): require('...')\n#8 {main}\n thrown","file":"\/var\/www\/myMySQLUser\/objects\/functions.php","line":8424} SCRIPT_NAME: /view/index.php

**Comment by DanielnetoDotCom** [comment]
I need more from your log

you are removing the most important part to understand the problem

**Comment by milehighkaraoke** [comment]
this is all that is in my log!!!!!
I am still not able to connect my live stream it says key is invalid. I looked and my key is correct


[10-Jul-2022 07:53:02 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Attempt to assign property \"title\" on bool in \/var\/www\/myMySQLUser\/objects\/functions.php:8424\nStack trace:\n#0 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/mediaSession.php(6): getMediaSession()\n#1 \/var\/www\/myMySQLUser\/plugin\/PlayerSkins\/PlayerSkins.php(335): include('...')\n#2 \/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php(179): PlayerSkins->getFooterCode()\n#3 \/var\/www\/myMySQLUser\/view\/include\/footer.php(90): AVideoPlugin::getFooterCode()\n#4 \/var\/www\/myMySQLUser\/view\/videoNotFound.php(47): include('...')\n#5 \/var\/www\/myMySQLUser\/objects\/functions.php(5989): include('...')\n#6 \/var\/www\/myMySQLUser\/view\/modeYoutube.php(271): videoNotFound()\n#7 \/var\/www\/myMySQLUser\/view\/index.php(50): require('...')\n#8 {main}\n  thrown","file":"\/var\/www\/myMySQLUser\/objects\/functions.php","line":8424} SCRIPT_NAME: /view/index.php

**Comment by milehighkaraoke** [comment]
It was up to date... I got a bigger set of SSD's so I am just gonna give it a fresh install.
