### ISSUE TITLE
Rating system bug

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#6972]
Hi,

This bug has been about a while now i just haven't reported it.

On the rating system now when it is turned on in the advanced settings plugin. Let's say MA rating is turned on and a user uses that rating on upload this error is constantly thrown until i turn the rating system off again in advanced settings. Only then will the video show and play fine. If the rating is on for that video an error page is displayed with the following error. mypath replaces my true website path.

int(1) ["message"]=> string(829) "Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, array given in /mypath/objects/functions.php:5636 Stack trace: #0 /mypath/objects/functions.php(5636): strip_tags() #1 /mypath/objects/functions.php(5917): html2plainText() #2 /mypath/plugin/CustomizeAdvanced/confirmRating.php(26): getSEODescription() #3 /mypath/plugin/CustomizeAdvanced/CustomizeAdvanced.php(342): include('...') #4 /mypath/plugin/AVideoPlugin.php(849): CustomizeAdvanced->getModeYouTube() #5 /mypath/view/modeYoutube.php(275): AVideoPlugin::getModeYouTube() #6 /mypath/view/index.php(50): require('...') #7 {main} thrown" ["file"]=> string(55) "/mypath/objects/functions.php" ["line"]=> int(5636) }

-------------------

array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(829) "Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, array given in /mypath/objects/functions.php:5636
Stack trace:
#0 /mypath/objects/functions.php(5636): strip_tags()
#1 /mypath/objects/functions.php(5917): html2plainText()
#2 /mypath/plugin/CustomizeAdvanced/confirmRating.php(26): getSEODescription()
#3 /mypath/plugin/CustomizeAdvanced/CustomizeAdvanced.php(342): include('...')
#4 /mypath/plugin/AVideoPlugin.php(849): CustomizeAdvanced->getModeYouTube()
#5 /mypath/view/modeYoutube.php(275): AVideoPlugin::getModeYouTube()
#6 /mypath/view/index.php(50): require('...')
#7 {main}
  thrown"
  ["file"]=>
  string(55) "/mypath/objects/functions.php"
  ["line"]=>
  int(5636)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by para2022** [comment]
That fixed it. Thank you buddy :)
