### ISSUE TITLE
SD media with previews extracted from the video display in "postage stamp" size on Roku

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6989]
**Describe the bug**
When we export a video for Roku (functions.php convertImageToRoku->convertImageIfNotExists->im_resizeV2), if it has a poster frame less than 1920x1280, it centers it within the frame.

When this 1920x1080 video is then scaled down in the preview on your Roku channel, the visible portion of the image shrinks to a postage stamp size.

Instead of calling im_resizev2 we should call something which scales **up** to the 1920x1080 bounds.

Output from im_resizev2 from a SD video:
![image](https://user-images.githubusercontent.com/11711050/184059072-4135e20f-a1a0-43bc-9f7c-64639460a0b2.jpeg)

As seen on Roku:
![IMG_8018](https://user-images.githubusercontent.com/11711050/184059493-39d7944f-db8e-4837-8f9c-108e64e5683b.jpg)

**Comment by DanielnetoDotCom** [comment]
scale up will result in a bad resolution image.

I recommend you submit a high-definition image for your posters and let the script create the resolution variations for all platforms.

**Comment by walt93** [comment]
Yes. Understood. I have a daunting amount of media to produce graphics for. This will take more time and money than I have patience and resources for. The graphics are going to reveal "this is from a VHS recording of a presentation in 1993". That's ok for my use case.

I'd even accept a switch that I had to turn on "ScaleUpTerribleLookingLowResImagesForRoku" knowing that it produces an ugly result. IMO it's better ugly than postage stamp.

**Comment by DanielnetoDotCom** [comment]
This update should allow upscales now

**Comment by walt93** [comment]
Testing this now, and the script went through about 500 pieces of media before it hit this:

Loading https://conspyre.tv/roku.json?catName=documentary gives the following error:
```
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(757) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /var/www/html/AVideo/objects/functions.php:1817
Stack trace:
#0 /var/www/html/AVideo/objects/functions.php(1817): imagesx(NULL)
#1 /var/www/html/AVideo/objects/functions.php(3844): scaleUpImage('/var/www/html/A...', '/var/www/html/A...', 1280, 720)
#2 /var/www/html/AVideo/objects/functions.php(3818): convertImageIfNotExists('/var/www/html/A...', '/var/www/html/A...', 1280, 720, true)
#3 /var/www/html/AVideo/objects/video.php(4000): convertImageToRoku('/var/www/html/A...', '/var/www/html/A...')
#4 /var/www/html/AVideo/feed/roku.json.php(62): Video::getRokuImage(10977)
#5 /var/www/html/AVideo/feed/index.php(52): include('/var/www/html/A...')
#6 {main}
  thrown"
  ["file"]=>
  string(42) "/var/www/html/AVideo/objects/functions.php"
  ["line"]=>
  int(1817)
}
<pre>array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(757) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /var/www/html/AVideo/objects/functions.php:1817
Stack trace:
#0 /var/www/html/AVideo/objects/functions.php(1817): imagesx(NULL)
#1 /var/www/html/AVideo/objects/functions.php(3844): scaleUpImage('/var/www/html/A...', '/var/www/html/A...', 1280, 720)
#2 /var/www/html/AVideo/objects/functions.php(3818): convertImageIfNotExists('/var/www/html/A...', '/var/www/html/A...', 1280, 720, true)
#3 /var/www/html/AVideo/objects/video.php(4000): convertImageToRoku('/var/www/html/A...', '/var/www/html/A...')
#4 /var/www/html/AVideo/feed/roku.json.php(62): Video::getRokuImage(10977)
#5 /var/www/html/AVideo/feed/index.php(52): include('/var/www/html/A...')
#6 {main}
  thrown"
  ["file"]=>
  string(42) "/var/www/html/AVideo/objects/functions.php"
  ["line"]=>
  int(1817)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
</pre>
```

**Comment by walt93** [comment]
Tail of avideo.log seems to contain the same, adding just in case.
```

[21-Aug-2022 18:41:03 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in \/var\/www\/html\/AVideo\/objects\/functions.php:1817\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1817): imagesx(NULL)\n#1 \/var\/www\/html\/AVideo\/objects\/functions.php(3844): scaleUpImage('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720)\n#2 \/var\/www\/html\/AVideo\/objects\/functions.php(3818): convertImageIfNotExists('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720, true)\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(4000): convertImageToRoku('\/var\/www\/html\/A...', '\/var\/www\/html\/A...')\n#4 \/var\/www\/html\/AVideo\/feed\/roku.json.php(62): Video::getRokuImage(10977)\n#5 \/var\/www\/html\/AVideo\/feed\/index.php(52): include('\/var\/www\/html\/A...')\n#6 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":1817} SCRIPT_NAME: /feed/index.php
[21-Aug-2022 18:41:04 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in \/var\/www\/html\/AVideo\/objects\/functions.php:1817\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1817): imagesx(NULL)\n#1 \/var\/www\/html\/AVideo\/objects\/functions.php(3844): scaleUpImage('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720)\n#2 \/var\/www\/html\/AVideo\/objects\/functions.php(3818): convertImageIfNotExists('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720, true)\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(4000): convertImageToRoku('\/var\/www\/html\/A...', '\/var\/www\/html\/A...')\n#4 \/var\/www\/html\/AVideo\/feed\/roku.json.php(62): Video::getRokuImage(10977)\n#5 \/var\/www\/html\/AVideo\/feed\/index.php(52): include('\/var\/www\/html\/A...')\n#6 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":1817} SCRIPT_NAME: /feed/index.php
[21-Aug-2022 18:41:05 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in \/var\/www\/html\/AVideo\/objects\/functions.php:1817\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1817): imagesx(NULL)\n#1 \/var\/www\/html\/AVideo\/objects\/functions.php(3844): scaleUpImage('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720)\n#2 \/var\/www\/html\/AVideo\/objects\/functions.php(3818): convertImageIfNotExists('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720, true)\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(4000): convertImageToRoku('\/var\/www\/html\/A...', '\/var\/www\/html\/A...')\n#4 \/var\/www\/html\/AVideo\/feed\/roku.json.php(62): Video::getRokuImage(10977)\n#5 \/var\/www\/html\/AVideo\/feed\/index.php(52): include('\/var\/www\/html\/A...')\n#6 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":1817} SCRIPT_NAME: /feed/index.php
[21-Aug-2022 18:41:05 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in \/var\/www\/html\/AVideo\/objects\/functions.php:1817\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/functions.php(1817): imagesx(NULL)\n#1 \/var\/www\/html\/AVideo\/objects\/functions.php(3844): scaleUpImage('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720)\n#2 \/var\/www\/html\/AVideo\/objects\/functions.php(3818): convertImageIfNotExists('\/var\/www\/html\/A...', '\/var\/www\/html\/A...', 1280, 720, true)\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(4000): convertImageToRoku('\/var\/www\/html\/A...', '\/var\/www\/html\/A...')\n#4 \/var\/www\/html\/AVideo\/feed\/roku.json.php(62): Video::getRokuImage(10977)\n#5 \/var\/www\/html\/AVideo\/feed\/index.php(52): include('\/var\/www\/html\/A...')\n#6 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/functions.php","line":1817} SCRIPT_NAME: /feed/index.php
```

**Comment by DanielnetoDotCom** [comment]
this may not fix the problem, but the stript may not crash and we may have some clue of what is missing.

**Comment by walt93** [comment]
Ok. This is odd. Building the JSON went without errors.

I see this once in the log:

`[22-Aug-2022 16:40:48 America/Los_Angeles] AVideoLog::DEBUG: scaleUpImage error, we could not convert it {"0":1280,"1":720,"2":18,"3":"width=\"1280\" height=\"720\"","bits":8,"mime":"image\/webp"} SCRIPT_NAME: /feed/index.php`

which I guess doesn't have the video id, so I'm not sure which video has the issue.

But the odd part is the tail of the log has this. Looks like an error in your sql debug logging? You might want to check it.

```
[22-Aug-2022 16:41:43 America/Los_Angeles] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":166,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1353,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/functions.php","line":79,"function":"getAllVideos","class":"Video","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php","line":89,"function":"createGallery"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php","line":31,"args":["\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php"],"function":"include"}] SCRIPT_NAME: /view/index.php
[22-Aug-2022 16:41:43 America/Los_Angeles] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1064) (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-24, 12' at line 1)  preparedStatement = "SELECT STRAIGHT_JOIN  u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category,c.description as category_description, v.created as videoCreation, v.modified as videoModified  FROM videos as v  LEFT JOIN categories c ON categories_id = c.id  LEFT JOIN users u ON v.users_id = u.id  WHERE 2=2  AND u.status = 'a'  AND  ((SELECT count(id) FROM videos_group_view as gv WHERE gv.videos_id = v.id ) = 0 AND (SELECT count(id) FROM categories_has_users_groups as cug WHERE cug.categories_id = v.categories_id ) = 0)  AND v.status IN ('a','k','f') ORDER BY  v.created DESC  LIMIT -24, 12 " formats = "" values = [] refreshCache = false stmt = null SCRIPT_NAME: /view/index.php
[22-Aug-2022 16:41:43 America/Los_Angeles] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":174,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1353,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/functions.php","line":79,"function":"getAllVideos","class":"Video","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php","line":89,"function":"createGallery"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php","line":31,"args":["\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php"],"function":"include"}] SCRIPT_NAME: /view/index.php
```

**Comment by DanielnetoDotCom** [comment]
Hi, I have sent you a couple of updates to try to avoid those errors

**Comment by walt93** [comment]
Cool. I'm going through the Roku-ingest-publish cycle again, cleared cached directory, and re-running the script that pulls all of the Roku JSONs. It looks like the images are still not being scaled.

From https://conspyre.tv/roku.json?catName=videos

https://conspyre.tv//videos//_YPTuniqid_604b0e8ac67461.91303424//_YPTuniqid_604b0e8ac67461.91303424_roku.jpg?cache=1659869803_1659869803
https://conspyre.tv//videos//_YPTuniqid_604b0e51d7e1e2.19820365//_YPTuniqid_604b0e51d7e1e2.19820365_roku.jpg
https:\/\/conspyre.tv\/videos\/_YPTuniqid_604b0dae50ed59.82533795\/_YPTuniqid_604b0dae50ed59.82533795_roku.jpg?cache=1660170325_1660170325

**Comment by DanielnetoDotCom** [comment]
Hi, you need to delete the old thumbs first, the script will regenerate the files

**Comment by walt93** [comment]
What is the process to delete the old thumbnail images?

**Comment by DanielnetoDotCom** [comment]
You may want to try the [deleteThumbsFiles.php](https://github.com/WWBN/AVideo/blob/master/install/deleteThumbsFiles.php)

`cd /var/www/html/AVideo/install/ && php deleteThumbsFiles.php`

**Comment by walt93** [comment]
Ohhhhh ok, notes added. TY
