### ISSUE TITLE
Stripe payment is not reflecting in the user account

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7184]
I am trying to add funds to my wallet using stripe. I can see the transaction successful in stripe account but it does not reflect on the wallet.
![image](https://user-images.githubusercontent.com/25535711/192426141-d0b6c5cd-cceb-4fbb-8b8c-a941ba45175b.png)

**Comment by DanielnetoDotCom** [comment]
check the logs for errors

**Comment by mankota** [comment]
Here is the error log related to stripe.

 [27-Sep-2022 06:32:54 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Stripe\\Exception\\SignatureVerificationException: No signatures found matching the expected signature for payload in \/var\/www\/html\/AVideo\/vendor\/stripe\/stripe-php\/lib\/Exception\/SignatureVerificationException.php:28\nStack trace:\n#0 \/var\/www\/html\/AVideo\/vendor\/stripe\/stripe-php\/lib\/WebhookSignature.php(61): Stripe\\Exception\\SignatureVerificationException::factory('No signatures f...', '{\\n  \"id\": \"evt_...', 't=1664260374,v1...')\n#1 \/var\/www\/html\/AVideo\/vendor\/stripe\/stripe-php\/lib\/Webhook.php(29): Stripe\\WebhookSignature::verifyHeader('{\\n  \"id\": \"evt_...', 't=1664260374,v1...', 'whsec_54gqoVeSu...', 300)\n#2 \/var\/www\/html\/AVideo\/plugin\/DiskUploadQuota\/Subscription\/Stripe\/ipn.php(18) : eval()'d code(1) : eval()'d code(40): Stripe\\Webhook::constructEvent('{\\n  \"id\": \"evt_...', 't=1664260374,v1...', 'whsec_54gqoVeSu...')\n#3 \/var\/www\/html\/AVideo\/plugin\/DiskUploadQuota\/Subscription\/Stripe\/ipn.php(18) : eval()'d code(1): eval()\n#4 \/var\/www\/html\/AVideo\/plugin\/DiskUploadQuota\/Subscription\/Stripe\/ipn.php(18): eval()\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/vendor\/stripe\/stripe-php\/lib\/Exception\/SignatureVerificationException.php","line":28} SCRIPT_NAME: /plugin/DiskUploadQuota/Subscription/Stripe/ipn.php

**Comment by mankota** [comment]
I noticed that there is no signature. What is that? How do I get the signature in stripe?

**Comment by DanielnetoDotCom** [comment]
this is because you did not get the correct webhook signature

here is the place to get it https://dashboard.stripe.com/test/webhooks/

![chrome-capture-2022-8-27 (1)](https://user-images.githubusercontent.com/18009293/192615828-42dd19fd-ec17-4b38-9aee-cfa0e9df80b0.gif)
