### ISSUE TITLE
GIt pull->update failure

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7404]
**Describe the bug**
Update via git pull. Update database via site update function.

**To Reproduce**
1. sudo git pull
2. Site Update->Update button

**Expected behavior**
Success

**Error Logs (on-screen) ** 
```
array(4) { ["type"]=> int(1) ["message"]=> string(230) "Uncaught mysqli_sql_exception: Duplicate column name 'publish_datetime' in /var/www/html/AVideo/view/update.php:143 Stack trace: #0 /var/www/html/AVideo/view/update.php(143): mysqli->query('\nALTER TABLE `v...') #1 {main} thrown" ["file"]=> string(36) "/var/www/html/AVideo/view/update.php" ["line"]=> int(143) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(230) "Uncaught mysqli_sql_exception: Duplicate column name 'publish_datetime' in /var/www/html/AVideo/view/update.php:143
Stack trace:
#0 /var/www/html/AVideo/view/update.php(143): mysqli->query('\nALTER TABLE `v...')
#1 {main}
  thrown"
  ["file"]=>
  string(36) "/var/www/html/AVideo/view/update.php"
  ["line"]=>
  int(143)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```
![Screen Shot 2022-11-21 at 1 27 12 AM](https://user-images.githubusercontent.com/11711050/203014263-6122bea7-d669-4038-b504-c308e4078728.png)

**Comment by DanielnetoDotCom** [comment]
if you refresh the page does the error disappear?

**Comment by walt93** [comment]
Yes, it cleared after that, just making sure I captured it in case you needed it.
