### ISSUE TITLE
piece of code

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7415]
Hello Daniel,
there is a piece of code at the bottom of the page
when we open the my account tab and go to the bottom of the page this piece of code pops up
if I disable the Login Control plugin the code disappears
also the tabs don't work when we are on the my account page because of this code issue 
Any help??
Thank you
Ilias

**User Account**
![piece code](https://user-images.githubusercontent.com/60543030/203655571-7c8dfefc-3dd3-4f87-8218-a11e36f04a9a.jpg)

**Admin Account**
![piece code1](https://user-images.githubusercontent.com/60543030/203655663-a8c63801-c6be-418c-8ec8-9377a0dc9556.jpg)

**Tab**
![tab](https://user-images.githubusercontent.com/60543030/203655686-5ebeb869-bb77-43d7-9692-405e2f373553.jpg)

**Comment by wetubeclub** [comment]
I don't know if this helps

-----------------------------------------------------------------------------------------------------------------------------------
[23-Nov-2022 23:35:12 Europe/Stockholm] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class 'phpseclib\\Crypt\\RSA' not found in \/var\/www\/html\/AVideo\/plugin\/LoginControl\/pgp\/functions.php:9\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/LoginControl\/profileTabContent.php(5): createKeys('Test myemail@mydomain.com 1669242912)\n#1 \/var\/www\/html\/AVideo\/plugin\/LoginControl\/LoginControl.php(476): include('\/var\/www\/html\/A...')\n#2 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1653): LoginControl::profileTabContent(1)\n#3 \/var\/www\/html\/AVideo\/view\/user.php(75): AVideoPlugin::profileTabContent(1)\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/LoginControl\/pgp\/functions.php","line":9} SCRIPT_NAME: /view/user.php
------------------------------------------------------------------------------------------------------------------------------------

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by wetubeclub** [comment]
Thank you Daniel,  all good now!!
it functions properly!
