### ISSUE TITLE
After videos no longer public, log being flooded errors

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7445]
@DanielnetoDotCom After I defined that all my videos are no longer public. My log is being flooded with errors:

`canWatchVideo`
`userCanWatchVideoWithAds`

I don't understand this "Ads" error, I don't have any advertising plugin running.

```
02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 245 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  245 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 245 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  245 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 247 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  247 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 247 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  247 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 246 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  246 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 246 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  246 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 207 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  207 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 207 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  207 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 203 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  203 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 203 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:02 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  203 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 238 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  238 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 238 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  238 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 235 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  235 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 235 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  235 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 147 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  147 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 147 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  147 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 205 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  205 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 205 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  205 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 204 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  204 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 204 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  204 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 206 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  206 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 206 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  206 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 145 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  145 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 145 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  145 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  25 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 146 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  146 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 146 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  146 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 143 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  143 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 143 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  143 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 138 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  138 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 138 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  138 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 156 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  156 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 156 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  156 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:01 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 120 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  120 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 120 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  120 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 209 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  209 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 209 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  209 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 211 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  211 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 211 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  211 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 152 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  152 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 152 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  152 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 99 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  99 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 99 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  99 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 150 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  150 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 150 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  150 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 126 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  126 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 126 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  126 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 236 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  236 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 236 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  236 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 208 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  208 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 208 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  208 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 94 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  94 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 94 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  94 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 149 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 00:41:00 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  149 SCRIPT_NAME: /view/index.php
```

**Comment by DanielnetoDotCom** [comment]
those are not errors, they are only logs

**Comment by gbrn** [comment]
Dani, the issue is that it is sequential, since when I enabled this private mode.
the Log in less than 10 hours already has more than 5 megs and keeps increasing.
Apparently it's the system trying to do something, as there are no users trying to access.
What do these logs represent in particular?

**Comment by DanielnetoDotCom** [comment]
if you know PHP I am sure you can figure it out

**Comment by gbrn** [comment]
I didn't understand your answer... I'm not a PHP developer.
OK, I see it's flagged as DEBUG.
As I informed, it is adding information to the LOG every second.
Sorry, I don't know which way to go.

```
 [02-Dec-2022 19:39:32 America/Sao_Paulo] AVideoLog::DEBUG: User::canWatchVideo (No can not) 152 SCRIPT_NAME: /view/index.php
 [02-Dec-2022 19:39:32 America/Sao_Paulo] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  152 SCRIPT_NAME: /view/index.php
```

**Comment by gbrn** [comment]
Now, errors started to be registered:
(These errors were not displayed before making the system private)

`[02-Dec-2022 20:01:34 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method User::canWatchVideoWithAds() in \/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/plugin\/YouPHPFlix2\/view\/BigVideoButtons.php:7\nStack trace:\n#0 \/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/plugin\/YouPHPFlix2\/view\/BigVideo.php(67): include()\n#1 \/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php(2): include('\/home\/storage\/e...')\n#2 \/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/plugin\/YouPHPFlix2\/view\/modeFlix.php(30): include('\/home\/storage\/e...')\n#3 \/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/view\/index.php(52): require('\/home\/storage\/e...')\n#4 {main}\n  thrown","file":"\/home\/storage\/e\/88\/c1\/myMySQLDatabaseo\/public_html\/cnetv\/_beta40\/plugin\/YouPHPFlix2\/view\/BigVideoButtons.php","line":7} SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
This update will reduce the logs
