### ISSUE TITLE
AVideo Encoder cannot log in

### ISSUE THREAD

**Issue by krsamue101** [WWBN/AVideo#7450]
https://user-images.githubusercontent.com/105032235/205446101-69643b9e-cbc8-4931-9e2b-82abe299769e.mp4

It stuck atlogging in.

**Comment by krsamue101** [comment]
It seems this error is not related to ssl

**Comment by DanielnetoDotCom** [comment]
all your servers MUST be HTTPS, and also set to use HTTPS (encoder, streamer, live, etc)

if you send a request to HTTP and it redirects to HTTPS it will fail.

open your js console and try to connect, it may give you some clues.

**Comment by krsamue101** [comment]
https://user-images.githubusercontent.com/105032235/205466371-012f8ea3-0d73-4643-9408-0887f7dd31ff.mp4

```
script.js:2811 showPleaseWait is in use 0 Error
    at Object.showPleaseWait (https://rdey.xyz/AVideo/view/js/script.js:2811:68)
    at HTMLFormElement.<anonymous> (https://rdey.xyz/AVideo-Encoder/:121:35)
    at HTMLFormElement.dispatch (https://rdey.xyz/AVideo-Encoder/node_modules/jquery/dist/jquery.min.js:2:43064)
    at v.handle (https://rdey.xyz/AVideo-Encoder/node_modules/jquery/dist/jquery.min.js:2:41048)
```
As you see on that video, I'm using https. And I see this  on console.

**Comment by DanielnetoDotCom** [comment]
you are probably loading something with HTTP, I recommend you reinstall AVideo now that you have the HTTPS in place (NOT THE WHOLE SERVER)
