### ISSUE TITLE
Video encoded but not appear in Channel

### ISSUE THREAD

**Issue by reda1977** [WWBN/AVideo#7619]
I install AVideo with local encoder and everything goes well but when I try to upload videos, it's successfully uploaded but not shown in 
channel I check log file it gives the following error

[02-Feb-2023 06:34:25 UTC] AVideo-Streamer sendFile error: {"duration":"EE:EE:EE","title":"TikVideo-App - 7179064112750710062-hd","videos_id":10,"video_id_hash":"SEFyQ2IrMGR5OWxmYnNiTWd5NDhrcmpocnhDRld2SU5xUnF3NThwQ3ZXaz0=","first_request":1,"categories_id":0,"format":"mp4","resolution":"720","videoDownloadedLink":"","description":"","user":"admin","password":"_user_hash_T3RlRkFLSWhaZTJYT0VBRUNWWmpkMHh0c3RxL1hMQW4rZDZvL243dkxUb015NitRVjVycXRObU5BOGVveXJZTVlBanBMcmx6aUFoc2Z5WVhXQk5WU1E9PQ==","downloadURL":"","chunkFile":"\/tmp\/YTPChunk_dA2qW3","encoderURL":"http:\/\/inivideos.com\/AVideo-Encoder\/","keepEncoding":"0","return_vars":"{\"videos_id\":10,\"video_id_hash\":\"SEFyQ2IrMGR5OWxmYnNiTWd5NDhrcmpocnhDRld2SU5xUnF3NThwQ3ZXaz0=\"}"} <=>[{"file":"\/var\/www\/html\/AVideo-Encoder\/objects\/Encoder.php","line":1518,"function":"sendFile","class":"Encoder","type":"::"},{"file":"\/var\/www\/html\/AVideo-Encoder\/objects\/Encoder.php","line":1168,"function":"sendFileChunk","class":"Encoder","type":"::"},{"file":"\/var\/www\/html\/AVideo-Encoder\/objects\/Encoder.php","line":938,"function":"send","class":"Encoder","type":"->"},{"file":"\/var\/www\/html\/AVideo-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::"}]
[02-Feb-2023 06:34:25 UTC] getReturn_vars {"videos_id":10,"video_id_hash":"SEFyQ2IrMGR5OWxmYnNiTWd5NDhrcmpocnhDRld2SU5xUnF3NThwQ3ZXaz0="}
[02-Feb-2023 06:34:25 UTC] AVideo-Encoder sending confirmation to http://inivideos.com/AVideo/objects/aVideoEncoderNotifyIsDone.json.php
[02-Feb-2023 06:34:25 UTC] AVideo-Streamer confirmation answer array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(297) "Uncaught TypeError: Illegal offset type in isset or empty in /var/www/html/AVideo/objects/video.php:670
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(716): Video->setStatus()
#1 /var/www/html/AVideo/objects/aVideoEncoderNotifyIsDone.json.php(41): Video->setAutoStatus()
#2 {main}
  thrown"
  ["file"]=>
  string(38) "/var/www/html/AVideo/objects/video.php"
  ["line"]=>
  int(670)
}
<pre>array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(297) "Uncaught TypeError: Illegal offset type in isset or empty in /var/www/html/AVideo/objects/video.php:670
Stack trace:
#0 /var/www/html/AVideo/objects/video.php(716): Video->setStatus()
#1 /var/www/html/AVideo/objects/aVideoEncoderNotifyIsDone.json.php(41): Video->setAutoStatus()
#2 {main}
  thrown"
  ["file"]=>
  string(38) "/var/www/html/AVideo/objects/video.php"
  ["line"]=>
  int(670)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
</pre>

Anny advice!

**Comment by DanielnetoDotCom** [comment]
Hi

I remember fixing a similar issue yesterday. can you please make a git pull and try again?

**Comment by reda1977** [comment]
Thanks for your support,
I tried git pull, but nothing changed as screenshots bellow

![image](https://user-images.githubusercontent.com/4091124/216421938-929c7a6e-ad92-4add-a49f-90d79d5adde4.png)
![image](https://user-images.githubusercontent.com/4091124/216422161-4e9de281-be0c-4eb1-b6bf-19ab65cbead6.png)

**Comment by DanielnetoDotCom** [comment]
did you submit the video again?

**Comment by reda1977** [comment]
I think it's resolved but another issue appears 😒
![image](https://user-images.githubusercontent.com/4091124/216433722-90caefef-48b5-41e9-95e1-9579abee4129.png)

**Comment by DanielnetoDotCom** [comment]
Please check this

https://github.com/WWBN/AVideo/wiki/What-to-do-if-your-video-does-not-play
