### ISSUE TITLE
Import YouTube it does not work

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7686]
Hi Daniel
I need help importing YouTube videos.
I insert the link as I always have and then click on Share.
It has always worked great.
From today it no longer works and no Sharing Queue or Queue Log is generated.
Can you help me to solve and tell me what to do?
I don't know if there is a need to update anything.
I kindly ask you to tell me the commands to do.
Thank you

![import youtube](https://user-images.githubusercontent.com/82677269/219790436-f6245c70-7655-4697-b355-5d3b57516e4d.JPG)

**Comment by walt93** [comment]
POSSIBLY related - @sharknetwork24 check your AVideo encoder log for something like the following
ALSO seeing failure from yt-dlp downloading from youtube.com today
SOUNDS like a yt-dlp error
WHAT do you think?

```
[17-Feb-2023 20:29:19 UTC] getTitleFromLink: Get Title Error: LC_ALL=en_US.UTF-8 /usr/local/bin/yt-dlp   --no-check-certificate --no-playlist --force-ipv4 --skip-download -e 'https://m.youtube.com/watch?v=HXuUILekAe0'
Array
(
    [0] => WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/11e3a4ec.json' failed: Traceback (most recent call last):
    [1] =>   File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 43, in store
    [2] =>     os.makedirs(os.path.dirname(fn))
    [3] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [4] =>     makedirs(head, exist_ok=exist_ok)
    [5] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [6] =>     makedirs(head, exist_ok=exist_ok)
    [7] =>   File "/usr/lib/python3.10/os.py", line 225, in makedirs
    [8] =>     mkdir(name, mode)
    [9] => PermissionError: [Errno 13] Permission denied: '/var/www/.cache'
    [10] =>
    [11] => WARNING: [youtube] HXuUILekAe0: nsig extraction failed: You may experience throttling for some formats
    [12] =>          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
    [13] =>          n = ILHY4rTZHTPjJXVR ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
    [14] => ERROR: [youtube] HXuUILekAe0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
)

[17-Feb-2023 20:29:19 UTC] youtubeDl::addVideo We could not get the title () of your video (https://m.youtube.com/watch?v=HXuUILekAe0)
[17-Feb-2023 20:29:31 UTC] getTitleFromLink: Get Title Error: LC_ALL=en_US.UTF-8 /usr/local/bin/yt-dlp   --no-check-certificate --no-playlist --force-ipv4 --skip-download -e 'https://m.youtube.com/watch?v=HXuUILekAe0'
Array
(
    [0] => WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/11e3a4ec.json' failed: Traceback (most recent call last):
    [1] =>   File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 43, in store
    [2] =>     os.makedirs(os.path.dirname(fn))
    [3] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [4] =>     makedirs(head, exist_ok=exist_ok)
    [5] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [6] =>     makedirs(head, exist_ok=exist_ok)
    [7] =>   File "/usr/lib/python3.10/os.py", line 225, in makedirs
    [8] =>     mkdir(name, mode)
    [9] => PermissionError: [Errno 13] Permission denied: '/var/www/.cache'
    [10] =>
    [11] => WARNING: [youtube] HXuUILekAe0: nsig extraction failed: You may experience throttling for some formats
    [12] =>          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
    [13] =>          n = NK2V0NH-9fgklgjB ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
    [14] => ERROR: [youtube] HXuUILekAe0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
)
```

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/WWBN/AVideo/issues/7685

**Comment by sharknetwork24** [comment]
> check this #7685
Why dont you change the $global['youtube-dl'] = 'yt-dlp';??

replace with this $global['youtube-dl'] = 'yt-dlp  --cookies /path/to/netscape-formatted-youtube-cookie/cookie.txt ';

Daniel I looked but I don't understand where I should change these entries.
Can you help me how to do it?
Thank you

**Comment by DanielnetoDotCom** [comment]
you should add it in your `Encoder/videos/configuration.php` file

**Comment by sharknetwork24** [comment]
Ok

**Comment by sharknetwork24** [comment]
Daniel I don't know where to insert.
Kindly help me?
Thanks for your help


<?php
$global['configurationVersion'] = 2;
$global['tablesPrefix'] = '';
$global['webSiteRootURL'] = 'https://sharktube.info/Encoder/';
$global['systemRootPath'] = '/var/www/html/AVideo/Encoder/';
$global['webSiteRootPath'] = '';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableImportVideo'] = false;
$global['disableWebM'] = false;
$global['defaultWebM'] = false;
$global['concurrent'] = 1;
$global['hideUserGroups'] = false;
$global['progressiveUpload'] = false;
$global['killWorkerOnDelete'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'youphptube';
$mysqlPass = 'youphptube';
$mysqlDatabase = 'AVideoEncoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}


require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by sharknetwork24** [comment]
<?php
$global['configurationVersion'] = 2;
$global['tablesPrefix'] = '';
$global['webSiteRootURL'] = 'https://sharktube.info/Encoder/';
$global['systemRootPath'] = '/var/www/html/AVideo/Encoder/';
$global['webSiteRootPath'] = '';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableImportVideo'] = false;
$global['disableWebM'] = false;
$global['defaultWebM'] = false;
$global['concurrent'] = 1;
$global['hideUserGroups'] = false;
$global['progressiveUpload'] = false;
$global['killWorkerOnDelete'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'youphptube';
$mysqlPass = 'youphptube';
$mysqlDatabase = 'AVideoEncoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}


require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by sharknetwork24** [comment]
![config](https://user-images.githubusercontent.com/82677269/219798632-0ed6a108-6121-4b2b-a8e1-3a22bae6232c.JPG)

**Comment by sharknetwork24** [comment]
![config](https://user-images.githubusercontent.com/82677269/219799865-77ff112e-8d97-4a85-99e5-c32534da03b5.JPG)

**Comment by walt93** [comment]
@sharknetwork24 it doesn't really matter, put it above the Do NOT change warning, just make sure it is formatted like the others and starts with $global and ends with a ;

**Comment by sharknetwork24** [comment]
Can you tell me where because I don't understand.

**Comment by DanielnetoDotCom** [comment]
> > check this #7685
> > Why dont you change the $global['youtube-dl'] = 'yt-dlp';??
> 
> replace with this $global['youtube-dl'] = 'yt-dlp --cookies /path/to/netscape-formatted-youtube-cookie/cookie.txt ';
> 
> Daniel I looked but I don't understand where I should change these entries. Can you help me how to do it? Thank you

this is about a different issue. be careful @sharknetwork24 you are mixing things

**Comment by DanielnetoDotCom** [comment]
> check this #7685

this is about your issue, this is a command line that you should use in the terminal

**Comment by DanielnetoDotCom** [comment]
I will update you soon with the correct answer

**Comment by DanielnetoDotCom** [comment]
@sharknetwork24 I am so sorry that is the correct answer

and you should use it in the terminal 

https://github.com/WWBN/AVideo/issues/7682#issuecomment-1434799136

**Comment by sharknetwork24** [comment]
> @sharknetwork24 I am so sorry that is the correct answer
> 
> and you should use it in the terminal 
> 
> https://github.com/WWBN/AVideo/issues/7682#issuecomment-1434799136

Can you explain yourself better Daniel?  I do not understand what I have to do.

**Comment by sharknetwork24** [comment]
Daniel, you still haven't told me what to do.
I am waiting for your help.

**Comment by DanielnetoDotCom** [comment]
If you know how to execute a command line in ubuntu this is enough:

```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```
but sorry I cannot teach you how to deal with Linux servers and execute command lines

**Comment by sharknetwork24** [comment]
But excuse me Daniel the problem I have that you can no longer upload videos with YouTube, Facebook, TikTok, Instagram is it the fault of python3? 
Just to understand....
You don't have to teach me how to use Ubuntu commands that's clear. 
But figuring out how to fix it by telling me how to fix it with the right commands to give. 
Thanks anyway and I'll let you know if I fix it.

**Comment by sharknetwork24** [comment]
<!-- Error while 

Can you see if ok?

**Comment by DanielnetoDotCom** [comment]
the commands on how to fix were in the links I sent you before https://github.com/WWBN/AVideo/issues/7686#issuecomment-1435401486

also, it is in the message I wrote for you today

https://github.com/WWBN/AVideo/issues/7686#issuecomment-1439853594

just read and you can easily resolve that issue

**Comment by sharknetwork24** [comment]
> i comandi su come risolvere erano nei link che ti ho inviato prima [del #7686 (commento)](https://github.com/WWBN/AVideo/issues/7686#issuecomment-1435401486)
> 
> inoltre, è nel messaggio che ho scritto per te oggi
> 
> [#7686 (commento)](https://github.com/WWBN/AVideo/issues/7686#issuecomment-1439853594)
> 
> basta leggere e puoi facilmente risolvere il problema

I did what you told me but keep not working.
Maybe I have to restart the server?
What should I do?

**Comment by DanielnetoDotCom** [comment]
I do not think restarting will help you.

check your logs again for new clues
