### ISSUE TITLE
Scheduler plugin from version 4.1 to 4.2 error

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7700]
@DanielnetoDotCom After I updated the Scheduler plugin from version 4.1 to 4.2, it showed the following logs:

```
 [22-Feb-2023 00:17:15 America/Sao_Paulo] AVideoLog::ERROR: Error in writeSql stmt->execute: 1060 Duplicate column name 'repeat_day_of_week' ALTER TABLE `scheduler_commands` 

 [22-Feb-2023 00:17:15 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":138,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Scheduler\/Scheduler.php","line":77,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":1250,"function":"updateScript","class":"Scheduler","type":"->"},{"file":"\/var\/www\/html\/AVideo\/objects\/pluginRunUpdateScript.json.php","line":18,"function":"updatePlugin","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php

 #4 {main} SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
 #3 path/to/my/streamer/site/objects/pluginRunUpdateScript.json.php(18): AVideoPlugin::updatePlugin()
 #2 path/to/my/streamer/site/plugin/AVideoPlugin.php(1250): Scheduler->updateScript()
 #1 path/to/my/streamer/site/plugin/Scheduler/Scheduler.php(77): sqlDAL::writeSql()
 [22-Feb-2023 00:17:15 America/Sao_Paulo] AVideoLog::ERROR: #0 path/to/my/streamer/site/objects/mysql_dal.php(135): mysqli_stmt->execute()

 [22-Feb-2023 00:17:15 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":137,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Scheduler\/Scheduler.php","line":77,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":1250,"function":"updateScript","class":"Scheduler","type":"->"},{"file":"\/var\/www\/html\/AVideo\/objects\/pluginRunUpdateScript.json.php","line":18,"function":"updatePlugin","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
```

**Comment by DanielnetoDotCom** [comment]
do not worry, you are good, this version is just because for some reason some installations did not have those columns.

**Comment by gbrn** [comment]
ok thanks
