### ISSUE TITLE
After git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#7701]
![Screenshot_20230222_004501_Chrome](https://user-images.githubusercontent.com/70327833/220555733-f450495d-067e-40b1-8415-f3b2a721cd43.jpg)

**Comment by milehighkaraoke** [comment]
Any idea @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
yes, 

install it and restart the socket

1. Open the terminal on your Ubuntu machine.
2. Update the package list by running the command: `sudo apt-get update`
3. Install the PHP SQLite extension by running the command: `sudo apt-get install php-sqlite3`
4. After the installation is complete, restart the Apache web server 

To stop the socket you can use the following command:

`php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php`

And to start the server, use the following command:

`php /var/www/html/AVideo/plugin/YPTSocket/server.php`

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom  OK, I did that and now I got this

 [22-Feb-2023 21:35:46 America/Denver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function __() in \/var\/www\/myMySQLDatabase\/plugin\/CustomizeUser\/CustomizeUser.php:98\nStack trace:\n#0 \/var\/www\/myMySQLDatabase\/plugin\/Plugin.abstract.php(118): CustomizeUser->getEmptyDataObject()\n#1 \/var\/www\/myMySQLDatabase\/plugin\/AVideoPlugin.php(424): PluginAbstract->getDataObject()\n#2 \/var\/www\/myMySQLDatabase\/plugin\/AVideoPlugin.php(394): AVideoPlugin::getDataObject()\n#3 \/var\/www\/myMySQLDatabase\/objects\/user.php(1526): AVideoPlugin::getObjectData()\n#4 \/var\/www\/myMySQLDatabase\/objects\/user.php(247): User::getUserDbFromUser()\n#5 \/var\/www\/myMySQLDatabase\/objects\/user.php(76): User->loadFromUser()\n#6 \/var\/www\/myMySQLDatabase\/objects\/user.php(1149): User->__construct()\n#7 \/var\/www\/myMySQLDatabase\/objects\/user.php(1171): User::recreateLoginFromCookie()\n#8 \/var\/www\/myMySQLDatabase\/objects\/functions.php(4412): User::isLogged()\n#9 \/var\/www\/myMySQLDatabase\/objects\/include_config.php(109): _session_start()\n#10 \/var\/www\/myMySQLDatabase\/videos\/configuration.php(47): require_once('...')\n#11 \/var\/www\/myMySQLDatabase\/objects\/videoAddViewCount.json.php(5): require_once('...')\n#12 {main}\n  thrown","file":"\/var\/www\/myMySQLDatabase\/plugin\/CustomizeUser\/CustomizeUser.php","line":98} SCRIPT_NAME: /objects/videoAddViewCount.json.php

**Comment by DanielnetoDotCom** [comment]
please check this update

**Comment by milehighkaraoke** [comment]
What on earth it's firing off 1000's of these a minute 
@DanielnetoDotCom 
![Screenshot_20230223_081428_Chrome](https://user-images.githubusercontent.com/70327833/220948546-3a1b9c47-70d5-418e-acaa-c56b880d7afc.jpg)
![Uploading Screenshot_20230223_081420_Chrome.jpg…]()

**Comment by milehighkaraoke** [comment]
![Screenshot_20230223_081420_Chrome](https://user-images.githubusercontent.com/70327833/220948800-3c73b58b-05e7-4a5d-a346-60f3e6694aaa.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20230223_082723_Chrome](https://user-images.githubusercontent.com/70327833/220952722-0282bafc-fb1d-4244-9794-fbd088a01c1c.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20230223_083002_Chrome](https://user-images.githubusercontent.com/70327833/220953498-8d022da4-f656-48d9-97da-aad2b5ad2182.jpg)

**Comment by DanielnetoDotCom** [comment]
In 2 hours I will release an update that will remove most of those warnings.

**Comment by milehighkaraoke** [comment]
Now it says this
![Screenshot_20230224_142709_Chrome](https://user-images.githubusercontent.com/70327833/221297013-bd852c61-e4c3-4cc1-9cab-922ff05ee4ae.jpg)

**Comment by DanielnetoDotCom** [comment]
so give the permission 

`chmod -R 777 /path/to/videos/folder`

**Comment by milehighkaraoke** [comment]
Tried that and it did ot work.main site  AVideo log file is non existent in the video folder.  The encoder log is still in that video  folder.

**Comment by DanielnetoDotCom** [comment]
can you try again and screenshot the output?

**Comment by milehighkaraoke** [comment]
Not sure how this happened but I unzipped it and removed the zip file and now it's working 

![20230225_060302](https://user-images.githubusercontent.com/70327833/221358532-51bad75a-9962-414d-8a2f-1f83ffc2e266.jpg)

**Comment by DanielnetoDotCom** [comment]
you not suppose to unzip, you should always use git pull

**Comment by milehighkaraoke** [comment]
Gitpull was showing up to date on both site and encoder
