### ISSUE TITLE
language change

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7742]
language change doesn't work
check out the demo

**Comment by palich91** [comment]
I confirm that changing the language does not work, even though the language logo is changing

**Comment by palich91** [comment]
after the update, the video is not displayed in the user profile and in the admin panel

https://user-images.githubusercontent.com/54632469/222746124-8d516322-6962-4706-9eea-67561ff152af.mp4

**Comment by palich91** [comment]
[03-Mar-2023 23:28:32 Asia/Yakutsk] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in \/var\/www\/html\/AVideo\/objects\/video.php:4214\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(4214): readdir(false)\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(4199): Video::getVideosPathsSearchingDir('video_230303135...', false)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(4987): Video::getVideosPaths('video_230303135...')\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(5000): Video::getVideoType('video_230303135...')\n#4 \/var\/www\/html\/AVideo\/objects\/videos.json.php(57): Video::getVideoTypeLabels('video_230303135...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":4214} SCRIPT_NAME: /objects/videos.json.php

...
 [03-Mar-2023 23:28:17 Asia/Yakutsk] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in \/var\/www\/html\/AVideo\/objects\/video.php:4214\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(4214): readdir(false)\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(4199): Video::getVideosPathsSearchingDir('video_230303135...', false)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(4987): Video::getVideosPaths('video_230303135...')\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(5000): Video::getVideoType('video_230303135...')\n#4 \/var\/www\/html\/AVideo\/objects\/videos.json.php(57): Video::getVideoTypeLabels('video_230303135...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":4214} SCRIPT_NAME: /objects/videos.json.php

...
 [03-Mar-2023 14:27:30 Africa/Abidjan] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640203d25bc95.jpg  SCRIPT_NAME: /view/info.php

 [03-Mar-2023 14:27:30 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_640203d25bc95.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1855

 [03-Mar-2023 14:27:30 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1855

...
 [03-Mar-2023 14:27:30 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_640203d25bc95.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1999

 [03-Mar-2023 14:27:30 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1999

...
 [03-Mar-2023 23:26:44 Asia/Yakutsk] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in \/var\/www\/html\/AVideo\/objects\/video.php:4214\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(4214): readdir(false)\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(4199): Video::getVideosPathsSearchingDir('video_230303135...', false)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(4987): Video::getVideosPaths('video_230303135...')\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(5000): Video::getVideoType('video_230303135...')\n#4 \/var\/www\/html\/AVideo\/objects\/videos.json.php(57): Video::getVideoTypeLabels('video_230303135...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":4214} SCRIPT_NAME: /objects/videos.json.php

...
 [03-Mar-2023 14:26:36 Africa/Abidjan] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_6402039c6abf6.jpg  SCRIPT_NAME: /view/modeYoutube.php

 [03-Mar-2023 14:26:36 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_6402039c6abf6.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1855

 [03-Mar-2023 14:26:36 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1855

...
 [03-Mar-2023 14:26:36 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_6402039c6abf6.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1999

 [03-Mar-2023 14:26:36 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1999

...
 [03-Mar-2023 14:26:35 Africa/Abidjan] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_6402039b74f59.jpg  SCRIPT_NAME: /view/modeYoutube.php

 [03-Mar-2023 14:26:35 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_6402039b74f59.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1855

 [03-Mar-2023 14:26:35 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1855

...
 [03-Mar-2023 14:26:35 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): &quot;path/to/my/streamer/site/videos/cache/_jpg_6402039b74f59.jpg&quot; is not a valid WEBP file in path/to/my/streamer/site/objects/functions.php on line 1999

 [03-Mar-2023 14:26:35 Africa/Abidjan] PHP Warning:  imagecreatefromwebp(): gd-webp cannot allocate temporary buffer in path/to/my/streamer/site/objects/functions.php on line 1999

...
 [03-Mar-2023 23:25:02 Asia/Yakutsk] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in \/var\/www\/html\/AVideo\/objects\/video.php:4214\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(4214): readdir(false)\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(4199): Video::getVideosPathsSearchingDir('video_230303135...', false)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(4987): Video::getVideosPaths('video_230303135...')\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(5000): Video::getVideoType('video_230303135...')\n#4 \/var\/www\/html\/AVideo\/objects\/videos.json.php(57): Video::getVideoTypeLabels('video_230303135...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":4214} SCRIPT_NAME: /objects/videos.json.php

...
 [03-Mar-2023 23:24:53 Asia/Yakutsk] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640203357de99.jpg  SCRIPT_NAME: /view/report.json.php

...
 [03-Mar-2023 23:24:24 Asia/Yakutsk] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in \/var\/www\/html\/AVideo\/objects\/video.php:4214\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(4214): readdir(false)\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(4199): Video::getVideosPathsSearchingDir('video_230303135...', false)\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(4987): Video::getVideosPaths('video_230303135...')\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(5000): Video::getVideoType('video_230303135...')\n#4 \/var\/www\/html\/AVideo\/objects\/videos.json.php(57): Video::getVideoTypeLabels('video_230303135...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":4214} SCRIPT_NAME: /objects/videos.json.php

...
 [03-Mar-2023 23:23:37 Asia/Yakutsk] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640202e971afd.jpg  SCRIPT_NAME: /view/img/image404.php

...
 [03-Mar-2023 23:23:37 Asia/Yakutsk] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640202e94b162.jpg  SCRIPT_NAME: /view/img/image404.php

...
 [03-Mar-2023 23:23:34 Asia/Yakutsk] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640202e607640.jpg  SCRIPT_NAME: /view/channel.php

...
 [03-Mar-2023 23:23:33 Asia/Yakutsk] AVideoLog::ERROR: im_resize error on source path/to/my/streamer/site/videos/cache/_jpg_640202e5db993.jpg  SCRIPT_NAME: /view/channel.php

**Comment by DanielnetoDotCom** [comment]
can you please try now?
