### ISSUE TITLE
errors log

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7761]
Daniel, 
such errors are displayed

`[06-Mar-2023 21:53:44 Europe/Warsaw] PHP Warning:  Undefined property: stdClass::$jpgSpegifDestctrumDest in path/to/my/streamer/site/objects/aVideoEncoderReceiveImage.json.php on line 170`
`[06-Mar-2023 21:53:44 Europe/Warsaw] PHP Warning:  Undefined array key "downloadURL_image" in path/to/my/streamer/site/objects/aVideoEncoderReceiveImage.json.php on line 54`
`[06-Mar-2023 20:05:45 Europe/Warsaw] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function im_resizePNG() in \/var\/www\/html\/AVideo\/view\/manifest.json.php:79\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/manifest.json.php(21): pwaIconsArray()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/manifest.json.php","line":79} SCRIPT_NAME: /view/manifest.json.php`
`[06-Mar-2023 20:05:45 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function im_resizePNG() in path/to/my/streamer/site/view/manifest.json.php:79`

**Comment by DanielnetoDotCom** [comment]
this may fix

**Comment by KrzysioMisio** [comment]
I have another

`[06-Mar-2023 22:38:26 Europe/Warsaw] PHP Warning:  Trying to access array offset on value of type null in path/to/my/streamer/site/objects/video_statistic.php on line 416`

`06-Mar-2023 22:38:26 Europe/Warsaw] PHP Warning:  Trying to access array offset on value of type null in path/to/my/streamer/site/objects/video.php on line 1335`

**Comment by KrzysioMisio** [comment]
Scheduler plugin cannot be updated

`[06-Mar-2023 23:06:49 Europe/Warsaw] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `type` VARCHAR(45) DEFAULT NULL' at line 2 in \/var\/www\/html\/AVideo\/objects\/mysql_dal.php:123\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/mysql_dal.php(123): mysqli->prepare()\n#1 \/var\/www\/html\/AVideo\/plugin\/Scheduler\/Scheduler.php(84): sqlDAL::writeSql()\n#2 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1253): Scheduler->updateScript()\n#3 \/var\/www\/html\/AVideo\/objects\/pluginRunUpdateScript.json.php(18): AVideoPlugin::updatePlugin()\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":123} SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php`

**Comment by KrzysioMisio** [comment]
doesn't work

**Comment by DanielnetoDotCom** [comment]
I am sorry, I am not facing the same error as you. 

please try this update, if persists you may need to share a more complete log

**Comment by KrzysioMisio** [comment]
it worked
Thanks

**Comment by KrzysioMisio** [comment]
new bugs

`[08-Mar-2023 17:04:14 UTC] PHP Fatal error:  Uncaught Error: Class "ADs" not found in path/to/my/streamer/site/plugin/AVideoPlugin.php(313) : eval()'d code:1`

`[08-Mar-2023 17:04:14 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"ADs\" not found in \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(313) : eval()'d code:1\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(313): eval()\n#1 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1735): AVideoPlugin::loadPlugin()\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(930): AVideoPlugin::getVideoWhereClause()\n#3 \/var\/www\/html\/AVideo\/objects\/video.php(1195): Video::getVideo()\n#4 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(244): Video::getVideoFromCleanTitle()\n#5 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(648): PlayLists->getStart()\n#6 \/var\/www\/html\/AVideo\/objects\/include_config.php(193): AVideoPlugin::getStart()\n#7 \/var\/www\/html\/AVideo\/videos\/configuration.php(47): require_once('...')\n#8 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(8): require_once('...')\n#9 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(313) : eval()'d code","line":1} SCRIPT_NAME: /view/modeYoutube.php`

`[08-Mar-2023 19:10:17 Europe/Warsaw] PHP Warning:  Trying to access array offset on value of type null in path/to/my/streamer/site/view/videoEmbeded.php on line 33`
`[08-Mar-2023 19:10:17 Europe/Warsaw] PHP Warning:  Trying to access array offset on value of type null in path/to/my/streamer/site/view/videoEmbeded.php on line 31`

**Comment by DanielnetoDotCom** [comment]
On what page exactly you are seeing this?

"PHP Fatal error:  Uncaught Error: Class "ADs" not found in "

**Comment by KrzysioMisio** [comment]
https://www.youhippo.pl/

this is a clone from youhippo.com

**Comment by DanielnetoDotCom** [comment]
I need to know exactly where is it happening, for now I have no idea what is causing it

**Comment by KrzysioMisio** [comment]
one of the symptoms is that the advertisement on BigVideo is visible to the user and admin even when the textarea field is empty

**Comment by DanielnetoDotCom** [comment]
I do not think they are related, also I already told you that behavior is expected

**Comment by KrzysioMisio** [comment]
why is the user showing a blank ad??
this is what my Ads BigVideo form looks like

![ads](https://user-images.githubusercontent.com/93145787/223834469-d27981f2-d454-432e-90fd-12c43e022fb3.png)
