### ISSUE TITLE
The language of the site is always English, you always have to change

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#7770]
The language of the site at the entrance is always English, you have to constantly switch to your own

**Comment by DanielnetoDotCom** [comment]
try this update

**Comment by KrzysioMisio** [comment]
doesn't work

`[09-Mar-2023 17:03:01 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"AVideoPlugin\" not found in \/var\/www\/html\/AVideo\/locale\/function.php:127\nStack trace:\n#0 \/var\/www\/html\/AVideo\/locale\/function.php(12): setSiteLang()\n#1 \/var\/www\/html\/AVideo\/objects\/include_config.php(178): require_once('...')\n#2 \/var\/www\/html\/AVideo\/videos\/configuration.php(47): require_once('...')\n#3 \/var\/www\/html\/AVideo\/objects\/user.php(7): require_once('...')\n#4 \/var\/www\/html\/AVideo\/objects\/comment.php(9): require_once('...')\n#5 \/var\/www\/html\/AVideo\/objects\/comments.json.php(6): require_once('...')\n#6 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/locale\/function.php","line":127} SCRIPT_NAME: /objects/comments.json.php`

**Comment by DanielnetoDotCom** [comment]
Please check it now

**Comment by KrzysioMisio** [comment]
doesn't work

`[09-Mar-2023 17:25:54 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"AVideoPlugin\" not found in \/var\/www\/html\/AVideo\/locale\/function.php:126\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/include_config.php(181): setSiteLang()\n#1 \/var\/www\/html\/AVideo\/videos\/configuration.php(47): require_once('...')\n#2 \/var\/www\/html\/AVideo\/objects\/user.php(7): require_once('...')\n#3 \/var\/www\/html\/AVideo\/objects\/comment.php(9): require_once('...')\n#4 \/var\/www\/html\/AVideo\/objects\/comments.json.php(6): require_once('...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/locale\/function.php","line":126} SCRIPT_NAME: /objects/comments.json.php`

**Comment by DanielnetoDotCom** [comment]
Sorry my bad

**Comment by KrzysioMisio** [comment]
the language does not change
I guess it's ok
