### ISSUE TITLE
Table 'avideo.plugins' doesn't exist  // docker-compose installation

### ISSUE THREAD

**Issue by laplace777** [WWBN/AVideo#7782]
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'avideo.plugins' doesn't exist in /var/www/html/AVideo/objects/mysql_dal.php:123
Stack trace:
#0 /var/www/html/AVideo/objects/mysql_dal.php(123): mysqli->prepare()
#1 /var/www/html/AVideo/objects/plugin.php(446): sqlDAL::writeSql()
#2 /var/www/html/AVideo/objects/plugin.php(183): Plugin::deleteByUUID()
#3 /var/www/html/AVideo/objects/plugin.php(199): Plugin::getPluginByUUID()
#4 /var/www/html/AVideo/objects/plugin.php(372): Plugin->loadFromUUID()
#5 /var/www/html/AVideo/plugin/AVideoPlugin.php(641): Plugin::getAllEnabled()
#6 /var/www/html/AVideo/objects/include_config.php(194): AVideoPlugin::getStart()
#7 /var/www/html/AVideo/videos/configuration.php(47): require_once('...')
#8 /var/www/html/AVideo/plugin/Scheduler/run.php(4): require_once('...')

**Comment by Famku** [comment]
I have the same error

**Comment by DanielnetoDotCom** [comment]
What do you have in the .env file?

**Comment by laplace777** [comment]
ENABLE_PHPMYADMIN=yes
PHPMYADMIN_PORT=8081
PHPMYADMIN_ENCODER_PORT=8082
SOCKET_PORT=2053
HTTP_PORT=1080
HTTPS_PORT=1443
NGINX_RTMP_PORT=1935
NGINX_HTTP_PORT=8080
NGINX_HTTPS_PORT=8443
DB_MYSQL_HOST=database
DB_MYSQL_PORT=3306
DB_MYSQL_NAME=avideo
DB_MYSQL_USER=avideo
DB_MYSQL_PASSWORD=avideo
SERVER_NAME=vidsclip.com
CREATE_TLS_CERTIFICATE=yes
WEBSITE_TITLE=VidsClip
MAIN_LANGUAGE=en_US

**Comment by DanielnetoDotCom** [comment]
I have this running locally and this is my env, try to compare it and do the same

```
SERVER_NAME=mydomain.com
CREATE_TLS_CERTIFICATE=yes
ENABLE_PHPMYADMIN=yes
SOCKET_PORT=2053
HTTP_PORT=80
HTTPS_PORT=443
NGINX_RTMP_PORT=1935
NGINX_HTTP_PORT=8080
NGINX_HTTPS_PORT=8443
DB_MYSQL_HOST=database
DB_MYSQL_PORT=3306
DB_MYSQL_NAME=avideo
DB_MYSQL_USER=avideo
DB_MYSQL_PASSWORD=avideo
```

**Comment by laplace777** [comment]
ty, I will try

**Comment by laplace777** [comment]
Did the same conf and the result is https://vidsclip.com/ the same error

**Comment by DanielnetoDotCom** [comment]
what is in the docker avideo output?

something may be happening there

**Comment by laplace777** [comment]
VideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":232,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":423,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":573,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":337,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":97,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
[2023-03-12 14:10:01] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) (Table 'avideo.plugins' doesn't exist)  preparedStatement = "SELECT * FROM  plugins WHERE status='active' AND uuid = '26570956-dc62-46e3-ace9-86c6e8f9c81b' ;" formats = "" values = [] refreshCache = false stmt = null SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
[sqlDAL::readSql] (mysqlnd) Prepare failed again return false[2023-03-12 14:10:01] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":240,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":423,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":573,"function":"getEnabled","class":"Plugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":337,"function":"isEnabled","class":"AVideoPlugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":97,"function":"loadPluginIfEnabled","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
[2023-03-12 14:10:01] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
[2023-03-12 14:10:01] AVideoLog::DEBUG: Plugin updated DELETE FROM plugins  WHERE uuid = ?:[{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":446,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":183,"function":"deleteByUUID","class":"Plugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":199,"function":"getPluginByUUID","class":"Plugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/plugin.php","line":372,"function":"loadFromUUID","class":"Plugin","type":"->"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":641,"function":"getAllEnabled","class":"Plugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/include_config.php","line":194,"function":"getStart","class":"AVideoPlugin","type":"::"},{"file":"\/var\/www\/html\/AVideo\/videos\/configuration.php","line":47,"args":["\/var\/www\/html\/AVideo\/objects\/include_config.php"],"function":"require_once"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Scheduler\/run.php","line":4,"args":["\/var\/www\/html\/AVideo\/videos\/configuration.php"],"function":"require_once"}] SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'avideo.plugins' doesn't exist in /var/www/html/AVideo/objects/mysql_dal.php:123
Stack trace:
#0 /var/www/html/AVideo/objects/mysql_dal.php(123): mysqli->prepare()
#1 /var/www/html/AVideo/objects/plugin.php(446): sqlDAL::writeSql()
#2 /var/www/html/AVideo/objects/plugin.php(183): Plugin::deleteByUUID()
#3 /var/www/html/AVideo/objects/plugin.php(199): Plugin::getPluginByUUID()
#4 /var/www/html/AVideo/objects/plugin.php(372): Plugin->loadFromUUID()
#5 /var/www/html/AVideo/plugin/AVideoPlugin.php(641): Plugin::getAllEnabled()
#6 /var/www/html/AVideo/objects/include_config.php(194): AVideoPlugin::getStart()
#7 /var/www/html/AVideo/videos/configuration.php(47): require_once('...')
#8 /var/www/html/AVideo/plugin/Scheduler/run.php(4): require_once('...')
#9 {main}
  thrown in /var/www/html/AVideo/objects/mysql_dal.php on line 123
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/AVideo/objects/mysql_dal.php:557) in Unknown on line 0

**Comment by laplace777** [comment]
root@ubuntu-4gb-hel1-1:/opt/AVideo# docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                    PORTS                                                                                                                                NAMES
a181bf3466ad   avideo_live             "/usr/local/bin/dock…"   22 minutes ago   Up 22 minutes (healthy)   0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp      avideo_live_1
796d44613752   avideo_avideo           "/usr/local/bin/dock…"   23 minutes ago   Up 23 minutes (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:2053->2053/tcp, :::2053->2053/tcp, 8081-8082/tcp   avideo_avideo_1
bf1e28b24003   phpmyadmin/phpmyadmin   "/docker-entrypoint.…"   23 minutes ago   Up 23 minutes             0.0.0.0:8081->80/tcp, :::8081->80/tcp                                                                                                avideo_phpmyadmin_1
0061f4edf51c   phpmyadmin/phpmyadmin   "/docker-entrypoint.…"   23 minutes ago   Up 23 minutes             0.0.0.0:8082->80/tcp, :::8082->80/tcp                                                                                                avideo_phpmyadmin_encoder_1
014cceed0c9f   mariadb:latest          "docker-entrypoint.s…"   23 minutes ago   Up 23 minutes (healthy)   3306/tcp                                                                                                                             avideo_database_1
e059546e3d76   mariadb:latest          "docker-entrypoint.s…"   23 minutes ago   Up 23 minutes (healthy)   3306/tcp                                                                                                                             avideo_database_encoder_1

**Comment by DanielnetoDotCom** [comment]
I mean when you start the docker

Btw is this a new installation or you previously have something?

**Comment by laplace777** [comment]
this is new installation after the .env change, when I start it builds well everything in the build context and containers are healthy

**Comment by DanielnetoDotCom** [comment]
Delete the .compose folder and try again

**Comment by laplace777** [comment]
yes it worked now
