### ISSUE TITLE
Error plugin CustomizeAdvanced

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7805]
@DanielnetoDotCom  Errors started to appear in the `CustomizeAdvanced.php` plugin, apparently after I enabled the `Gallery` plugin.
```
[16-Mar-2023 00:17:29 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function __() in \/var\/www\/html\/AVideo\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php:181\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/Plugin.abstract.php(118): CustomizeAdvanced->getEmptyDataObject()\n#1 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(472): PluginAbstract->getDataObject()\n#2 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(442): AVideoPlugin::getDataObject()\n#3 \/var\/www\/html\/AVideo\/objects\/user.php(992): AVideoPlugin::getObjectData()\n#4 \/var\/www\/html\/AVideo\/objects\/user.php(1158): User->login()\n#5 \/var\/www\/html\/AVideo\/objects\/user.php(1177): User::recreateLoginFromCookie()\n#6 \/var\/www\/html\/AVideo\/objects\/functions.php(4704): User::isLogged()\n#7 \/var\/www\/html\/AVideo\/objects\/include_config.php(127): _session_start()\n#8 \/var\/www\/html\/AVideo\/videos\/configuration.php(48): require_once('...')\n#9 \/var\/www\/html\/AVideo\/objects\/videoAddViewCount.json.php(5): require_once('...')\n#10 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php","line":181} SCRIPT_NAME: /objects/videoAddViewCount.json.php

...
 [16-Mar-2023 00:17:29 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function __() in path/to/my/streamer/site/plugin/CustomizeAdvanced/CustomizeAdvanced.php:181
```

**Comment by DanielnetoDotCom** [comment]
I am not sure why are you getting this error, but please try this update
