### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7827]
Fresh install; Ubuntu 22.04; PHP 8.2.4 and doesn't even make it to install screen. Here is error on browser:
```
array(4) { ["type"]=> int(1) ["message"]=> string(376) "Uncaught Error: Failed opening required 'objects/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/locale/function.php:119 Stack trace: #0 /var/www/html/AVideo/locale/function.php(12): setSiteLang() #1 /var/www/html/AVideo/locale/function.php(8): includeLangFile() #2 /var/www/html/AVideo/install/index.php(3): require_once('...') #3 {main} thrown" ["file"]=> string(40) "/var/www/html/AVideo/locale/function.php" ["line"]=> int(119) }
```
Apache2 error log:
```
[Thu Mar 23 21:51:14.867277 2023] [php:warn] [pid 3533] [client 192.168.1.98:53262] PHP Warning:  Undefined array key "systemRootPath" in /var/www/html/AVideo/locale/function.php on line 119
[Thu Mar 23 21:51:14.867389 2023] [php:warn] [pid 3533] [client 192.168.1.98:53262] PHP Warning:  require_once(objects/configuration.php): Failed to open stream: No such file or directory in /var/www/html/AVideo/locale/function.php on line 119
[Thu Mar 23 21:51:14.867429 2023] [php:error] [pid 3533] [client 192.168.1.98:53262] PHP Fatal error:  Uncaught Error: Failed opening required 'objects/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/locale/function.php:119\nStack trace:\n#0 /var/www/html/AVideo/locale/function.php(12): setSiteLang()\n#1 /var/www/html/AVideo/locale/function.php(8): includeLangFile()\n#2 /var/www/html/AVideo/install/index.php(3): require_once('...')\n#3 {main}\n  thrown in /var/www/html/AVideo/locale/function.php on line 119
[Thu Mar 23 21:51:14.867560 2023] [php:notice] [pid 3533] [client 192.168.1.98:53262] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Failed opening required 'objects\\/configuration.php' (include_path='.:\\/usr\\/share\\/php') in \\/var\\/www\\/html\\/AVideo\\/locale\\/function.php:119\\nStack trace:\\n#0 \\/var\\/www\\/html\\/AVideo\\/locale\\/function.php(12): setSiteLang()\\n#1 \\/var\\/www\\/html\\/AVideo\\/locale\\/function.php(8): includeLangFile()\\n#2 \\/var\\/www\\/html\\/AVideo\\/install\\/index.php(3): require_once('...')\\n#3 {main}\\n  thrown","file":"\\/var\\/www\\/html\\/AVideo\\/locale\\/function.php","line":119} SCRIPT_NAME: /install/index.php
[Thu Mar 23 21:51:14.867600 2023] [php:error] [pid 3533] [client 192.168.1.98:53262] PHP Fatal error:  Uncaught Error: Class "User" not found in /var/www/html/AVideo/objects/functions.php:6777\nStack trace:\n#0 [internal function]: avideoShutdown()\n#1 {main}\n  thrown in /var/www/html/AVideo/objects/functions.php on line 6777
[Thu Mar 23 21:51:14.936293 2023] [php:warn] [pid 3532] [client 192.168.1.98:53261] PHP Warning:  require_once(/var/www/html/AVideo/view/img/../../videos/configuration.php): Failed to open stream: No such file or directory in /var/www/html/AVideo/view/img/image404.php on line 4, referer: https://tube.farmersmarket.site/install/index.php
[Thu Mar 23 21:51:14.936343 2023] [php:error] [pid 3532] [client 192.168.1.98:53261] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/AVideo/view/img/../../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/view/img/image404.php:4\nStack trace:\n#0 {main}\n  thrown in /var/www/html/AVideo/view/img/image404.php on line 4, referer: https://tube.farmersmarket.site/install/index.php
```

**Comment by racazahassem09191990** [comment]
Me to

**Comment by lopaoc** [comment]
Yes,me to, OS:Ubuntu 22.10 live server

**Comment by DanielnetoDotCom** [comment]
Can you please make a git pull, I released a fix for that 8 hours ago

**Comment by DanielnetoDotCom** [comment]
can you please check this update?
