### ISSUE TITLE
Uncaught Error ?

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7868]
@DanielnetoDotCom It started showing these Uncaught Errors. I couldn't understand what it is about:

` [03-Apr-2023 19:57:37 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"Configuration\" not found in \/var\/www\/html\/AVideo\/objects\/user.php:2397\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/user.php(1015): User::sendVerificationLink()\n#1 \/var\/www\/html\/AVideo\/objects\/user.php(2662): User->login()\n#2 \/var\/www\/html\/AVideo\/objects\/user.php(2647): User::loginFromRequest()\n#3 \/var\/www\/html\/AVideo\/plugin\/Live\/Live.php(15): User::loginFromRequestIfNotLogged()\n#4 \/var\/www\/html\/AVideo\/plugin\/LiveLinks\/LiveLinks.php(6): require_once('...')\n#5 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(349): require_once('...')\n#6 \/var\/www\/html\/AVideo\/plugin\/Plugin.abstract.php(147): AVideoPlugin::loadPlugin()\n#7 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(472): PluginAbstract->getDataObject()\n#8 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(442): AVideoPlugin::getDataObject()\n#9 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(496): AVideoPlugin::getObjectData()\n#10 \/var\/www\/html\/AVideo\/locale\/function.php(122): AVideoPlugin::getDataObjectIfEnabled()\n#11 \/var\/www\/html\/AVideo\/locale\/function.php(12): setSiteLang()\n#12 \/var\/www\/html\/AVideo\/locale\/function.php(8): includeLangFile()\n#13 \/var\/www\/html\/AVideo\/plugin\/Plugin.abstract.php(3): require_once('...')\n#14 \/var\/www\/html\/AVideo\/objects\/user.php(10): require_once('...')\n#15 \/var\/www\/html\/AVideo\/objects\/configuration.php(6): require_once('...')\n#16 \/var\/www\/html\/AVideo\/objects\/include_config.php(98): require_once('...')\n#17 \/var\/www\/html\/AVideo\/videos\/configuration.php(48): require_once('...')\n#18 \/var\/www\/html\/AVideo\/objects\/login.json.php(8): require_once('...')\n#19 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/user.php","line":2397} SCRIPT_NAME: /objects/login.json.php`

**Comment by gbrn** [comment]
Updated and monitoring...

**Comment by gbrn** [comment]
This problem no longer appeared. I keep monitoring.
