### ISSUE TITLE
500 error for upload

### ISSUE THREAD

**Issue by TheCazz** [WWBN/AVideo#7910]
Hi
Not sure but I think I have this 500 error after I change the address from local IP to my domain.
I have open` /video/configuration.php` and change one line from my local IP address to my domain but I wonder if I have to change somewhere for upload?

The only thing I have done after that was remove the installations folder for YouPHPTube and upload?

When I look inside the apache2 log I find this

```
[Sun Apr 16 12:26:29.382589 2023] [php:error] [pid 28525] [client 192.168.1.99:64847] PHP Fatal error:  Uncaught Error: Call to undefined function _mysql_is_open() in /var/www/AVideo/plugin/WWBNIndex/submitIndex.php:7\nStack trace:\n#0 /var/www/AVideo/install/checkConfiguration.php(260): include()\n#1 {main}\n  thrown in /var/www/AVideo/plugin/WWBNIndex/submitIndex.php on line 7, referer: http://172.16.0.14/install/index.p>

[Sun Apr 16 12:38:31.699732 2023] [php:error] [pid 919] [client 172.16.0.10:54074] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/AVideo/upload/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/AVideo/upload/view/index.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/AVideo/upload/view/index.php on line 17
```

Where 192.168.1.99 is my computer and 172.16.0.14 is the local address for the server.

**Comment by DanielnetoDotCom** [comment]
you should use the git clone to get your files

**Comment by DanielnetoDotCom** [comment]
I just notice, is this a clean installation?

it does not suppose to install the WWBNIndex plugin yet.

did you try it manually or it did do it automatically?

**Comment by DanielnetoDotCom** [comment]
I just submit an update to make sure it will not be executed.

**Comment by TheCazz** [comment]
Thanks for the fast replay
yes it is a clean installation on Ubuntu Server 22.04 LTS

All I did for Encoder was rename it to upload and then give www-data owner of the files and folders

**Comment by DanielnetoDotCom** [comment]
please make a git pull ant try again.

**Comment by TheCazz** [comment]
Hmm it did feel first that it was going to work.
I first remove the database for encoder (AVideoEncoder)
I then remover the folder (upload)
After that I did run the git pull and after I did rename it to "upload"
After that I did run chown 
`sudo chown www-data:www-data /var/www/AVideo/ -R`
After that I did open a browser and go to the https address for my upload (https://mydomain.se/upload)
I then I filled in all the fields and press Install.
I did get a green box and it say "Your system is installed"
I press "Go to the main page" and then I get a 500 error again?
I have look in the apache2 log error and I can't see anything that have writen in this time (did just have some old one)

**Comment by DanielnetoDotCom** [comment]
check your logs for the 500 error

**Comment by TheCazz** [comment]
`Fatal error: Uncaught Error: Class "Locale" not found in /var/www/AVideo/upload/locale/function.php:15 Stack trace: #0 /var/www/AVideo/upload/view/index.php(23): require_once() #1 {main} thrown in /var/www/AVideo/upload/locale/function.php on line 15`

I use 8.1 PHP version

**Comment by DanielnetoDotCom** [comment]
`sudo apt-get install php8.1-intl`

**Comment by TheCazz** [comment]
Thanks alot, it work perfect now :)
