### ISSUE TITLE
NOTIFICATION plugin upgrade cases error in older version of AVideo

### ISSUE THREAD

**Issue by hervaden** [WWBN/AVideo#8054]
**Describe the bug**
Updated the NOTIFICATION plugin which causes the upload of videos to hang.

**To Reproduce**
1. Running a older version of the code base: about 8 months old
2. Follow recommended NOTIFICATION plugin upgrade to latest version
3. Try to upload a video, animation keeps going and does not provide access to the upload model

**Expected behavior**
1. The Upload function should not be effected

**Error Logs**
Provide the log files at the moment you found the issue.
Log output:
[22-May-2023 16:10:15 America/Vancouver] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Access to undeclared static property: Video::$statusUnlistedButSearchable in \/mnt\/volume_tor1_01\/www\/tcs\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code:210\nStack trace:\n#0 \/mnt\/volume_tor1_01\/www\/tcs\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code(353): Notifications->sendVideoUploadEmails()\n#1 \/mnt\/volume_tor1_01\/www\/tcs\/plugin\/AVideoPlugin.php(736): Notifications->onNewVideo()\n#2 \/mnt\/volume_tor1_01\/www\/tcs\/objects\/video.php(456): AVideoPlugin::onNewVideo()\n#3 \/mnt\/volume_tor1_01\/www\/tcs\/objects\/videoAddNew.json.php(165): Video->save()\n#4 {main}\n  thrown","file":"\/mnt\/volume_tor1_01\/www\/tcs\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code","line":210} SCRIPT_NAME: /objects/videoAddNew.json.php

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Safari
 - Version: Latest

**Comment by gbrn** [comment]
If you are talking about the UserNotifications plugin, I had serious problems with this plugin, my server was not compatible, I couldn't update otherwise it crashed the website. And then to solve the problem, I had to change servers. Issue: #6956

**Comment by hervaden** [comment]
@gbrn & @DanielnetoDotCom Thanks for the replies.  I am not planning to upgrade the entire system - too much customization to risk it.

I do need the Notification to either be backward compatible, or the source code.  Cannot have it ask for an upgrade and then breaking a seemingly unrelated function - video uploads.

**Comment by DanielnetoDotCom** [comment]
Sorry, I cannot provide the source or an older version. 

the only solution I have for you is to upgrade all.

**Comment by hervaden** [comment]
Could you fix the bug so it is backward compatible?

**Comment by gbrn** [comment]
@hervaden If you follow my drama on issue #6956, you'll find you're wasting your time.
Put on a server the maximum compatible with the requirements of the AVIDEO platform, your problems will decrease, but not all.

**Comment by hervaden** [comment]
Thank, @gbrn . I am
