### ISSUE TITLE
Hitting brick wall on DB performance

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8139]
**Describe the bug**
Conspyre News was a new site and was **zippy** AND _peppy_, but it ingests videos at a mad pace, and now is big sad. :-(

Loading non-cached pages takes several minutes with the CPU for mysql buried at 200 or 300%

**To Reproduce**
1. Go to site.
2. Click on Next page button
3. Wait…

**Expected behavior**
mysql to not suck

**Error Logs**
```
[29-Jun-2023 18:53:38 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  ORDER BY id DESC LIMIT 1], ssss, ["hashName__getVideoInfo_4775",1,"news.conspyre.tv","undefined"], ] On  Line mysql_dal takes 1.4015 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
[29-Jun-2023 18:53:38 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getInfo index=50 id=4775 video] On  Line 1657 takes 1.4022 seconds to complete, Limit (0.25). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
[29-Jun-2023 18:53:40 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  ORDER BY id DESC LIMIT 1], ssss, ["hashName__getVideoInfo_4831",1,"news.conspyre.tv","undefined"], ] On  Line mysql_dal takes 1.4833 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/view/info.php SCRIPT_NAME: /view/info.php
[29-Jun-2023 18:53:40 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getInfo index=14 id=4831 video] On  Line 1657 takes 1.4842 seconds to complete, Limit (0.25). /var/www/html/news.conspyre.tv/view/info.php SCRIPT_NAME: /view/info.php
[29-Jun-2023 18:53:40 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  ORDER BY id DESC LIMIT 1], ssss, ["hashName__getVideoInfo_4772",1,"news.conspyre.tv","undefined"], ] On  Line mysql_dal takes 1.4614 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
[29-Jun-2023 18:53:40 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getInfo index=51 id=4772 video] On  Line 1657 takes 1.4623 seconds to complete, Limit (0.25). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
[29-Jun-2023 18:53:41 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  ORDER BY id DESC LIMIT 1], ssss, ["hashName__getVideoInfo_4834",1,"news.conspyre.tv","undefined"], ] On  Line mysql_dal takes 1.4723 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/view/info.php SCRIPT_NAME: /view/info.php
[29-Jun-2023 18:53:41 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getInfo index=15 id=4834 video] On  Line 1657 takes 1.4731 seconds to complete, Limit (0.25). /var/www/html/news.conspyre.tv/view/info.php SCRIPT_NAME: /view/info.php
[29-Jun-2023 18:53:41 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [[SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  ORDER BY id DESC LIMIT 1], ssss, ["hashName__getVideoInfo_4898",1,"news.conspyre.tv","undefined"], ] On  Line mysql_dal takes 1.487 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
[29-Jun-2023 18:53:41 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getInfo getStatistcs] On  Line 1734 takes 1.4905 seconds to complete, Limit (0.2). /var/www/html/news.conspyre.tv/view/index.php SCRIPT_NAME: /view/index.php
```
Note: https://github.com/major/MySQLTuner-perl is like super-active these days, and it has a lot to say about the database & is complaining that our database tables are not utf8 compliant, unknown if that could affect performance

**Comment by DanielnetoDotCom** [comment]
try to truncate the table CachesInDB , could be some garbage on it

**Comment by walt93** [comment]
Done, and I turned down the number of rows displayed on the home page (gallery->DateAddedRowCount was at 84), loading is much faster

However from Plugins, I see that "Cache" needs to be updated to 3.0. I hit update. And it spins, seemingly forever. Tried numerous times.  Do you see anything outstanding here? Few errors on uninstalled tables.

```
[30-Jun-2023 14:55:43 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.3265 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:44 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230531232424_v2283) new resolution found 458 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:44 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230530141643_vcef5) new resolution found 358 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:44 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 898, extinction-ai-art-ai-nightmares, v_230228201209_vd5bb SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:46 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2842 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:46 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230613203119_v490c) new resolution found 712 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:46 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230522212514_va50d) new resolution found 716 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:46 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230530123145_vf1eb) new resolution found 352 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:46 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230529202731_ve602) new resolution found 320 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230531133840_vc787) new resolution found 238 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230531170309_v6efd) new resolution found 242 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230605155904_v232c) new resolution found 420 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230605161043_v032b) new resolution found 468 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(v_230605164712_v7f24) new resolution found 460 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:47 America/Los_Angeles] AVideoLog::DEBUG: Video::duration_in_seconds: id=673 EE:EE:EE video SCRIPT_NAME: /view/info.php
[30-Jun-2023 14:55:49 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2109 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:50 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2466, supernatural-saturday---your-identity-and-destiny.mp4, v_230529120155_v3d07 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:52 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.0255 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:52 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2107, friday-thoughts-mothman-random-history-calls-ft.-matt-42823.mp4, v_230525161536_vd6b5 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:53 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3796, back-porch-talk-current-events-culture-ft-an0maly-32223.mp4, v_230605194542_v38de SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:54 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 0.5447 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:56 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2298 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:57 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2174, the-great-reset-|-ep.-562---the-daily-dose, v_230526134843_v73a9 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:55:59 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 0.9255 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:01 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 0.8772 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:03 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2129 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:04 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3262, 3-amigos-on-the-arise-usa-tour-june-16-2021.mp4, v_230601120450_v4575 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:06 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3270, arise-usa-update-the-team-is-at-the-pope-county-fairgrounds-in-russellville-ar.mp4, v_230601130135_vb095 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:08 America/Los_Angeles] AVideoLog::DEBUG: Video::duration_in_seconds: id=673 EE:EE:EE video SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:08 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2756 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:09 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 673, mkultra-later-generations-advanced-mind-control-unconventional-warfare-1of2-1, video_230210192901_va2f3 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:10 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210192558_vb708) new resolution found 408 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:12 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.505 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:13 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210005713_v28e8) new resolution found 716 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:13 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210005707_v48b0) new resolution found 454 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:13 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210005700_vfd61) new resolution found 680 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:13 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210005647_vfe60) new resolution found 662 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:13 America/Los_Angeles] AVideoLog::DEBUG: getVideosPathsGloob(video_230210005622_v3a8b) new resolution found 468 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:14 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.0517 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:15 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2843, navigating-a-collective-madness.mp4, v_230530163430_v75ad SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:17 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2893 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:17 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2570, tfh-663-chemtrails-artificial-archaeans-cybernetics-and-biden-s-illegal-cabinet-with-sofia-smal, v_230529164300_v518d SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:17 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 2756, tfh-644-the-technocratic-state-fluoride-and-the-utah-satanic-ritual-sexual-abuse-scandal-with-de.mp4, v_230530125714_v4ac7 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:18 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3642, tfh-620-the-qanon-shaman-and-jan-6th-with-jason-rink.mp4, v_230605151308_v5690 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:19 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.248 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:20 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3729, 11-11-22-tore-says-show.mp4, v_230605173011_v4dde SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:22 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2945 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:25 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.4477 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php[30-Jun-2023 14:56:26 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 3880, tru-reporting-live-save-america-rally-in-dayton-ohio-will-trump-announce.mp4, v_230605234126_v0f7c SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:26 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 4060, tru-reporting-live-tensions-are-escalating-are-we-even-having-an-election-102422.mp4, v_230607130521_v3ab4 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:26 America/Los_Angeles] AVideoLog::DEBUG: Roku Empty video source 4104, tru-reporting-live-comms-are-necessary-101922.mp4, v_230607140630_va904 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:26 America/Los_Angeles] AVideoLog::DEBUG: Video::updateLikesDislikes: id=5175 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:26 America/Los_Angeles] AVideoLog::DEBUG: Video::updateLikesDislikes: id=5175 SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:27 America/Los_Angeles] AVideoLog::DEBUG: Video::save (Ep. 3097a - The Battle Between Economic Systems Is About To Go Into Overdrive) Saved id = 5175 0:28:09 [{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":5530,"function":"save","class":"Video","type":"->"},{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":4248,"function":"setVideoHigestResolution","class":"Video","type":"->"},{"file":"\/var\/www\/html\/news.conspyre.tv\/plugin\/PlayerSkins\/PlayerSkins.php","line":738,"function":"getHigestResolution","class":"Video","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/plugin\/AVideoPlugin.php","line":1791,"function":"getVideoTags","class":"PlayerSkins","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":3228,"function":"getVideoTags","class":"AVideoPlugin","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":2901,"function":"getTags_","class":"Video","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":1767,"function":"getTags","class":"Video","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/objects\/video.php","line":1656,"function":"getInfo","class":"Video","type":"::"},{"file":"\/var\/www\/html\/news.conspyre.tv\/feed\/index.php","line":50,"function":"getAllVideos","class":"Video","type":"::"}] SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:56:28 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1670 takes 1.2142 seconds to complete, Limit (0.5). /var/www/html/news.conspyre.tv/feed/index.php SCRIPT_NAME: /feed/index.php
[30-Jun-2023 14:57:27 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [navbar.php] On  Line 120 takes 0.587 seconds to complete, Limit (0.2). /var/www/html/news.conspyre.tv/view/managerPlugins.php SCRIPT_NAME: /view/managerPlugins.php
[30-Jun-2023 14:57:28 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [navbar.php] On  Line 129 takes 0.2394 seconds to complete, Limit (0.2). /var/www/html/news.conspyre.tv/view/managerPlugins.php SCRIPT_NAME: /view/managerPlugins.php
[30-Jun-2023 14:57:29 America/Los_Angeles] AVideoLog::ERROR: You need to install table ip2location_db3 for the plugin (User_Location) SCRIPT_NAME: /objects/pluginsAvailable.json.php
[30-Jun-2023 14:57:31 America/Los_Angeles] AVideoLog::DEBUG: AVideoPlugin::updatePlugin name=(Cache) uuid=(10573225-3807-4167-ba81-0509dd280e06)  SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
[30-Jun-2023 14:57:31 America/Los_Angeles] AVideoLog::WARNING: AVideoPlugin::updatePlugin method_exists  SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
[30-Jun-2023 14:57:31 America/Los_Angeles] AVideoLog::DEBUG: writeSql empty(preparedStatement) SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
[30-Jun-2023 14:57:31 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Class "LiveTransmitionHistory" not found in /var/www/html/news.conspyre.tv/plugin/Cache/Cache.php:45
Stack trace:
#0 /var/www/html/news.conspyre.tv/plugin/AVideoPlugin.php(1336): Cache->updateScript()
#1 /var/www/html/news.conspyre.tv/objects/pluginRunUpdateScript.json.php(18): AVideoPlugin::updatePlugin()
#2 {main}
  thrown in /var/www/html/news.conspyre.tv/plugin/Cache/Cache.php on line 45
[30-Jun-2023 14:57:31 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"LiveTransmitionHistory\" not found in \/var\/www\/html\/news.conspyre.tv\/plugin\/Cache\/Cache.php:45\nStack trace:\n#0 \/var\/www\/html\/news.conspyre.tv\/plugin\/AVideoPlugin.php(1336): Cache->updateScript()\n#1 \/var\/www\/html\/news.conspyre.tv\/objects\/pluginRunUpdateScript.json.php(18): AVideoPlugin::updatePlugin()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/news.conspyre.tv\/plugin\/Cache\/Cache.php","line":45} SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
[30-Jun-2023 14:58:16 America/Los_Angeles] AVideoLog::DEBUG: Warning: Slow process detected [navbar.php] On  Line 129 takes 0.3004 seconds to complete, Limit (0.2). /var/www/html/news.conspyre.tv/view/managerPlugins.php SCRIPT_NAME: /view/managerPlugins.php
[30-Jun-2023 14:58:16 America/Los_Angeles] AVideoLog::ERROR: You need to install table ip2location_db3 for the plugin (User_Location) SCRIPT_NAME: /objects/pluginsAvailable.json.php
```

**Comment by DanielnetoDotCom** [comment]
Make another git pull and try again
