### ISSUE TITLE
videos are not visible

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#8177]
after upgrading to 12.5
What is the issue here ???
Why new videos are not visible to users ???

![avideo](https://github.com/WWBN/AVideo/assets/93145787/1e029119-7251-4fb8-9069-210ec9feeed8)

**Comment by DanielnetoDotCom** [comment]
Make sure you have this plugin in your crontab

![image](https://github.com/WWBN/AVideo/assets/18009293/c880e879-c0db-49e3-8dcf-ed733e27bd25)

**Comment by KrzysioMisio** [comment]
she is mandatory ?
I do not use it because I do not need it
in version 12.4 I also did not use and there were no problems

**Comment by DanielnetoDotCom** [comment]
yes, it is required now

**Comment by DanielnetoDotCom** [comment]
All required are here

![image](https://github.com/WWBN/AVideo/assets/18009293/49872279-6d47-4bdb-a0de-23703bea24c8)

**Comment by KrzysioMisio** [comment]
I added the plugin to cron
I have everything in green
But it doesn't work !!!
i still have to accept the video in the admin panel 
i have to click Release now to make the video visible to users

![szhe](https://github.com/WWBN/AVideo/assets/93145787/16011841-1236-4a04-bff9-27023ae505f4)

**Comment by DanielnetoDotCom** [comment]
edit the video and check what time it should be released. 

also check your server time

**Comment by KrzysioMisio** [comment]
Server time is correct (Europe/Warsaw)
The video is expected to display in 2 hours
how to change it ?

![relas](https://github.com/WWBN/AVideo/assets/93145787/6279dc73-4ae4-45d7-96e1-a8426aa3867e)

**Comment by DanielnetoDotCom** [comment]
usually, this date comes from your encoder. check what date you have there.

**Comment by DanielnetoDotCom** [comment]
I mean, when you submit the file, what date do you see in the encoder?

**Comment by KrzysioMisio** [comment]
the date is correct
in Poland it is now 17:03
![dar](https://github.com/WWBN/AVideo/assets/93145787/63b49934-b563-4d7a-924f-39edd8bbacf1)

**Comment by DanielnetoDotCom** [comment]
is this correct?

**Comment by DanielnetoDotCom** [comment]
I am no idea why it is saving 2 hours ahead, so for now you will need to inspect the logs in the Encoder and streamer when you submit a video. so we can check the times.

**Comment by DanielnetoDotCom** [comment]
These are NOT the logs I am talking about. 

![image](https://github.com/WWBN/AVideo/assets/18009293/b960d04a-259c-4cfe-a30b-1da851bca2a9)

but your log reveals another issue. 

check this update

**Comment by KrzysioMisio** [comment]
emcoder

`[17-Jul-2023 16:15:43 Europe/Berlin] getTitleFromLink: Get Title: LC_ALL=en_US.UTF-8 /usr/local/bin/yt-dlp   --no-check-certificate --no-playlist --force-ipv4 --skip-download -e 'https://youtu.be/gDQbwS6t-uw' 
Array
(
    [0] => WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/4cc5d082.json' failed: Traceback (most recent call last):
    [1] =>   File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 41, in store
    [2] =>     os.makedirs(os.path.dirname(fn), exist_ok=True)
    [3] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [4] =>     makedirs(head, exist_ok=exist_ok)
    [5] =>   File "/usr/lib/python3.10/os.py", line 215, in makedirs
    [6] =>     makedirs(head, exist_ok=exist_ok)
    [7] =>   File "/usr/lib/python3.10/os.py", line 225, in makedirs
    [8] =>     mkdir(name, mode)
    [9] => PermissionError: [Errno 13] Permission denied: '/var/www/.cache'
    [10] => 
    [11] => Atta w niebocentryżmie i w Słowiaństwie - podcast PL
)`

**Comment by DanielnetoDotCom** [comment]
Without the correct logs, it becomes difficult for me to provide accurate assistance and understand the root cause of the problem. As much as I would like to help you, I have limitations in terms of time and availability.

If you are able to provide the logs as requested, I will be more than willing to continue assisting you in finding a solution, otherwise, I cannot continue in this thread.

**Comment by KrzysioMisio** [comment]
where do i get the other logs?
there are 2
one in the AVideo.log encoder
second AVideo.log streamer

**Comment by DanielnetoDotCom** [comment]
the logs seem to be correct, but the time is not. 

![image](https://github.com/WWBN/AVideo/assets/18009293/ddda5667-c4ed-4cd9-b605-277ae7ab2046)

also, you need so share more from it. 

I want to see when the video is saved in the database. 

another option, 

It may be an issue with the timezone converter. try to see if your servers are in the same timezone as you are.

**Comment by DanielnetoDotCom** [comment]
in your streamer log MUST be something like "Scheduler::addVideoToRelease" this will give some clue what is going on. 

without it I cannot help

**Comment by DanielnetoDotCom** [comment]
if the video is being scheduled this MUST be somewhere in your log

**Comment by KrzysioMisio** [comment]
I don't plan anything,
I don't have a schedule
you can see from the logs that the video loads at the correct time and then it changes

**Comment by DanielnetoDotCom** [comment]
all the videos go to the scheduled. 

some of them are scheduled to now and some of them are scheduled to some time ahead.

I am talking about the schedule plugin

**Comment by KrzysioMisio** [comment]
I changed the encoder to public and everything works fine

**Comment by DanielnetoDotCom** [comment]
try to update your encoder. maybe is something there.

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

update the encoder and the streamer

**Comment by KrzysioMisio** [comment]
these fixes worked
but in the encoder logs it is still (minus) - 2 hours
and in video editing it is (plus) + 1 hour
![relase](https://github.com/WWBN/AVideo/assets/93145787/2523bc61-d272-4a59-a959-f4e5fa0a206f)
![re](https://github.com/WWBN/AVideo/assets/93145787/bbc4d415-ceba-4d70-954d-9605e75877fc)

**Comment by DanielnetoDotCom** [comment]
Just asking, is it releasing in the correct time?

**Comment by KrzysioMisio** [comment]
yes it works now
the video is visible to users
