### ISSUE TITLE
global $config becomes null - LoginControl Plugin

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#8179]
I'm experiencing this error since I updated to latest version, just wanna know why and if you're experiencing the same? I tried to debug but can't find what causing this. Kindly check on your side too, thank you!

Network Tab Error:  
Uncaught Error: Call to a member function getWebSiteTitle() on null in ~

**Comment by DanielnetoDotCom** [comment]
What exactly is the error ? 

Copy the whole error message here

**Comment by julzxcapz** [comment]
here's the error log sir


avideo.log
`[17-Jul-2023 13:58:41 UTC] AVideoLog::DEBUG: LoginControl::getConfirmationCode ERROR  1, 145d12bc-0fd2-45ac-b7ac-3739a6f8f643 SCRIPT_NAME: /objects/login.json.php
[17-Jul-2023 13:58:41 UTC] AVideoLog::DEBUG: Login_control::onUserSignIn 2FA is required for user (1) (Chrome) (145d12bc-0fd2-45ac-b7ac-3739a6f8f643) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36) SCRIPT_NAME: /objects/login.json.php
[17-Jul-2023 13:58:41 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to a member function getWebSiteTitle() on null in \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php:232\nStack trace:\n#0 \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php(100): LoginControl::send2FAEmail()\n#1 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(1642): LoginControl->onUserSignIn()\n#2 \/var\/www\/html\/allsides\/objects\/user.php(1044): AVideoPlugin::onUserSignIn()\n#3 \/var\/www\/html\/allsides\/objects\/user.php(2672): User->login()\n#4 \/var\/www\/html\/allsides\/objects\/user.php(2657): User::loginFromRequest()\n#5 \/var\/www\/html\/allsides\/plugin\/Meet\/Meet.php(12): User::loginFromRequestIfNotLogged()\n#6 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(369): require_once('\/var\/www\/html\/a...')\n#7 \/var\/www\/html\/allsides\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php(288): AVideoPlugin::loadPlugin()\n#8 \/var\/www\/html\/allsides\/plugin\/Plugin.abstract.php(119): CustomizeAdvanced->getEmptyDataObject()\n#9 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(498): PluginAbstract->getDataObject()\n#1","file":"\/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php","line":232} SCRIPT_NAME: /objects/login.json.php
`

**Comment by julzxcapz** [comment]
here's the new log sir

`[17-Jul-2023 14:12:09 UTC] AVideoLog::DEBUG: Login_control::onUserSignIn 2FA is required for user (1) (Chrome) (145d12bc-0fd2-45ac-b7ac-3739a6f8f643) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36) SCRIPT_NAME: /objects/login.json.php
[17-Jul-2023 14:12:09 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class 'Configuration' not found in \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php:232\nStack trace:\n#0 \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php(100): LoginControl::send2FAEmail()\n#1 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(1642): LoginControl->onUserSignIn()\n#2 \/var\/www\/html\/allsides\/objects\/user.php(1044): AVideoPlugin::onUserSignIn()\n#3 \/var\/www\/html\/allsides\/objects\/user.php(2672): User->login()\n#4 \/var\/www\/html\/allsides\/objects\/user.php(2657): User::loginFromRequest()\n#5 \/var\/www\/html\/allsides\/plugin\/Meet\/Meet.php(12): User::loginFromRequestIfNotLogged()\n#6 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(369): require_once('\/var\/www\/html\/a...')\n#7 \/var\/www\/html\/allsides\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php(288): AVideoPlugin::loadPlugin()\n#8 \/var\/www\/html\/allsides\/plugin\/Plugin.abstract.php(119): CustomizeAdvanced->getEmptyDataObject()\n#9 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(498): PluginAbstract->getDataObject()\n#10 \/var\/www\/html\/alls","file":"\/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php","line":232} SCRIPT_NAME: /objects/login.json.php
`

**Comment by DanielnetoDotCom** [comment]
try this

**Comment by julzxcapz** [comment]
still same issue sir with my first log

`[17-Jul-2023 14:17:23 UTC] AVideoLog::DEBUG: Login_control::onUserSignIn 2FA is required for user (1) (Chrome) (145d12bc-0fd2-45ac-b7ac-3739a6f8f643) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36) SCRIPT_NAME: /objects/login.json.php
[17-Jul-2023 14:17:23 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to a member function getWebSiteTitle() on null in \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php:239\nStack trace:\n#0 \/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php(100): LoginControl::send2FAEmail()\n#1 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(1642): LoginControl->onUserSignIn()\n#2 \/var\/www\/html\/allsides\/objects\/user.php(1044): AVideoPlugin::onUserSignIn()\n#3 \/var\/www\/html\/allsides\/objects\/user.php(2672): User->login()\n#4 \/var\/www\/html\/allsides\/objects\/user.php(2657): User::loginFromRequest()\n#5 \/var\/www\/html\/allsides\/plugin\/Meet\/Meet.php(12): User::loginFromRequestIfNotLogged()\n#6 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(369): require_once('\/var\/www\/html\/a...')\n#7 \/var\/www\/html\/allsides\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php(288): AVideoPlugin::loadPlugin()\n#8 \/var\/www\/html\/allsides\/plugin\/Plugin.abstract.php(119): CustomizeAdvanced->getEmptyDataObject()\n#9 \/var\/www\/html\/allsides\/plugin\/AVideoPlugin.php(498): PluginAbstract->getDataObject()\n#1","file":"\/var\/www\/html\/allsides\/plugin\/LoginControl\/LoginControl.php","line":239} SCRIPT_NAME: /objects/login.json.php`

**Comment by DanielnetoDotCom** [comment]
Now you need to debug your side. why you cannot find the Configuration class

check this 

![image](https://github.com/WWBN/AVideo/assets/18009293/db8f8e3b-5208-4621-b8a4-2ba66e8e3280)

does not make sense this error anymore

This update last will resolve it, but you need to check what is causing that.

**Comment by julzxcapz** [comment]
That last update still not help fixing the issue though. I will try to debug more but are you not encountering this error on your side? (enabled LoginControl)

**Comment by DanielnetoDotCom** [comment]
On what page exactly are you facing it?

**Comment by julzxcapz** [comment]
when logging-in from login page sir, stuck in loading display because of that error

**Comment by julzxcapz** [comment]
here sir

![Screenshot 2023-07-17 224458](https://github.com/WWBN/AVideo/assets/61785146/34fe0aa3-4639-4b52-a49e-2200f66913af)

**Comment by DanielnetoDotCom** [comment]
I just tested on my side with the exact same configuration and it works fine

**Comment by julzxcapz** [comment]
https://github.com/WWBN/AVideo/commit/b85532e42f8d29f1749643de5f5b4635d76421e1

I just pulled again and this fixed the display error, will fix the email setup next and test. I will update again, thank you sir

**Comment by julzxcapz** [comment]
It seems other file are affected too on my side, I will check more and do some debugging. Thank you again sir!

`[17-Jul-2023 15:37:09 UTC] AVideoLog::DEBUG: sendSiteEmail: subject= Confirm  log in from a new browser SCRIPT_NAME: /objects/login.json.php
[17-Jul-2023 15:37:09 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to a member function getWebSiteTitle() on null in \/var\/www\/html\/gwinnett\/objects\/functions.php:827\nStack trace:\n#0 \/var\/www\/html\/gwinnett\/objects\/functions.php(687): createEmailMessageFromTemplate()\n#1 \/var\/www\/html\/gwinnett\/plugin\/LoginControl\/LoginControl.php(264): sendSiteEmail()\n#2 \/var\/www\/html\/gwinnett\/plugin\/LoginControl\/LoginControl.php(100): LoginControl::send2FAEmail()\n#3 \/var\/www\/html\/gwinnett\/plugin\/AVideoPlugin.php(1642): LoginControl->onUserSignIn()\n#4 \/var\/www\/html\/gwinnett\/objects\/user.php(1044): AVideoPlugin::onUserSignIn()\n#5 \/var\/www\/html\/gwinnett\/objects\/user.php(2672): User->login()\n#6 \/var\/www\/html\/gwinnett\/objects\/user.php(2657): User::loginFromRequest()\n#7 \/var\/www\/html\/gwinnett\/plugin\/Meet\/Meet.php(12): User::loginFromRequestIfNotLogged()\n#8 \/var\/www\/html\/gwinnett\/plugin\/AVideoPlugin.php(369): require_once('\/var\/www\/html\/g...')\n#9 \/var\/www\/html\/gwinnett\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php(288): AVideoPlugin::loadPlugin()\n#10 \/var\/www\/html\/gwinnett\/plugi","file":"\/var\/www\/html\/gwinnett\/objects\/functions.php","line":827} SCRIPT_NAME: /objects/login.json.php`

**Comment by DanielnetoDotCom** [comment]
same error as before, please debug and find out what is causing it

I cannot be bypassing an error that only happens with you. 

you must be able to instance the Configuration class.

**Comment by julzxcapz** [comment]
question is your email configuration already setup on your side? and did it sent an email successfully too?

**Comment by DanielnetoDotCom** [comment]
I do not have it set. but yes it may work

**Comment by DanielnetoDotCom** [comment]
Just tested with the email setup and also no problem

**Comment by julzxcapz** [comment]
weird.. ok sir I will do some more debugging and testing on my side for now and will let know you if I found something. thank you!

**Comment by julzxcapz** [comment]
sorry but can you confirm if it send an 2fa email to you sir? (I did clear cache too then the error show)

**Comment by DanielnetoDotCom** [comment]
Just tested again on my side and it is working. 

you MUST find out why it is not loading the $config, you may need to inject some code to debug. 

once you find a solution, you can make a pull request
