### ISSUE TITLE
Site broken stack trace error

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#8263]
My main page became broken for absolutely no reason i have not done anything on the site all week.

avideo.log flooded with this error

 [31-Jul-2023 00:15:43 Europe/London] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/video.php:1883\nStack trace:\n#0 \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/video.php(1838): Video::getInfo()\n#1 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Gallery\/functions.php(79): Video::getAllVideos()\n#2 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Gallery\/view\/mainArea.php(95): createGallery()\n#3 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Gallery\/view\/modeGallery.php(19): include('...')\n#4 \/home\/myMySQLUser\/public_html\/myMySQLUser\/view\/index_firstPage.php(58): require('...')\n#5 \/home\/myMySQLUser\/public_html\/myMySQLUser\/view\/index.php(20): include('...')\n#6 {main}\n  thrown","file":"\/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/video.php","line":1883} SCRIPT_NAME: /view/index.php

**Comment by DanielnetoDotCom** [comment]
looks like you are not using the latest git pull.

first try to update

**Comment by para2022** [comment]
I have updated it today like everyday and it was up to date when this happened

**Comment by DanielnetoDotCom** [comment]
but the logs you shared does not match with the latest git pull

**Comment by DanielnetoDotCom** [comment]
please check this update
