### ISSUE TITLE
netflix page 

### ISSUE THREAD

**Issue by junflix** [WWBN/AVideo#8371]
hello please i have one problem how i can change from this  https://prnt.sc/bpWfcEExm4U3

to this https://prnt.sc/CjlP4poy_gBE   thanksss

**Comment by DanielnetoDotCom** [comment]
If you mean the portrait image you can uncheck this

![image](https://github.com/WWBN/AVideo/assets/18009293/48512e13-3d2b-48b5-8fd2-d2c7e914bb47)

**Comment by junflix** [comment]
yes i have this but same problem 

https://prnt.sc/0EoZDm09clbc

**Comment by junflix** [comment]
bravo it works now thanks

**Comment by DanielnetoDotCom** [comment]
your database user probably does not have permission to create tables. 

but check your avideo.log

**Comment by junflix** [comment]
yes but as plugins I have bought everything worked normally in the install....that's the only problem I have

**Comment by junflix** [comment]
the last error is this 

`[31-Aug-2023 17:48:58 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php`

**Comment by DanielnetoDotCom** [comment]
Check the log when you try to install the plugin. not the last log only, but everything that happened in your attempt to install

**Comment by DanielnetoDotCom** [comment]
Are you sure this is the only error?

Please share some lines before it and after it

**Comment by junflix** [comment]
...
 [31-Aug-2023 17:59:34 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 17:48:58 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 17:40:35 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"ZipArchive\" not found in \/var\/www\/html\/AVideo\/view\/logArchive.json.php:23\nStack trace:\n#0 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/logArchive.json.php","line":23} SCRIPT_NAME: /view/logArchive.json.php

...
 [31-Aug-2023 17:28:50 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 17:24:35 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 14:42:26 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 14:42:26 Europe/Athens] PHP Fatal error:  Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in path/to/my/streamer/site/objects/pluginRunDatabaseScript.json.php:31

...
 [31-Aug-2023 14:42:02 Europe/Athens] AVideoLog::ERROR: Socket server For better performance install PDO SQLite in your PHP SCRIPT_NAME: path/to/my/streamer/site/plugin/YPTSocket/server.php

...
 [31-Aug-2023 13:20:11 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 13:20:11 Europe/Athens] PHP Fatal error:  Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in path/to/my/streamer/site/objects/pluginRunDatabaseScript.json.php:31

...
 [31-Aug-2023 10:28:55 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

...
 [31-Aug-2023 10:28:55 Europe/Athens] PHP Fatal error:  Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in path/to/my/streamer/site/objects/pluginRunDatabaseScript.json.php:31

...
 [31-Aug-2023 10:27:35 Europe/Athens] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Failed to open the referenced table 'playlists' in \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

**Comment by DanielnetoDotCom** [comment]
You must show what is in the ... 

You are not getting the error properly 

Also check your avideo health check 

I can see you are missing the php-zip

You must google to find out how to install it

**Comment by junflix** [comment]
https://prnt.sc/rpf2czhKcMZu

please check again this error i have every time after install

**Comment by DanielnetoDotCom** [comment]
It is probably because you already have the database.

drop the database or use a different database name

**Comment by junflix** [comment]
i have put new name same problem ..and if install from beginning have same error

**Comment by DanielnetoDotCom** [comment]
check your apache log

**Comment by DanielnetoDotCom** [comment]
This issue is fixed https://github.com/WWBN/AVideo/issues/8080#issuecomment-1701757422

**Comment by junflix** [comment]
now everything works fine thanks please closed ticket
