### ISSUE TITLE
install SubtitleSwitcher in Avideo 10.1, but fail

### ISSUE THREAD

**Issue by yuwiesu** [WWBN/AVideo#8423]
**Describe the question**
we used avideo 10.1 with some customization. After SubtitleSwitcher installed, the site was broken.
how can i fix that?

**Comment by yuwiesu** [comment]
attach error message---
Uncaught Error: Call to undefined function getURL() in /var/www/AVideo/plugin/SubtitleSwitcher/SubtitleSwitcher.php(18) : eval()'d code(1) : eval()'d code:234
Stack trace:
#0 /var/www/AVideo/plugin/AVideoPlugin.php(62): SubtitleSwitcher-&gt;getHeadCode()
#1 /var/www/AVideo/view/include/head.php(168): AVideoPlugin::getHeadCode()
#2 /var/www/AVideo/plugin/YouTube/view/modeYouTube.php(67): include('...')
#3 /var/www/AVideo/view/index.php(30): require('...')
#4 {main}
  thrown in 
  /var/www/AVideo/plugin/SubtitleSwitcher/SubtitleSwitcher.php(18) : eval()'d code(1) : eval()'d code
   on line 234

**Comment by DanielnetoDotCom** [comment]
To utilize our newest plugins, you must upgrade AVideo to the most recent version. 

There's no alternative method.

Please note, updating might result in the loss of your modifications. Modifying the AVideo core is not recommended.
