### ISSUE TITLE
ERROR - Uncaught TypeError: Cannot access offset of type string on string video.php modeFlixCategory.php

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8435]
@DanielnetoDotCom I'm receiving several error messages (Cannot access offset of type string on string):
```
 [14-Sep-2023 08:57:48 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/var\/www\/html\/AVideo\/objects\/video.php:1909\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(1864): Video::getInfo()\n#1 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php(221): Video::getAllVideos()\n#2 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php(30): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index_firstPage.php(58): require('...')\n#4 \/var\/www\/html\/AVideo\/view\/index.php(20): include('...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1909} SCRIPT_NAME: /view/index.php

 [16-Sep-2023 00:55:40 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/var\/www\/html\/AVideo\/objects\/video.php:1909\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(1864): Video::getInfo()\n#1 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixCategory.php(94): Video::getAllVideos()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1909} SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php
```

**Comment by DanielnetoDotCom** [comment]
looks to me like you are outdated. this error does not match with the current code.

**Comment by gbrn** [comment]
ok
