### ISSUE TITLE
Video deletion is almost impossible.

### ISSUE THREAD

**Issue by techisgreat** [WWBN/AVideo#8459]
I have a problem that I can't trace. 
When a video needs to be deleted. 
I have a loading issue that loads endlessly without deleting the video file.

I was not able to know where to fixed this issue. 
I am using FTP storage as well. 

![image](https://github.com/WWBN/AVideo/assets/100486259/48c69ff9-cc62-4d3f-996b-f281316f2cf4)

**Comment by techisgreat** [comment]
`cat avideo.log
[22-Sep-2023 14:03:52 America/Toronto] AVideoLog::DEBUG: removeVideoFiles: [v_230921183845_v25b8]  SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:52 America/Toronto] AVideoLog::DEBUG: removeVideoFiles FTP  SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:52 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:53 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:54 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:54 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /objects/videoDelete.json.php
[22-Sep-2023 14:03:54 America/Toronto] PHP Fatal error:  Uncaught TypeError: pathinfo(): Argument #1 ($path) must be of type string, array given in /var/www/html/AVideo/plugin/FTP_Storage/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code:145
Stack trace:
#0 /var/www/html/AVideo/plugin/FTP_Storage/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code(145): pathinfo()
#1 /var/www/html/AVideo/objects/video.php(2784): FTP_Storage->removeFiles()
#2 /var/www/html/AVideo/objects/video.php(2750): Video->removeVideoFiles()
#3 /var/www/html/AVideo/objects/videoDelete.json.php(22): Video->delete()
#4 {main}
  thrown in /var/www/html/AVideo/plugin/FTP_Storage/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code on line 145
[22-Sep-2023 14:03:54 America/Toronto] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: pathinfo(): Argument #1 ($path) must be of type string, array given in \/var\/www\/html\/AVideo\/plugin\/FTP_Storage\/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code:145\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/FTP_Storage\/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code(145): pathinfo()\n#1 \/var\/www\/html\/AVideo\/objects\/video.php(2784): FTP_Storage->removeFiles()\n#2 \/var\/www\/html\/AVideo\/objects\/video.php(2750): Video->removeVideoFiles()\n#3 \/var\/www\/html\/AVideo\/objects\/videoDelete.json.php(22): Video->delete()\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/FTP_Storage\/FTP_Storage.php(18) : eval()'d code(1) : eval()'d code","line":145} SCRIPT_NAME: /objects/videoDelete.json.php
root@gamegalaxy:/var/www/html/AVideo/videos# `

**Comment by techisgreat** [comment]
It seems the FTP modules was the issue in code.
Maybe it needs to have update ?

**Comment by DanielnetoDotCom** [comment]
is the storage working properly?

can you check if the video was deleted even with this error?

**Comment by techisgreat** [comment]
Yeah the Storage are set correctly and it's reading the video perfect on website.
And yes the video is deleting when i refresh the page.

**Comment by DanielnetoDotCom** [comment]
Not the video in the database, but the video file in the FTP storage

**Comment by techisgreat** [comment]
Some are stuck there

**Comment by DanielnetoDotCom** [comment]
I just sent FTP_Storage version 3.1, can you please download it again and check if is fine now?

**Comment by techisgreat** [comment]
i still see 3.0

**Comment by DanielnetoDotCom** [comment]
Sorry I said too earlier, now it is available on the marketplace

**Comment by techisgreat** [comment]
Mmm.. i dont know but i still have 3.0 XD

**Comment by DanielnetoDotCom** [comment]
Download it again from marketplace

**Comment by techisgreat** [comment]
I changed my DNS still 3.0
![image](https://github.com/WWBN/AVideo/assets/100486259/269d08eb-f905-45b7-856b-4a45db2f5ef6)

**Comment by techisgreat** [comment]
> I changed my DNS still 3.0 ![image](https://user-images.githubusercontent.com/100486259/270033835-269d08eb-f905-45b7-856b-4a45db2f5ef6.png)
Is still there  
https://youphp.tube/marketplace/

**Comment by DanielnetoDotCom** [comment]
did you download it again from the marketplace?

**Comment by techisgreat** [comment]
> did you download it again from the marketplace?

Exact and i am still stuck on 3.0

**Comment by DanielnetoDotCom** [comment]
delete the FTP_Storage folder and upload again

**Comment by techisgreat** [comment]
Working but for some reason it deleting every video but only one left the 720 .

**Comment by DanielnetoDotCom** [comment]
humm, do you mean it delete all the videos but 720 no?

what other resolutions were deleted?

**Comment by techisgreat** [comment]
1080p - 1440p - 2160p  all gone 
But only 720 p stay on fille zilla maybe it's be cause some one was watching this one at same time ?

**Comment by DanielnetoDotCom** [comment]
I do not think so, but there was any error in the logs?

**Comment by techisgreat** [comment]
i gonna re-try if it was my mistake.

**Comment by techisgreat** [comment]
ALL GOOD. 
It was my fault.

**Comment by techisgreat** [comment]
Thanks for this update very appreciate !
