### ISSUE TITLE
ERROR - Uncaught TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8461]
@DanielnetoDotCom Danny, several errors _Uncaught TypeError: Cannot access offset of type string on string_.

```
 [23-Sep-2023 09:08:15 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/var\/www\/html\/AVideo\/objects\/video.php:1906\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(1861): Video::getInfo()\n#1 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php(221): Video::getAllVideos()\n#2 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php(30): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index_firstPage.php(58): require('...')\n#4 \/var\/www\/html\/AVideo\/view\/index.php(20): include('...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1906} SCRIPT_NAME: /view/index.php

 [23-Sep-2023 09:07:54 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/var\/www\/html\/AVideo\/objects\/video.php:1906\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/video.php(1861): Video::getInfo()\n#1 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php(221): Video::getAllVideos()\n#2 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php(30): include('...')\n#3 \/var\/www\/html\/AVideo\/view\/index_firstPage.php(58): require('...')\n#4 \/var\/www\/html\/AVideo\/view\/index.php(20): include('...')\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1906} SCRIPT_NAME: /view/index.php
```

**Comment by DanielnetoDotCom** [comment]
Can you please check this update

**Comment by gbrn** [comment]
OK
