### ISSUE TITLE
Comments have stopped working

### ISSUE THREAD

**Issue by ourchube** [WWBN/AVideo#8479]
Since yesterdays update comments are now broken. Not appearing on videos or in comments panel. was working fine before. Nothing in the log.

**Comment by DanielnetoDotCom** [comment]
can you please check your logs when you comment on something?

**Comment by para2022** [comment]
No error in the log mate. When i comment the comment appears. If i refresh then it is gone. Comments panel  doesnt load its blank. Ive had this bug once before a long time ago but it was fixed.

**Comment by DanielnetoDotCom** [comment]
what about if you clear the cache?

can you reproduce it on the demo site?

**Comment by para2022** [comment]
nothing happens if i clear the cache

**Comment by para2022** [comment]
Ive not tried on the demo site. But it happened after a git pull 2 days ago. The demo site that i havnt applied that update to is working fine.

**Comment by para2022** [comment]
I get this in my php log. 

Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7

**Comment by DanielnetoDotCom** [comment]
show more regarding this last error

**Comment by para2022** [comment]
sorry mate.

[27-Sep-2023 19:59:42 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function includeConfigLog() in /home/ourtube/public_html/ourtube/objects/user.php:7
Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7
[27-Sep-2023 19:59:46 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function includeConfigLog() in /home/ourtube/public_html/ourtube/objects/user.php:7
Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7
[27-Sep-2023 19:59:48 Europe/London] /home/ourtube/public_html/ourtube/view/../plugin/VideoOffline/offlineVideo.php
[27-Sep-2023 19:59:49 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function includeConfigLog() in /home/ourtube/public_html/ourtube/objects/user.php:7
Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7
[27-Sep-2023 19:59:57 Europe/London] /home/ourtube/public_html/ourtube/view/../plugin/VideoOffline/offlineVideo.php
[27-Sep-2023 20:00:01 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function includeConfigLog() in /home/ourtube/public_html/ourtube/objects/user.php:7
Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7
[27-Sep-2023 20:00:06 Europe/London] /home/ourtube/public_html/ourtube/view/../plugin/VideoOffline/offlineVideo.php
[27-Sep-2023 20:00:18 Europe/London] SCORE ==> fileAge = 72 AND lifetimeSeconds = 60
[27-Sep-2023 20:00:18 Europe/London] PING ==> fileAge = 73 AND lifetimeSeconds = 30
[27-Sep-2023 20:00:18 Europe/London] PING ==> fileAge = 72 AND lifetimeSeconds = 30
[27-Sep-2023 20:00:19 Europe/London] PING ==> fileAge = 73 AND lifetimeSeconds = 30
[27-Sep-2023 20:00:33 Europe/London] SCORE ==> fileAge = 14 AND lifetimeSeconds = 60
[27-Sep-2023 20:01:02 Europe/London] /home/ourtube/public_html/ourtube/view/../plugin/VideoOffline/offlineVideo.php
[27-Sep-2023 20:01:17 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function includeConfigLog() in /home/ourtube/public_html/ourtube/objects/user.php:7
Stack trace:
#0 /home/ourtube/public_html/ourtube/objects/comment.php(9): require_once()
#1 /home/ourtube/public_html/ourtube/objects/comments.json.php(6): require_once('...')
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/objects/user.php on line 7

**Comment by DanielnetoDotCom** [comment]
try this update

**Comment by para2022** [comment]
And just like magic they are back working again. Cheers buddy much appreciated :)
