### ISSUE TITLE
[Security Risk] Stripe "Restricted Access" key must be created with read/write access to all APIs

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8516]
**Describe the bug**
I was iteratively able to determine that the Stripe "restricted key" needs the following permissions:

Customer **WRITE**
Subscription **WRITE**
Webhook **READ**

However, with these, when creating a customer we hit the error rak_plan_write and on researching this error, we find that "_Stripe has transitioned from Plans and Subscriptions to using Prices and Products for a more simplified subscription model_."

Therefore, we have to create a "restricted access" key with read/write permissions to ALL APIs, which violates the Principle of Least Privilege. We don't want a hacker to get 100% API control of our Stripe accounts.

**Comment by para2022** [comment]
Yes i can confirm this. I cannot setup my stripe anymore due to this.

Having the 'rak_plan_write' permission would allow this request to continue.\n  thrown","file":"\/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/Exception\/ApiErrorException.php","line":38} SCRIPT_NAME: /plugin/YPTWallet/plugins/YPTWalletStripe/requestSubscription.json.php

**Comment by para2022** [comment]
> **Describe the bug** I was iteratively able to determine that the Stripe "restricted key" needs the following permissions:
> 
> Customer **WRITE** Subscription **WRITE** Webhook **READ**
> 
> However, with these, when creating a customer we hit the error rak_plan_write and on researching this error, we find that "_Stripe has transitioned from Plans and Subscriptions to using Prices and Products for a more simplified subscription model_."
> 
> Therefore, we have to create a "restricted access" key with read/write permissions to ALL APIs, which violates the Principle of Least Privilege. We don't want a hacker to get 100% API control of our Stripe accounts.

webhook should be write not read! Your log tells you this. Subscription should be read

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure what is it. I also use Stripe by myself with no issue. 

maybe some of the APIs we do not need access to, but I am not sure what exactly we need. 

anyway you can try to deactivate some of them

**Comment by para2022** [comment]
Which ones do you have activated Dan?

**Comment by para2022** [comment]
this is after your git pull on the nodes:

[09-Jan-2024 16:11:22 Europe/London] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error sending request to Stripe: (Status 403) (Request req_sIVuSVnnDP0NSM) The provided key 'rk_live_*********************************************************************************************0JzNNb' does not have the required permissions for this endpoint on account 'acct_myaccount'. Having the 'rak_plan_write' permission would allow this request to continue.\nStripe\\Exception\\PermissionException: The provided key 'rk_live_*********************************************************************************************0JzNNb' does not have the required permissions for this endpoint on account 'acct_myaccount'. Having the 'rak_plan_write' permission would allow this request to continue. in \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/Exception\/ApiErrorException.php:38\nStack trace:\n#0 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiRequestor.php(227): Stripe\\Exception\\ApiErrorException::factory()\n#1 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiRequestor.php(180): Stripe\\ApiRequestor::_specificAPIError()\n#2 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiRequestor.php(564): Stripe\\ApiRequestor->handleErrorResponse()\n#3 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiRequestor.php(128): Stripe\\ApiRequestor->_interpretResponse()\n#4 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiOperations\/Request.php(81): Stripe\\ApiRequestor->request()\n#5 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/ApiOperations\/Create.php(25): Stripe\\ApiResource::_staticRequest()\n#6 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/StripeYPT\/StripeYPT.php(302): Stripe\\Plan::create()\n#7 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/StripeYPT\/StripeYPT.php(469): StripeYPT->createBillingPlan()\n#8 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/YPTWallet\/plugins\/YPTWalletStripe\/requestSubscription.json.php(54): StripeYPT->setUpSubscription()\n#9 {main}\n  thrown","file":"\/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/stripe\/stripe-php\/lib\/Exception\/ApiErrorException.php","line":38} SCRIPT_NAME: /plugin/YPTWallet/plugins/YPTWalletStripe/requestSubscription.json.php

**Comment by para2022** [comment]
rak_plan api was removed by stripe

**Comment by DanielnetoDotCom** [comment]
For myself, I added everything. 

but try to create a new access key
