### ISSUE TITLE
Crash in plugins->AD_Server->Install tables

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8523]
**Describe the bug**
Crashing installing tables for AD_Server.

**To Reproduce**
1. Go to Plugins.
2. Click on 'Install Tables' under AD_Server.
3. Spins forever.

**Expected behavior**
To install tables for AD_Server.

**Error Logs**
```
$ tail avideo.log
[14-Oct-2023 02:03:09 America/Los_Angeles] AVideoLog::DEBUG: NOT isShareEnabled() SCRIPT_NAME: /view/index.php
[14-Oct-2023 02:03:09 America/Los_Angeles] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser(1) = false SCRIPT_NAME: /view/index.php
[14-Oct-2023 02:03:59 America/Los_Angeles] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB' at line 20 in /var/www/html/burrow.tv/objects/pluginRunDatabaseScript.json.php:31
Stack trace:
#0 /var/www/html/burrow.tv/objects/pluginRunDatabaseScript.json.php(31): mysqli->query()
#1 {main}
  thrown in /var/www/html/burrow.tv/objects/pluginRunDatabaseScript.json.php on line 31
[14-Oct-2023 02:03:59 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CASCADE\n    ON UPDATE NO ACTION)\nENGINE = InnoDB' at line 20 in \/var\/www\/html\/burrow.tv\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/burrow.tv\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/burrow.tv\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php
```

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it. 

can you please try this update?
