### ISSUE TITLE
Latest Git Pull - Front Page Error

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8533]
After latest pull, here is result of home page:

```
array(4) { ["type"]=> int(1) ["message"]=> string(538) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/URT/objects/video.php:6530 Stack trace: #0 /mnt/www/AVideo/URT/plugin/Gallery/view/BigVideo.php(83): Video::getVideoImagewithHoverAnimationFromVideosId() #1 /mnt/www/AVideo/URT/plugin/Gallery/view/mainArea.php(45): include('...') #2 /mnt/www/AVideo/URT/plugin/Gallery/view/modeGallery.php(21): include('...') #3 /mnt/www/AVideo/URT/view/index_firstPage.php(58): require('...') #4 /mnt/www/AVideo/URT/view/index.php(20): include('...') #5 {main} thrown" ["file"]=> string(37) "/mnt/www/AVideo/URT/objects/video.php" ["line"]=> int(6530) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(538) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/URT/objects/video.php:6530
Stack trace:
#0 /mnt/www/AVideo/URT/plugin/Gallery/view/BigVideo.php(83): Video::getVideoImagewithHoverAnimationFromVideosId()
#1 /mnt/www/AVideo/URT/plugin/Gallery/view/mainArea.php(45): include('...')
#2 /mnt/www/AVideo/URT/plugin/Gallery/view/modeGallery.php(21): include('...')
#3 /mnt/www/AVideo/URT/view/index_firstPage.php(58): require('...')
#4 /mnt/www/AVideo/URT/view/index.php(20): include('...')
#5 {main}
  thrown"
  ["file"]=>
  string(37) "/mnt/www/AVideo/URT/objects/video.php"
  ["line"]=>
  int(6530)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by GreenDragonTavern** [comment]
And on another site:
```
[Trending](https://tube.farmersmarket.site/?showOnly=TrendingOrder)
array(4) { ["type"]=> int(1) ["message"]=> string(703) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/FMS/objects/video.php:6530 Stack trace: #0 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(297): Video::getVideoImagewithHoverAnimationFromVideosId() #1 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(199): createGallerySectionVideo() #2 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(86): createGallerySection() #3 /mnt/www/AVideo/FMS/plugin/Gallery/view/mainArea.php(125): createGallery() #4 /mnt/www/AVideo/FMS/plugin/Gallery/view/modeGallery.php(21): include('...') #5 /mnt/www/AVideo/FMS/view/index_firstPage.php(58): require('...') #6 /mnt/www/AVideo/FMS/view/index.php(20): include('...') #7 {main} thrown" ["file"]=> string(37) "/mnt/www/AVideo/FMS/objects/video.php" ["line"]=> int(6530) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(703) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/FMS/objects/video.php:6530
Stack trace:
#0 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(297): Video::getVideoImagewithHoverAnimationFromVideosId()
#1 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(199): createGallerySectionVideo()
#2 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(86): createGallerySection()
#3 /mnt/www/AVideo/FMS/plugin/Gallery/view/mainArea.php(125): createGallery()
#4 /mnt/www/AVideo/FMS/plugin/Gallery/view/modeGallery.php(21): include('...')
#5 /mnt/www/AVideo/FMS/view/index_firstPage.php(58): require('...')
#6 /mnt/www/AVideo/FMS/view/index.php(20): include('...')
#7 {main}
  thrown"
  ["file"]=>
  string(37) "/mnt/www/AVideo/FMS/objects/video.php"
  ["line"]=>
  int(6530)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}[Trending](https://tube.farmersmarket.site/?showOnly=TrendingOrder)
array(4) { ["type"]=> int(1) ["message"]=> string(703) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/FMS/objects/video.php:6530 Stack trace: #0 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(297): Video::getVideoImagewithHoverAnimationFromVideosId() #1 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(199): createGallerySectionVideo() #2 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(86): createGallerySection() #3 /mnt/www/AVideo/FMS/plugin/Gallery/view/mainArea.php(125): createGallery() #4 /mnt/www/AVideo/FMS/plugin/Gallery/view/modeGallery.php(21): include('...') #5 /mnt/www/AVideo/FMS/view/index_firstPage.php(58): require('...') #6 /mnt/www/AVideo/FMS/view/index.php(20): include('...') #7 {main} thrown" ["file"]=> string(37) "/mnt/www/AVideo/FMS/objects/video.php" ["line"]=> int(6530) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(703) "Uncaught TypeError: Cannot access offset of type string on string in /mnt/www/AVideo/FMS/objects/video.php:6530
Stack trace:
#0 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(297): Video::getVideoImagewithHoverAnimationFromVideosId()
#1 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(199): createGallerySectionVideo()
#2 /mnt/www/AVideo/FMS/plugin/Gallery/functions.php(86): createGallerySection()
#3 /mnt/www/AVideo/FMS/plugin/Gallery/view/mainArea.php(125): createGallery()
#4 /mnt/www/AVideo/FMS/plugin/Gallery/view/modeGallery.php(21): include('...')
#5 /mnt/www/AVideo/FMS/view/index_firstPage.php(58): require('...')
#6 /mnt/www/AVideo/FMS/view/index.php(20): include('...')
#7 {main}
  thrown"
  ["file"]=>
  string(37) "/mnt/www/AVideo/FMS/objects/video.php"
  ["line"]=>
  int(6530)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by GreenDragonTavern** [comment]
AVideo log:

```
[17-Oct-2023 09:47:00 America/Los_Angeles] AVideoLog::DEBUG: [{"file":"\/mnt\/www\/AVideo\/OFN\/objects\/user.php","line":1118,"function":"_session_write_close","args":[]},{"file":"\/mnt\/www\/AVideo\/OFN\/objects\/user.php","line":1248,"function":"login","class":"User","object":{"created":"2023-08-08 17:58:16","lastLogin":"2023-09-23 18:56:21"},"type":"->","args":[false,true]},{"file":"\/mnt\/www\/AVideo\/OFN\/objects\/user.php","line":1291,"function":"recreateLoginFromCookie","class":"User","type":"::","args":[]},{"file":"\/mnt\/www\/AVideo\/OFN\/objects\/video.php","line":7055,"function":"isAdmin","class":"User","type":"::","args":[]},{"file":"\/mnt\/www\/AVideo\/OFN\/objects\/include_config.php","line":198,"args":["\/mnt\/www\/AVideo\/OFN\/objects\/video.php"],"function":"require_once"},{"file":"\/mnt\/www\/AVideo\/OFN\/videos\/configuration.php","line":47,"args":["\/mnt\/www\/AVideo\/OFN\/objects\/include_config.php"],"function":"require_once"},{"file":"\/mnt\/www\/AVideo\/OFN\/view\/index.php","line":7,"args":["\/mnt\/www\/AVideo\/OFN\/videos\/configuration.php"],"function":"require_once"}] SCRIPT_NAME: /view/index.php
[17-Oct-2023 09:47:00 America/Los_Angeles] AVideoLog::DEBUG: User:login finish users_id=7 SCRIPT_NAME: /view/index.php
[17-Oct-2023 09:47:00 America/Los_Angeles] AVideoLog::DEBUG: user::recreateLoginFromCookie: do cookie-login: RDubYaB   id: 7 SCRIPT_NAME: /view/index.php
[17-Oct-2023 09:47:00 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Cannot access offset of type string on string in \/mnt\/www\/AVideo\/OFN\/objects\/video.php:6530\nStack trace:\n#0 \/mnt\/www\/AVideo\/OFN\/plugin\/Gallery\/functions.php(297): Video::getVideoImagewithHoverAnimationFromVideosId()\n#1 \/mnt\/www\/AVideo\/OFN\/plugin\/Gallery\/functions.php(199): createGallerySectionVideo()\n#2 \/mnt\/www\/AVideo\/OFN\/plugin\/Gallery\/functions.php(86): createGallerySection()\n#3 \/mnt\/www\/AVideo\/OFN\/plugin\/Gallery\/view\/mainArea.php(125): createGallery()\n#4 \/mnt\/www\/AVideo\/OFN\/plugin\/Gallery\/view\/modeGallery.php(21): include('...')\n#5 \/mnt\/www\/AVideo\/OFN\/view\/index_firstPage.php(58): require('...')\n#6 \/mnt\/www\/AVideo\/OFN\/view\/index.php(20): include('...')\n#7 {main}\n  thrown","file":"\/mnt\/www\/AVideo\/OFN\/objects\/video.php","line":6530} SCRIPT_NAME: /view/index.php
```

**Comment by DanielnetoDotCom** [comment]
can you please manually truncate the CachesInDB table?

**Comment by DanielnetoDotCom** [comment]
anyway, this update will avoid this error. 

but you still need to clear the cache

**Comment by GreenDragonTavern** [comment]
CachesInDB table cleaned and yep, that did the trick on all sites. Thank you.
