### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#8542]
Sorry to be a pain. This appears to be the last bug.

Its the spinner again (loading page), and nothing happens. I refresh the page and no backup has occurred. Just the loading page again that continues to load but never stops.

![Screenshot 2023-10-19 at 21 45 22](https://github.com/WWBN/AVideo/assets/107706817/003befe2-abcf-439b-95c1-746afca91aa5)

**Comment by DanielnetoDotCom** [comment]
can you please check your logs?

**Comment by para2022** [comment]
I should have posted this here sorry.

[19-Oct-2023 22:38:47 Europe/London] PHP Fatal error: Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1): eval()
https://github.com/WWBN/AVideo/pull/1 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18): eval()
https://github.com/WWBN/AVideo/issues/2 {main}
thrown in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code on line 4
[19-Oct-2023 22:38:50 Europe/London] PHP Fatal error: Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1): eval()
https://github.com/WWBN/AVideo/pull/1 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18): eval()
https://github.com/WWBN/AVideo/issues/2 {main}
thrown in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code on line 4

**Comment by DanielnetoDotCom** [comment]
make a git pull and try again

**Comment by para2022** [comment]
Sorry still the same dan. I deleted it from plugins and all db entries and updated.

[19-Oct-2023 22:59:37 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1): eval()
#1 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18): eval()
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code on line 4
[19-Oct-2023 22:59:37 Europe/London] SCORE ==> fileAge = 1 AND lifetimeSeconds = 60
[19-Oct-2023 22:59:37 Europe/London] /home/ourtube/public_html/ourtube/view/../plugin/VideoOffline/offlineVideo.php
[19-Oct-2023 22:59:41 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1): eval()
#1 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18): eval()
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code on line 4

**Comment by DanielnetoDotCom** [comment]
Sorry I found the bug, I will send an update soon

**Comment by DanielnetoDotCom** [comment]
Backup plugin version 2.6 will fix it

**Comment by para2022** [comment]
im on 2.6 and still the same loading page in a loop:

[19-Oct-2023 23:28:38 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1): eval()
#1 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18): eval()
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code on line 4

**Comment by DanielnetoDotCom** [comment]
version 2.7 soon

**Comment by para2022** [comment]
Dan before you release it read the following

**Comment by para2022** [comment]
I probs should have told you this before your plugin update. Are you aware that if you move the default save path to anywhere else out of the default plugin save path then the backup will not work? (This is a separate bug worth mentioning). This has never worked but as it was not a major deal i never brought it up. But it became a big deal as i deleted all backups during plugin deletion. Read below.

1. I create a new directory outside of the plugins dir  for my 'backup' i chmod it 777 and make sure its ownership is correct.
2. I paste this path into the plugin settings and save, and it has saved correctly.
3. It will not complete a backup if i do this and it doesn't matter where i move the backup dir.
4. If i put the default plugin save path back in the settings and i have created the dir already, chmod 777 it and ownership is correct. Then the backup will always complete flawlessly.

Here is the big design flaw! When a user updates the 'backup' plugin and he/she is not paying attention then all there backups are gone and this could have been avoided if they can successfully change the dir, which i tried to do as i anticipated this may happen. I was tired one day and deleted all my backups by deleting and updating the plugin. This absolutely needs addressing. However i always run other db backups as a failsafe to this problem so i did not loose my db backups, but i could have if i wasn't forward thinking.

**Comment by DanielnetoDotCom** [comment]
I see, 
I understand but I cannot change it now.

**Comment by para2022** [comment]
Thats absolutely fine, i just wanted to make you aware so you can add to your todo list for future bug fixes.

**Comment by para2022** [comment]
This is fixed now Dan. Thanks so much for the update and fix :)
