### ISSUE TITLE
Message of the day bug

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#8544]
Hi,

There is always a black message of the day that always appears. If the message has expired the blank message will still appear. If there is an active message the phantom blank message will appear before it. I have checked the database and there is no blank message or bug there.

![Screenshot 2023-10-19 at 21 53 48](https://github.com/WWBN/AVideo/assets/107706817/6c32ebc1-d774-49ef-bc2d-7838fcdb0699)

![Screenshot 2023-10-19 at 21 54 25](https://github.com/WWBN/AVideo/assets/107706817/338ab4b5-ccae-4da2-ad35-f158a65705b1)

**Comment by para2022** [comment]
Tones of these in my Avideo.log buddy.

 [19-Oct-2023 22:22:40 Europe/London] AVideoLog::ERROR: Time: 3.438s   | Limit: 0.7s | Location: path/to/my/streamer/site/objects/videoAddNew.json.php Line 183 [path/to/my/streamer/site/objects/videoAddNew.json.php] IP=2a02:c7c:5f98:6500:ccf7:7a46:3cac:e6fc backtrace=[{"file":"\/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/videoAddNew.json.php","line":183,"function":"TimeLogEnd","args":["\/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/videoAddNew.json.php",183]}] SCRIPT_NAME: /objects/videoAddNew.json.php

And here for my server logs:

[19-Oct-2023 22:38:47 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1): eval()
#1 /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18): eval()
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/plugin/Backup/status.json.php(18) : eval()'d code(1) : eval()'d code on line 4
[19-Oct-2023 22:38:50 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _session_write_close() in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code:4
Stack trace:
#0 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1): eval()
#1 /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18): eval()
#2 {main}
  thrown in /home/ourtube/public_html/ourtube/plugin/Backup/execBackupInBackground.json.php(18) : eval()'d code(1) : eval()'d code on line 4

**Comment by DanielnetoDotCom** [comment]
the PHP Fatal error should be resolved with a git pull from a couple of days ago

the MessageOfTheDay plugin, please update it to version 1.9

if it persists, please check your MessageOfTheDay plugin parameters

**Comment by para2022** [comment]
I updated message of the day already. There was loads of plugin updates i completed over the past few days. I will update it again and report back. Their are no options to address on message of the day, just system wide message and message of the day. These are blank now, there are no entries so need explanation why a blank message would keep popping up.

**Comment by para2022** [comment]
I will delete it from plugins and all database entries and start again

**Comment by para2022** [comment]
Working now since i did the above. Thanks mate.
