### ISSUE TITLE
Does AWS_S3 plugin works for other S3 compatible object store like MinIO?

### ISSUE THREAD

**Issue by osvaldolivondeni** [WWBN/AVideo#8616]
**Describe the question**
Hi guys,

Has anyone used the AWS_S3 plugin with other S3 compatible object store like MinIO?

I'm trying to configure it with my MinIO bucket and it returns the following error:
"Error executing "PutObject" on "https://my-bucket-name.myendpointurl.com:9000/test.txt"; AWS HTTP error: cURL error 6: Could not resolve host: [my-bucket-name.myendpointurl.com](http://my-bucket-name.myendpointurl.com/) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my-bucket-name.myendpointurl.com:9000/test.txt"

It turns out that MinIO bucket url is accessible via the following URL: "https://myendpointurl.com:9000/my-bucket-name/" and not "https://my-bucket-name.myendpointurl.com:9000/" as AWS_S3 plugins sugests.

Thanks alot for any help

**Comment by osvaldolivondeni** [comment]
Hi @DanielnetoDotCom thanks alot for your reply.

Here I send the full error log (I just replaced some sensitive texts for privacy):

Error executing "PutObject" on "https://my-bucket-name.myendpointurl.com:9000/test.txt"; AWS HTTP error: cURL error 6: Could not resolve host: my-bucket-name.myendpointurl.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my-bucket-name.myendpointurl.com:9000/test.txt

#0 /var/www/html/AVideo/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(96): Aws\WrappedHttpHandler->parseError() #1 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}() #2 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}() #5 /var/www/html/AVideo/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\Promise\TaskQueue->run() #6 /var/www/html/AVideo/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(184): GuzzleHttp\Handler\CurlMultiHandler->tick() #7 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute() #8 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #9 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #10 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #11 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #12 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #13 /var/www/html/AVideo/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /var/www/html/AVideo/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait() #15 /var/www/html/AVideo/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute() #16 /var/www/html/AVideo/plugin/AWS_S3/AWS_S3.php(18) : eval()'d code(1) : eval()'d code(223): Aws\AwsClient->__call() #17 /var/www/html/AVideo/plugin/AWS_S3/test.php(18) : eval()'d code(1) : eval()'d code(14): AWS_S3->copy_to_s3() #18 /var/www/html/AVideo/plugin/AWS_S3/test.php(18) : eval()'d code(1): eval() #19 /var/www/html/AVideo/plugin/AWS_S3/test.php(18): eval() #20 {main}

**Comment by DanielnetoDotCom** [comment]
Can you please share more from your log and also screenshot the AWS_S3 parameters page?
