### ISSUE TITLE
Videos not found after upgrading from 12.X to 14

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#8618]
Hello,

we just upgraded our instance from v12.x to v14 however after doing that, videos are listed but once you click on it to watch an error is displayed:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/660948bf-263a-45ed-b656-fe3770f571d0)

Any idea why? Videos were working fine before upgrading.

Thanks.

**Comment by tbprince** [comment]
Also, the encoder won't encode anymore:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/0b5986cc-52ce-4e88-a819-c83d7f9b1e82)

**Comment by tbprince** [comment]
I'm adding further details:

Videos accessed using the URL scheme:
[avideo]/channel/VaiSulWebMedia/videoEmbed/2?autoplay=1&controls=1&loop=0&mute=0&t=0

display a 403 error. However, videos accessed using the scheme:
[avideo]/channel/VaiSulWebMedia/video/2

display just fine. A page is displayed and the video is available. It seems that videos ARE available but the links in homepage won't work anymore as well as links in /mvideos, that is these ones:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/7f23527a-f932-430f-8b2e-53acd19b6e3f)


Thanks.

**Comment by tbprince** [comment]
In the encoder log I can see this error:

11-Nov-2023 14:05:48 Europe/Berlin] setStatusError(42, deleted from queue, ) [{"file":"\/var\/www\/html\/objects\/Encoder.php","line":951,"function":"setStatusError","class":"Encoder","type":"::","args":["42","deleted from queue"]},{"file":"\/var\/www\/html\/view\/deleteQueue.php","line":21,"function":"deleteQueue","class":"Encoder","object":{},"type":"->","args":[false]}]
[11-Nov-2023 14:05:48 Europe/Berlin] Encoder::save id=(42) title=(Hitech_3_no-captions)
[11-Nov-2023 14:07:32 Europe/Berlin] Upload.php will let function decide decideFormatOrder
[11-Nov-2023 14:07:32 Europe/Berlin] decideFormatOrder: {"file":"Hitech_3_no-captions.mp4","audioOnly":"false","spectrum":"false","webm":"false","override_status":"","update_video_id":0,"inputHLS":"false","inputLow":"false","inputSD":"false","inputHD":"false","inputAutoHLS":"true","inputAutoMP4":"false","inputAutoWebm":"false","inputAutoAudio":"false","title":"HiTech2","description":"","categories_id":0,"releaseDate":"2023-11-11 13:58:00","timezone":"Europe\/Rome","PHPSESSID":"095927tssuqv4e65uirhigj02r","notifyURL":""}
[11-Nov-2023 14:07:32 Europe/Berlin] decideFormatOrder: auto HLS
[11-Nov-2023 14:07:32 Europe/Berlin] AVideo-Encoder Format::getFromOrder(6)
[11-Nov-2023 14:07:32 Europe/Berlin] Upload.php line: 113 "m3u8"
[11-Nov-2023 14:07:32 Europe/Berlin] Encoder::sendFile videos_id=0, format=m3u8
[11-Nov-2023 14:07:32 Europe/Berlin] Encoder::sendFile sending file to aVideoEncoder.json from 
[11-Nov-2023 14:07:32 Europe/Berlin] sendToStreamer to aVideoEncoder.json 
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer spectrumimage not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer rawVideo not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer image not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer gifimage not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer webpimage not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer video not set
[11-Nov-2023 14:07:34 Europe/Berlin] sendToStreamer https://_[edited]_/aVideoEncoder.json in 1.140 seconds {"error":true,"target":"aVideoEncoder.json","postFields":{"duration":"EE:EE:EE","title":"HiTech2","first_request":1,"categories_id":0,"format":"m3u8","resolution":"","videoDownloadedLink":null,"description":"","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/encoder1.vaisulweb.media\/","keepEncoding":"0","streamers_id":1,"user":"_[edited]_","pass":"_[edited]_","return_vars":"{\"videos_id\":0,\"video_id_hash\":\"\",\"releaseDate\":\"2023-11-11 13:58:00\"}","releaseDate":"2023-11-11 13:58:00","releaseTime":1699707480,"timezone":"Europe\/Berlin"},"response_raw":"array(4) {\n  [\"type\"]=>\n  int(1)\n  [\"message\"]=>\n  string(694) \"Uncaught mysqli_sql_exception: Can't find FULLTEXT index matching the column list in \/var\/www\/AVideo\/objects\/mysql_dal.php:132\nStack trace:\n#0 \/var\/www\/AVideo\/objects\/mysql_dal.php(132): mysqli->prepare()\n#1 \/var\/www\/AVideo\/plugin\/Cache\/Objects\/CachesInDB.php(293): sqlDAL::writeSql()\n#2 \/var\/www\/AVideo\/plugin\/Cache\/Objects\/CacheDB.php(26): CachesInDB::_deleteCacheStartingWith()\n#3 \/var\/www\/AVideo\/objects\/Object.php(1095): CacheDB::deleteCacheStartingWith()\n#4 \/var\/www\/AVideo\/objects\/category.php(843): CacheHandler->deleteCache()\n#5 \/var\/www\/AVideo\/objects\/video.php(597): Category::clearCacheCount()\n#6 \/var\/www\/AVideo\/objects\/aVideoEncoder.json.php(191): Video->save()\n#7 {main}\n  thrown\"\n  [\"file\"]=>\n  string(37) \"\/var\/www\/AVideo\/objects\/mysql_dal.php\"\n  [\"line\"]=>\n  int(132)\n}\n<pre>array(4) {\n  [\"type\"]=>\n  int(1)\n  [\"message\"]=>\n  string(694) \"Uncaught mysqli_sql_exception: Can't find FULLTEXT index matching the column list in \/var\/www\/AVideo\/objects\/mysql_dal.php:132\nStack trace:\n#0 \/var\/www\/AVideo\/objects\/mysql_dal.php(132): mysqli->prepare()\n#1 \/var\/www\/AVideo\/plugin\/Cache\/Objects\/CachesInDB.php(293): sqlDAL::writeSql()\n#2 \/var\/www\/AVideo\/plugin\/Cache\/Objects\/CacheDB.php(26): CachesInDB::_deleteCacheStartingWith()\n#3 \/var\/www\/AVideo\/objects\/Object.php(1095): CacheDB::deleteCacheStartingWith()\n#4 \/var\/www\/AVideo\/objects\/category.php(843): CacheHandler->deleteCache()\n#5 \/var\/www\/AVideo\/objects\/video.php(597): Category::clearCacheCount()\n#6 \/var\/www\/AVideo\/objects\/aVideoEncoder.json.php(191): Video->save()\n#7 {main}\n  thrown\"\n  [\"file\"]=>\n  string(37) \"\/var\/www\/AVideo\/objects\/mysql_dal.php\"\n  [\"line\"]=>\n  int(132)\n}\narray(1) {\n  [0]=>\n  array(2) {\n    [\"function\"]=>\n    string(14) \"avideoShutdown\"\n    [\"args\"]=>\n    array(0) {\n    }\n  }\n}\n<\/pre>","response":null,"msg":"Response was not an json object"}
[11-Nov-2023 14:07:34 Europe/Berlin] AVideo-Streamer sendFile error: {"duration":"EE:EE:EE","title":"HiTech2","first_request":1,"categories_id":0,"format":"m3u8","resolution":"","videoDownloadedLink":null,"description":"","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/encoder1.vaisulweb.media\/","keepEncoding":"0"} <=>[{"file":"\/var\/www\/html\/view\/upload.php","line":114,"function":"sendFile","class":"Encoder","type":"::"},{"file":"\/var\/www\/html\/view\/jquery-file-upload\/server\/php\/fileuploadchunkdone.php","line":31,"args":["\/var\/www\/html\/view\/upload.php"],"function":"require_once"}]
[11-Nov-2023 14:07:34 Europe/Berlin] Encoder::save id=() title=(Hitech_3_no-captions)

which seems to be an issue with the databases, specially with caches maybe? This could affect the previous error on the portal as well. 

How can we fix this? Caches have been deleted using the relevant options in the menu.

Thanks.

**Comment by tbprince** [comment]
I'm adding further details. It seems maybe that the database upgrade didn't went smoothly. While we have no tables to install in our plugins screen (all updated, not tables to install) if I push the "Test IP" button for _User Location_ plugin the following image appears:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/5f46a936-3e32-423c-a5ca-2274d4034d4c)

which, I guess, means that tables for that plugin have not been installed. However, we have no tables to install.

Thanks for your support.

**Comment by DanielnetoDotCom** [comment]
First, make sure all your plugins are updated and there is no red or yellow update button in all of them even if the plugin is disabled.

then run this to make sure your CachesInDB table is up to date

run this https://github.com/WWBN/AVideo/blob/master/install/recreateCacheDB.php

```
cd /var/www/html/AVideo/install
php recreateCacheDB.php
```

**Comment by tbprince** [comment]
Hello,

yep, thanks. I just had found that solution and, as I wrote in my previous post, I fixed the encoding issue with that. Thanks!

However, pages for video are still not showing as per my first message.

Thanks.

**Comment by DanielnetoDotCom** [comment]
check your plugins

<img width="1238" alt="image" src="https://github.com/WWBN/AVideo/assets/18009293/473f759b-751f-4e99-b2a7-d412ac99c8e2">

**Comment by tbprince** [comment]
Thanks. That fixed the issue (though the result for my IP check is wildly inaccurate. Probably the Lite database is too ... lite! I'm in Italy, it reports India... not exactly close.).

However, my main issue is the 403 video not found issue:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/f4b7f7f3-1c3a-4b2a-acf0-26f2c0a0b64a)

What can this issue be related to? Had no issues with video before upgrading. I also get a 403 from time to time when navigating videos but a CTRL+F5 fixes that.

However, for this URL scheme:

[avideo]/channel/VaiSulWebMedia/videoEmbed/2?autoplay=1&controls=1&loop=0&mute=0&t=0

reloading doesn't work. It always show the issue in the pic. Any hint?

Thanks.

**Comment by tbprince** [comment]
Oh, maybe I found the issue. When I try to display the video without logging in, I always receive this message:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/c9439e02-7245-4ebe-9562-a28bd201ebb3)

However, that user has NOT run of out disk space. Disk space used is just a tiny fraction of the available disk space:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/cdd15675-f1a0-4921-820f-1a548635b2f8)

Any idea why the plugin reports no more storage space?

Thanks.

**Comment by tbprince** [comment]
Gosh. This literally seems to be a caching issue. The same link that reports a storage space issue, it works after a simple CTRL+F5.

Is there a way to completely wipe the cache out so it will be rebuilt ?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Disable the DiskUploadQuota plugin

**Comment by tbprince** [comment]
Disable the DiskUploadQuota:

![immagine](https://github.com/WWBN/AVideo/assets/15170491/3dad01a7-67d4-4ba9-bfd8-c83895cf1499)

How can it state video is not found?

The issue is always showing up when using this URL scheme:
[avideo]/channel/VaiSulWebMedia/videoEmbed/2?autoplay=1&controls=1&loop=0&mute=0&t=0

Refreshing this one always fails.

Using this scheme:
[avideo]/channel/VaiSulWebTech/video/18/kubernetes-as-a-service-installazione-automatica-e-aggiornamenti

doesn't work at first but works fine after a CTRL+F5.

Not sure how it could report a "Video not found". It seems that broken links are those out of homepages.

If one access a channel and then clicks on a video, things seems to be working, mostly.

Is there a way to reset or completely disable caching?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by tbprince** [comment]
Excellent. That fixed all issues and now everything works fine, including the DiskUploadQuota plugin.

Thanks a lot.

**Comment by rapiz** [comment]
Last version

The problem is the path:
now: /channel/xxxxxxx/video/1685/absolute-glow-logo-reveal_1080p
correct: /video/1685/absolute-glow-logo-reveal_1080p

need fix this bug
