### ISSUE TITLE
AI errors after this latest pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8660]
@DanielnetoDotCom 
20-Nov-2023 17:25:24 America/Denver] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [20-Nov-2023 17:25:24 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":310,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [20-Nov-2023 17:25:24 America/Denver] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1054) (Unknown column 'ai' in 'order clause')  preparedStatement = "SELECT * FROM  ai_transcribe_responses WHERE 1=1  ORDER BY  `ai` asc  LIMIT 0, 10 " formats = "" values = [] refreshCache = false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [20-Nov-2023 17:25:24 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":298,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

**Comment by gbrn** [comment]
I'm also facing some MySQL errors:

```
 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":310,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1054) (Unknown column 'ai' in 'order clause')  preparedStatement = "SELECT * FROM  ai_transcribe_responses WHERE 1=1  ORDER BY  `ai` asc  LIMIT 0, 10 " formats = "" values = [] refreshCache = false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":298,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

...
 [20-Nov-2023 19:09:03 America/Sao_Paulo] AVideoLog::ERROR: Time: 5.898s   | Limit: 0.5s | Location: path/to/my/streamer/site/view/user.php Line mysql_dal [[SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name ], , [], ] IP=179.55.70.71 backtrace=[{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":338,"function":"TimeLogEnd","args":["[SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name ], , [], ","mysql_dal",0.5]},{"file":"\/var\/www\/html\/AVideo\/plugin\/User_Location\/Objects\/IP2Location.php","line":100,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name "]},{"file":"\/var\/www\/html\/AVideo\/view\/userPersonalInfo.php","line":53,"function":"getCountries","class":"IP2Location","type":"::","args":[]},{"file":"\/var\/www\/html\/AVideo\/view\/userBody.php","line":40,"args":["\/var\/www\/html\/AVideo\/view\/userPersonalInfo.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/view\/user.php","line":35,"args":["\/var\/www\/html\/AVideo\/view\/userBody.php"],"function":"include"}] SCRIPT_NAME: /view/user.php
```

**Comment by gbrn** [comment]
More...

```
 [21-Nov-2023 12:23:07 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: implode(): Argument #1 ($array) must be of type array, string given in \/var\/www\/html\/AVideo\/view\/modeYoutube.php:85\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(85): implode()\n#1 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(1121): include('...')\n#2 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(973): PlayListPlayer->checkPlayMode()\n#3 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/player.php(11): PlayListPlayer->__construct()\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/modeYoutube.php","line":85} SCRIPT_NAME: /plugin/PlayLists/player.php

...
 [21-Nov-2023 07:57:59 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: implode(): Argument #1 ($array) must be of type array, string given in \/var\/www\/html\/AVideo\/view\/modeYoutube.php:85\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(85): implode()\n#1 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(1121): include('...')\n#2 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(973): PlayListPlayer->checkPlayMode()\n#3 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/player.php(11): PlayListPlayer->__construct()\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/modeYoutube.php","line":85} SCRIPT_NAME: /plugin/PlayLists/player.php

...
 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":310,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1054) (Unknown column 'ai' in 'order clause')  preparedStatement = "SELECT * FROM  ai_transcribe_responses WHERE 1=1  ORDER BY  `ai` asc  LIMIT 0, 10 " formats = "" values = [] refreshCache = false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [21-Nov-2023 00:18:14 America/Sao_Paulo] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":298,"function":"log_error"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php
```

**Comment by DanielnetoDotCom** [comment]
AI is not ready yet, please give me about a week to complete

**Comment by DanielnetoDotCom** [comment]
Hi

AI plugin is ready for tests

https://github.com/WWBN/AVideo/wiki/AI-Plugin

**Comment by milehighkaraoke** [comment]
Errors 
[24-Nov-2023 12:38:42 America/Denver] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [24-Nov-2023 12:38:42 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":310,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [24-Nov-2023 12:38:42 America/Denver] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1054) (Unknown column 'ai' in 'order clause')  preparedStatement = "SELECT * FROM  ai_transcribe_responses WHERE 1=1  ORDER BY  `ai` asc  LIMIT 0, 10 " formats = "" values = [] refreshCache = false SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

 [24-Nov-2023 12:38:42 America/Denver] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":298,"function":"log_error"},{"file":"\/var\/www\/myMySQLUser\/objects\/Object.php","line":104,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/myMySQLUser\/plugin\/AI\/View\/Ai_transcribe_responses\/list.json.php","line":6,"function":"getAll","class":"ObjectYPT","type":"::"}] SCRIPT_NAME: /plugin/AI/View/Ai_transcribe_responses/list.json.php

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
Will the AI plugin work on my server since I am on my own network void of CDN

**Comment by DanielnetoDotCom** [comment]
I am preparing some updates

@milehighkaraoke what CDN are you using?

**Comment by milehighkaraoke** [comment]
I am not on a CDN

**Comment by milehighkaraoke** [comment]
XFinity Fiber
