### ISSUE TITLE
Cannot create user

### ISSUE THREAD

**Issue by nikolatsio** [WWBN/AVideo#8740]
**Describe the bug**
When started to create a user I received this in the log file:
 [20-Dec-2023 16:55:46 Europe/Bucharest] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Unknown column 'canCreateMeet' in 'field list' in \/var\/www\/YouPHPTube\/objects\/mysql_dal.php:132\nStack trace:\n#0 \/var\/www\/YouPHPTube\/objects\/mysql_dal.php(132): mysqli->prepare()\n#1 \/var\/www\/YouPHPTube\/objects\/user.php(843): sqlDAL::writeSql()\n#2 \/var\/www\/YouPHPTube\/objects\/userAddNew.json.php(95): User->save()\n#3 {main}\n  thrown","file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","line":132} SCRIPT_NAME: /objects/userAddNew.json.php

**To Reproduce**
1. Go to Users and Create a user

**Expected behavior**

**Error Logs**
 [20-Dec-2023 16:55:46 Europe/Bucharest] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Unknown column 'canCreateMeet' in 'field list' in \/var\/www\/YouPHPTube\/objects\/mysql_dal.php:132\nStack trace:\n#0 \/var\/www\/YouPHPTube\/objects\/mysql_dal.php(132): mysqli->prepare()\n#1 \/var\/www\/YouPHPTube\/objects\/user.php(843): sqlDAL::writeSql()\n#2 \/var\/www\/YouPHPTube\/objects\/userAddNew.json.php(95): User->save()\n#3 {main}\n  thrown","file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","line":132} SCRIPT_NAME: /objects/userAddNew.json.php

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
The platform was with version 8.7 so we updated it to the latest step-by-step patch-by-patch.
All the videos and the users are there, we can upload a video without a problem. 

Server config: debian latest 12.4, mariadb latest coming from the official repository of the debian, PHP is 8.2.7.

**Comment by DanielnetoDotCom** [comment]
I have no idea how you install it, but definitely is wrong. 

canCreateMeet is in the create database script fro a while

**Comment by nikolatsio** [comment]
Clone it from git, create the db, and create the web server. Back then the application was 8.7(not 10.4).
Is it safe to run the DB script again? And where I can find it?

**Comment by DanielnetoDotCom** [comment]
Currently, AVideo is version 14.0

I have no idea how you install version 8.7 or 10.04

**Comment by nikolatsio** [comment]
Maybe I was not so clear. We update from 8.7 to 14.0. The update was successful without any issues. Now we are using 14.0 with all the features like uploading a video, showing statistics, and so on. But when we try to create a user we hit this error.

**Comment by DanielnetoDotCom** [comment]
I am not sure why you missed that column. 

you will need to compare your table with how the table supposed to be

https://github.com/WWBN/AVideo/blob/d1ab3aaf6c406f29cad9d4dfba87a1ee9dfa102f/install/database.sql#L10-L46C17

**Comment by nikolatsio** [comment]
Yes, that was! 
It was missing, so created it and now it looks good.

Thank you!
