### ISSUE TITLE
ionic version of app, cannot log in using Google

### ISSUE THREAD

**Issue by jiangzik** [WWBN/AVideo#8787]
This error occurs when debugging on the simulator

**Comment by jiangzik** [comment]
TypeError: browser.on(...).subscribe is not a function
    at webpackJsonp.167.LoginPage.oauth (http://localhost:8100/build/main.js:564:32)
    at Object.eval [as handleEvent] (ng:///AppModule/LoginPage.ngfactory.js:356:27)
    at handleEvent (http://localhost:8100/build/vendor.js:13608:172)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15093:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:14680:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10057:25)
    at http://localhost:8100/build/vendor.js:10671:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:24381:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not sure. 

if you have the ionic source code you will need to find out what is missing. 

I cannot support you in that.
