### ISSUE TITLE
ERRor

### ISSUE THREAD

**Issue by LuccaDanielGit** [WWBN/AVideo#8810]
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1097) "Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\netflix\objects\functionImages.php:957
Stack trace:
#0 C:\xampp\htdocs\netflix\objects\functionImages.php(280): convertImage('C:\\xampp\\htdocs...', 'C:\\Users\\lucca\\...', 100)
#1 C:\xampp\htdocs\netflix\objects\configuration.php(245): convertImageToOG('C:\\xampp\\htdocs...', 'C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\netflix\objects\functionsOpenGraph.php(259): AVideoConf::getOGImage()
#3 C:\xampp\htdocs\netflix\objects\functions.php(3657): getOpenGraphSite()
#4 C:\xampp\htdocs\netflix\view\include\head.php(203): ogSite()
#5 C:\xampp\htdocs\netflix\objects\Page.php(77): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\netflix\objects\Page.php(147): Page->getHead()
#7 C:\xampp\htdocs\netflix\objects\Page.php(157): Page->getPage()
#8 C:\xampp\htdocs\netflix\plugin\Gallery\view\modeGallery.php(27): Page->print()
#9 C:\xampp\htdocs\netflix\view\index_firstPage.php(58): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\netflix\view\index.php(20): include('C:\\xampp\\htdocs...')
#11 {main}
  thrown"
  ["file"]=>
  string(50) "C:\xampp\htdocs\netflix\objects\functionImages.php"
  ["line"]=>
  int(957)
}

**Comment by DanielnetoDotCom** [comment]
First, we strongly recommend Ubuntu, NOT Windows. 

Also you may find a solution for it if you google for **"Uncaught Error: Call to undefined function imagecreatefrompng()"**
