### ISSUE TITLE
cant install plugin tables

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#8929]
Nothing happens when i try to install plugin tables, it just waits forever and nothing happens. Is there something wrong? Cant say ive had this problem before.
Thanks

**Comment by DanielnetoDotCom** [comment]
what plugin exactly?

check the logs

**Comment by para2022** [comment]
Happens on any plugin:

[26-Mar-2024 20:56:07 Europe/London] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: REFERENCES command denied to user myemail@mydomain.com for table 'myMySQLDatabase.vast_campaigns' in \/var\/www\/html\/ourtube\/objects\/pluginRunDatabaseScript.json.php:31\nStack trace:\n#0 \/var\/www\/html\/ourtube\/objects\/pluginRunDatabaseScript.json.php(31): mysqli->query()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/ourtube\/objects\/pluginRunDatabaseScript.json.php","line":31} SCRIPT_NAME: /objects/pluginRunDatabaseScript.json.php

**Comment by para2022** [comment]
thrown in path/to/my/myMySQLDatabase/site/objects/pluginRunDatabaseScript.json.php on line 31
 #1 {main}
 #0 path/to/my/myMySQLDatabase/site/objects/pluginRunDatabaseScript.json.php(31): mysqli->query()
 Stack trace:

**Comment by DanielnetoDotCom** [comment]
`command denied to user [myemail@mydomain.com](mailto:myemail@mydomain.com) for table`

your user is probably missing permissions

**Comment by para2022** [comment]
Thanks mate il look into that :)

**Comment by para2022** [comment]
Sorted thanks.

Does this mean anything dan?

rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
