### ISSUE TITLE
Stack trace error in log

### ISSUE THREAD

**Issue by ourchube** [WWBN/AVideo#8952]
Do i need to fix anything here? Thanks.   

thrown in path/to/my/streamer/site/plugin/YPTSocket/MessageSQLite.php on line 475
 #12 {main}
 #11 path/to/my/streamer/site/plugin/YPTSocket/server.php(177): React\EventLoop\StreamSelectLoop->run()
 #10 path/to/my/streamer/site/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
 #9 path/to/my/streamer/site/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData()
 #8 path/to/my/streamer/site/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
 #7 path/to/my/streamer/site/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}()
 #6 path/to/my/streamer/site/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
 #5 path/to/my/streamer/site/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\Server\IoServer->Ratchet\Server\{closure}()
 #4 path/to/my/streamer/site/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(95): Ratchet\Server\IoServer->handleData()
 #3 path/to/my/streamer/site/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(112): Ratchet\Http\HttpServer->onMessage()
 #2 path/to/my/streamer/site/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(51): Ratchet\WebSocket\WsServer->onOpen()
 #1 path/to/my/streamer/site/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(142): Socket\Message->onOpen()
 #0 path/to/my/streamer/site/plugin/YPTSocket/MessageSQLite.php(128): Socket\Message->msgToAll()
 Stack trace:

**Comment by para2022** [comment]
cache errors too. My cache table exists and is being writen too:

[05-Apr-2024 17:21:36 Europe/London] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/ourtube\/objects\/mysql_dal.php","line":315,"function":"log_error"},{"file":"\/var\/www\/html\/ourtube\/plugin\/Cache\/Objects\/CachesInDB.php","line":146,"function":"readSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/ourtube\/plugin\/Cache\/Objects\/CacheDB.php","line":66,"function":"_getCache","class":"CachesInDB","type":"::"},{"file":"\/var\/www\/html\/ourtube\/plugin\/Cache\/Cache.php","line":389,"function":"getCache","class":"CacheDB","type":"::"},{"file":"\/var\/www\/html\/ourtube\/objects\/Object.php","line":661,"function":"getCache","class":"Cache","type":"::"}] SCRIPT_NAME: /view/info.php




 [05-Apr-2024 17:21:36 Europe/London] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) (Table 'myMySQLDatabase.CachesInDB' doesn't exist)  preparedStatement = "SELECT * FROM CachesInDB WHERE name = ?   AND ishttps = ? AND domain = ? AND user_location = ?  AND loggedType = ?  ORDER BY id DESC LIMIT 1" formats = "sisss" values = ["hashName__a880e914e952824ccd3ff79cb91e5e13__aen_GB_cache",1,"www.mysite.com","undefined","n"] refreshCache = false SCRIPT_NAME: /view/manifest.json.php

**Comment by para2022** [comment]
apache says this all the time:

rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/video/video_220822125856_v26d3/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/video/video_220822122809_v4fff/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/video/video_220530122109_va018/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/video/v_220703172347_v0e43/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/video/v_220717170510_v93ed/': No such file or directory
rm: cannot remove '/var/www/html/ourtube/videos/cache/YPTObjectCache/videosQueries/': No such file or directory
