### ISSUE TITLE
Unable to Encode with current git versions // Debian 12

### ISSUE THREAD

**Issue by christianreiss** [WWBN/AVideo#8971]
Hey all,

I am running -on Debian 12, using PHP 8.2- a current installation of both Avideo and the encoder. Both databases are updated, video site is working.

When I try do add a video, I get this error in the encoder log:

```
[10-Apr-2024 15:10:33 Europe/Berlin] decideFormatOrder: {"fileURI":"\/videos\/johann_2024_01_01_(15_11)_Tanzt.mp4","audioOnly":"false","spectrum":"false","webm":"false","inputHLS":"false","inputLow":"false","inputSD":"false","inputHD":"false","inputAutoHLS":"false","inputAutoMP4":"true","inputAutoWebm":"false","inputAutoAudio":"false","categories_id":3,"releaseDate":"2024-04-10 15:09","notifyURL":"","filename":"johann_2024_01_01_(15_11)_Tanzt.mp4"}
[10-Apr-2024 15:10:33 Europe/Berlin] decideFormatOrder: auto MP4
[10-Apr-2024 15:10:33 Europe/Berlin] AVideo-Encoder Format::getFromOrder(7)
[10-Apr-2024 15:10:33 Europe/Berlin] queue : Encoder::sendFile
[10-Apr-2024 15:10:33 Europe/Berlin] Encoder::sendFile videos_id=0, format=mp4
[10-Apr-2024 15:10:33 Europe/Berlin] Encoder::sendFile sending file to aVideoEncoder.json from 
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer to aVideoEncoder.json 
[10-Apr-2024 15:10:33 Europe/Berlin] getReturn_vars 
[10-Apr-2024 15:10:33 Europe/Berlin] $return_vars is empty -[null]- [{"file":"\/var\/www\/vhosts\/convert.theotube.alpha-labs.net\/objects\/Encoder.php","line":1467,"function":"sendToStreamer","class":"Encoder","type":"::","args":["aVideoEncoder.json",{"duration":"EE:EE:EE","title":"johann_2024_01_01_(15_11)_Tanzt","first_request":1,"categories_id":3,"format":"mp4","resolution":"","videoDownloadedLink":null,"description":"","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/convert.theotube.alpha-labs.net\/","keepEncoding":"0","streamers_id":2,"user":null,"pass":null},null,{}]},{"file":"\/var\/www\/vhosts\/convert.theotube.alpha-labs.net\/view\/queue.php","line":71,"function":"sendFile","class":"Encoder","type":"::","args":["",0,"mp4",{}]}]
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer spectrumimage not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer rawVideo not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer image not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer gifimage not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer webpimage not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer video not set
[10-Apr-2024 15:10:33 Europe/Berlin] sendToStreamer /aVideoEncoder.json in 0.001 seconds {"error":true,"target":"aVideoEncoder.json","postFields":{"duration":"EE:EE:EE","title":"johann_2024_01_01_(15_11)_Tanzt","first_request":1,"categories_id":3,"format":"mp4","resolution":"","videoDownloadedLink":null,"description":"","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/convert.theotube.alpha-labs.net\/","keepEncoding":"0","streamers_id":2,"user":null,"pass":null,"timezone":"Europe\/Berlin"},"response_raw":false,"response":null,"msg":"sendToStreamer cURL error (3): URL using bad\/illegal format or missing URL => aVideoEncoder.json "}
[10-Apr-2024 15:10:33 Europe/Berlin] AVideo-Streamer sendFile error: {"duration":"EE:EE:EE","title":"johann_2024_01_01_(15_11)_Tanzt","first_request":1,"categories_id":3,"format":"mp4","resolution":"","videoDownloadedLink":null,"description":"","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/convert.theotube.alpha-labs.net\/","keepEncoding":"0"} <=>[{"file":"\/var\/www\/vhosts\/convert.theotube.alpha-labs.net\/view\/queue.php","line":71,"function":"sendFile","class":"Encoder","type":"::"}]
[10-Apr-2024 15:10:33 Europe/Berlin] queue : Encoder::sendFile done
[10-Apr-2024 15:10:33 Europe/Berlin] queue: will save
[10-Apr-2024 15:10:33 Europe/Berlin] Encoder::save id=() title=(johann_2024_01_01_(15_11)_Tanzt)
[10-Apr-2024 15:10:33 Europe/Berlin] PHP Fatal error:  Uncaught mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`theocode`.`encoder_queue`, CONSTRAINT `fk_encoder_queue_streamers1` FOREIGN KEY (`streamers_id`) REFERENCES `streamers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in /var/www/vhosts/convert.theotube.alpha-labs.net/objects/Object.php:189
Stack trace:
#0 /var/www/vhosts/convert.theotube.alpha-labs.net/objects/Object.php(189): mysqli->query()
#1 /var/www/vhosts/convert.theotube.alpha-labs.net/objects/Encoder.php(138): ObjectYPT->save()
#2 /var/www/vhosts/convert.theotube.alpha-labs.net/view/queue.php(84): Encoder->save()
#3 {main}
  thrown in /var/www/vhosts/convert.theotube.alpha-labs.net/objects/Object.php on line 189
```

I even tried to wipe the database, reinstalling and re-setuping everything to no avail.

The streamers database contains:

```
MariaDB [theocode]> select id,siteURL,user,priority,isAdmin,created,modified from streamers;
+----+----------------------------------+-------+----------+---------+---------------------+---------------------+
| id | siteURL                          | user  | priority | isAdmin | created             | modified            |
+----+----------------------------------+-------+----------+---------+---------------------+---------------------+
|  1 | https://theotube.alpha-labs.net/ | admin |        1 |       1 | 2024-04-10 14:24:29 | 2024-04-10 14:24:29 |
+----+----------------------------------+-------+----------+---------+---------------------+---------------------+
1 row in set (0.000 sec)
```

and configurations_encoder:

```
MariaDB [theocode]> select * from configurations_encoder;
+----+---------------------------------+-----------------+---------------------+---------------------+---------+------------+--------------------------------------+
| id | allowedStreamersURL             | defaultPriority | created             | modified            | version | autodelete | resolutions                          |
+----+---------------------------------+-----------------+---------------------+---------------------+---------+------------+--------------------------------------+
|  1 | https://theotube.alpha-labs.net |               1 | 2024-04-10 14:24:29 | 2024-04-10 13:09:49 | 4.0     |          1 | [240,360,480,540,720,1080,1440,2160] |
+----+---------------------------------+-----------------+---------------------+---------------------+---------+------------+--------------------------------------+
```

Except for formats are all other tables empty.
I do not know how to proceed; any help is welcome.

**Comment by DanielnetoDotCom** [comment]
try to logout and login again

**Comment by christianreiss** [comment]
That... worked. Huh. Thanks!
