### ISSUE TITLE
After a recent git pull, *all* uploads result in "Broken missing files"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9009]
**Describe the bug**
After a recent git pull, _all_ uploads result in "Broken missing files"

**To Reproduce**
1. Upload a video using any method
2. Observe "Broken missing files"

**Expected behavior**
Video upload to work

**Error Logs**
https://pastebin.com/xfUNdeWV

**Comment by DanielnetoDotCom** [comment]
that is the encoder log, you should share your AVideo log

**Comment by walt93** [comment]
I just created a fresh broken/missing file video and dumped the last ≈2K lines of log

https://pastebin.com/FjwczjJy

**Comment by DanielnetoDotCom** [comment]
there is no clue in your logs

**Comment by walt93** [comment]
In the encoder logs I can see the video here:

`[23-Apr-2024 11:10:29 America/Los_Angeles] sendToStreamer https://conspyre.tv/aVideoEncoder.json in 0.285 seconds {"error":false,"target":"aVideoEncoder.json","postFields":{"duration":"EE:EE:EE","title":"Redpill Drifter - 9 WARNING SIGNS YOU MAY HAVE PARASITES  Many of the symptoms you may be feeling could, in fact, be parasites. Mainstream pharma shill Doctors do not want you to know because it can be treated naturally.  Also, check out @TheParasiteGuy ","first_request":1,"categories_id":16,"format":"mp4","resolution":"","videoDownloadedLink":"https:\/\/x.com\/RedpillDrifter\/status\/1782507044735729981","description":"9 WARNING SIGNS YOU MAY HAVE PARASITES  Many of the symptoms you may be feeling could, in fact, be parasites. Mainstream pharma shill Doctors do not want you to know because it can be treated naturally.  Also, check out @TheParasiteGuy for more great information on this topic https:\/\/t.co\/uObfiymEF5","downloadURL":"","chunkFile":"","encoderURL":"https:\/\/prometheus.conspyre.tv\/","keepEncoding":"0","streamers_id":1,"user":"Conspyre","pass":"_user_hash_dFZsZUk2UCtMcHJWUXFKQXNqM0h0V2h0b0tUSFF1eGpBR2pYZVVkak9ScEhQelBYNUhJc3ZvQlVJUmp5K21EOC81ejhnQTVkYzlJVjRoRUxPYXBJdVE9PQ==","return_vars":"{\"videos_id\":0,\"video_id_hash\":\"\",\"releaseDate\":\"2024-04-23 11:07\"}","releaseDate":"2024-04-23 11:07","releaseTime":1713895620,"timezone":"America\/Los_Angeles"},"response_raw":"{\"error\":false,\"video_id\":18387,\"video_id_hash\":\"NG93YkkvOTdoVDQvWUxSZzJZeEUrQWtLUmdyZjNLR0FzOVN1bElPKzZKcz0=\",\"releaseDate\":\"2024-04-23 11:07\",\"releaseTime\":\"1713895620\"}","response":{"error":false,"video_id":18387,"video_id_hash":"NG93YkkvOTdoVDQvWUxSZzJZeEUrQWtLUmdyZjNLR0FzOVN1bElPKzZKcz0=","releaseDate":"2024-04-23 11:07","releaseTime":"1713895620"}}
`

Looking at the log from the streamer site, the last log entry is one day previous to this, and was output with tail -n 1500. I don't even have a theory here.

I wonder if it could be due to the avideo.log being stupid huge? 42GB is ... a lot of log

```
ubuntu@pyron:/var/www/html/conspyre.tv/videos$ ls -lsh *.log
42G -rw-r--r-- 1 ubuntu ubuntu 42G Apr 24 01:00 avideo.log
```

I removed the contents of the avideo.log and ran the video through the transcoder two more times. The result is Broken Missing Files two more times. The avideo.log file is still empty.

Not sure what to do at this point.

**Comment by DanielnetoDotCom** [comment]
For the same video should be multiple `sendToStreamer https://conspyre.tv/aVideoEncoder.json`

this one does not have the video

**Comment by walt93** [comment]
What do you suggest, Daniel?

Uploading all videos fails.

24 hours after erasing avideo.log, the file avideo.log is still empty.

Why does the site no longer emit logfiles, Daniel? That seems strange. There were 42GB in avideo.log and all I did was echo "" > avideo.log to erase the contents. Also, that logfile had current timestamps to 24 hours before the encoder (you can check the pastebins above). Why did my avideo site stop logging ≈48 hours ago?

**Comment by DanielnetoDotCom** [comment]
1. delete your encoder and streamer logs
2. encode only 1 video
3. once it is complete share both logs (complete)

**Comment by walt93** [comment]
Encoder:
$ tail avideo.log
[25-Apr-2024 18:21:47 UTC] sendToStreamer to objects/aVideoEncoderNotifyIsDone.json.php
[25-Apr-2024 18:21:48 UTC] Encoder::save id=(496) title=(Redpill Drifter - 9 WARNING SIGNS YOU MAY HAVE PARASITES  Many of the symptoms you may be feeling could, in fact, be parasites. Mainstream pharma shill Doctors do not want you to know because it can be treated naturally.  Also, check out @TheParasiteGuy ) streamers_id=1
[25-Apr-2024 18:21:48 UTC] sendToStreamer spectrumimage not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer rawVideo not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer image not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer gifimage not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer webpimage not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer video not set
[25-Apr-2024 18:21:48 UTC] sendToStreamer https://conspyre.tv/objects/aVideoEncoderNotifyIsDone.json.php in 0.214 seconds {"error":false,"target":"objects\/aVideoEncoderNotifyIsDone.json.php","postFields":{"fail":0,"streamers_id":"1","user":"Conspyre","pass":"_user_hash_Sm1jRnNMdnlQNTVDS3lqUWJlTVVsMm5GZGhrRy9rQVE1RXU3QmxZMkFDd3JFcVFXYXRXZk5uRE9kVkpEY0drR3JDdG5ueW10dXhqeUZBSW1JeUpBOXc9PQ==","return_vars":"{\"videos_id\":18395,\"video_id_hash\":\"NG93YkkvOTdoVDQvWUxSZzJZeEUrRGhkaU9HSEFnellURHBQTmdzUTBWST0=\",\"releaseDate\":\"2024-04-25 11:20\"}","releaseDate":"2024-04-25 11:20","releaseTime":1714044000,"videos_id":18395,"video_id_hash":"NG93YkkvOTdoVDQvWUxSZzJZeEUrRGhkaU9HSEFnellURHBQTmdzUTBWST0=","timezone":"UTC"},"response_raw":"{\"error\":false,\"video_id\":18395}","response":{"error":false,"video_id":18395}}
[25-Apr-2024 18:21:48 UTC] Encoder::save id=(496) title=(Redpill Drifter - 9 WARNING SIGNS YOU MAY HAVE PARASITES  Many of the symptoms you may be feeling could, in fact, be parasites. Mainstream pharma shill Doctors do not want you to know because it can be treated naturally.  Also, check out @TheParasiteGuy ) streamers_id=1

Streamer:
ubuntu@pyron:/var/www/html/conspyre.tv/videos$ cat avideo.log

[24-Apr-2024 20:00:03 America/Lima] AVideoLog::ERROR: Socket server For better performance install PDO SQLite in your PHP SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[24-Apr-2024 20:00:03 America/Lima] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[24-Apr-2024 20:00:03 America/Lima] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php:184
Stack trace:
#0 /var/www/html/conspyre.tv/vendor/react/socket/src/Server.php(77): React\Socket\TcpServer->__construct()
#1 /var/www/html/conspyre.tv/plugin/YPTSocket/server.php(166): React\Socket\Server->__construct()
#2 {main}
  thrown in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php on line 184
[24-Apr-2024 20:00:04 America/Lima] AVideoLog::ERROR: Socket server For better performance install PDO SQLite in your PHP SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[24-Apr-2024 20:00:04 America/Lima] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[24-Apr-2024 20:00:04 America/Lima] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php:184
Stack trace:
#0 /var/www/html/conspyre.tv/vendor/react/socket/src/Server.php(77): React\Socket\TcpServer->__construct()
#1 /var/www/html/conspyre.tv/plugin/YPTSocket/server.php(166): React\Socket\Server->__construct()
#2 {main}
  thrown in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php on line 184
[25-Apr-2024 08:40:07 America/Lima] AVideoLog::ERROR: Socket server For better performance install PDO SQLite in your PHP SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[25-Apr-2024 08:40:07 America/Lima] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/conspyre.tv/plugin/YPTSocket/server.php
[25-Apr-2024 08:40:07 America/Lima] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php:184
Stack trace:
#0 /var/www/html/conspyre.tv/vendor/react/socket/src/Server.php(77): React\Socket\TcpServer->__construct()
#1 /var/www/html/conspyre.tv/plugin/YPTSocket/server.php(166): React\Socket\Server->__construct()
#2 {main}
  thrown in /var/www/html/conspyre.tv/vendor/react/socket/src/TcpServer.php on line 184

**Comment by walt93** [comment]
Daniel, those are the logs from the streamer and the encoder. I'm uploading them to pastebin *with* the commands and directories so you may see that this is the case.

Here is the encoder: https://pastebin.com/gT0i44tT
Here is the streamer: https://pastebin.com/whccLwU2

The streamer is NOT picking up the encode. This is the encoder which is configured for the streamer. I do not know what is wrong.

Screenshot showing that prometheus.conspyre.tv is the encoder configured (we only have one)
![Screenshot 2024-04-25 at 12 51 46 PM](https://github.com/WWBN/AVideo/assets/11711050/213471fa-0066-4e04-90d6-68947cbed01b)

I have updates which need to go out for my Roku channel but am completely blocked until I can make my streamer site accept new files.

**Comment by DanielnetoDotCom** [comment]
What do you mean "The streamer is NOT picking up the encode."?

**Comment by walt93** [comment]
Daniel, that solved the issue. I did the chmod 777, encoded the video, and it worked.

Health check is solid green (I didn't check it before the chmod - perhaps it showed something? and that is where I need to check first when something happens… noted!)
