### ISSUE TITLE
Cannot upload video from Youtube

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#9014]
Daniel,
I have a bug when I tried to upload video from Youtube. This happen after the last version update. Here is the error message I am receiving below

Sorry!
WARNING: [youtube] YouTube said: ERROR - Precondition check failed., WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)..., WARNING: [youtube] YouTube said: ERROR - Precondition check failed., WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)..., WARNING: [youtube] YouTube said: ERROR - Precondition check failed., WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)..., WARNING: [youtube] YouTube said: ERROR - Precondition check failed., WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by ); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U, WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-sigfuncs/js_652ba3a2_110.json' failed: Traceback (most recent call last):, File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 44, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/652ba3a2.json' failed: Traceback (most recent call last):, File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 44, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , WARNING: [youtube] aNB3q9OuaPY: nsig extraction failed: You may experience throttling for some formats, Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html, n = udYjqYJ2FB6jHlhPdd ; player = https://www.youtube.com/s/player/652ba3a2/player_ias.vflset/en_US/base.js, WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/652ba3a2.json' failed: Traceback (most recent call last):, File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 44, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , WARNING: [youtube] aNB3q9OuaPY: nsig extraction failed: You may experience throttling for some formats, Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html, n = JCFfyfl9FTPEAJED3Q ; player = https://www.youtube.com/s/player/652ba3a2/player_ias.vflset/en_US/base.js, WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-sigfuncs/js_652ba3a2_106.json' failed: Traceback (most recent call last):, File "/usr/local/bin/yt-dlp/yt_dlp/cache.py", line 44, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , ERROR: [youtube] aNB3q9OuaPY: Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

**Comment by DanielnetoDotCom** [comment]
Try to fix this first

`Permission denied: '/var/www/.cache',`
