### ISSUE TITLE
Some day could we give some love to the "Organize Program" feature? It has many long standing issues and is unreliable.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9210]
**Describe the bug**
There are a number of long standing issues with the "Organize Program" feature, and some new issues which have crept in over the last year.

(1) Removing a video from a program is not reliable.

**To Reproduce**
1. Go to Organize Program
2. Click on any program you've created
3. Remove some videos from the program
4. Close and re-open the program
5. Observe that some, but not all of the videos you removed, have actually been removed.

**Expected behavior**
Removing a program to work 100% of the time.

------------------------------------------------------------------------------------------------------------
(2) Re-ordering a video within a program is not reliable, and only works some of the time.
** To Reproduce **
Repeat above steps 1-6 replacing "remove program" with "drag video into a new position"

**Expected behavior**
Re-ordering a program to work reliably and consistently.

------------------------------------------------------------------------------------------------------------
(3) Deleting a program from the programs list does not work. The program remains after being deleted.

**To Reproduce**
1. Go to Organize Program
2. Delete a program
3. Re-load the programs list
4. Observe the program still exists

**Expected behavior**
Deleting a program, should.

------------------------------------------------------------------------------------------------------------
(4) Programs list contains "phantom duplicates" [NEW]

Programs appear to have "phantoms" which exist only to occupy screen real estate. The appear to have their
own unique IDs but were not created by the user (except, as a "side-effect" of creating the program)

Take a look at this example. I just created the program "NXIVM" and added some media to it. Now there are
two phantom programs "NXIVM" which just occupy space. If you try to delete the phantom programs, nothing 
happens (this holds true for any program - delete simply does not work).

![Screenshot 2024-07-13 at 10 27 48 AM](https://github.com/user-attachments/assets/7c1b22a2-df05-439f-a7d8-764f24523cf6)

------------------------------------------------------------------------------------------------------------
(5) Adding new media to a program is adding to the end of the list

We specifically discussed this ≈2 years ago, and we had you specifically fix this behavior so that new programs add to the head of the program. This is the correct behavior on Roku. New programs appear at the left end (head) of the list.

For reasons unknown to me (another user wants it the other way, I assume), the behavior is now inverted, on adding any new video we have to go into the program editor and re-order the list. Now **all workflows** are hitting the program re-ordering bug. **_This leads to editing the same list over, and over, and over, and over until all changes "take"._**

------------------------------------------------------------------------------------------------------------
(6) Programs list has an irregular number of rows and columns.

Loading the programs list, we get three rows, with rows 1 & 2 having 4 columns, and row 3 having 2 columns.

???

![Screenshot 2024-07-13 at 10 40 10 AM](https://github.com/user-attachments/assets/51e7a3e9-8b52-4118-989d-7b8752e594e5)

It seems worth noting, that as we page through, each page gets its own "phantoms". Page 2 gets duplicates of 74478 Energy From The Vacuum at ids 190073 and 190073

![Screenshot 2024-07-13 at 10 56 37 AM](https://github.com/user-attachments/assets/75795701-93de-45d3-9278-4253b0011720)

Let's check those database ids to see if the "phantoms" exist or not.

```
mysql> select * from playlists where name = "NXIVM";
+--------+-------+---------------------+---------------------+----------+--------+----------+-----------------+
| id     | name  | created             | modified            | users_id | status | showOnTV | showOnFirstPage |
+--------+-------+---------------------+---------------------+----------+--------+----------+-----------------+
| 190006 | NXIVM | 2024-07-09 23:53:34 | 2024-07-09 23:53:34 |        1 | public |        0 |               0 |
+--------+-------+---------------------+---------------------+----------+--------+----------+-----------------+
1 row in set (0.02 sec)

mysql> select * from playlists where name = "Energy From The Vacuum";
+-------+------------------------+---------------------+---------------------+----------+--------+----------+-----------------+
| id    | name                   | created             | modified            | users_id | status | showOnTV | showOnFirstPage |
+-------+------------------------+---------------------+---------------------+----------+--------+----------+-----------------+
| 74478 | Energy from the Vacuum | 2022-10-04 20:13:21 | 2022-10-04 20:13:21 |        1 | public |        0 |               0 |
+-------+------------------------+---------------------+---------------------+----------+--------+----------+-----------------+
1 row in set (0.02 sec)
```

So I guess it's a presentation layer bug.

**Comment by DanielnetoDotCom** [comment]
for 1, 2 and 3 if you clear the cache does it resolves?

for the 4 and 6, are you runing the latest git pull?
I remember fixing a similar issue about a month ago

for 5, I may need to create a custom option for that. some users wants at the end and some want at the begin

**Comment by walt93** [comment]
It is entirely unclear if resolving the cache helps or not, but yes, every time I go to make a change to the program, I typically clear the cache before opening the program again. 

I probably did not pull this recent update ... checking it now ... 

The update went terribly. There was a very strange conflict in Git that had me removing entire directories to get the pull to take. Now that I'm 100% in sync (running "git status" is clean) the site is completely down.

---

```
array(4) { ["type"]=> int(1) ["message"]=> string(681) "Uncaught Error: Failed opening required '/var/www/html/conspyre.tv/plugin/CustomizeUser/Objects/Categories_has_users_groups.php' (include_path='.:/usr/share/php') in /var/www/html/conspyre.tv/plugin/CustomizeUser/CustomizeUser.php:9 Stack trace: #0 /var/www/html/conspyre.tv/plugin/AVideoPlugin.php(399): require_once() #1 /var/www/html/conspyre.tv/plugin/AVideoPlugin.php(776): AVideoPlugin::loadPlugin() #2 /var/www/html/conspyre.tv/objects/include_config.php(236): AVideoPlugin::getStart() #3 /var/www/html/conspyre.tv/videos/configuration.php(48): require_once('...') #4 /var/www/html/conspyre.tv/plugin/PlayLists/managerPlaylists.php(4): require_once('...') #5 {main} thrown" ["file"]=> string(64) "/var/www/html/conspyre.tv/plugin/CustomizeUser/CustomizeUser.php" ["line"]=> int(9) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(681) "Uncaught Error: Failed opening required '/var/www/html/conspyre.tv/plugin/CustomizeUser/Objects/Categories_has_users_groups.php' (include_path='.:/usr/share/php') in /var/www/html/conspyre.tv/plugin/CustomizeUser/CustomizeUser.php:9
Stack trace:
#0 /var/www/html/conspyre.tv/plugin/AVideoPlugin.php(399): require_once()
#1 /var/www/html/conspyre.tv/plugin/AVideoPlugin.php(776): AVideoPlugin::loadPlugin()
#2 /var/www/html/conspyre.tv/objects/include_config.php(236): AVideoPlugin::getStart()
#3 /var/www/html/conspyre.tv/videos/configuration.php(48): require_once('...')
#4 /var/www/html/conspyre.tv/plugin/PlayLists/managerPlaylists.php(4): require_once('...')
#5 {main}
  thrown"
  ["file"]=>
  string(64) "/var/www/html/conspyre.tv/plugin/CustomizeUser/CustomizeUser.php"
  ["line"]=>
  int(9)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by DanielnetoDotCom** [comment]
Is it after full update?

I have no idea where this error comes from

Try to make sure you reset your version 


`sudo git fetch --all && sudo git reset --hard origin/master`
