### ISSUE TITLE
Error with the encoder

### ISSUE THREAD

**Issue by AlexVinet** [WWBN/AVideo#9333]
**Describe the question**
Hi,

I'm trying to upload a video using the "Encode video and audio", but I got an error:

**Here's a few logs from AVideo:**

 [13-Aug-2024 22:50:56 America/New_York] AVideoLog::DEBUG:      writeSql [1048] Column 'order' cannot be null  [{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":403,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":636,"function":"save","class":"ObjectYPT","type":"->"},{"file":"\/var\/www\/html\/AVideo\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php","line":775,"function":"save","class":"Video","type":"->"},{"file":"\/var\/www\/html\/AVideo\/plugin\/CustomizeAdvanced\/CustomizeAdvanced.php","line":719,"function":"setRedirectVideo","class":"CustomizeAdvanced","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":1963,"function":"saveVideosAddNew","class":"CustomizeAdvanced","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/videoAddNew.json.php","line":255,"function":"saveVideosAddNew","class":"AVideoPlugin","type":"::"}] SCRIPT_NAME: /objects/videoAddNew.json.php
 [13-Aug-2024 22:50:56 America/New_York] AVideoLog::DEBUG:      Video::save Error : (0)  SCRIPT_NAME: /objects/videoAddNew.json.php
 [13-Aug-2024 22:50:56 America/New_York] AVideoLog::DEBUG:      onNewVideo error $insert_row is empty SCRIPT_NAME: /objects/videoAddNew.json.php

[13-Aug-2024 22:50:56 America/New_York] AVideoLog::ERROR:      ObjectYPT::Error on save 2: [0,0,1,"66bc1b901e532","00:00:00",0,"{\"doNotShowAdsOnThisVideo\":false}","video_240813225056_ve742",0,0,0,0,0,0,0,"a","66bc1b901e532","video",1,"",0,1] SCRIPT_NAME: /objects/videoAddNew.json.php

**Here's the logs from the server (AVdeo and AVideo-Encoder tailed):**

[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] downloadFile: start queue_id = 3  url = http://*************/Encoder/videos/original_SampleVideo1280x72010mb_YPTuniqid_66bc18422bf4b9.26375844 pathFileName = /var/www/html/AVideo/Encoder/videos/3_tmpFile.mp4
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] downloadFile: not using getYoutubeDl
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] downloadFile: this file was uploaded from file and thus is in the videos
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] downloadFile: downloadedFile = /var/www/html/AVideo/Encoder/videos/original_SampleVideo1280x72010mb_YPTuniqid_66bc18422bf4b9.26375844 | url = http://************/Encoder/videos/original_SampleVideo1280x72010mb_YPTuniqid_66bc18422bf4b9.26375844
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getVideoFile start(http://***************/Encoder/videos/original_SampleVideo1280x72010mb_YPTuniqid_66bc18422bf4b9.26375844, 3, /var/www/html/AVideo/Encoder/videos/original_SampleVideo1280x72010mb_YPTuniqid_66bc18422bf4b9.26375844, /var/www/html/AVideo/Encoder/videos/3_tmpFile.mp4)
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getVideoFile done 10.01MB
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] setDownloadedFileName(/var/www/html/AVideo/Encoder/videos/3_tmpFile.mp4) [{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":618,"function":"setDownloadedFileName","class":"Encoder","type":"->"},{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":1160,"function":"downloadFile","class":"Encoder","type":"::"},{"file":"\/var\/www\/html\/AVideo\/Encoder\/view\/run.php","line":7,"function":"run","class":"Encoder","type":"::"}]
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] downloadFile: {"error":false,"filename":"3_tmpFile.mp4","pathFileName":"\/var\/www\/html\/AVideo\/Encoder\/videos\/3_tmpFile.mp4","msg":"We downloaded the file with success"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Original filesize is 10.01MB
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::setStatus(downloaded) [{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":643,"function":"setStatus","class":"Encoder","object":{},"type":"->","args":["downloaded"]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":633,"function":"setDownloaded","class":"Encoder","type":"::","args":["3","\/var\/www\/html\/AVideo\/Encoder\/videos\/3_tmpFile.mp4"]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":1160,"function":"downloadFile","class":"Encoder","type":"::","args":["3"]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/view\/run.php","line":7,"function":"run","class":"Encoder","type":"::","args":[]}]
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] queue: Encoder::sendFile done line=2808 {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::sendFile videos_id=0, format=mp4
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::sendFile sending file to aVideoEncoder.json from
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer to aVideoEncoder.json
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer spectrumimage not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer rawVideo not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer image not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer gifimage not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer webpimage not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer video not set
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] sendToStreamer http://*****************/aVideoEncoder.json in 0.037 seconds {"error":false,"target":"aVideoEncoder.json","postFields":{"duration":"EE:EE:EE","title":"SampleVideo_1280x720_10mb","first_request":1,"categories_id":0,"format":"mp4","resolution":"","videoDownloadedLink":"","description":"","downloadURL":"","chunkFile":"","encoderURL":"http:\/\/10.245.223.104\/Encoder\/","keepEncoding":"0","streamers_id":"1","user":"admin","pass":"_user_hash_TCtTOFA3MVQvOG9pcldUS3k4dCtQMW5HaEdGYkJ1aFpSNW9oeGh3b3cwTzFKVmFGS0VBMkN4aWZtV1QrdGJlZGh0WU9YcE40SC8zcEh0VUc4MTl4a2c9PQ==","return_vars":"{\"videos_id\":0,\"video_id_hash\":\"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=\",\"releaseDate\":\"2024-08-13 22:35:00\"}","releaseDate":"2024-08-13 22:35:00","releaseTime":1723588500,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","timezone":"UTC"},"response_raw":"{\"error\":false,\"video_id\":false,\"video_id_hash\":\"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=\",\"releaseDate\":\"2024-08-13 22:35:00\",\"releaseTime\":\"1723588500\"}","response":{"error":false,"video_id":false,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00","releaseTime":"1723588500"}}
[14-Aug-2024 02:36:50 UTC] queue: Encoder::sendFile done line=2820
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] setStatusError(3, We could not get videos_id check the streamer logs, 1) [{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":1257,"function":"setStatusError","class":"Encoder","type":"::","args":["3","We could not get videos_id check the streamer logs",1]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/view\/run.php","line":7,"function":"run","class":"Encoder","type":"::","args":[]}]
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::setStatus(error) [{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":989,"function":"setStatus","class":"Encoder","object":{},"type":"->","args":["error"]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/objects\/Encoder.php","line":1257,"function":"setStatusError","class":"Encoder","type":"::","args":["3","We could not get videos_id check the streamer logs",1]},{"file":"\/var\/www\/html\/AVideo\/Encoder\/view\/run.php","line":7,"function":"run","class":"Encoder","type":"::","args":[]}]
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] Encoder::save id=(3) title=(SampleVideo_1280x720_10mb) streamers_id=1
[14-Aug-2024 02:36:50 UTC] [2024-08-14 02:36:50] getReturn_vars {"videos_id":0,"video_id_hash":"TWdpSHJpN0JTaCtxaXEwZmQyRStmN2ZjdFpKSzJlcW1XdFFxc21sVHRaQT0=","releaseDate":"2024-08-13 22:35:00"}

Can you please help.

Thank you.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
can you please check this?

https://github.com/WWBN/AVideo/issues/8441#issuecomment-1723276539

**Comment by AlexVinet** [comment]
The videos table doesn't exist.

**Comment by AlexVinet** [comment]
Seems it worked. Thank you.

**Comment by AlexVinet** [comment]
BY any chance, do you know how I can solve my update issue?

You are running AVideo version 12.0!
array(4) { ["type"]=> int(1) ["message"]=> string(201) "Uncaught mysqli_sql_exception: Duplicate column name 'epg_link' in /var/www/html/AVideo/view/update.php:141 Stack trace: #0 /var/www/html/AVideo/view/update.php(141): mysqli->query() #1 {main} thrown" ["file"]=> string(36) "/var/www/html/AVideo/view/update.php" ["line"]=> int(141) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(201) "Uncaught mysqli_sql_exception: Duplicate column name 'epg_link' in /var/www/html/AVideo/view/update.php:141
Stack trace:
#0 /var/www/html/AVideo/view/update.php(141): mysqli->query()
#1 {main}
  thrown"
  ["file"]=>
  string(36) "/var/www/html/AVideo/view/update.php"
  ["line"]=>
  int(141)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
