### ISSUE TITLE
Unable to remove users – error: Internal Server Error

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#9343]
**Describe the bug**
When I try to remove users, an internal server error message appears. I am currently using the latest version of AVideo (14.4).

**Error Logs**
[19-Aug-2024 00:07:51 America/New_York] AVideoLog::ERROR:      {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'outreach-avideo-research.live_transmition_history_log' doesn't exist in \/var\/www\/vhosts\/site.com\/html\/research\/research-avideo\/objects\/mysql_dal.php:137\nStack trace:\n#0 \/var\/www\/vhosts\/site.com\/html\/research\/research-avideo\/objects\/mysql_dal.php(137): mysqli->prepare()\n#1 \/var\/www\/vhosts\/site.com\/html\/research\/research-avideo\/objects\/user.php(1096): sqlDAL::writeSql()\n#2 \/var\/www\/vhosts\/site.com\/html\/research\/research-avideo\/plugin\/CustomizeUser\/confirmDeleteUser.json.php(48): User->delete()\n#3 {main}\n  thrown","file":"\/var\/www\/vhosts\/site.com\/html\/research\/research-avideo\/objects\/mysql_dal.php","line":137} SCRIPT_NAME: /plugin/CustomizeUser/confirmDeleteUser.json.php

**Desktop (please complete the following information):**
 - OS: Mac 12.7.6
 - Browser: Firefox Developer Edition, Chrome
 - Version 130.0b6 (64-bit), Version 127.0.6533.120

Any help would be most appreciated. Thanks so much.

**Comment by DanielnetoDotCom** [comment]
Hi, please install all the plugins missing tables, even the ones you are not using.
