### ISSUE TITLE
Pulled latest from Github. Update fails with error: SQL duplicate column "isChannelSuggested"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9359]
**Describe the bug**
Update database tables fails after recent pull from Github.

**To Reproduce**
1. Do a git pull
2. Do an update
3. Observe that the update fails
4. Share error on GItHub (https://github.com/WWBN/AVideo/issues/9359)

**Expected behavior**
Update not to fail

**Error Logs**
```
You are running AVideo version 14.4!
array(4) { ["type"]=> int(1) ["message"]=> string(221) "Uncaught mysqli_sql_exception: Duplicate column name 'isChannelSuggested' in /var/www/html/conspyre.tv/view/update.php:141 Stack trace: #0 /var/www/html/conspyre.tv/view/update.php(141): mysqli->query() #1 {main} thrown" ["file"]=> string(41) "/var/www/html/conspyre.tv/view/update.php" ["line"]=> int(141) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(221) "Uncaught mysqli_sql_exception: Duplicate column name 'isChannelSuggested' in /var/www/html/conspyre.tv/view/update.php:141
Stack trace:
#0 /var/www/html/conspyre.tv/view/update.php(141): mysqli->query()
#1 {main}
  thrown"
  ["file"]=>
  string(41) "/var/www/html/conspyre.tv/view/update.php"
  ["line"]=>
  int(141)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```
**Screenshots**
![Screenshot 2024-08-26 at 2 55 06 PM](https://github.com/user-attachments/assets/48a45fe8-c894-4b16-a4dd-e8c87f13be4d)

**Comment by DanielnetoDotCom** [comment]
What update number exactly was that?

**Comment by walt93** [comment]
14.4

I just noticed that it seems to have succeeded - I just reloaded the page to check the version and it looks good now.

Is there anything I can check to get you more information before I close this?

![Screenshot 2024-08-26 at 3 00 57 PM](https://github.com/user-attachments/assets/9ca1ec77-7d07-4902-8449-6cb008a4422a)

**Comment by DanielnetoDotCom** [comment]
I suspect you run the update twice that is why the error
