### ISSUE TITLE
[ERROR] Uncaught ValueError TCP/IP

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9451]
@DanielnetoDotCom Danny, I found this error that I hadn't seen before:

[29-Sep-2024 00:11:17 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught ValueError: TCP/IP option is not available for error logging in /var/www/html/AVideo/plugin/AVideoPlugin.php:405

**Comment by DanielnetoDotCom** [comment]
share more from your log

**Comment by gbrn** [comment]
@DanielnetoDotCom I didn't find much similar information. But I found this one interesting because I hadn't seen it before.

`[28-Sep-2024 22:51:22 UTC] AVideoLog::ERROR:      {"type":1,"message":"Uncaught ValueError: TCP/IP option is not available for error logging in /var/www/html/AVideo/plugin/AVideoPlugin.php:405\nStack trace:\n#0 /var/www/html/AVideo/plugin/AVideoPlugin.php(405): error_log()\n#1 /var/www/html/AVideo/plugin/Plugin.abstract.php(230): AVideoPlugin::loadPlugin()\n#2 /var/www/html/AVideo/plugin/AVideoPlugin.php(556): PluginAbstract->getDataObject()\n#3 /var/www/html/AVideo/plugin/AVideoPlugin.php(504): AVideoPlugin::getDataObject()\n#4 /var/www/html/AVideo/plugin/AVideoPlugin.php(580): AVideoPlugin::getObjectData()\n#5 /var/www/html/AVideo/locale/function.php(157): AVideoPlugin::getDataObjectIfEnabled()\n#6 /var/www/html/AVideo/locale/function.php(21): setSiteLang()\n#7 /var/www/html/AVideo/locale/function.php(10): includeLangFile()\n#8 /var/www/html/AVideo/plugin/Plugin.abstract.php(4): require_once('...')\n#9 /var/www/html/AVideo/objects/user.php(14): require_once('...')\n#10 /var/www/html/AVideo/objects/configuration.php(7): require_once('...')\n#11 /var/www/html/AVideo/objects/include_config.php(135): require_once('...')\n#12 /var/www/html/AVideo/videos/configuration.php(49): require_once('...')\n#13 /var/www/html/AVideo/plugin/WWBNIndex/WWBNIndex.php(5): require_once('...')\n#14 /var/www/html/AVideo/plugin/WWBNIndex/submitIndex.php(6): require_once('...')\n#15 {main}\n  thrown","file":"/var/www/html/AVideo/plugin/AVideoPlugin.php","line":405} SCRIPT_NAME: /plugin/WWBNIndex/submitIndex.php`


`[29-Sep-2024 00:11:17 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught ValueError: TCP/IP option is not available for error logging in /var/www/html/AVideo/plugin/AVideoPlugin.php:405\nStack trace:\n#0 /var/www/html/AVideo/plugin/AVideoPlugin.php(405): error_log()\n#1 /var/www/html/AVideo/plugin/Plugin.abstract.php(230): AVideoPlugin::loadPlugin()\n#2 /var/www/html/AVideo/plugin/AVideoPlugin.php(556): PluginAbstract->getDataObject()\n#3 /var/www/html/AVideo/plugin/AVideoPlugin.php(504): AVideoPlugin::getDataObject()\n#4 /var/www/html/AVideo/plugin/AVideoPlugin.php(580): AVideoPlugin::getObjectData()\n#5 /var/www/html/AVideo/locale/function.php(157): AVideoPlugin::getDataObjectIfEnabled()\n#6 /var/www/html/AVideo/locale/function.php(21): setSiteLang()\n#7 /var/www/html/AVideo/locale/function.php(10): includeLangFile()\n#8 /var/www/html/AVideo/plugin/Plugin.abstract.php(4): require_once('...')\n#9 /var/www/html/AVideo/objects/user.php(14): require_once('...')\n#10 /var/www/html/AVideo/objects/configuration.php(7): require_once('...')\n#11 /var/www/html/AVideo/objects/include_config.php(135): require_once('...')\n#12 /var/www/html/AVideo/videos/configuration.php(49): require_once('...')\n#13 /var/www/html/AVideo/plugin/WWBNIndex/WWBNIndex.php(5): require_once('...')\n#14 /var/www/html/AVideo/plugin/WWBNIndex/submitIndex.php(6): require_once('...')\n#15 {main}\n  thrown","file":"/var/www/html/AVideo/plugin/AVideoPlugin.php","line":405} SCRIPT_NAME: /plugin/WWBNIndex/submitIndex.php`

**Comment by DanielnetoDotCom** [comment]
can you please check this update?
