### ISSUE TITLE
Encoder - Cannot authenticate youtube account to download videos. Authorise screen keeps disappearing

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#9462]
hi 

Trying to authenticate my youtube video account to download videos but the login options does not stay on the screen. It disappears straightaway. 
Please advise.

Checked logfile and it shows this:-

[04-Oct-2024 11:54:38 Europe/London] AVideoLog::ERROR:      {"type":1,"message":"Uncaught Error: Class \"PlayLists\" not found in \/var\/www\/html\/AVideo\/objects\/playlist.php:996\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/playlist.php(266): PlayList->save()\n#1 \/var\/www\/html\/AVideo\/objects\/playlists.json.php(20): PlayList::getAllFromUser()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/playlist.php","line":996} SCRIPT_NAME: /objects/playlists.json.php

**Comment by DanielnetoDotCom** [comment]
Please check this update, this may fix the `Uncaught Error: Class "PlayLists" not found `

but the authentication should be something else.  check your logs and also the js console

**Comment by kollossus55** [comment]
Sorry where are you referring to regarding uncaught error.

Will double check logs.. what is js console ? Not familiar with that...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by DanielnetoDotCom** [comment]
screencapture all your browser window when the error happens

https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

**Comment by kollossus55** [comment]
![youtube encoder problem](https://github.com/user-attachments/assets/0fe8178a-93b8-43a0-9858-9afcf015f132)

Screencaptured

**Comment by kollossus55** [comment]
In logfile last entry:-
=====================================
 [04-Oct-2024 17:21:58 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: done videos_id=481 path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.vtt SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:58 Europe/London] AVideoLog::DEBUG:      transcribe subtitle:  exec vosk-transcriber -i 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3'  -t srt -o 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt' > 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt.log' 2>&1 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:58 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: SRT will be created srtFile=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt mp3File=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 16:21:58 UTC] AVideoLog::DEBUG:      Return value: 0 SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:58 UTC] AVideoLog::DEBUG:      Command output: [] SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:58 UTC] AVideoLog::DEBUG:      execAsync Linux: nohup sh -c "/usr/bin/php path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php 481 & echo \$!" > /dev/null 2>&1 & SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:58 UTC] AVideoLog::DEBUG:      convertVideoToMP3FileIfNotExists: start videos_id=481 try=0  SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 17:21:40 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: done videos_id=481 path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.vtt SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:40 Europe/London] AVideoLog::DEBUG:      transcribe subtitle:  exec vosk-transcriber -i 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3'  -t srt -o 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt' > 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt.log' 2>&1 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:40 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: SRT will be created srtFile=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt mp3File=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 16:21:39 UTC] AVideoLog::DEBUG:      Return value: 0 SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:39 UTC] AVideoLog::DEBUG:      Command output: [] SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:39 UTC] AVideoLog::DEBUG:      execAsync Linux: nohup sh -c "/usr/bin/php path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php 481 & echo \$!" > /dev/null 2>&1 & SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:39 UTC] AVideoLog::DEBUG:      convertVideoToMP3FileIfNotExists: start videos_id=481 try=0  SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 17:21:37 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: done videos_id=411 path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.vtt SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:37 Europe/London] AVideoLog::DEBUG:      transcribe subtitle:  exec vosk-transcriber -i 'path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.mp3'  -t srt -o 'path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.srt' > 'path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.srt.log' 2>&1 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:37 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: SRT will be created srtFile=path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.srt mp3File=path/to/my/streamer/site/videos/video_230328160532_v6f6f/video_230328160532_v6f6f.mp3 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 16:21:37 UTC] AVideoLog::DEBUG:      Return value: 0 SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:37 UTC] AVideoLog::DEBUG:      Command output: [] SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:37 UTC] AVideoLog::DEBUG:      execAsync Linux: nohup sh -c "/usr/bin/php path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php 411 & echo \$!" > /dev/null 2>&1 & SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:37 UTC] AVideoLog::DEBUG:      convertVideoToMP3FileIfNotExists: start videos_id=411 try=0  SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 17:21:20 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: done videos_id=481 path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.vtt SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:20 Europe/London] AVideoLog::DEBUG:      transcribe subtitle:  exec vosk-transcriber -i 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3'  -t srt -o 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt' > 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt.log' 2>&1 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:20 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: SRT will be created srtFile=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt mp3File=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 16:21:20 UTC] AVideoLog::DEBUG:      Return value: 0 SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:20 UTC] AVideoLog::DEBUG:      Command output: [] SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:20 UTC] AVideoLog::DEBUG:      execAsync Linux: nohup sh -c "/usr/bin/php path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php 481 & echo \$!" > /dev/null 2>&1 & SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 16:21:20 UTC] AVideoLog::DEBUG:      convertVideoToMP3FileIfNotExists: start videos_id=481 try=0  SCRIPT_NAME: /view/modeYoutube.php
 [04-Oct-2024 17:21:01 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: done videos_id=481 path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.vtt SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:01 Europe/London] AVideoLog::DEBUG:      transcribe subtitle:  exec vosk-transcriber -i 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3'  -t srt -o 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt' > 'path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt.log' 2>&1 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php
 [04-Oct-2024 17:21:01 Europe/London] AVideoLog::DEBUG:      transcribe subtitle: SRT will be created srtFile=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.srt mp3File=path/to/my/streamer/site/videos/video_230417131628_v0ec9/video_230417131628_v0ec9.mp3 SCRIPT_NAME: path/to/my/streamer/site/plugin/SubtitleSwitcher/transcribe.php

**Comment by kollossus55** [comment]
https://www.awesomescreenshot.com/video/32284975?key=84142d5bae2934190d0c72bf829908c2

I have also included a bit of the log file in Encoder. 
Please advise....
===========================================
[17-May-2024 15:37:31 UTC] PHP Warning:  unlink(/var/www/html/AVideo/Encoder/videos/youphptube.log): No such file or directory in /root/ue.php on line 98
[17-May-2024 15:37:31 UTC] PHP Notice:  ob_flush(): Failed to flush buffer. No buffer to flush in /root/ue.php on line 117
[17-May-2024 15:37:31 UTC] PHP Deprecated:  Creation of dynamic property Configuration::$id is deprecated in /var/www/html/AVideo/Encoder/objects/Object.php on line 20
[17-May-2024 15:37:31 UTC] PHP Deprecated:  Creation of dynamic property Configuration::$created is deprecated in /var/www/html/AVideo/Encoder/objects/Object.php on line 20
[17-May-2024 15:37:31 UTC] PHP Deprecated:  Creation of dynamic property Configuration::$modified is deprecated in /var/www/html/AVideo/Encoder/objects/Object.php on line 20
[17-May-2024 15:37:31 UTC] PHP Notice:  ob_flush(): Failed to flush buffer. No buffer to flush in /root/ue.php on line 123
[31-May-2024 20:36:05 UTC] PHP Warning:  Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/AVideo/Encoder/locale/function.php on line 31
[02-Jun-2024 23:13:27 UTC] PHP Warning:  Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/AVideo/Encoder/locale/function.php on line 31
[07-Jun-2024 06:55:05 UTC] PHP Warning:  Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/AVideo/Encoder/locale/function.php on line 31
[24-Jun-2024 13:19:13 Europe/London] logoff:: done session_id = q3en9falllm4r1bb7disb5puvl
[24-Jun-2024 13:19:14 Europe/London] login.json: Login::run
[24-Jun-2024 13:19:14 Europe/London] Login::run (admin, ***, https://kollossus.com/, true)
[24-Jun-2024 13:19:14 Europe/London] Login::run request login user (admin)
[24-Jun-2024 13:19:14 Europe/London] Login::run request login complete user (admin)
[24-Jun-2024 13:19:14 Europe/London] Login::run got an object
[24-Jun-2024 13:19:14 Europe/London] createIfNotExists:: admin
[24-Jun-2024 13:19:14 Europe/London] Verification Start https://kollossus.com/
[24-Jun-2024 13:19:14 Europe/London] Verification Creating the Cache https://kollossus.com/
[24-Jun-2024 13:19:15 Europe/London] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fkollossus.com%2F): {"msg":["https:\/\/kollossus.com\/ Site verified"],"isPrivate":false,"verified":true,"status":"a"}
[24-Jun-2024 13:19:15 Europe/London] Login:: almost done
[24-Jun-2024 13:19:15 Europe/London] Login:: done session_id = v3q9sf8boas8t25na9qr6b23jo session_login
[24-Jun-2024 12:19:32 UTC] PHP Warning:  Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/AVideo/Encoder/locale/function.php on line 31
[24-Jun-2024 12:19:32 UTC] PHP Warning:  Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/AVideo/Encoder/locale/function.php on line 31
[24-Jun-2024 15:05:27 Europe/London] [2024-06-24 15:05:27] Encoder::setStatus(queue) [{"file":"\/var\/www\/html\/AVideo\/Encoder\/view\/upload.php","line":59,"function":"setStatus","class":"Encoder","object":{},"type":"->","args":["queu>
[24-Jun-2024 15:05:27 Europe/London] Upload.php will let function decide decideFormatOrder
[24-Jun-2024 15:05:27 Europe/London] decideFormatOrder: {"file":"Matthew Henson -Who Was the First Person to Reach the North Pole.mp4","audioOnly":"false","spectrum":"false","webm":"false","override_status":"","videos_id":0,"update_vide>
[24-Jun-2024 15:05:27 Europe/London] decideFormatOrder: auto MP4
[24-Jun-2024 15:05:27 Europe/London] AVideo-Encoder Format::getFromOrder(7)

**Comment by DanielnetoDotCom** [comment]
Hi, you should also provide the console js log.

but are you sure one of your plugins is not closing that window?

there is no sense to make it autoclose.

**Comment by kollossus55** [comment]
which plugin would cause this ? I have no idea. I'm trying to create a site map for google indexing, but now there is problems doing this now. whats going on ?
Checked logfile=
================================
 [08-Oct-2024 09:51:12 Europe/London] AVideoLog::ERROR:      {"type":1,"message":"Uncaught Error: Class \"PlayLists\" not found in \/var\/www\/html\/AVideo\/objects\/playlist.php:996\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/playlist.php(266): PlayList->save()\n#1 \/var\/www\/html\/AVideo\/objects\/playlists.json.php(20): PlayList::getAllFromUser()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/playlist.php","line":996} SCRIPT_NAME: /objects/playlists.json.php

**Comment by DanielnetoDotCom** [comment]
You should make a git pull, the `Uncaught Error: Class "PlayLists"` was fixed some time ago

the authentication window close, is something else.

try an  icognito browser.

**Comment by kollossus55** [comment]
Hi

Yes that worked!.. So its some plugin stopping the window.

Will check all..

Thanks
________________________________

**Comment by kollossus55** [comment]
Will close this issue. Workaround of incognito until I find out the plugin causing issue..
