### ISSUE TITLE
[Plugin Rebroadcaster + PlayLists + VideoHLS] ERROR Playlist

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9585]
@DanielnetoDotCom Danny, I'm running tests to use the Rebroadcaster plugin. From what I understand, this plugin works dependently on the PlayLists and VideoHLS plugins.

When I click PLAY, it displays the error below:
![image](https://github.com/user-attachments/assets/1d306dca-2e84-4e59-b9d4-126bea4889b5)

ERROR:
```
array(4) { ["type"]=> int(1) ["message"]=> string(488) "Uncaught ArgumentCountError: Too few arguments to function VideoHLS::getToken(), 0 passed in /var/www/html/AVideo/plugin/PlayLists/PlayListElement.php on line 166 and exactly 1 expected in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(18) : eval()'d code(1) : eval()'d code:377 Stack trace: #0 /var/www/html/AVideo/plugin/PlayLists/PlayListElement.php(166): VideoHLS::getToken() #1 /var/www/html/AVideo/plugin/PlayLists/embed.php(121): playListSource->__construct() #2 {main} thrown" ["file"]=> string(88) "/var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(377) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(488) "Uncaught ArgumentCountError: Too few arguments to function VideoHLS::getToken(), 0 passed in /var/www/html/AVideo/plugin/PlayLists/PlayListElement.php on line 166 and exactly 1 expected in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(18) : eval()'d code(1) : eval()'d code:377
Stack trace:
#0 /var/www/html/AVideo/plugin/PlayLists/PlayListElement.php(166): VideoHLS::getToken()
#1 /var/www/html/AVideo/plugin/PlayLists/embed.php(121): playListSource->__construct()
#2 {main}
  thrown"
  ["file"]=>
  string(88) "/var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(18) : eval()'d code(1) : eval()'d code"
  ["line"]=>
  int(377)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

ArgumentCountError, which indicates that the VideoHLS::getToken() function is being called with no arguments, but is defined to receive a required argument.

**Comment by gbrn** [comment]
@DanielnetoDotCom The reported errors are now resolved. I continue testing the Rebroadcaster Plugin.
