### ISSUE TITLE
Direct upload problem

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#9677]
Hi, when i open direct upload it just continues loading and never finished so i cannot use it. The error showing in avideo log is below:

 [05-Dec-2024 23:24:12 Europe/London] AVideoLog::ERROR:      {"type":1,"message":"Uncaught Error: Class \"React\\Cache\\ArrayCache\" not found in \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/react\/dns\/src\/Resolver\/Factory.php:78\nStack trace:\n#0 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/react\/socket\/src\/Connector.php(108): React\\Dns\\Resolver\\Factory->createCached()\n#1 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/ratchet\/pawl\/src\/Connector.php(22): React\\Socket\\Connector->__construct()\n#2 \/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/ratchet\/pawl\/src\/functions.php(13): Ratchet\\Client\\Connector->__construct()\n#3 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/YPTSocket\/YPTSocket.php(184): Ratchet\\Client\\connect()\n#4 \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/functionsSocket.php(16): YPTSocket::send()\n#5 \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/functionsSocket.php(49): sendSocketMessage()\n#6 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/UserNotifications\/UserNotifications.php(136): sendSocketMessageToUsers_id()\n#7 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/UserNotifications\/UserNotifications.php(256): UserNotifications::notifySocket()\n#8 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code(671): UserNotifications::createNotification()\n#9 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code(131): Notifications->addBellNotificationToUsers()\n#10 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code(292): Notifications->addBellNotificationVideo()\n#11 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/Notifications\/Notifications.php(18) : eval()'d code(1) : eval()'d code(503): Notifications->sendVideoUploadEmails()\n#12 \/home\/myMySQLUser\/public_html\/myMySQLUser\/plugin\/AVideoPlugin.php(896): Notifications->onNewVideo()\n#13 \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/video.php(639): AVideoPlugin::onNewVideo()\n#14 \/home\/myMySQLUser\/public_html\/myMySQLUser\/objects\/videoAddNew.json.php(235): Video->save()\n#15 {main}\n  thrown","file":"\/home\/myMySQLUser\/public_html\/myMySQLUser\/vendor\/react\/dns\/src\/Resolver\/Factory.php","line":78} SCRIPT_NAME: /objects/videoAddNew.json.php

**Comment by DanielnetoDotCom** [comment]
I have never seen this error before, but I suspect you are not using Ubuntu or you have some kind of control panel 

It means it is not the standard installation, so the behavior is unpredictable

**Comment by para2022** [comment]
Its the notification plugin doing it somehow. Ive turned it off and now direct upload is working again.

**Comment by DanielnetoDotCom** [comment]
I can see is the notification but it is something specific in your environment configuration

**Comment by para2022** [comment]
Thanks Dan you were right i had a miss configured mail server would you believe. Ive rebuilt my AVideo server incase it was buggy. I guess i missed that out. Thanks for that mate.
