### ISSUE TITLE
Ant Media Server for the Web Rtc? 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#9727]
@DanielnetoDotCom 
How do we go about mating Ant Media Server on github into Avideo for our real time Web RTC?

**Comment by DanielnetoDotCom** [comment]
Hi, maybe in the future I do implement a WebRTC server.

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom do you see any issues with running this side by side so that I can serve out a VOD of the latest broadcasts to my live streams when they are not broadcasting?
it uses port 5280 and 1935. What if any would be  workaround on AVideo for 1935

**Comment by DanielnetoDotCom** [comment]
**🎉 Exciting News: You Can Now Livestream from Your Webpage!**  

Good news! I’ve added a new feature called the **WebRTC plugin** to AVideo. This makes livestreaming easier than ever. You can now go live directly from your webpage without needing any other software.  

### What Can It Do?  
- **Livestream with One Click**: Use your webcam to start a livestream directly from your webpage.  
- **No Extra Software Needed**: Everything happens right in your browser — no downloads required.  
- **Easy to Use**: Just enable the feature, and you’re ready to stream.  

### How to Get It:  
1. **Update Your AVideo**: Make sure your AVideo is updated to the latest version. (You or your tech helper can follow this guide: [[How to Update AVideo](https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform)](https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform)).  
2. **Update Your Plugins**: After updating AVideo, ensure your plugins are up to date.  

### Learn More:  
To find out more about this exciting feature, visit the [[WebRTC Plugin Wiki](https://github.com/WWBN/AVideo/wiki/WebRTC-plugin)](https://github.com/WWBN/AVideo/wiki/WebRTC-plugin).

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom when the webrtc plug-in is enabled  will it pass all rtmp traffic off to web rtc?

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/user-attachments/assets/55d56a36-9333-4ff5-af1e-f5514a9041f5)

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/user-attachments/assets/60a5d184-5893-4c4a-b7e9-3974d006b01a)

**Comment by DanielnetoDotCom** [comment]
![chrome-capture-2025-0-13 (3)](https://github.com/user-attachments/assets/0a49aaf5-8ebf-4f7b-8105-52b0dbeae9d6)

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull and check the server status in your plugins?

https://github.com/WWBN/AVideo/wiki/WebRTC-plugin#troubleshooting

**Comment by milehighkaraoke** [comment]
Ok before the git pull everything was active in here except the Premium Features. Now after pull only server file is active
![20250114_185531](https://github.com/user-attachments/assets/37ca034b-53be-4fa7-a850-96b8c0ea1735)

**Comment by DanielnetoDotCom** [comment]
Your server is disconnect. 

you you make another git pull and check again?

then try this https://github.com/WWBN/AVideo/wiki/WebRTC-plugin#forcing-stop-update-and-restart-of-the-webrtc-server

**Comment by milehighkaraoke** [comment]
Ok, this was the result 
![20250115_062636](https://github.com/user-attachments/assets/1dca4430-a97e-471b-8e51-886288e7a282)
![20250115_062833](https://github.com/user-attachments/assets/e8319798-69c9-4604-9dfa-7fbd3ca4ca9a)

**Comment by DanielnetoDotCom** [comment]
check the videos/WebRTC2RTMP.log file

also can you please try to manually run the WebRTC2RTMP?

just copy and paste this
`
/var/www/MHKTube/plugin/WebRTC/WebRTC2RTMP
`

**Comment by DanielnetoDotCom** [comment]
Hold on I will make an update now

**Comment by DanielnetoDotCom** [comment]
Please make a git pull and try this
```bash
cd /var/www/MHKTube/plugin/WebRTC/tools
php stop.php
php update.php
/var/www/MHKTube/plugin/WebRTC/WebRTC2RTMP
```

**Comment by DanielnetoDotCom** [comment]
Try in 2 min, I am still submiting the changes

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by milehighkaraoke** [comment]
Now it is working....
![20250115_095731](https://github.com/user-attachments/assets/9970e813-6fed-46b7-aa93-1c5a83cf95ec)

**Comment by milehighkaraoke** [comment]
This is working really nice. We are encoding and streaming as fast as Facebook now. Tested by watching a live streambfrom a patrons phone to  Facebook and my sites broadcast are within milliseconds of each other!!!!!

**Comment by baoang** [comment]
Is that we don't have to install nginx when trying webrtc mode? The only ports to open are 443 and 3000?

**Comment by DanielnetoDotCom** [comment]
nginx is the live server , it is required if you want to use WebRTC to livestream.

**Comment by baoang** [comment]
> nginx is the live server , it is required if you want to use WebRTC to livestream.

Thank you, Daniel. I thought not having to install other software meant only clicking the webrtc plugin is enough. Forgive my ignorance.

**Comment by baoang** [comment]
![Image](https://github.com/user-attachments/assets/f7b24acc-e59d-4b24-9cf2-9bb221a05be2)

`/var/www/html/AVideo/plugin/WebRTC/tools$ php forceAll.php`

```
Starting WebRTC Server
Searching for port: 3000
No Need to kill, port NOT found
WebRTC::checkAndUpdate: Required JSON file(s) missing. Skipping update.
Starting WebRTC Server
nc: connect to 127.0.0.1 port 3000 (tcp) failed: Connection refused
Port 3000 is not open, start the server
execAsync Linux: nohup sh -c "/var/www/html/AVideo/plugin/WebRTC/WebRTC2RTMP --port=3000 > /var/www/html/AVideo/videos/WebRTC2RTMP.log  & echo \$!" > /dev/null 2>&1 &
Command output: []
Return value: 0
```

so, what's that JSON file?

**Comment by baoang** [comment]
Hello, Daniel,

I ran `cd /var/www/html/AVideo/ && sudo git pull` to keep the files up to date.

I ran `cd /var/www/html/AVideo/plugin/WebRTC/tools && php forceAll.php` and got the following output (as illustrated in the [WebRTC plugin wiki](https://github.com/WWBN/AVideo/wiki/WebRTC-plugin#forcing-stop-update-and-restart-of-the-webrtc-server)) saying port 3000 connection refused.
```
Starting WebRTC Server
Searching for port: 3000
No Need to kill, port NOT found
WebRTC::checkAndUpdate: Required JSON file(s) missing. Skipping update.
Starting WebRTC Server
nc: connect to 127.0.0.1 port 3000 (tcp) failed: Connection refused
Port 3000 is not open, start the server
execAsync Linux: nohup sh -c "/var/www/html/AVideo/plugin/WebRTC/WebRTC2RTMP --port=3000 > /var/www/html/AVideo/videos/WebRTC2RTMP.log  & echo \$!" > /dev/null 2>&1 &
Command output: []
Return value: 0
```

But it seems the log file, WebRTC2RTMP.log, is a zero byte file, nothing written in it.

![Image](https://github.com/user-attachments/assets/2776fcdb-e004-45ea-8879-1be8d280ff7a)

I've checked the iptables firewall. `sudo iptables -I INPUT -p tcp --dport 3000 -j ACCEPT`

![Image](https://github.com/user-attachments/assets/b1c48e65-6604-49c5-acc6-a5a9b9897b39)

The RTMP part is working.

![Image](https://github.com/user-attachments/assets/f3124cce-eaf1-45eb-9e08-3ca0bd72cb62)

But the (WebRTC plugin) server status page always says server not connected, and shows no log file output.

![Image](https://github.com/user-attachments/assets/9a85ae6c-a11b-4ec7-852f-bec8c68c78a0)

When iptables shows port 3000 is open, the AVideo Health Check module tells this (WebRTC) port is not accessible, internally or externally.

![Image](https://github.com/user-attachments/assets/a924b333-1f04-4ec2-bef6-f4000a40c88f)

Is there something besides the firewall that blocked the accessibility of the port?

**Comment by DanielnetoDotCom** [comment]
'/etc/letsencrypt/live/'

Make sure you fix your ssl paths in the socket plugin

**Comment by baoang** [comment]
> '/etc/letsencrypt/live/'
> 
> Make sure you fix your ssl paths in the socket plugin

Thank you, Daniel, for quickly located the problem.

I have actually set a different location, like `/var/www/ssl/mydomain.tld.key` for **SSL Certificate Key File** column, and `/var/www/ssl/mydomain.tld.fullchain.cer` for **SSL Certificate File** column. These two files were uploaded and placed in the above directory, and were requested from Letsencrypt from another VPS (I am using acme.sh).

I'll try to move them to /etc/letsencrypt/live dir for a try.

**Comment by baoang** [comment]
tried to run `sudo /var/www/html/AVideo/plugin/WebRTC/WebRTC2RTMP --port=3000` and got the following output.

```
SSL files not found for domain "mydomain.tld". Ensure either:
1. The provided paths exist:
   - Key: undefined
   - Cert: D:/git/htdocs/AVideo/.compose/letsencrypt/live/vlu.me/fullchain.pem
2. Or valid files exist under /etc/letsencrypt/live/ matching "mydomain.tld*"
internal/fs/utils.js:652
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:490:10)
    at Object.openSync (pkg/prelude/bootstrap.js:793:32)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at Object.<anonymous> (/snapshot/obfuscated/combined.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
I've also tried ` sudo php forceAll.php` which produced the like output as before -- required json file missing something.

So my guess is as follows:
- my separately applied letsencrypt file is not pem format which could be a possible reason.
- the file may be corrupted as it says not mathing 'mydomain.tld'
- or the server provider blocked ports including 3000 and above to prevent p2p communication
I may find another server provider to see if the problem could be solved.

**Comment by DanielnetoDotCom** [comment]
I can see the Key: undefined

Cert seems to be correct but the key is not

check if this exists and the script can access it

/var/www/ssl/mydomain.tld.key

**Comment by baoang** [comment]
> I can see the Key: undefined
> 
> Cert seems to be correct but the key is not
> 
> check if this exists and the script can access it
> 
> /var/www/ssl/mydomain.tld.key

Thank you, Daniel.

![Image](https://github.com/user-attachments/assets/a0718da2-a69a-474c-9a93-84e56e6a5c21)

Finally all went green.

What I've done is go back and reinstall the whole server, making it fresh, Ubuntu 22 LTS.
Then git pull to make AVideo a fresh one, and almost everything from start-over.
Then finally follow your advice, the path fix. At first, it didn't work, and I changed the file name, respectively to fullchain.pem and to privkey.pem. Actually I mkdired /etc/letsencrypt/live/. It's now working. Cannot believe the file name counts.

The problem now seems to be the weakness of the server. I'll try to see if I can relocate to a stronger one so that I won't be disconnected.

Now, the mobile app, ytp media. It stopped at the login page, and won't go further. Every time I press login, nothing happened.

**Comment by DanielnetoDotCom** [comment]
Regarding the app, you need to check the server log for some clue.

debug from the app is a bit harder.

**Comment by baoang** [comment]
> Regarding the app, you need to check the server log for some clue.
> 
> debug from the app is a bit harder.

Thank you, Daniel.

From the server log which my guess is the avideo.log, I did the following:
- clear the cache from the side bar menu
- clear the prev log and start from the beginning by `sudo bash -c "cat /dev/null > /var/www/html/AVideo/videos/avideo.log"`
- when I was still logged in and clicked **Connect Mobile App** from the left menu bar, the platform prompted a qrcode with a few-digit-number/charactor. Then I started YPT media App from the mobile phone (android). The first UI is like below

![Image](https://github.com/user-attachments/assets/a2fae127-becb-4dba-b931-c3a554686ae5)

Finally I turned to the log page and saw the following codes. Is there something wrong with MySQL (mine is MariaDB 10.6)?

```
 [17-Apr-2025 05:14:01 Africa/Abidjan] myMySQLDatabaseLog::DEBUG:      Live::getStatsObject[0] 5: forced to be recreated done [{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":2165,"function":"getStatsObject","class":"Live","object":{},"type":"->","args":[0,true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":1827,"function":"_getStats","class":"Live","type":"::","args":[0,true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":1772,"function":"getStats","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":1745,"function":"getStatsApplications","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":1696,"function":"unfinishAllFromStats","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/Live.php","line":4283,"function":"checkAllFromStats","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/myMySQLDatabasePlugin.php","line":3162,"function":"executeEveryMinute","class":"Live","object":{},"type":"->","args":[]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Scheduler\/run.php","line":85,"function":"executeEveryMinute","class":"myMySQLDatabasePlugin","type":"::","args":[]}] SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php

 [17-Apr-2025 05:14:01 Africa/Abidjan] myMySQLDatabaseLog::DEBUG:      Live::getStatsObject[0] 5: forced to be recreated SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php

 [17-Apr-2025 05:14:01 Africa/Abidjan] myMySQLDatabaseLog::DEBUG:      WebRTC::checkAndUpdate: You are already running the latest version. SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      deleteALLCache end in 0.00036501884460449 seconds SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      deleteALLCache 2 rmdir path/to/my/streamer/site/videos/cache/YPTObjectCache/da39a3ee5e6b4b0d3255bfef95601890afd80709/https_www.mysite.com/admin_6ab6c08798be6adeec537fc33219c66468008e12c9641 SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      deleteALLCache rename(path/to/my/streamer/site/videos/cache/YPTObjectCache/da39a3ee5e6b4b0d3255bfef95601890afd80709/https_www.mysite.com/admin_6ab6c08798be6adeec537fc33219c664/, path/to/my/streamer/site/videos/cache/YPTObjectCache/da39a3ee5e6b4b0d3255bfef95601890afd80709/https_www.mysite.com/admin_6ab6c08798be6adeec537fc33219c66468008e12c9641)  SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      deleteALLCache starts  SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      clearCache end in 0.034916162490845 seconds SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: do not delete videos or cache folder path/to/my/streamer/site/videos/cache/ SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/f7b2d60c9afb4f56a2b2afb00ae097c9e3d390aa SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/f7b2d60c9afb4f56a2b2afb00ae097c9e3d390aa/http_www.mysite.com SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/aed59b79e94a74cba61825e2bfb0781b6720147a SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/aed59b79e94a74cba61825e2bfb0781b6720147a/http_www.mysite.com SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/16986d36af8226d0a2d5e53c66dde4f91fa48526 SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      rrmdir: could not delete folder path/to/my/streamer/site/videos/cache/YPTObjectCache/live/16986d36af8226d0a2d5e53c66dde4f91fa48526/http_www.mysite.com SCRIPT_NAME: /objects/configurationClearCache.json.php

 [17-Apr-2025 13:13:54 Asia/Shanghai] myMySQLDatabaseLog::DEBUG:      clearCache starts  SCRIPT_NAME: /objects/configurationClearCache.json.php
```

**Comment by DanielnetoDotCom** [comment]
is your server public?

How can you livestream without login?

COnfirm If you could login 

share more from your logs when you try to go live.

**Comment by baoang** [comment]
https://github.com/user-attachments/assets/9a3335d1-4c60-439e-b58e-7f1310d12a39

and about the mobile app, shrinking screen but not login issue, I recorded a video clip (before that I obtained the qrcode and the 8 digit code)

**Comment by DanielnetoDotCom** [comment]
I believe we need to organize this issue a bit better.

At the moment, it's unclear what you're trying to do. Are you:

- Trying to log in from the app?
- Attempting to livestream from the app?
- Attempting to livestream using WebRTC?
- Experiencing flickering in the mobile app?

Right now, all of these topics are mixed together in a single issue, which makes it difficult for me to understand the exact problem and provide effective support.

I kindly ask that you create a separate issue for each topic so I can assist you properly with each one.

**Comment by baoang** [comment]
Sorry for making things unclear, and thank you for your patience. Let me explain.

I follow this thread and posted after it because I searched and found similar problems, [server disconnected and port closed](https://github.com/WWBN/AVideo/issues/9727#issuecomment-2591473225).

After comparing [different methods of livestreaming](https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream), I think WebRTC would be an easy entry, not having to install extra software/apps. I attempted to try livestreaming by WebRTC way.

But that didn't make through. I still saw error codes, so I turned to YPT media, to see if I could do from the app way, because RTMP, [for example](https://mydomain.tld:8443/stat), seemed to work.

To try the YPT media, the app way, I installed it on one of my old Android phone, and followed the guide, login-fill in codes-connect the app with account. But failed again even at the first step, not being able to click the login button on the screeen.

I'll then create separate issues.
